#!/usr/bin/env python3
"""Extract the authored SF1 particle vectors and preceding table bytes.

The zero-count allocation branch wraps its remaining count. Its vector reads
walk backwards through the immediately preceding fade/snow/star/reciprocal
tables, rather than indexing the circular-vector table. Decode those finite
data outcomes here; native gameplay never reads source addresses.
"""
from __future__ import annotations

import argparse
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "reference/ultrastarfox/SF/MARIO/MDATA.MC"
OUTPUT = ROOT / "rust/sf-core/src/particle_tables.rs"


def data_bytes(source: str, start: str, stop: str) -> list[int]:
    section = source.split("\n" + start + "\n", 1)[1].split("\n" + stop + "\n", 1)[0]
    result: list[int] = []
    for line in section.splitlines():
        code = line.split(";", 1)[0].strip()
        if re.match(r"ifeq\s+1$", code, re.IGNORECASE):
            break
        if match := re.fullmatch(r"db\s+([-\d,\s]+)", code, re.IGNORECASE):
            result.extend(int(value) & 255 for value in match[1].split(","))
    return result


def render() -> str:
    source = SOURCE.read_text()
    # Guard the reciprocal-table layout whose tail is visible to zero count.
    for expression in [
        r"maxztab\s+equ\s+12\*1024",
        r"ztab\s+rept\s+256/2",
        r"zv\s*=\s*256",
        r"rept\s+\(maxztab\+512\)/2",
        r"dw\s+32767\*256/zv",
        r"zv\s*=\s*zv\+2",
    ]:
        if not re.search(expression, source):
            raise ValueError(f"unreviewed reciprocal table: {expression}")
    star = data_bytes(source, "star_cols", "snow_cols")
    snow = data_bytes(source, "snow_cols", "partfadetab")
    fade = data_bytes(source, "partfadetab", "particle_circle")
    circle = data_bytes(source, "particle_circle", "mscalechars")
    if tuple(map(len, (star, snow, fade, circle))) != (64, 16, 32, 510):
        raise ValueError("unreviewed particle table lengths")
    reciprocal = [32767] * 128
    reciprocal.extend(32767 * 256 // depth for depth in range(256, 256 + 12288 + 512, 2))
    preceding = [byte for word in reciprocal for byte in (word & 255, word >> 8)]
    preceding += star + snow + fade
    underflow = preceding[-600:]
    signed = lambda byte: byte if byte < 128 else byte - 256

    def vectors(name: str, data: list[int]) -> str:
        pairs = [[signed(data[index]), signed(data[index + 1])] for index in range(0, len(data), 2)]
        lines = [f"pub(super) const {name}: [[i8; 2]; {len(pairs)}] = ["]
        for index in range(0, len(pairs), 6):
            lines.append("    " + ", ".join(str(pair) for pair in pairs[index:index + 6]) + ",")
        return "\n".join(lines + ["];", ""])

    return (
        "// Generated by tools/sf1/generate_particle_tables.py; do not edit.\n"
        "// Original MDATA.MC literals, including the bounded zero-count look-behind.\n\n"
        + vectors("PARTICLE_CIRCLE", circle)
        + "\n"
        + vectors("PARTICLE_COUNT_UNDERFLOW", underflow)
        + "\n"
        + "pub(super) const PARTICLE_FADE: [u8; 32] = [\n    "
        + ", ".join(map(str, fade))
        + ",\n];\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != expected:
            print(f"stale particle data: {OUTPUT}", file=sys.stderr)
            return 1
        print("SF1 particle tables match original source")
    else:
        OUTPUT.write_text(expected)
        print(OUTPUT)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
