// Auto-generated by tools/color_compiler.py -- do not edit
//! Byte-exact SF1 shape colour tables, animations, and texture descriptors.

#[derive(Debug, Clone, Copy)]
pub struct ColorTable {
    pub name: &'static str,
    pub entries: &'static [u16],
}
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct TextureSprite {
    pub bank: u8,
    pub offset: u16,
}

#[rustfmt::skip]
pub static TABLE_ID_0_C_0: [u16; 109] = [0x0000, 0x0101, 0x0202, 0x0303, 0x0404, 0x0505, 0x0606, 0x0707, 0x0808, 0x0909, 0x3E00, 0x3E01, 0x3E02, 0x3E03, 0x3E04, 0x3E05, 0x3E06, 0x3E07, 0x3E08, 0x3E09, 0x3E0A, 0x3E0B, 0x3E0C, 0x3E0D, 0x3E0E, 0x3E0F, 0x3E10, 0x3E11, 0x3E12, 0x3E13, 0x3E14, 0x3E15, 0x3E16, 0x3E17, 0x3E18, 0x3E19, 0x3E1A, 0x3E1B, 0x3E1C, 0x3E1D, 0x3E1E, 0x3E1F, 0x84E1, 0x84EA, 0x84FC, 0x8505, 0x850E, 0x8517, 0x401B, 0x6028, 0x6028, 0x6028, 0x878C, 0x87AD, 0x87B8, 0x87D4, 0x87C3, 0x602C, 0x876D, 0x605B, 0x685B, 0x8722, 0x872B, 0x8734, 0x873D, 0x8746, 0x84F3, 0x4005, 0x4001, 0x4002, 0x6056, 0x3F99, 0x3FA9, 0x3FAA, 0x3FBA, 0x3FBB, 0x3FCB, 0x3FCC, 0x3FDC, 0x3FDD, 0x3FED, 0x3FEE, 0x3F11, 0x3F21, 0x3F22, 0x3F32, 0x3F33, 0x3F43, 0x3F44, 0x3F55, 0x3F65, 0x3F66, 0x3F76, 0x3F77, 0x3F87, 0x3F88, 0x6751, 0x88D7, 0x88E8, 0x88F9, 0x4006, 0x890A, 0x4006, 0x602C, 0x85B3, 0x463C, 0x400C, 0x400D, 0x4004];
#[rustfmt::skip]
pub static TABLE_ID_1_C_1: [u16; 106] = [0x0000, 0x0101, 0x0303, 0x0202, 0x0505, 0x0404, 0x0707, 0x0606, 0x0909, 0x0808, 0x3E00, 0x3E01, 0x3E02, 0x3E03, 0x3E04, 0x3E05, 0x3E06, 0x3E07, 0x3E08, 0x3E09, 0x3E0A, 0x3E12, 0x3E13, 0x3E14, 0x3E15, 0x3E16, 0x3E17, 0x3E18, 0x3E0B, 0x3E0C, 0x3E0D, 0x3E0E, 0x3E0F, 0x3E10, 0x3E11, 0x3E19, 0x3E1A, 0x3E1B, 0x3E1C, 0x3E1D, 0x3E1E, 0x3E1F, 0x84E1, 0x84EA, 0x84FC, 0x8505, 0x850E, 0x8517, 0x401B, 0x6028, 0x6028, 0x6028, 0x878C, 0x87AD, 0x87B8, 0x87D4, 0x87C3, 0x602C, 0x876D, 0x605B, 0x685B, 0x8722, 0x872B, 0x8734, 0x873D, 0x8746, 0x84F3, 0x4005, 0x4001, 0x4002, 0x6057, 0x3F99, 0x3FA9, 0x3FAA, 0x3FBA, 0x3FBB, 0x3FCB, 0x3FCC, 0x3FDC, 0x3FDD, 0x3FED, 0x3FEE, 0x3F11, 0x3F21, 0x3F22, 0x3F32, 0x3F33, 0x3F43, 0x3F44, 0x3F55, 0x3F65, 0x3F66, 0x3F76, 0x3F77, 0x3F87, 0x3F88, 0x6751, 0x88D7, 0x88E8, 0x88F9, 0x4006, 0x890A, 0x4006, 0x602C, 0x85B3, 0x463C];
#[rustfmt::skip]
pub static TABLE_ID_2_C_2: [u16; 48] = [0x0202, 0x0606, 0x0000, 0x0303, 0x0404, 0x0505, 0x0101, 0x0707, 0x0808, 0x0909, 0x3E00, 0x3E01, 0x3E0B, 0x3E0C, 0x3E0D, 0x3E0E, 0x3E0F, 0x3E10, 0x3E11, 0x3E09, 0x3E0A, 0x3E02, 0x3E03, 0x3E04, 0x3E05, 0x3E06, 0x3E07, 0x3E08, 0x3E12, 0x3E13, 0x3E14, 0x3E15, 0x3E16, 0x3E17, 0x3E18, 0x3E19, 0x3E1A, 0x3E1B, 0x3E1C, 0x3E1D, 0x3E1E, 0x3E1F, 0x84E1, 0x84EA, 0x84FC, 0x8505, 0x850E, 0x8517];
#[rustfmt::skip]
pub static TABLE_ID_3_C_3: [u16; 48] = [0x0303, 0x0707, 0x0202, 0x0000, 0x0404, 0x0505, 0x0606, 0x0101, 0x0808, 0x0909, 0x3E00, 0x3E01, 0x3E12, 0x3E13, 0x3E14, 0x3E15, 0x3E16, 0x3E17, 0x3E18, 0x3E09, 0x3E0A, 0x3E0B, 0x3E0C, 0x3E0D, 0x3E0E, 0x3E0F, 0x3E10, 0x3E11, 0x3E02, 0x3E03, 0x3E04, 0x3E05, 0x3E06, 0x3E07, 0x3E08, 0x3E19, 0x3E1A, 0x3E1B, 0x3E1C, 0x3E1D, 0x3E1E, 0x3E1F, 0x84E1, 0x84EA, 0x84FC, 0x8505, 0x850E, 0x8517];
#[rustfmt::skip]
pub static TABLE_ID_5_C_4: [u16; 48] = [0x0000, 0x0101, 0x0202, 0x0000, 0x0404, 0x0505, 0x0606, 0x0101, 0x0808, 0x0909, 0x3E00, 0x3E01, 0x3E02, 0x3E03, 0x3E04, 0x3E05, 0x3E06, 0x3E07, 0x3E08, 0x3E09, 0x3E0A, 0x3E0B, 0x3E0C, 0x3E0D, 0x3E0E, 0x3E0F, 0x3E10, 0x3E11, 0x3E00, 0x3E01, 0x3E02, 0x3E03, 0x3E04, 0x3E05, 0x3E06, 0x3E19, 0x3E1A, 0x3E1B, 0x3E1C, 0x3E1D, 0x3E1E, 0x3E1F, 0x84E1, 0x84FC, 0x84EA, 0x8505, 0x850E, 0x8517];
#[rustfmt::skip]
pub static TABLE_ID_5_C_5: [u16; 48] = [0x0000, 0x0101, 0x0202, 0x0000, 0x0404, 0x0505, 0x0606, 0x0101, 0x0808, 0x0909, 0x3E00, 0x3E01, 0x3E02, 0x3E03, 0x3E04, 0x3E05, 0x3E06, 0x3E07, 0x3E08, 0x3E09, 0x3E0A, 0x3E0B, 0x3E0C, 0x3E0D, 0x3E0E, 0x3E0F, 0x3E10, 0x3E11, 0x3E00, 0x3E01, 0x3E02, 0x3E03, 0x3E04, 0x3E05, 0x3E06, 0x3E19, 0x3E1A, 0x3E1B, 0x3E1C, 0x3E1D, 0x3E1E, 0x3E1F, 0x84E1, 0x84FC, 0x84EA, 0x8505, 0x850E, 0x8517];
#[rustfmt::skip]
pub static TABLE_BLACK_C_6: [u16; 64] = [0x3F99, 0x3F99, 0x3F99, 0x3F99, 0x3F99, 0x3F99, 0x3F99, 0x3F99, 0x3F99, 0x3F99, 0x3F99, 0x3F99, 0x3F99, 0x3F99, 0x3F99, 0x3F99, 0x3F99, 0x3F99, 0x3F99, 0x3F99, 0x3F99, 0x3F99, 0x3F99, 0x3F99, 0x3F99, 0x3F99, 0x3F99, 0x3F99, 0x3F99, 0x3F99, 0x3F99, 0x3F99, 0x3F99, 0x3F99, 0x3F99, 0x3F99, 0x3F99, 0x3F99, 0x3F99, 0x3F99, 0x3F99, 0x3F99, 0x3F99, 0x3F99, 0x3F99, 0x3F99, 0x3F99, 0x3F99, 0x3F99, 0x3F99, 0x3F99, 0x3F99, 0x3F99, 0x3F99, 0x3F99, 0x3F99, 0x3F99, 0x3F99, 0x3F99, 0x3F99, 0x3F99, 0x3F99, 0x3F99, 0x3F99];
#[rustfmt::skip]
pub static TABLE_AMOEBA_C_7: [u16; 1] = [0x8719];
#[rustfmt::skip]
pub static TABLE_ANDROSS_C_8: [u16; 2] = [0x6626, 0x6626];
#[rustfmt::skip]
pub static TABLE_ANDROSSHOLE_C_9: [u16; 2] = [0x6650, 0x6150];
#[rustfmt::skip]
pub static TABLE_ANDROSSL3_C_10: [u16; 2] = [0x6626, 0x8589];
#[rustfmt::skip]
pub static TABLE_ASTEROID2_C_11: [u16; 1] = [0x401F];
#[rustfmt::skip]
pub static TABLE_ASTEROID_C_12: [u16; 1] = [0x401B];
#[rustfmt::skip]
pub static TABLE_BALLANDCHAIN_C_13: [u16; 1] = [0x6029];
#[rustfmt::skip]
pub static TABLE_BIG_METEOR_C_14: [u16; 1] = [0x6653];
#[rustfmt::skip]
pub static TABLE_BLACKHOLE_C_15: [u16; 1] = [0x6650];
#[rustfmt::skip]
pub static TABLE_BONFIRE_C_16: [u16; 2] = [0x8578, 0x4007];
#[rustfmt::skip]
pub static TABLE_BOOST_C_17: [u16; 1] = [0x85B8];
#[rustfmt::skip]
pub static TABLE_BOUNCYBALL_C_18: [u16; 1] = [0x880F];
#[rustfmt::skip]
pub static TABLE_BRITENORMAL_C_19: [u16; 10] = [0x3F00, 0x3F11, 0x3F22, 0x3F33, 0x3F44, 0x3F55, 0x3F66, 0x3F77, 0x3F88, 0x3FAA];
#[rustfmt::skip]
pub static TABLE_BULLET_C_20: [u16; 1] = [0x87F5];
#[rustfmt::skip]
pub static TABLE_BURNMARK_C_21: [u16; 1] = [0x4018];
#[rustfmt::skip]
pub static TABLE_CORNFLAKES_C_22: [u16; 1] = [0x4018];
#[rustfmt::skip]
pub static TABLE_DEFAULT_C_23: [u16; 16] = [0x0404, 0x0101, 0x0202, 0x0303, 0x0404, 0x0505, 0x0606, 0x0707, 0x0808, 0x0909, 0x0A0A, 0x0B0B, 0x0000, 0x0101, 0x0202, 0x0303];
#[rustfmt::skip]
pub static TABLE_EBULLET_C_24: [u16; 1] = [0x8806];
#[rustfmt::skip]
pub static TABLE_EGG_C_25: [u16; 1] = [0x602A];
#[rustfmt::skip]
pub static TABLE_ESCAPEE_C_26: [u16; 2] = [0x605F, 0x605F];
#[rustfmt::skip]
pub static TABLE_EXITLIGHT_C_27: [u16; 1] = [0x87DF];
#[rustfmt::skip]
pub static TABLE_EXPLODE2_C_28: [u16; 1] = [0x8840];
#[rustfmt::skip]
pub static TABLE_EXPLODE3_C_29: [u16; 1] = [0x8851];
#[rustfmt::skip]
pub static TABLE_EXPLODE_C_30: [u16; 1] = [0x8837];
#[rustfmt::skip]
pub static TABLE_FINALBOSS_C_31: [u16; 8] = [0x85BF, 0x85E8, 0x8611, 0x863A, 0x8663, 0x868C, 0x86B5, 0x86DE];
#[rustfmt::skip]
pub static TABLE_FIRE_C_32: [u16; 1] = [0x875C];
#[rustfmt::skip]
pub static TABLE_FIREBALL_C_33: [u16; 1] = [0x8710];
#[rustfmt::skip]
pub static TABLE_FLASH_C_34: [u16; 1] = [0x88D2];
#[rustfmt::skip]
pub static TABLE_FRUITMACHINE_C_35: [u16; 1] = [0x6252];
#[rustfmt::skip]
pub static TABLE_GAME_C_36: [u16; 2] = [0x6454, 0x6554];
#[rustfmt::skip]
pub static TABLE_HYPER_C_37: [u16; 4] = [0x3FEE, 0x3F44, 0x3F77, 0x3F88];
#[rustfmt::skip]
pub static TABLE_IRONBALL_C_38: [u16; 1] = [0x4000];
#[rustfmt::skip]
pub static TABLE_LFDIE_C_39: [u16; 1] = [0x8772];
#[rustfmt::skip]
pub static TABLE_LINE_C_40: [u16; 1] = [0x87E4];
#[rustfmt::skip]
pub static TABLE_NORMAL_C_41: [u16; 45] = [0x3F00, 0x3F11, 0x3F22, 0x3F33, 0x3F44, 0x3F55, 0x3F66, 0x3F77, 0x3F88, 0x3F99, 0x3FAA, 0x3FBB, 0x3FCC, 0x3FDD, 0x3FEE, 0x3FFF, 0x8862, 0x6028, 0x6028, 0x3F00, 0x3F11, 0x3F22, 0x3F33, 0x3F44, 0x3F55, 0x3F66, 0x3F77, 0x3F88, 0x3FAA, 0x3FBB, 0x3FCC, 0x3FDD, 0x3FEE, 0x3FEE, 0x3FFF, 0x8862, 0x6028, 0x6028, 0x2008, 0x2160, 0x2260, 0x2360, 0x2460, 0x2460, 0x2560];
#[rustfmt::skip]
pub static TABLE_OVALBEAM_C_42: [u16; 1] = [0x890F];
#[rustfmt::skip]
pub static TABLE_OVER_C_43: [u16; 2] = [0x6455, 0x6555];
#[rustfmt::skip]
pub static TABLE_PEXPLOD2S_C_44: [u16; 1] = [0x4639];
#[rustfmt::skip]
pub static TABLE_PLAYERBEAM_C_45: [u16; 1] = [0x4005];
#[rustfmt::skip]
pub static TABLE_RINGLASER_C_46: [u16; 1] = [0x874B];
#[rustfmt::skip]
pub static TABLE_ROCKBEAM_C_47: [u16; 1] = [0x8707];
#[rustfmt::skip]
pub static TABLE_SMOKE_C_48: [u16; 1] = [0x8814];
#[rustfmt::skip]
pub static TABLE_SPARK_C_49: [u16; 1] = [0x8825];
#[rustfmt::skip]
pub static TABLE_SPECIALWEAPON_C_50: [u16; 1] = [0x877B];
#[rustfmt::skip]
pub static TABLE_SPLASH_C_51: [u16; 1] = [0x88BF];
#[rustfmt::skip]
pub static TABLE_TELEPORT_C_52: [u16; 1] = [0x6034];
#[rustfmt::skip]
pub static TABLE_WHITE_C_53: [u16; 56] = [0x3FEE, 0x3FEE, 0x3FEE, 0x3FEE, 0x3FEE, 0x3FEE, 0x3FEE, 0x3FEE, 0x3FEE, 0x3FEE, 0x3FEE, 0x3FEE, 0x3FEE, 0x3FEE, 0x3FEE, 0x3FEE, 0x3FEE, 0x3FEE, 0x3FEE, 0x3FEE, 0x3FEE, 0x3FEE, 0x3FEE, 0x3FEE, 0x3FEE, 0x3FEE, 0x3FEE, 0x3FEE, 0x3FEE, 0x3FEE, 0x3FEE, 0x3FEE, 0x3FEE, 0x3FEE, 0x3FEE, 0x3FEE, 0x3FEE, 0x3FEE, 0x3FEE, 0x3FEE, 0x3F99, 0x3F99, 0x3F99, 0x3F99, 0x3F99, 0x3F99, 0x3F99, 0x3F99, 0x3F99, 0x3F99, 0x3F99, 0x3F99, 0x3F99, 0x3F99, 0x3F99, 0x84FC];

pub const COLOR_TABLE_COUNT: usize = 54;
#[rustfmt::skip]
pub static COLOR_TABLES: [ColorTable; COLOR_TABLE_COUNT] = [
    ColorTable { name: "id_0_c", entries: &TABLE_ID_0_C_0 },
    ColorTable { name: "id_1_c", entries: &TABLE_ID_1_C_1 },
    ColorTable { name: "id_2_c", entries: &TABLE_ID_2_C_2 },
    ColorTable { name: "id_3_c", entries: &TABLE_ID_3_C_3 },
    ColorTable { name: "id_5_c", entries: &TABLE_ID_5_C_4 },
    ColorTable { name: "id_5_c", entries: &TABLE_ID_5_C_5 },
    ColorTable { name: "black_c", entries: &TABLE_BLACK_C_6 },
    ColorTable { name: "amoeba_c", entries: &TABLE_AMOEBA_C_7 },
    ColorTable { name: "andross_c", entries: &TABLE_ANDROSS_C_8 },
    ColorTable { name: "androsshole_c", entries: &TABLE_ANDROSSHOLE_C_9 },
    ColorTable { name: "androssl3_c", entries: &TABLE_ANDROSSL3_C_10 },
    ColorTable { name: "asteroid2_c", entries: &TABLE_ASTEROID2_C_11 },
    ColorTable { name: "asteroid_c", entries: &TABLE_ASTEROID_C_12 },
    ColorTable { name: "ballandchain_c", entries: &TABLE_BALLANDCHAIN_C_13 },
    ColorTable { name: "big_meteor_c", entries: &TABLE_BIG_METEOR_C_14 },
    ColorTable { name: "blackhole_c", entries: &TABLE_BLACKHOLE_C_15 },
    ColorTable { name: "bonfire_c", entries: &TABLE_BONFIRE_C_16 },
    ColorTable { name: "boost_c", entries: &TABLE_BOOST_C_17 },
    ColorTable { name: "bouncyball_c", entries: &TABLE_BOUNCYBALL_C_18 },
    ColorTable { name: "britenormal_c", entries: &TABLE_BRITENORMAL_C_19 },
    ColorTable { name: "bullet_c", entries: &TABLE_BULLET_C_20 },
    ColorTable { name: "burnmark_c", entries: &TABLE_BURNMARK_C_21 },
    ColorTable { name: "cornflakes_c", entries: &TABLE_CORNFLAKES_C_22 },
    ColorTable { name: "default_c", entries: &TABLE_DEFAULT_C_23 },
    ColorTable { name: "ebullet_c", entries: &TABLE_EBULLET_C_24 },
    ColorTable { name: "egg_c", entries: &TABLE_EGG_C_25 },
    ColorTable { name: "escapee_c", entries: &TABLE_ESCAPEE_C_26 },
    ColorTable { name: "exitlight_c", entries: &TABLE_EXITLIGHT_C_27 },
    ColorTable { name: "explode2_c", entries: &TABLE_EXPLODE2_C_28 },
    ColorTable { name: "explode3_c", entries: &TABLE_EXPLODE3_C_29 },
    ColorTable { name: "explode_c", entries: &TABLE_EXPLODE_C_30 },
    ColorTable { name: "finalboss_c", entries: &TABLE_FINALBOSS_C_31 },
    ColorTable { name: "fire_c", entries: &TABLE_FIRE_C_32 },
    ColorTable { name: "fireball_c", entries: &TABLE_FIREBALL_C_33 },
    ColorTable { name: "flash_c", entries: &TABLE_FLASH_C_34 },
    ColorTable { name: "fruitmachine_c", entries: &TABLE_FRUITMACHINE_C_35 },
    ColorTable { name: "game_c", entries: &TABLE_GAME_C_36 },
    ColorTable { name: "hyper_c", entries: &TABLE_HYPER_C_37 },
    ColorTable { name: "ironball_c", entries: &TABLE_IRONBALL_C_38 },
    ColorTable { name: "lfdie_c", entries: &TABLE_LFDIE_C_39 },
    ColorTable { name: "line_c", entries: &TABLE_LINE_C_40 },
    ColorTable { name: "normal_c", entries: &TABLE_NORMAL_C_41 },
    ColorTable { name: "ovalbeam_c", entries: &TABLE_OVALBEAM_C_42 },
    ColorTable { name: "over_c", entries: &TABLE_OVER_C_43 },
    ColorTable { name: "pexplod2s_c", entries: &TABLE_PEXPLOD2S_C_44 },
    ColorTable { name: "playerbeam_c", entries: &TABLE_PLAYERBEAM_C_45 },
    ColorTable { name: "ringlaser_c", entries: &TABLE_RINGLASER_C_46 },
    ColorTable { name: "rockbeam_c", entries: &TABLE_ROCKBEAM_C_47 },
    ColorTable { name: "smoke_c", entries: &TABLE_SMOKE_C_48 },
    ColorTable { name: "spark_c", entries: &TABLE_SPARK_C_49 },
    ColorTable { name: "specialweapon_c", entries: &TABLE_SPECIALWEAPON_C_50 },
    ColorTable { name: "splash_c", entries: &TABLE_SPLASH_C_51 },
    ColorTable { name: "teleport_c", entries: &TABLE_TELEPORT_C_52 },
    ColorTable { name: "white_c", entries: &TABLE_WHITE_C_53 },
];

pub fn table_id_by_name(name: &str) -> Option<u16> {
    match name.to_ascii_lowercase().as_str() {
        "id_4_c" => Some(4),
        "amoeba_c" => Some(7),
        "andross_c" => Some(8),
        "androsshole_c" => Some(9),
        "androssl3_c" => Some(10),
        "asteroid2_c" => Some(11),
        "asteroid_c" => Some(12),
        "ballandchain_c" => Some(13),
        "big_meteor_c" => Some(14),
        "black_c" => Some(6),
        "blackhole_c" => Some(15),
        "bonfire_c" => Some(16),
        "boost_c" => Some(17),
        "bouncyball_c" => Some(18),
        "britenormal_c" => Some(19),
        "bullet_c" => Some(20),
        "burnmark_c" => Some(21),
        "cornflakes_c" => Some(22),
        "default_c" => Some(23),
        "ebullet_c" => Some(24),
        "egg_c" => Some(25),
        "escapee_c" => Some(26),
        "exitlight_c" => Some(27),
        "explode2_c" => Some(28),
        "explode3_c" => Some(29),
        "explode_c" => Some(30),
        "finalboss_c" => Some(31),
        "fire_c" => Some(32),
        "fireball_c" => Some(33),
        "flash_c" => Some(34),
        "fruitmachine_c" => Some(35),
        "game_c" => Some(36),
        "hyper_c" => Some(37),
        "id_0_c" => Some(0),
        "id_1_c" => Some(1),
        "id_2_c" => Some(2),
        "id_3_c" => Some(3),
        "id_5_c" => Some(5),
        "ironball_c" => Some(38),
        "lfdie_c" => Some(39),
        "line_c" => Some(40),
        "normal_c" => Some(41),
        "ovalbeam_c" => Some(42),
        "over_c" => Some(43),
        "pexplod2s_c" => Some(44),
        "playerbeam_c" => Some(45),
        "ringlaser_c" => Some(46),
        "rockbeam_c" => Some(47),
        "smoke_c" => Some(48),
        "spark_c" => Some(49),
        "specialweapon_c" => Some(50),
        "splash_c" => Some(51),
        "teleport_c" => Some(52),
        "white_c" => Some(53),
        _ => None,
    }
}

#[rustfmt::skip]
static ANIM_04E1: [u16; 4] = [0x3FEE, 0x3F77, 0x3F22, 0x3FFF];
#[rustfmt::skip]
static ANIM_04EA: [u16; 4] = [0x3F44, 0x3F33, 0x3F22, 0x3F11];
#[rustfmt::skip]
static ANIM_04F3: [u16; 4] = [0x3E11, 0x3E1B, 0x3E11, 0x3E1B];
#[rustfmt::skip]
static ANIM_04FC: [u16; 4] = [0x3F88, 0x3F77, 0x3F66, 0x3F55];
#[rustfmt::skip]
static ANIM_0505: [u16; 4] = [0x3FEE, 0x3FDD, 0x3FCC, 0x3FBB];
#[rustfmt::skip]
static ANIM_050E: [u16; 4] = [0x3FE4, 0x3F86, 0x3F82, 0x3F31];
#[rustfmt::skip]
static ANIM_0517: [u16; 4] = [0x3FE0, 0x3F70, 0x3F20, 0x3FF0];
#[rustfmt::skip]
static ANIM_0578: [u16; 2] = [0x463B, 0x463C];
#[rustfmt::skip]
static ANIM_0589: [u16; 4] = [0x0000, 0x0707, 0x0606, 0x6626];
#[rustfmt::skip]
static ANIM_05B3: [u16; 2] = [0x3FEE, 0x3F77];
#[rustfmt::skip]
static ANIM_05B8: [u16; 2] = [0x604B, 0x4013];
#[rustfmt::skip]
static ANIM_05BF: [u16; 32] = [0x3FDD, 0x3FDD, 0x3FED, 0x3FED, 0x3FED, 0x3FED, 0x3FED, 0x3FEE, 0x3FEE, 0x3FEE, 0x3FEE, 0x3FEE, 0x3FEE, 0x3FEE, 0x3FEE, 0x3FEE, 0x3FEE, 0x3FEE, 0x3FEE, 0x3FEE, 0xDD20, 0xDD3F, 0xDD3F, 0xDD3F, 0xDD3F, 0xDD3F, 0xDD3F, 0xDD3F, 0xDD3F, 0xDD3F, 0xDD3F, 0xDD3F];
#[rustfmt::skip]
static ANIM_05E8: [u16; 32] = [0x3FDD, 0x3FDD, 0x3FDD, 0x3FDD, 0x3FDD, 0x3FDD, 0x3FDD, 0x3FDD, 0x3FDD, 0x3FDD, 0x3FDD, 0x3FDD, 0x3FDD, 0x3FDD, 0x3FDD, 0x3FDD, 0x3FDD, 0x3FDD, 0x3FDD, 0x3FDD, 0xDD20, 0xDD3F, 0xDD3F, 0xDC3F, 0xDC3F, 0xDD3F, 0xDC3F, 0xCC3F, 0xCC3F, 0xCC3F, 0xCC3F, 0xCC3F];
#[rustfmt::skip]
static ANIM_0611: [u16; 32] = [0x3FDD, 0x3FDD, 0x3FDD, 0x3FDC, 0x3FDC, 0x3FDD, 0x3FDC, 0x3FCC, 0x3FCC, 0x3FCC, 0x3FCC, 0x3FCC, 0x3FCC, 0x3FCC, 0x3FCC, 0x3FCC, 0x3FCC, 0x3FCC, 0x3FCC, 0x3FCC, 0xDD20, 0xDC3F, 0xDC3F, 0xCC3F, 0xCC3F, 0xCB3F, 0xCB3F, 0xBB3F, 0xBB3F, 0xBB3F, 0xBB3F, 0xBB3F];
#[rustfmt::skip]
static ANIM_063A: [u16; 32] = [0x3FDD, 0x3FDC, 0x3FDC, 0x3FCC, 0x3FCC, 0x3FCB, 0x3FCB, 0x3FBB, 0x3FBB, 0x3FBB, 0x3FBB, 0x3FBB, 0x3FBB, 0x3FBB, 0x3FBB, 0x3FBB, 0x3FBB, 0x3FBB, 0x3FBB, 0x3FBB, 0xDD20, 0xDC3F, 0xDC3F, 0xCC3F, 0xCB3F, 0xBB3F, 0xBB3F, 0xBA3F, 0xBA3F, 0xAA3F, 0xAA3F, 0xAA3F];
#[rustfmt::skip]
static ANIM_0663: [u16; 32] = [0x3FDD, 0x3FDC, 0x3FDC, 0x3FCC, 0x3FCB, 0x3FBB, 0x3FBB, 0x3FBA, 0x3FBA, 0x3FAA, 0x3FAA, 0x3FAA, 0x3FAA, 0x3FAA, 0x3FAA, 0x3FAA, 0x3FAA, 0x3FAA, 0x3FAA, 0x3FAA, 0xDD20, 0xDC3F, 0xCC3F, 0xCB3F, 0xBB3F, 0xBA3F, 0xAA3F, 0xA93F, 0xA93F, 0x993F, 0x993F, 0x993F];
#[rustfmt::skip]
static ANIM_068C: [u16; 32] = [0x3FDD, 0x3FDC, 0x3FCC, 0x3FCB, 0x3FBB, 0x3FBA, 0x3FAA, 0x3FA9, 0x3FA9, 0x3F99, 0x3F99, 0x3F99, 0x3F99, 0x3F99, 0x3F99, 0x3F99, 0x3F99, 0x3F99, 0x3F99, 0x3F99, 0x8820, 0x773F, 0x663F, 0x553F, 0x883F, 0x773F, 0x663F, 0x553F, 0x883F, 0x773F, 0x553F, 0x883F];
#[rustfmt::skip]
static ANIM_06B5: [u16; 32] = [0x3F88, 0x3F77, 0x3F66, 0x3F55, 0x3F88, 0x3F77, 0x3F66, 0x3F55, 0x3F88, 0x3F77, 0x3F55, 0x3F88, 0x3F99, 0x3F99, 0x3F55, 0x3F88, 0x3F99, 0x3F99, 0x3F22, 0x3F22, 0x8820, 0x773F, 0x663F, 0x553F, 0x883F, 0x773F, 0x663F, 0x553F, 0x883F, 0x773F, 0x553F, 0x883F];
#[rustfmt::skip]
static ANIM_06DE: [u16; 32] = [0x3F88, 0x3F77, 0x3F66, 0x3F55, 0x3F88, 0x3F77, 0x3F66, 0x3F55, 0x3F88, 0x3F77, 0x3F55, 0x3F88, 0x3F55, 0x3F88, 0x3F99, 0x3F99, 0x3F99, 0x3F22, 0x3F99, 0x3F22, 0x2704, 0x2B60, 0x5C60, 0x2B60, 0x0460, 0x4015, 0x4016, 0x4017, 0x4016, 0x4C04, 0x4D60, 0x4C60];
#[rustfmt::skip]
static ANIM_0707: [u16; 4] = [0x6027, 0x602B, 0x605C, 0x602B];
#[rustfmt::skip]
static ANIM_0710: [u16; 4] = [0x4015, 0x4016, 0x4017, 0x4016];
#[rustfmt::skip]
static ANIM_0719: [u16; 4] = [0x604C, 0x604D, 0x604C, 0x604E];
#[rustfmt::skip]
static ANIM_0722: [u16; 4] = [0x401E, 0x401D, 0x401D, 0x401D];
#[rustfmt::skip]
static ANIM_072B: [u16; 4] = [0x401D, 0x401E, 0x401D, 0x401D];
#[rustfmt::skip]
static ANIM_0734: [u16; 4] = [0x401D, 0x401D, 0x401E, 0x401D];
#[rustfmt::skip]
static ANIM_073D: [u16; 4] = [0x401D, 0x401D, 0x401D, 0x401E];
#[rustfmt::skip]
static ANIM_0746: [u16; 2] = [0x401E, 0x401D];
#[rustfmt::skip]
static ANIM_074B: [u16; 8] = [0x401D, 0x401E, 0x401D, 0x401E, 0x401D, 0x401E, 0x401D, 0x401E];
#[rustfmt::skip]
static ANIM_075C: [u16; 8] = [0x463D, 0x463C, 0x463B, 0x463B, 0x463A, 0x463A, 0x4639, 0x4639];
#[rustfmt::skip]
static ANIM_076D: [u16; 2] = [0x3F11, 0x3F33];
#[rustfmt::skip]
static ANIM_0772: [u16; 4] = [0x400A, 0x400B, 0x400F, 0x400B];
#[rustfmt::skip]
static ANIM_077B: [u16; 8] = [0x4019, 0x401A, 0x401C, 0x4019, 0x401A, 0x401C, 0x4019, 0x401A];
#[rustfmt::skip]
static ANIM_078C: [u16; 16] = [0x3F88, 0x3F77, 0x3F66, 0x3F55, 0x3F44, 0x3F44, 0x3F33, 0x3F33, 0x3F22, 0x3F22, 0x3F11, 0x3F11, 0x3F11, 0x3F22, 0x3F33, 0x3F44];
#[rustfmt::skip]
static ANIM_07AD: [u16; 8] = [0x3F44, 0x3F33, 0x3F22, 0x3F11, 0x3E00, 0x4408, 0x333F, 0x223F];
#[rustfmt::skip]
static ANIM_07B8: [u16; 8] = [0x3F44, 0x3F33, 0x3F22, 0x3F11, 0x3E06, 0x8808, 0x773F, 0x663F];
#[rustfmt::skip]
static ANIM_07C3: [u16; 8] = [0x3F88, 0x3F77, 0x3F66, 0x3F55, 0x3F44, 0x3F33, 0x3F22, 0x3F11];
#[rustfmt::skip]
static ANIM_07D4: [u16; 8] = [0x3F88, 0x3F77, 0x3F66, 0x3F55, 0x3E1D, 0x4402, 0x113F, 0x083F];
#[rustfmt::skip]
static ANIM_07DF: [u16; 2] = [0x3F44, 0x3F11];
#[rustfmt::skip]
static ANIM_07E4: [u16; 8] = [0x3FEE, 0x3FDD, 0x3FCC, 0x3FBB, 0x3FAA, 0x3F99, 0x3F99, 0x3F99];
#[rustfmt::skip]
static ANIM_07F5: [u16; 8] = [0x3FEE, 0x3F88, 0x3FEE, 0x3F77, 0x3FEE, 0x3F88, 0x3FEE, 0x3F66];
#[rustfmt::skip]
static ANIM_0806: [u16; 4] = [0x3FEE, 0x3F33, 0x3FEE, 0x3F44];
#[rustfmt::skip]
static ANIM_080F: [u16; 2] = [0x4010, 0x4011];
#[rustfmt::skip]
static ANIM_0814: [u16; 8] = [0x4639, 0x4008, 0x6041, 0x6042, 0x6043, 0x6044, 0x6045, 0x6046];
#[rustfmt::skip]
static ANIM_0825: [u16; 4] = [0x400A, 0x400B, 0x400F, 0x400B];
#[rustfmt::skip]
static ANIM_0837: [u16; 4] = [0x4639, 0x463A, 0x4008, 0x4009];
#[rustfmt::skip]
static ANIM_0840: [u16; 8] = [0x4639, 0x463A, 0x463B, 0x463E, 0x463F, 0x4640, 0x4640, 0x4640];
#[rustfmt::skip]
static ANIM_0851: [u16; 8] = [0x4639, 0x463A, 0x463B, 0x463C, 0x463D, 0x463E, 0x463F, 0x4640];
#[rustfmt::skip]
static ANIM_0862: [u16; 8] = [0x3F66, 0x3F66, 0x3FEE, 0x3FEE, 0x3F33, 0x3F33, 0x3F11, 0x3F11];
#[rustfmt::skip]
static ANIM_08BF: [u16; 8] = [0x6020, 0x6021, 0x6022, 0x6023, 0x6024, 0x6024, 0x6025, 0x6025];
#[rustfmt::skip]
static ANIM_08D2: [u16; 2] = [0x4012, 0x4013];
#[rustfmt::skip]
static ANIM_08D7: [u16; 8] = [0x3FEE, 0x3FDD, 0x3FCC, 0x3FBB, 0x3FAA, 0x3FA9, 0x3F99, 0x3F99];
#[rustfmt::skip]
static ANIM_08E8: [u16; 8] = [0x3F22, 0x3F22, 0x3F21, 0x3F21, 0x3F11, 0x3F11, 0x3F11, 0x3F11];
#[rustfmt::skip]
static ANIM_08F9: [u16; 8] = [0x3FDD, 0x3FCC, 0x3FBB, 0x3FAA, 0x3FA9, 0x3F99, 0x3F99, 0x3F99];
#[rustfmt::skip]
static ANIM_090A: [u16; 2] = [0x3F19, 0x3F22];
#[rustfmt::skip]
static ANIM_090F: [u16; 4] = [0x6047, 0x6049, 0x6048, 0x6049];

pub fn animation_frames(pointer: u16) -> Option<&'static [u16]> {
    match pointer {
        0x04E1 => Some(&ANIM_04E1),
        0x04EA => Some(&ANIM_04EA),
        0x04F3 => Some(&ANIM_04F3),
        0x04FC => Some(&ANIM_04FC),
        0x0505 => Some(&ANIM_0505),
        0x050E => Some(&ANIM_050E),
        0x0517 => Some(&ANIM_0517),
        0x0578 => Some(&ANIM_0578),
        0x0589 => Some(&ANIM_0589),
        0x05B3 => Some(&ANIM_05B3),
        0x05B8 => Some(&ANIM_05B8),
        0x05BF => Some(&ANIM_05BF),
        0x05E8 => Some(&ANIM_05E8),
        0x0611 => Some(&ANIM_0611),
        0x063A => Some(&ANIM_063A),
        0x0663 => Some(&ANIM_0663),
        0x068C => Some(&ANIM_068C),
        0x06B5 => Some(&ANIM_06B5),
        0x06DE => Some(&ANIM_06DE),
        0x0707 => Some(&ANIM_0707),
        0x0710 => Some(&ANIM_0710),
        0x0719 => Some(&ANIM_0719),
        0x0722 => Some(&ANIM_0722),
        0x072B => Some(&ANIM_072B),
        0x0734 => Some(&ANIM_0734),
        0x073D => Some(&ANIM_073D),
        0x0746 => Some(&ANIM_0746),
        0x074B => Some(&ANIM_074B),
        0x075C => Some(&ANIM_075C),
        0x076D => Some(&ANIM_076D),
        0x0772 => Some(&ANIM_0772),
        0x077B => Some(&ANIM_077B),
        0x078C => Some(&ANIM_078C),
        0x07AD => Some(&ANIM_07AD),
        0x07B8 => Some(&ANIM_07B8),
        0x07C3 => Some(&ANIM_07C3),
        0x07D4 => Some(&ANIM_07D4),
        0x07DF => Some(&ANIM_07DF),
        0x07E4 => Some(&ANIM_07E4),
        0x07F5 => Some(&ANIM_07F5),
        0x0806 => Some(&ANIM_0806),
        0x080F => Some(&ANIM_080F),
        0x0814 => Some(&ANIM_0814),
        0x0825 => Some(&ANIM_0825),
        0x0837 => Some(&ANIM_0837),
        0x0840 => Some(&ANIM_0840),
        0x0851 => Some(&ANIM_0851),
        0x0862 => Some(&ANIM_0862),
        0x08BF => Some(&ANIM_08BF),
        0x08D2 => Some(&ANIM_08D2),
        0x08D7 => Some(&ANIM_08D7),
        0x08E8 => Some(&ANIM_08E8),
        0x08F9 => Some(&ANIM_08F9),
        0x090A => Some(&ANIM_090A),
        0x090F => Some(&ANIM_090F),
        _ => None,
    }
}

pub const ANIM_PTR_CA_0: u16 = 0x04E1;
pub const ANIM_PTR_CA_1: u16 = 0x04EA;
pub const ANIM_PTR_CA_2: u16 = 0x04FC;
pub const ANIM_PTR_CA_3: u16 = 0x0505;
pub const ANIM_PTR_CA_4: u16 = 0x050E;
pub const ANIM_PTR_CA_5: u16 = 0x0517;
pub const ANIM_PTR_BULLET_A1: u16 = 0x07F5;

#[rustfmt::skip]
pub static TEXTURE_SPRITES: [TextureSprite; 98] = [
    TextureSprite { bank: 0, offset: 0x0000 },
    TextureSprite { bank: 0, offset: 0x0020 },
    TextureSprite { bank: 0, offset: 0x0040 },
    TextureSprite { bank: 0, offset: 0x0060 },
    TextureSprite { bank: 0, offset: 0x0080 },
    TextureSprite { bank: 0, offset: 0x00A0 },
    TextureSprite { bank: 0, offset: 0x00C0 },
    TextureSprite { bank: 0, offset: 0x00E0 },
    TextureSprite { bank: 0, offset: 0x2000 },
    TextureSprite { bank: 0, offset: 0x2020 },
    TextureSprite { bank: 0, offset: 0x2040 },
    TextureSprite { bank: 0, offset: 0x2060 },
    TextureSprite { bank: 0, offset: 0x2080 },
    TextureSprite { bank: 0, offset: 0x20A0 },
    TextureSprite { bank: 0, offset: 0x20C0 },
    TextureSprite { bank: 0, offset: 0x20E0 },
    TextureSprite { bank: 0, offset: 0x4000 },
    TextureSprite { bank: 0, offset: 0x4020 },
    TextureSprite { bank: 0, offset: 0x4040 },
    TextureSprite { bank: 0, offset: 0x4060 },
    TextureSprite { bank: 0, offset: 0x4080 },
    TextureSprite { bank: 0, offset: 0x40A0 },
    TextureSprite { bank: 0, offset: 0x40C0 },
    TextureSprite { bank: 0, offset: 0x40E0 },
    TextureSprite { bank: 0, offset: 0x6000 },
    TextureSprite { bank: 0, offset: 0x6020 },
    TextureSprite { bank: 0, offset: 0x6040 },
    TextureSprite { bank: 0, offset: 0x6060 },
    TextureSprite { bank: 0, offset: 0x6080 },
    TextureSprite { bank: 0, offset: 0x60A0 },
    TextureSprite { bank: 0, offset: 0x60C0 },
    TextureSprite { bank: 0, offset: 0x60E0 },
    TextureSprite { bank: 0, offset: 0x0000 },
    TextureSprite { bank: 0, offset: 0x0020 },
    TextureSprite { bank: 0, offset: 0x0040 },
    TextureSprite { bank: 0, offset: 0x0060 },
    TextureSprite { bank: 0, offset: 0x0080 },
    TextureSprite { bank: 0, offset: 0x00A0 },
    TextureSprite { bank: 0, offset: 0x00C0 },
    TextureSprite { bank: 0, offset: 0x2000 },
    TextureSprite { bank: 0, offset: 0x2020 },
    TextureSprite { bank: 0, offset: 0x2040 },
    TextureSprite { bank: 0, offset: 0x2060 },
    TextureSprite { bank: 0, offset: 0x2080 },
    TextureSprite { bank: 0, offset: 0x20A0 },
    TextureSprite { bank: 0, offset: 0x20C0 },
    TextureSprite { bank: 0, offset: 0x4000 },
    TextureSprite { bank: 0, offset: 0x4020 },
    TextureSprite { bank: 0, offset: 0x4040 },
    TextureSprite { bank: 0, offset: 0x4060 },
    TextureSprite { bank: 0, offset: 0x4080 },
    TextureSprite { bank: 0, offset: 0x40A0 },
    TextureSprite { bank: 0, offset: 0x40C0 },
    TextureSprite { bank: 0, offset: 0x6000 },
    TextureSprite { bank: 0, offset: 0x6040 },
    TextureSprite { bank: 0, offset: 0x6080 },
    TextureSprite { bank: 0, offset: 0x60C0 },
    TextureSprite { bank: 1, offset: 0x0000 },
    TextureSprite { bank: 1, offset: 0x0040 },
    TextureSprite { bank: 1, offset: 0x0080 },
    TextureSprite { bank: 1, offset: 0x00C0 },
    TextureSprite { bank: 1, offset: 0x4000 },
    TextureSprite { bank: 1, offset: 0x4040 },
    TextureSprite { bank: 1, offset: 0x4080 },
    TextureSprite { bank: 1, offset: 0x40C0 },
    TextureSprite { bank: 1, offset: 0x0000 },
    TextureSprite { bank: 1, offset: 0x0020 },
    TextureSprite { bank: 1, offset: 0x0040 },
    TextureSprite { bank: 1, offset: 0x0060 },
    TextureSprite { bank: 1, offset: 0x0080 },
    TextureSprite { bank: 1, offset: 0x00A0 },
    TextureSprite { bank: 1, offset: 0x00C0 },
    TextureSprite { bank: 1, offset: 0x00E0 },
    TextureSprite { bank: 1, offset: 0x2000 },
    TextureSprite { bank: 1, offset: 0x2020 },
    TextureSprite { bank: 1, offset: 0x20E0 },
    TextureSprite { bank: 1, offset: 0x4080 },
    TextureSprite { bank: 1, offset: 0x40A0 },
    TextureSprite { bank: 1, offset: 0x40C0 },
    TextureSprite { bank: 1, offset: 0x40E0 },
    TextureSprite { bank: 1, offset: 0x2040 },
    TextureSprite { bank: 1, offset: 0x6080 },
    TextureSprite { bank: 1, offset: 0x7080 },
    TextureSprite { bank: 1, offset: 0x4000 },
    TextureSprite { bank: 1, offset: 0x6040 },
    TextureSprite { bank: 1, offset: 0x7040 },
    TextureSprite { bank: 1, offset: 0x2080 },
    TextureSprite { bank: 1, offset: 0x20A0 },
    TextureSprite { bank: 1, offset: 0x20C0 },
    TextureSprite { bank: 1, offset: 0x2020 },
    TextureSprite { bank: 1, offset: 0x2030 },
    TextureSprite { bank: 1, offset: 0x2080 },
    TextureSprite { bank: 1, offset: 0x20A0 },
    TextureSprite { bank: 1, offset: 0x68A0 },
    TextureSprite { bank: 1, offset: 0x68C0 },
    TextureSprite { bank: 1, offset: 0x20C0 },
    TextureSprite { bank: 255, offset: 0x0000 },
    TextureSprite { bank: 255, offset: 0x0000 }
];
