// Auto-generated by tools/sf2/extract_contact_boxes.py -- do not edit by hand.
// Extracted from the user-owned retail ROM at the docs/SF2_RECON.md
// offsets, reusing the SF1 engine formats. Regenerate with:
//   nix develop --command python3 tools/sf2/extract.py

//! Authored object-contact boxes, distinct from downward-surface profiles.
//! Variant-specific continuation links are decoded into typed group IDs.

pub const CONTACT_BOX_SHAPE_COUNT: usize = 61;
pub const CONTACT_BOX_GROUP_COUNT: usize = 94;
pub const CONTACT_BOX_RECORD_COUNT: usize = 94;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ContactBoxGroupId(usize);

impl ContactBoxGroupId {
    pub fn group(self) -> &'static ContactBoxGroup {
        &GROUPS[self.0]
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ContactBox {
    pub next: Option<ContactBoxGroupId>,
    pub center: [i16; 3],
    pub half_extents: [u16; 3],
    /// High nibble selects rotation; low nibble is the byte-axis shift.
    pub rotation_flags: u8,
    pub hit_flags: u8,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ContactBoxGroup {
    pub variant_mask: u8,
    pub variants: &'static [ContactBox],
}

// Source contact-box group $7F:494D.
static BOXES_0: [ContactBox; 1] = [ContactBox {
    next: Some(ContactBoxGroupId(1)),
    center: [0, 0, 0],
    half_extents: [10, 10, 10],
    rotation_flags: 0x80,
    hit_flags: 0x01,
}];

// Source contact-box group $7F:495F.
static BOXES_1: [ContactBox; 1] = [ContactBox {
    next: Some(ContactBoxGroupId(2)),
    center: [-25, 10, -15],
    half_extents: [10, 10, 10],
    rotation_flags: 0x80,
    hit_flags: 0x02,
}];

// Source contact-box group $7F:4971.
static BOXES_2: [ContactBox; 1] = [ContactBox {
    next: None,
    center: [25, 10, -15],
    half_extents: [10, 10, 10],
    rotation_flags: 0x80,
    hit_flags: 0x04,
}];

// Source contact-box group $7F:4983.
static BOXES_3: [ContactBox; 1] = [ContactBox {
    next: Some(ContactBoxGroupId(4)),
    center: [0, 0, 0],
    half_extents: [15, 10, 15],
    rotation_flags: 0x80,
    hit_flags: 0x01,
}];

// Source contact-box group $7F:4995.
static BOXES_4: [ContactBox; 1] = [ContactBox {
    next: Some(ContactBoxGroupId(5)),
    center: [-20, -5, -10],
    half_extents: [10, 10, 10],
    rotation_flags: 0x80,
    hit_flags: 0x02,
}];

// Source contact-box group $7F:49A7.
static BOXES_5: [ContactBox; 1] = [ContactBox {
    next: None,
    center: [20, -5, -10],
    half_extents: [10, 10, 10],
    rotation_flags: 0x80,
    hit_flags: 0x04,
}];

// Source contact-box group $7F:4AB5.
static BOXES_6: [ContactBox; 1] = [ContactBox {
    next: None,
    center: [0, 0, 0],
    half_extents: [240, 960, 240],
    rotation_flags: 0x24,
    hit_flags: 0x07,
}];

// Source contact-box group $7F:4AC7.
static BOXES_7: [ContactBox; 1] = [ContactBox {
    next: None,
    center: [0, 0, 0],
    half_extents: [240, 240, 240],
    rotation_flags: 0x24,
    hit_flags: 0x07,
}];

// Source contact-box group $7F:4AD9.
static BOXES_8: [ContactBox; 1] = [ContactBox {
    next: None,
    center: [0, 0, 0],
    half_extents: [240, 160, 240],
    rotation_flags: 0x24,
    hit_flags: 0x07,
}];

// Source contact-box group $7F:4AEB.
static BOXES_9: [ContactBox; 1] = [ContactBox {
    next: None,
    center: [0, 0, 0],
    half_extents: [240, 160, 240],
    rotation_flags: 0x24,
    hit_flags: 0x07,
}];

// Source contact-box group $7F:4AFD.
static BOXES_10: [ContactBox; 1] = [ContactBox {
    next: Some(ContactBoxGroupId(11)),
    center: [0, 0, 60],
    half_extents: [160, 320, 160],
    rotation_flags: 0x85,
    hit_flags: 0x01,
}];

// Source contact-box group $7F:4B0F.
static BOXES_11: [ContactBox; 1] = [ContactBox {
    next: Some(ContactBoxGroupId(12)),
    center: [0, 0, 40],
    half_extents: [160, 320, 160],
    rotation_flags: 0x85,
    hit_flags: 0x01,
}];

// Source contact-box group $7F:4B21.
static BOXES_12: [ContactBox; 1] = [ContactBox {
    next: Some(ContactBoxGroupId(13)),
    center: [0, 0, 20],
    half_extents: [160, 320, 160],
    rotation_flags: 0x85,
    hit_flags: 0x01,
}];

// Source contact-box group $7F:4B33.
static BOXES_13: [ContactBox; 1] = [ContactBox {
    next: Some(ContactBoxGroupId(14)),
    center: [0, 0, 0],
    half_extents: [160, 320, 160],
    rotation_flags: 0x85,
    hit_flags: 0x01,
}];

// Source contact-box group $7F:4B45.
static BOXES_14: [ContactBox; 1] = [ContactBox {
    next: Some(ContactBoxGroupId(15)),
    center: [0, 0, -20],
    half_extents: [160, 320, 160],
    rotation_flags: 0x85,
    hit_flags: 0x01,
}];

// Source contact-box group $7F:4B57.
static BOXES_15: [ContactBox; 1] = [ContactBox {
    next: None,
    center: [0, 0, -40],
    half_extents: [160, 160, 160],
    rotation_flags: 0x85,
    hit_flags: 0x01,
}];

// Source contact-box group $7F:4B69.
static BOXES_16: [ContactBox; 1] = [ContactBox {
    next: Some(ContactBoxGroupId(17)),
    center: [-30, -320, -30],
    half_extents: [160, 160, 160],
    rotation_flags: 0x23,
    hit_flags: 0x02,
}];

// Source contact-box group $7F:4B7B.
static BOXES_17: [ContactBox; 1] = [ContactBox {
    next: None,
    center: [30, -320, -30],
    half_extents: [160, 160, 160],
    rotation_flags: 0x23,
    hit_flags: 0x01,
}];

// Source contact-box group $7F:4B8D.
static BOXES_18: [ContactBox; 1] = [ContactBox {
    next: None,
    center: [0, 0, 50],
    half_extents: [64, 64, 64],
    rotation_flags: 0x83,
    hit_flags: 0x01,
}];

// Source contact-box group $7F:4B9F.
static BOXES_19: [ContactBox; 1] = [ContactBox {
    next: Some(ContactBoxGroupId(20)),
    center: [0, 0, 0],
    half_extents: [40, 40, 40],
    rotation_flags: 0x82,
    hit_flags: 0x07,
}];

// Source contact-box group $7F:4BB1.
static BOXES_20: [ContactBox; 1] = [ContactBox {
    next: Some(ContactBoxGroupId(21)),
    center: [0, 0, -20],
    half_extents: [40, 40, 40],
    rotation_flags: 0x82,
    hit_flags: 0x07,
}];

// Source contact-box group $7F:4BC3.
static BOXES_21: [ContactBox; 1] = [ContactBox {
    next: None,
    center: [0, 0, -40],
    half_extents: [40, 40, 40],
    rotation_flags: 0x82,
    hit_flags: 0x07,
}];

// Source contact-box group $7F:4BD5.
static BOXES_22: [ContactBox; 1] = [ContactBox {
    next: Some(ContactBoxGroupId(23)),
    center: [0, 0, 10],
    half_extents: [20, 20, 20],
    rotation_flags: 0x82,
    hit_flags: 0x07,
}];

// Source contact-box group $7F:4BE7.
static BOXES_23: [ContactBox; 1] = [ContactBox {
    next: Some(ContactBoxGroupId(24)),
    center: [0, 0, 30],
    half_extents: [20, 20, 20],
    rotation_flags: 0x82,
    hit_flags: 0x07,
}];

// Source contact-box group $7F:4BF9.
static BOXES_24: [ContactBox; 1] = [ContactBox {
    next: None,
    center: [0, 0, 50],
    half_extents: [20, 20, 20],
    rotation_flags: 0x82,
    hit_flags: 0x07,
}];

// Source contact-box group $7F:4C0B.
static BOXES_25: [ContactBox; 1] = [ContactBox {
    next: Some(ContactBoxGroupId(26)),
    center: [0, 0, 10],
    half_extents: [40, 40, 40],
    rotation_flags: 0x82,
    hit_flags: 0x07,
}];

// Source contact-box group $7F:4C1D.
static BOXES_26: [ContactBox; 1] = [ContactBox {
    next: Some(ContactBoxGroupId(27)),
    center: [0, 0, -20],
    half_extents: [40, 40, 40],
    rotation_flags: 0x82,
    hit_flags: 0x07,
}];

// Source contact-box group $7F:4C2F.
static BOXES_27: [ContactBox; 1] = [ContactBox {
    next: Some(ContactBoxGroupId(28)),
    center: [0, 0, -50],
    half_extents: [40, 40, 40],
    rotation_flags: 0x82,
    hit_flags: 0x07,
}];

// Source contact-box group $7F:4C41.
static BOXES_28: [ContactBox; 1] = [ContactBox {
    next: None,
    center: [0, 0, -80],
    half_extents: [40, 40, 40],
    rotation_flags: 0x82,
    hit_flags: 0x07,
}];

// Source contact-box group $7F:4C53.
static BOXES_29: [ContactBox; 1] = [ContactBox {
    next: Some(ContactBoxGroupId(30)),
    center: [0, 0, 105],
    half_extents: [40, 40, 40],
    rotation_flags: 0x83,
    hit_flags: 0x07,
}];

// Source contact-box group $7F:4C65.
static BOXES_30: [ContactBox; 1] = [ContactBox {
    next: Some(ContactBoxGroupId(31)),
    center: [0, 0, 75],
    half_extents: [40, 40, 40],
    rotation_flags: 0x83,
    hit_flags: 0x07,
}];

// Source contact-box group $7F:4C77.
static BOXES_31: [ContactBox; 1] = [ContactBox {
    next: Some(ContactBoxGroupId(32)),
    center: [0, 0, 45],
    half_extents: [40, 40, 40],
    rotation_flags: 0x83,
    hit_flags: 0x07,
}];

// Source contact-box group $7F:4C89.
static BOXES_32: [ContactBox; 1] = [ContactBox {
    next: Some(ContactBoxGroupId(33)),
    center: [0, 0, 15],
    half_extents: [40, 40, 40],
    rotation_flags: 0x83,
    hit_flags: 0x07,
}];

// Source contact-box group $7F:4C9B.
static BOXES_33: [ContactBox; 1] = [ContactBox {
    next: None,
    center: [0, 0, -15],
    half_extents: [40, 40, 40],
    rotation_flags: 0x83,
    hit_flags: 0x07,
}];

// Source contact-box group $7F:4CAD.
static BOXES_34: [ContactBox; 1] = [ContactBox {
    next: Some(ContactBoxGroupId(35)),
    center: [0, 0, 20],
    half_extents: [80, 80, 80],
    rotation_flags: 0x83,
    hit_flags: 0x07,
}];

// Source contact-box group $7F:4CBF.
static BOXES_35: [ContactBox; 1] = [ContactBox {
    next: Some(ContactBoxGroupId(36)),
    center: [0, 0, 60],
    half_extents: [80, 80, 80],
    rotation_flags: 0x83,
    hit_flags: 0x07,
}];

// Source contact-box group $7F:4CD1.
static BOXES_36: [ContactBox; 1] = [ContactBox {
    next: Some(ContactBoxGroupId(37)),
    center: [0, 0, 100],
    half_extents: [80, 80, 80],
    rotation_flags: 0x83,
    hit_flags: 0x07,
}];

// Source contact-box group $7F:4CE3.
static BOXES_37: [ContactBox; 1] = [ContactBox {
    next: Some(ContactBoxGroupId(38)),
    center: [0, 0, -20],
    half_extents: [80, 80, 80],
    rotation_flags: 0x83,
    hit_flags: 0x07,
}];

// Source contact-box group $7F:4CF5.
static BOXES_38: [ContactBox; 1] = [ContactBox {
    next: Some(ContactBoxGroupId(39)),
    center: [0, 0, -60],
    half_extents: [80, 80, 80],
    rotation_flags: 0x83,
    hit_flags: 0x07,
}];

// Source contact-box group $7F:4D07.
static BOXES_39: [ContactBox; 1] = [ContactBox {
    next: None,
    center: [0, 0, -100],
    half_extents: [80, 80, 80],
    rotation_flags: 0x83,
    hit_flags: 0x07,
}];

// Source contact-box group $7F:4D19.
static BOXES_40: [ContactBox; 1] = [ContactBox {
    next: Some(ContactBoxGroupId(41)),
    center: [0, 0, 0],
    half_extents: [280, 280, 280],
    rotation_flags: 0x83,
    hit_flags: 0x07,
}];

// Source contact-box group $7F:4D2B.
static BOXES_41: [ContactBox; 1] = [ContactBox {
    next: Some(ContactBoxGroupId(42)),
    center: [0, 0, 90],
    half_extents: [280, 280, 280],
    rotation_flags: 0x83,
    hit_flags: 0x07,
}];

// Source contact-box group $7F:4D3D.
static BOXES_42: [ContactBox; 1] = [ContactBox {
    next: None,
    center: [0, 0, -90],
    half_extents: [280, 280, 280],
    rotation_flags: 0x83,
    hit_flags: 0x07,
}];

// Source contact-box group $7F:4D4F.
static BOXES_43: [ContactBox; 1] = [ContactBox {
    next: None,
    center: [0, 0, 0],
    half_extents: [1440, 1440, 1440],
    rotation_flags: 0x25,
    hit_flags: 0x01,
}];

// Source contact-box group $7F:4D61.
static BOXES_44: [ContactBox; 1] = [ContactBox {
    next: Some(ContactBoxGroupId(45)),
    center: [0, 0, 0],
    half_extents: [80, 240, 80],
    rotation_flags: 0x23,
    hit_flags: 0x01,
}];

// Source contact-box group $7F:4D73.
static BOXES_45: [ContactBox; 1] = [ContactBox {
    next: Some(ContactBoxGroupId(46)),
    center: [0, 0, 20],
    half_extents: [80, 240, 80],
    rotation_flags: 0x23,
    hit_flags: 0x01,
}];

// Source contact-box group $7F:4D85.
static BOXES_46: [ContactBox; 1] = [ContactBox {
    next: None,
    center: [0, 0, -20],
    half_extents: [80, 240, 80],
    rotation_flags: 0x23,
    hit_flags: 0x01,
}];

// Source contact-box group $7F:4D97.
static BOXES_47: [ContactBox; 1] = [ContactBox {
    next: Some(ContactBoxGroupId(48)),
    center: [0, 0, 0],
    half_extents: [60, 60, 60],
    rotation_flags: 0x82,
    hit_flags: 0x01,
}];

// Source contact-box group $7F:4DA9.
static BOXES_48: [ContactBox; 1] = [ContactBox {
    next: Some(ContactBoxGroupId(49)),
    center: [0, 0, 100],
    half_extents: [60, 60, 60],
    rotation_flags: 0x82,
    hit_flags: 0x01,
}];

// Source contact-box group $7F:4DBB.
static BOXES_49: [ContactBox; 1] = [ContactBox {
    next: None,
    center: [0, 0, -100],
    half_extents: [60, 60, 60],
    rotation_flags: 0x82,
    hit_flags: 0x01,
}];

// Source contact-box group $7F:4DCD.
static BOXES_50: [ContactBox; 1] = [ContactBox {
    next: Some(ContactBoxGroupId(51)),
    center: [0, 0, 0],
    half_extents: [56, 80, 56],
    rotation_flags: 0x23,
    hit_flags: 0x01,
}];

// Source contact-box group $7F:4DDF.
static BOXES_51: [ContactBox; 1] = [ContactBox {
    next: None,
    center: [0, 96, 0],
    half_extents: [80, 64, 80],
    rotation_flags: 0x23,
    hit_flags: 0x01,
}];

// Source contact-box group $7F:4DF1.
static BOXES_52: [ContactBox; 1] = [ContactBox {
    next: Some(ContactBoxGroupId(53)),
    center: [15, -5, 0],
    half_extents: [192, 192, 192],
    rotation_flags: 0x85,
    hit_flags: 0x01,
}];

// Source contact-box group $7F:4E03.
static BOXES_53: [ContactBox; 1] = [ContactBox {
    next: Some(ContactBoxGroupId(54)),
    center: [15, 15, 0],
    half_extents: [192, 192, 192],
    rotation_flags: 0x85,
    hit_flags: 0x01,
}];

// Source contact-box group $7F:4E15.
static BOXES_54: [ContactBox; 1] = [ContactBox {
    next: None,
    center: [-25, 15, 0],
    half_extents: [192, 192, 192],
    rotation_flags: 0x85,
    hit_flags: 0x01,
}];

// Source contact-box group $7F:4E27.
static BOXES_55: [ContactBox; 1] = [ContactBox {
    next: Some(ContactBoxGroupId(56)),
    center: [0, -240, -60],
    half_extents: [160, 160, 160],
    rotation_flags: 0x22,
    hit_flags: 0x01,
}];

// Source contact-box group $7F:4E39.
static BOXES_56: [ContactBox; 1] = [ContactBox {
    next: None,
    center: [0, -80, -30],
    half_extents: [80, 80, 80],
    rotation_flags: 0x22,
    hit_flags: 0x01,
}];

// Source contact-box group $7F:4E4B.
static BOXES_57: [ContactBox; 1] = [ContactBox {
    next: None,
    center: [0, -120, 20],
    half_extents: [96, 96, 96],
    rotation_flags: 0x23,
    hit_flags: 0x01,
}];

// Source contact-box group $7F:4E5D.
static BOXES_58: [ContactBox; 1] = [ContactBox {
    next: None,
    center: [0, -120, 0],
    half_extents: [40, 120, 40],
    rotation_flags: 0x22,
    hit_flags: 0x01,
}];

// Source contact-box group $7F:4E6F.
static BOXES_59: [ContactBox; 1] = [ContactBox {
    next: None,
    center: [0, 0, 40],
    half_extents: [60, 60, 60],
    rotation_flags: 0x21,
    hit_flags: 0x01,
}];

// Source contact-box group $7F:4E81.
static BOXES_60: [ContactBox; 1] = [ContactBox {
    next: Some(ContactBoxGroupId(61)),
    center: [0, 0, 0],
    half_extents: [72, 80, 72],
    rotation_flags: 0x23,
    hit_flags: 0x01,
}];

// Source contact-box group $7F:4E93.
static BOXES_61: [ContactBox; 1] = [ContactBox {
    next: Some(ContactBoxGroupId(62)),
    center: [23, 0, 0],
    half_extents: [72, 80, 72],
    rotation_flags: 0x23,
    hit_flags: 0x01,
}];

// Source contact-box group $7F:4EA5.
static BOXES_62: [ContactBox; 1] = [ContactBox {
    next: None,
    center: [-23, 0, 0],
    half_extents: [72, 80, 72],
    rotation_flags: 0x23,
    hit_flags: 0x01,
}];

// Source contact-box group $7F:4EED.
static BOXES_63: [ContactBox; 1] = [ContactBox {
    next: Some(ContactBoxGroupId(64)),
    center: [0, 0, -35],
    half_extents: [240, 240, 240],
    rotation_flags: 0x23,
    hit_flags: 0x01,
}];

// Source contact-box group $7F:4EFF.
static BOXES_64: [ContactBox; 1] = [ContactBox {
    next: None,
    center: [0, 0, 25],
    half_extents: [240, 240, 240],
    rotation_flags: 0x23,
    hit_flags: 0x01,
}];

// Source contact-box group $7F:4F11.
static BOXES_65: [ContactBox; 1] = [ContactBox {
    next: Some(ContactBoxGroupId(66)),
    center: [0, 0, -15],
    half_extents: [40, 40, 40],
    rotation_flags: 0x22,
    hit_flags: 0x01,
}];

// Source contact-box group $7F:4F23.
static BOXES_66: [ContactBox; 1] = [ContactBox {
    next: Some(ContactBoxGroupId(67)),
    center: [0, 0, -45],
    half_extents: [40, 40, 40],
    rotation_flags: 0x22,
    hit_flags: 0x01,
}];

// Source contact-box group $7F:4F35.
static BOXES_67: [ContactBox; 1] = [ContactBox {
    next: Some(ContactBoxGroupId(68)),
    center: [0, 0, -75],
    half_extents: [40, 40, 40],
    rotation_flags: 0x22,
    hit_flags: 0x01,
}];

// Source contact-box group $7F:4F47.
static BOXES_68: [ContactBox; 1] = [ContactBox {
    next: Some(ContactBoxGroupId(69)),
    center: [0, 0, 15],
    half_extents: [40, 40, 40],
    rotation_flags: 0x22,
    hit_flags: 0x01,
}];

// Source contact-box group $7F:4F59.
static BOXES_69: [ContactBox; 1] = [ContactBox {
    next: Some(ContactBoxGroupId(70)),
    center: [0, 0, 45],
    half_extents: [40, 40, 40],
    rotation_flags: 0x22,
    hit_flags: 0x01,
}];

// Source contact-box group $7F:4F6B.
static BOXES_70: [ContactBox; 1] = [ContactBox {
    next: None,
    center: [0, 0, 75],
    half_extents: [40, 40, 40],
    rotation_flags: 0x22,
    hit_flags: 0x01,
}];

// Source contact-box group $7F:4F7D.
static BOXES_71: [ContactBox; 1] = [ContactBox {
    next: None,
    center: [0, 0, -20],
    half_extents: [200, 200, 200],
    rotation_flags: 0x23,
    hit_flags: 0x01,
}];

// Source contact-box group $7F:4F8F.
static BOXES_72: [ContactBox; 1] = [ContactBox {
    next: Some(ContactBoxGroupId(73)),
    center: [20, 0, -18],
    half_extents: [40, 120, 40],
    rotation_flags: 0x21,
    hit_flags: 0x01,
}];

// Source contact-box group $7F:4FA1.
static BOXES_73: [ContactBox; 1] = [ContactBox {
    next: None,
    center: [-20, 0, -18],
    half_extents: [40, 120, 40],
    rotation_flags: 0x21,
    hit_flags: 0x01,
}];

// Source contact-box group $7F:4FB3.
static BOXES_74: [ContactBox; 1] = [ContactBox {
    next: Some(ContactBoxGroupId(75)),
    center: [0, 0, 40],
    half_extents: [160, 160, 160],
    rotation_flags: 0x22,
    hit_flags: 0x01,
}];

// Source contact-box group $7F:4FC5.
static BOXES_75: [ContactBox; 1] = [ContactBox {
    next: Some(ContactBoxGroupId(76)),
    center: [0, 0, 80],
    half_extents: [160, 160, 160],
    rotation_flags: 0x22,
    hit_flags: 0x01,
}];

// Source contact-box group $7F:4FD7.
static BOXES_76: [ContactBox; 1] = [ContactBox {
    next: Some(ContactBoxGroupId(77)),
    center: [0, 0, -40],
    half_extents: [160, 160, 160],
    rotation_flags: 0x22,
    hit_flags: 0x01,
}];

// Source contact-box group $7F:4FE9.
static BOXES_77: [ContactBox; 1] = [ContactBox {
    next: None,
    center: [0, 0, -80],
    half_extents: [160, 160, 160],
    rotation_flags: 0x22,
    hit_flags: 0x01,
}];

// Source contact-box group $7F:4FFB.
static BOXES_78: [ContactBox; 1] = [ContactBox {
    next: Some(ContactBoxGroupId(79)),
    center: [0, 0, 0],
    half_extents: [160, 160, 160],
    rotation_flags: 0x23,
    hit_flags: 0x01,
}];

// Source contact-box group $7F:500D.
static BOXES_79: [ContactBox; 1] = [ContactBox {
    next: Some(ContactBoxGroupId(80)),
    center: [0, -160, 40],
    half_extents: [160, 160, 160],
    rotation_flags: 0x23,
    hit_flags: 0x01,
}];

// Source contact-box group $7F:501F.
static BOXES_80: [ContactBox; 1] = [ContactBox {
    next: None,
    center: [0, 80, -30],
    half_extents: [160, 160, 160],
    rotation_flags: 0x23,
    hit_flags: 0x01,
}];

// Source contact-box group $7F:5031.
static BOXES_81: [ContactBox; 1] = [ContactBox {
    next: None,
    center: [45, 200, 0],
    half_extents: [60, 200, 60],
    rotation_flags: 0x22,
    hit_flags: 0x01,
}];

// Source contact-box group $7F:5043.
static BOXES_82: [ContactBox; 1] = [ContactBox {
    next: None,
    center: [-45, 200, 0],
    half_extents: [60, 200, 60],
    rotation_flags: 0x22,
    hit_flags: 0x01,
}];

// Source contact-box group $7F:5055.
static BOXES_83: [ContactBox; 1] = [ContactBox {
    next: None,
    center: [0, -30, 0],
    half_extents: [40, 30, 20],
    rotation_flags: 0x21,
    hit_flags: 0x01,
}];

// Source contact-box group $7F:5067.
static BOXES_84: [ContactBox; 1] = [ContactBox {
    next: None,
    center: [0, -130, 0],
    half_extents: [40, 30, 20],
    rotation_flags: 0x21,
    hit_flags: 0x01,
}];

// Source contact-box group $7F:50C1.
static BOXES_85: [ContactBox; 1] = [ContactBox {
    next: Some(ContactBoxGroupId(86)),
    center: [0, -10, 0],
    half_extents: [10, 10, 10],
    rotation_flags: 0x21,
    hit_flags: 0x01,
}];

// Source contact-box group $7F:50D3.
static BOXES_86: [ContactBox; 1] = [ContactBox {
    next: Some(ContactBoxGroupId(87)),
    center: [0, -30, 0],
    half_extents: [10, 10, 10],
    rotation_flags: 0x21,
    hit_flags: 0x01,
}];

// Source contact-box group $7F:50E5.
static BOXES_87: [ContactBox; 1] = [ContactBox {
    next: Some(ContactBoxGroupId(88)),
    center: [0, -50, 0],
    half_extents: [10, 10, 10],
    rotation_flags: 0x21,
    hit_flags: 0x01,
}];

// Source contact-box group $7F:50F7.
static BOXES_88: [ContactBox; 1] = [ContactBox {
    next: None,
    center: [0, -70, 0],
    half_extents: [10, 10, 10],
    rotation_flags: 0x21,
    hit_flags: 0x01,
}];

// Source contact-box group $7F:5109.
static BOXES_89: [ContactBox; 1] = [ContactBox {
    next: Some(ContactBoxGroupId(90)),
    center: [-70, -80, 0],
    half_extents: [80, 80, 80],
    rotation_flags: 0x23,
    hit_flags: 0x01,
}];

// Source contact-box group $7F:511B.
static BOXES_90: [ContactBox; 1] = [ContactBox {
    next: Some(ContactBoxGroupId(91)),
    center: [-40, -80, 0],
    half_extents: [80, 80, 80],
    rotation_flags: 0x23,
    hit_flags: 0x01,
}];

// Source contact-box group $7F:512D.
static BOXES_91: [ContactBox; 1] = [ContactBox {
    next: Some(ContactBoxGroupId(92)),
    center: [40, -80, 0],
    half_extents: [80, 80, 80],
    rotation_flags: 0x23,
    hit_flags: 0x01,
}];

// Source contact-box group $7F:513F.
static BOXES_92: [ContactBox; 1] = [ContactBox {
    next: Some(ContactBoxGroupId(93)),
    center: [70, -80, 0],
    half_extents: [80, 80, 80],
    rotation_flags: 0x23,
    hit_flags: 0x01,
}];

// Source contact-box group $7F:5151.
static BOXES_93: [ContactBox; 1] = [ContactBox {
    next: None,
    center: [0, -80, 0],
    half_extents: [80, 80, 80],
    rotation_flags: 0x23,
    hit_flags: 0x02,
}];

static GROUPS: [ContactBoxGroup; 94] = [
    ContactBoxGroup {
        variant_mask: 0x00,
        variants: &BOXES_0,
    },
    ContactBoxGroup {
        variant_mask: 0x00,
        variants: &BOXES_1,
    },
    ContactBoxGroup {
        variant_mask: 0x00,
        variants: &BOXES_2,
    },
    ContactBoxGroup {
        variant_mask: 0x00,
        variants: &BOXES_3,
    },
    ContactBoxGroup {
        variant_mask: 0x00,
        variants: &BOXES_4,
    },
    ContactBoxGroup {
        variant_mask: 0x00,
        variants: &BOXES_5,
    },
    ContactBoxGroup {
        variant_mask: 0x00,
        variants: &BOXES_6,
    },
    ContactBoxGroup {
        variant_mask: 0x00,
        variants: &BOXES_7,
    },
    ContactBoxGroup {
        variant_mask: 0x00,
        variants: &BOXES_8,
    },
    ContactBoxGroup {
        variant_mask: 0x00,
        variants: &BOXES_9,
    },
    ContactBoxGroup {
        variant_mask: 0x00,
        variants: &BOXES_10,
    },
    ContactBoxGroup {
        variant_mask: 0x00,
        variants: &BOXES_11,
    },
    ContactBoxGroup {
        variant_mask: 0x00,
        variants: &BOXES_12,
    },
    ContactBoxGroup {
        variant_mask: 0x00,
        variants: &BOXES_13,
    },
    ContactBoxGroup {
        variant_mask: 0x00,
        variants: &BOXES_14,
    },
    ContactBoxGroup {
        variant_mask: 0x00,
        variants: &BOXES_15,
    },
    ContactBoxGroup {
        variant_mask: 0x00,
        variants: &BOXES_16,
    },
    ContactBoxGroup {
        variant_mask: 0x00,
        variants: &BOXES_17,
    },
    ContactBoxGroup {
        variant_mask: 0x00,
        variants: &BOXES_18,
    },
    ContactBoxGroup {
        variant_mask: 0x00,
        variants: &BOXES_19,
    },
    ContactBoxGroup {
        variant_mask: 0x00,
        variants: &BOXES_20,
    },
    ContactBoxGroup {
        variant_mask: 0x00,
        variants: &BOXES_21,
    },
    ContactBoxGroup {
        variant_mask: 0x00,
        variants: &BOXES_22,
    },
    ContactBoxGroup {
        variant_mask: 0x00,
        variants: &BOXES_23,
    },
    ContactBoxGroup {
        variant_mask: 0x00,
        variants: &BOXES_24,
    },
    ContactBoxGroup {
        variant_mask: 0x00,
        variants: &BOXES_25,
    },
    ContactBoxGroup {
        variant_mask: 0x00,
        variants: &BOXES_26,
    },
    ContactBoxGroup {
        variant_mask: 0x00,
        variants: &BOXES_27,
    },
    ContactBoxGroup {
        variant_mask: 0x00,
        variants: &BOXES_28,
    },
    ContactBoxGroup {
        variant_mask: 0x00,
        variants: &BOXES_29,
    },
    ContactBoxGroup {
        variant_mask: 0x00,
        variants: &BOXES_30,
    },
    ContactBoxGroup {
        variant_mask: 0x00,
        variants: &BOXES_31,
    },
    ContactBoxGroup {
        variant_mask: 0x00,
        variants: &BOXES_32,
    },
    ContactBoxGroup {
        variant_mask: 0x00,
        variants: &BOXES_33,
    },
    ContactBoxGroup {
        variant_mask: 0x00,
        variants: &BOXES_34,
    },
    ContactBoxGroup {
        variant_mask: 0x00,
        variants: &BOXES_35,
    },
    ContactBoxGroup {
        variant_mask: 0x00,
        variants: &BOXES_36,
    },
    ContactBoxGroup {
        variant_mask: 0x00,
        variants: &BOXES_37,
    },
    ContactBoxGroup {
        variant_mask: 0x00,
        variants: &BOXES_38,
    },
    ContactBoxGroup {
        variant_mask: 0x00,
        variants: &BOXES_39,
    },
    ContactBoxGroup {
        variant_mask: 0x00,
        variants: &BOXES_40,
    },
    ContactBoxGroup {
        variant_mask: 0x00,
        variants: &BOXES_41,
    },
    ContactBoxGroup {
        variant_mask: 0x00,
        variants: &BOXES_42,
    },
    ContactBoxGroup {
        variant_mask: 0x00,
        variants: &BOXES_43,
    },
    ContactBoxGroup {
        variant_mask: 0x00,
        variants: &BOXES_44,
    },
    ContactBoxGroup {
        variant_mask: 0x00,
        variants: &BOXES_45,
    },
    ContactBoxGroup {
        variant_mask: 0x00,
        variants: &BOXES_46,
    },
    ContactBoxGroup {
        variant_mask: 0x00,
        variants: &BOXES_47,
    },
    ContactBoxGroup {
        variant_mask: 0x00,
        variants: &BOXES_48,
    },
    ContactBoxGroup {
        variant_mask: 0x00,
        variants: &BOXES_49,
    },
    ContactBoxGroup {
        variant_mask: 0x00,
        variants: &BOXES_50,
    },
    ContactBoxGroup {
        variant_mask: 0x00,
        variants: &BOXES_51,
    },
    ContactBoxGroup {
        variant_mask: 0x00,
        variants: &BOXES_52,
    },
    ContactBoxGroup {
        variant_mask: 0x00,
        variants: &BOXES_53,
    },
    ContactBoxGroup {
        variant_mask: 0x00,
        variants: &BOXES_54,
    },
    ContactBoxGroup {
        variant_mask: 0x00,
        variants: &BOXES_55,
    },
    ContactBoxGroup {
        variant_mask: 0x00,
        variants: &BOXES_56,
    },
    ContactBoxGroup {
        variant_mask: 0x00,
        variants: &BOXES_57,
    },
    ContactBoxGroup {
        variant_mask: 0x00,
        variants: &BOXES_58,
    },
    ContactBoxGroup {
        variant_mask: 0x00,
        variants: &BOXES_59,
    },
    ContactBoxGroup {
        variant_mask: 0x00,
        variants: &BOXES_60,
    },
    ContactBoxGroup {
        variant_mask: 0x00,
        variants: &BOXES_61,
    },
    ContactBoxGroup {
        variant_mask: 0x00,
        variants: &BOXES_62,
    },
    ContactBoxGroup {
        variant_mask: 0x00,
        variants: &BOXES_63,
    },
    ContactBoxGroup {
        variant_mask: 0x00,
        variants: &BOXES_64,
    },
    ContactBoxGroup {
        variant_mask: 0x00,
        variants: &BOXES_65,
    },
    ContactBoxGroup {
        variant_mask: 0x00,
        variants: &BOXES_66,
    },
    ContactBoxGroup {
        variant_mask: 0x00,
        variants: &BOXES_67,
    },
    ContactBoxGroup {
        variant_mask: 0x00,
        variants: &BOXES_68,
    },
    ContactBoxGroup {
        variant_mask: 0x00,
        variants: &BOXES_69,
    },
    ContactBoxGroup {
        variant_mask: 0x00,
        variants: &BOXES_70,
    },
    ContactBoxGroup {
        variant_mask: 0x00,
        variants: &BOXES_71,
    },
    ContactBoxGroup {
        variant_mask: 0x00,
        variants: &BOXES_72,
    },
    ContactBoxGroup {
        variant_mask: 0x00,
        variants: &BOXES_73,
    },
    ContactBoxGroup {
        variant_mask: 0x00,
        variants: &BOXES_74,
    },
    ContactBoxGroup {
        variant_mask: 0x00,
        variants: &BOXES_75,
    },
    ContactBoxGroup {
        variant_mask: 0x00,
        variants: &BOXES_76,
    },
    ContactBoxGroup {
        variant_mask: 0x00,
        variants: &BOXES_77,
    },
    ContactBoxGroup {
        variant_mask: 0x00,
        variants: &BOXES_78,
    },
    ContactBoxGroup {
        variant_mask: 0x00,
        variants: &BOXES_79,
    },
    ContactBoxGroup {
        variant_mask: 0x00,
        variants: &BOXES_80,
    },
    ContactBoxGroup {
        variant_mask: 0x00,
        variants: &BOXES_81,
    },
    ContactBoxGroup {
        variant_mask: 0x00,
        variants: &BOXES_82,
    },
    ContactBoxGroup {
        variant_mask: 0x00,
        variants: &BOXES_83,
    },
    ContactBoxGroup {
        variant_mask: 0x00,
        variants: &BOXES_84,
    },
    ContactBoxGroup {
        variant_mask: 0x00,
        variants: &BOXES_85,
    },
    ContactBoxGroup {
        variant_mask: 0x00,
        variants: &BOXES_86,
    },
    ContactBoxGroup {
        variant_mask: 0x00,
        variants: &BOXES_87,
    },
    ContactBoxGroup {
        variant_mask: 0x00,
        variants: &BOXES_88,
    },
    ContactBoxGroup {
        variant_mask: 0x00,
        variants: &BOXES_89,
    },
    ContactBoxGroup {
        variant_mask: 0x00,
        variants: &BOXES_90,
    },
    ContactBoxGroup {
        variant_mask: 0x00,
        variants: &BOXES_91,
    },
    ContactBoxGroup {
        variant_mask: 0x00,
        variants: &BOXES_92,
    },
    ContactBoxGroup {
        variant_mask: 0x00,
        variants: &BOXES_93,
    },
];

/// None selects the shape header's ordinary bounds.
pub fn contact_boxes_by_index(index: usize) -> Option<ContactBoxGroupId> {
    match index {
        25 => Some(ContactBoxGroupId(25)),
        26 => Some(ContactBoxGroupId(22)),
        27 => Some(ContactBoxGroupId(29)),
        28 => Some(ContactBoxGroupId(34)),
        29 => Some(ContactBoxGroupId(40)),
        42 => Some(ContactBoxGroupId(43)),
        47 => Some(ContactBoxGroupId(18)),
        52 => Some(ContactBoxGroupId(0)),
        85 => Some(ContactBoxGroupId(3)),
        118 => Some(ContactBoxGroupId(10)),
        128 => Some(ContactBoxGroupId(44)),
        129 => Some(ContactBoxGroupId(44)),
        137 => Some(ContactBoxGroupId(52)),
        138 => Some(ContactBoxGroupId(29)),
        139 => Some(ContactBoxGroupId(29)),
        140 => Some(ContactBoxGroupId(29)),
        155 => Some(ContactBoxGroupId(60)),
        162 => Some(ContactBoxGroupId(65)),
        163 => Some(ContactBoxGroupId(65)),
        164 => Some(ContactBoxGroupId(47)),
        177 => Some(ContactBoxGroupId(71)),
        178 => Some(ContactBoxGroupId(71)),
        181 => Some(ContactBoxGroupId(74)),
        231 => Some(ContactBoxGroupId(50)),
        317 => Some(ContactBoxGroupId(16)),
        329 => Some(ContactBoxGroupId(6)),
        330 => Some(ContactBoxGroupId(7)),
        331 => Some(ContactBoxGroupId(8)),
        332 => Some(ContactBoxGroupId(9)),
        335 => Some(ContactBoxGroupId(55)),
        357 => Some(ContactBoxGroupId(19)),
        358 => Some(ContactBoxGroupId(25)),
        359 => Some(ContactBoxGroupId(22)),
        360 => Some(ContactBoxGroupId(25)),
        361 => Some(ContactBoxGroupId(22)),
        363 => Some(ContactBoxGroupId(25)),
        364 => Some(ContactBoxGroupId(22)),
        365 => Some(ContactBoxGroupId(34)),
        366 => Some(ContactBoxGroupId(40)),
        368 => Some(ContactBoxGroupId(25)),
        394 => Some(ContactBoxGroupId(22)),
        395 => Some(ContactBoxGroupId(22)),
        396 => Some(ContactBoxGroupId(22)),
        406 => Some(ContactBoxGroupId(34)),
        407 => Some(ContactBoxGroupId(40)),
        408 => Some(ContactBoxGroupId(34)),
        421 => Some(ContactBoxGroupId(57)),
        422 => Some(ContactBoxGroupId(57)),
        424 => Some(ContactBoxGroupId(58)),
        462 => Some(ContactBoxGroupId(78)),
        470 => Some(ContactBoxGroupId(89)),
        513 => Some(ContactBoxGroupId(59)),
        519 => Some(ContactBoxGroupId(63)),
        521 => Some(ContactBoxGroupId(72)),
        543 => Some(ContactBoxGroupId(85)),
        544 => Some(ContactBoxGroupId(83)),
        545 => Some(ContactBoxGroupId(83)),
        546 => Some(ContactBoxGroupId(84)),
        547 => Some(ContactBoxGroupId(84)),
        567 => Some(ContactBoxGroupId(81)),
        568 => Some(ContactBoxGroupId(82)),
        _ => None,
    }
}
