// Auto-generated by tools/sf2/extract_audio.py -- do not edit by hand.
// Extracted from the user-owned retail ROM at the docs/SF2_RECON.md
// offsets, reusing the SF1 engine formats. Regenerate with:
//   nix develop --command python3 tools/sf2/extract.py

//! Verification-only decoding of the retail SF2 host audio tables.

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct UploadProgram {
    pub source_record_offset: u16,
    pub preload_command: Option<u8>,
    pub start_cue: u8,
    pub blob_ids: &'static [u16],
}

pub const SOURCE_MODE_COUNT: usize = 16;
pub const UPLOAD_PROGRAM_COUNT: usize = 50;
pub const BASE_BOOT_BLOB_IDS: [u16; 2] = [3, 4];

static PROGRAM_00_BLOBS: [u16; 5] = [15, 45, 2, 51, 52];
static PROGRAM_01_BLOBS: [u16; 6] = [17, 28, 41, 42, 2, 50];
static PROGRAM_02_BLOBS: [u16; 5] = [16, 45, 2, 51, 61];
static PROGRAM_03_BLOBS: [u16; 1] = [16];
static PROGRAM_04_BLOBS: [u16; 2] = [16, 45];
static PROGRAM_05_BLOBS: [u16; 5] = [16, 45, 2, 51, 61];
static PROGRAM_06_BLOBS: [u16; 4] = [18, 41, 42, 50];
static PROGRAM_07_BLOBS: [u16; 6] = [35, 19, 41, 42, 56, 58];
static PROGRAM_08_BLOBS: [u16; 6] = [35, 20, 41, 43, 53, 58];
static PROGRAM_09_BLOBS: [u16; 6] = [35, 21, 41, 42, 53, 59];
static PROGRAM_10_BLOBS: [u16; 6] = [35, 22, 41, 42, 56, 58];
static PROGRAM_11_BLOBS: [u16; 5] = [35, 23, 41, 43, 53];
static PROGRAM_12_BLOBS: [u16; 5] = [39, 24, 45, 56, 60];
static PROGRAM_13_BLOBS: [u16; 4] = [39, 36, 25, 45];
static PROGRAM_14_BLOBS: [u16; 7] = [39, 36, 32, 45, 2, 51, 52];
static PROGRAM_15_BLOBS: [u16; 4] = [39, 36, 27, 45];
static PROGRAM_16_BLOBS: [u16; 4] = [39, 36, 27, 45];
static PROGRAM_17_BLOBS: [u16; 6] = [39, 36, 40, 25, 45, 55];
static PROGRAM_18_BLOBS: [u16; 6] = [39, 36, 40, 26, 45, 55];
static PROGRAM_19_BLOBS: [u16; 6] = [39, 36, 27, 45, 53, 57];
static PROGRAM_20_BLOBS: [u16; 5] = [39, 36, 29, 45, 51];
static PROGRAM_21_BLOBS: [u16; 5] = [39, 36, 30, 45, 54];
static PROGRAM_22_BLOBS: [u16; 5] = [39, 36, 40, 45, 55];
static PROGRAM_23_BLOBS: [u16; 4] = [31, 45, 46, 47];
static PROGRAM_24_BLOBS: [u16; 3] = [31, 45, 1];
static PROGRAM_25_BLOBS: [u16; 2] = [31, 45];
static PROGRAM_26_BLOBS: [u16; 3] = [17, 41, 42];
static PROGRAM_27_BLOBS: [u16; 1] = [17];
static PROGRAM_28_BLOBS: [u16; 4] = [15, 45, 1, 51];
static PROGRAM_29_BLOBS: [u16; 0] = [];
static PROGRAM_30_BLOBS: [u16; 0] = [];
static PROGRAM_31_BLOBS: [u16; 2] = [15, 45];
static PROGRAM_32_BLOBS: [u16; 3] = [38, 45, 48];
static PROGRAM_33_BLOBS: [u16; 0] = [];
static PROGRAM_34_BLOBS: [u16; 3] = [34, 45, 44];
static PROGRAM_35_BLOBS: [u16; 7] = [39, 36, 32, 33, 45, 2, 51];
static PROGRAM_36_BLOBS: [u16; 0] = [];
static PROGRAM_37_BLOBS: [u16; 0] = [];
static PROGRAM_38_BLOBS: [u16; 2] = [38, 45];
static PROGRAM_39_BLOBS: [u16; 0] = [];
static PROGRAM_40_BLOBS: [u16; 3] = [17, 41, 42];
static PROGRAM_41_BLOBS: [u16; 3] = [17, 41, 42];
static PROGRAM_42_BLOBS: [u16; 5] = [35, 28, 41, 42, 58];
static PROGRAM_43_BLOBS: [u16; 4] = [39, 36, 29, 45];
static PROGRAM_44_BLOBS: [u16; 4] = [39, 36, 30, 45];
static PROGRAM_45_BLOBS: [u16; 3] = [17, 41, 42];
static PROGRAM_46_BLOBS: [u16; 4] = [37, 35, 41, 42];
static PROGRAM_47_BLOBS: [u16; 5] = [39, 36, 37, 45, 49];
static PROGRAM_48_BLOBS: [u16; 6] = [35, 19, 41, 42, 56, 58];
static PROGRAM_49_BLOBS: [u16; 0] = [];

pub static UPLOAD_PROGRAMS: [UploadProgram; UPLOAD_PROGRAM_COUNT] = [
    UploadProgram {
        source_record_offset: 0x000,
        preload_command: Some(0x05),
        start_cue: 0xF9,
        blob_ids: &PROGRAM_00_BLOBS,
    },
    UploadProgram {
        source_record_offset: 0x011,
        preload_command: Some(0x01),
        start_cue: 0xFB,
        blob_ids: &PROGRAM_01_BLOBS,
    },
    UploadProgram {
        source_record_offset: 0x025,
        preload_command: None,
        start_cue: 0xF9,
        blob_ids: &PROGRAM_02_BLOBS,
    },
    UploadProgram {
        source_record_offset: 0x036,
        preload_command: Some(0x05),
        start_cue: 0xFB,
        blob_ids: &PROGRAM_03_BLOBS,
    },
    UploadProgram {
        source_record_offset: 0x03B,
        preload_command: Some(0x06),
        start_cue: 0xFB,
        blob_ids: &PROGRAM_04_BLOBS,
    },
    UploadProgram {
        source_record_offset: 0x043,
        preload_command: None,
        start_cue: 0xFB,
        blob_ids: &PROGRAM_05_BLOBS,
    },
    UploadProgram {
        source_record_offset: 0x054,
        preload_command: Some(0x01),
        start_cue: 0xFB,
        blob_ids: &PROGRAM_06_BLOBS,
    },
    UploadProgram {
        source_record_offset: 0x062,
        preload_command: Some(0x01),
        start_cue: 0xFB,
        blob_ids: &PROGRAM_07_BLOBS,
    },
    UploadProgram {
        source_record_offset: 0x076,
        preload_command: Some(0x01),
        start_cue: 0xFB,
        blob_ids: &PROGRAM_08_BLOBS,
    },
    UploadProgram {
        source_record_offset: 0x08A,
        preload_command: Some(0x01),
        start_cue: 0xFB,
        blob_ids: &PROGRAM_09_BLOBS,
    },
    UploadProgram {
        source_record_offset: 0x09E,
        preload_command: Some(0x01),
        start_cue: 0xFB,
        blob_ids: &PROGRAM_10_BLOBS,
    },
    UploadProgram {
        source_record_offset: 0x0B2,
        preload_command: Some(0x01),
        start_cue: 0xFB,
        blob_ids: &PROGRAM_11_BLOBS,
    },
    UploadProgram {
        source_record_offset: 0x0C3,
        preload_command: Some(0x01),
        start_cue: 0xFC,
        blob_ids: &PROGRAM_12_BLOBS,
    },
    UploadProgram {
        source_record_offset: 0x0D4,
        preload_command: Some(0x01),
        start_cue: 0xF9,
        blob_ids: &PROGRAM_13_BLOBS,
    },
    UploadProgram {
        source_record_offset: 0x0E2,
        preload_command: Some(0x01),
        start_cue: 0xFA,
        blob_ids: &PROGRAM_14_BLOBS,
    },
    UploadProgram {
        source_record_offset: 0x0F9,
        preload_command: Some(0x01),
        start_cue: 0xF9,
        blob_ids: &PROGRAM_15_BLOBS,
    },
    UploadProgram {
        source_record_offset: 0x107,
        preload_command: Some(0x01),
        start_cue: 0xF9,
        blob_ids: &PROGRAM_16_BLOBS,
    },
    UploadProgram {
        source_record_offset: 0x115,
        preload_command: Some(0x01),
        start_cue: 0xF9,
        blob_ids: &PROGRAM_17_BLOBS,
    },
    UploadProgram {
        source_record_offset: 0x129,
        preload_command: Some(0x01),
        start_cue: 0xF9,
        blob_ids: &PROGRAM_18_BLOBS,
    },
    UploadProgram {
        source_record_offset: 0x13D,
        preload_command: Some(0x01),
        start_cue: 0xF9,
        blob_ids: &PROGRAM_19_BLOBS,
    },
    UploadProgram {
        source_record_offset: 0x151,
        preload_command: Some(0x01),
        start_cue: 0xF9,
        blob_ids: &PROGRAM_20_BLOBS,
    },
    UploadProgram {
        source_record_offset: 0x162,
        preload_command: Some(0x01),
        start_cue: 0xF9,
        blob_ids: &PROGRAM_21_BLOBS,
    },
    UploadProgram {
        source_record_offset: 0x173,
        preload_command: Some(0x02),
        start_cue: 0xF9,
        blob_ids: &PROGRAM_22_BLOBS,
    },
    UploadProgram {
        source_record_offset: 0x184,
        preload_command: Some(0x02),
        start_cue: 0xF9,
        blob_ids: &PROGRAM_23_BLOBS,
    },
    UploadProgram {
        source_record_offset: 0x192,
        preload_command: None,
        start_cue: 0xF9,
        blob_ids: &PROGRAM_24_BLOBS,
    },
    UploadProgram {
        source_record_offset: 0x19D,
        preload_command: None,
        start_cue: 0xF9,
        blob_ids: &PROGRAM_25_BLOBS,
    },
    UploadProgram {
        source_record_offset: 0x1A5,
        preload_command: Some(0x03),
        start_cue: 0xFB,
        blob_ids: &PROGRAM_26_BLOBS,
    },
    UploadProgram {
        source_record_offset: 0x1B0,
        preload_command: Some(0x03),
        start_cue: 0xFB,
        blob_ids: &PROGRAM_27_BLOBS,
    },
    UploadProgram {
        source_record_offset: 0x1B5,
        preload_command: Some(0x01),
        start_cue: 0xF9,
        blob_ids: &PROGRAM_28_BLOBS,
    },
    UploadProgram {
        source_record_offset: 0x1C3,
        preload_command: Some(0x03),
        start_cue: 0xF9,
        blob_ids: &PROGRAM_29_BLOBS,
    },
    UploadProgram {
        source_record_offset: 0x1C5,
        preload_command: None,
        start_cue: 0xF9,
        blob_ids: &PROGRAM_30_BLOBS,
    },
    UploadProgram {
        source_record_offset: 0x1C7,
        preload_command: Some(0x04),
        start_cue: 0xF9,
        blob_ids: &PROGRAM_31_BLOBS,
    },
    UploadProgram {
        source_record_offset: 0x1CF,
        preload_command: Some(0x01),
        start_cue: 0xF9,
        blob_ids: &PROGRAM_32_BLOBS,
    },
    UploadProgram {
        source_record_offset: 0x1DA,
        preload_command: None,
        start_cue: 0xF9,
        blob_ids: &PROGRAM_33_BLOBS,
    },
    UploadProgram {
        source_record_offset: 0x1DC,
        preload_command: Some(0x01),
        start_cue: 0xFB,
        blob_ids: &PROGRAM_34_BLOBS,
    },
    UploadProgram {
        source_record_offset: 0x1E7,
        preload_command: Some(0x01),
        start_cue: 0xF9,
        blob_ids: &PROGRAM_35_BLOBS,
    },
    UploadProgram {
        source_record_offset: 0x1FE,
        preload_command: Some(0x04),
        start_cue: 0xF9,
        blob_ids: &PROGRAM_36_BLOBS,
    },
    UploadProgram {
        source_record_offset: 0x200,
        preload_command: None,
        start_cue: 0xF9,
        blob_ids: &PROGRAM_37_BLOBS,
    },
    UploadProgram {
        source_record_offset: 0x202,
        preload_command: Some(0x03),
        start_cue: 0xF9,
        blob_ids: &PROGRAM_38_BLOBS,
    },
    UploadProgram {
        source_record_offset: 0x20A,
        preload_command: None,
        start_cue: 0xF9,
        blob_ids: &PROGRAM_39_BLOBS,
    },
    UploadProgram {
        source_record_offset: 0x20C,
        preload_command: Some(0x01),
        start_cue: 0xFB,
        blob_ids: &PROGRAM_40_BLOBS,
    },
    UploadProgram {
        source_record_offset: 0x217,
        preload_command: Some(0x01),
        start_cue: 0xFB,
        blob_ids: &PROGRAM_41_BLOBS,
    },
    UploadProgram {
        source_record_offset: 0x222,
        preload_command: Some(0x01),
        start_cue: 0xFB,
        blob_ids: &PROGRAM_42_BLOBS,
    },
    UploadProgram {
        source_record_offset: 0x233,
        preload_command: Some(0x01),
        start_cue: 0xF9,
        blob_ids: &PROGRAM_43_BLOBS,
    },
    UploadProgram {
        source_record_offset: 0x241,
        preload_command: Some(0x01),
        start_cue: 0xFA,
        blob_ids: &PROGRAM_44_BLOBS,
    },
    UploadProgram {
        source_record_offset: 0x24F,
        preload_command: None,
        start_cue: 0xF9,
        blob_ids: &PROGRAM_45_BLOBS,
    },
    UploadProgram {
        source_record_offset: 0x25A,
        preload_command: Some(0x01),
        start_cue: 0xFB,
        blob_ids: &PROGRAM_46_BLOBS,
    },
    UploadProgram {
        source_record_offset: 0x268,
        preload_command: Some(0x01),
        start_cue: 0xF9,
        blob_ids: &PROGRAM_47_BLOBS,
    },
    UploadProgram {
        source_record_offset: 0x279,
        preload_command: Some(0x01),
        start_cue: 0xFB,
        blob_ids: &PROGRAM_48_BLOBS,
    },
    UploadProgram {
        source_record_offset: 0x28D,
        preload_command: None,
        start_cue: 0xF9,
        blob_ids: &PROGRAM_49_BLOBS,
    },
];

pub const SOURCE_MODE_PROGRAM_INDEX: [usize; 16] =
    [0, 49, 6, 23, 49, 46, 1, 2, 24, 27, 26, 25, 5, 49, 49, 49];

static CONDITIONAL_00_BLOBS: [u16; 0] = [];
static CONDITIONAL_01_BLOBS: [u16; 1] = [51];
static CONDITIONAL_02_BLOBS: [u16; 1] = [52];
static CONDITIONAL_03_BLOBS: [u16; 1] = [53];
static CONDITIONAL_04_BLOBS: [u16; 1] = [54];
static CONDITIONAL_05_BLOBS: [u16; 1] = [55];
static CONDITIONAL_06_BLOBS: [u16; 1] = [56];
static CONDITIONAL_07_BLOBS: [u16; 1] = [57];
static CONDITIONAL_08_BLOBS: [u16; 1] = [51];
static CONDITIONAL_09_BLOBS: [u16; 1] = [52];

pub static CONDITIONAL_BLOB_IDS: [&[u16]; 10] = [
    &CONDITIONAL_00_BLOBS,
    &CONDITIONAL_01_BLOBS,
    &CONDITIONAL_02_BLOBS,
    &CONDITIONAL_03_BLOBS,
    &CONDITIONAL_04_BLOBS,
    &CONDITIONAL_05_BLOBS,
    &CONDITIONAL_06_BLOBS,
    &CONDITIONAL_07_BLOBS,
    &CONDITIONAL_08_BLOBS,
    &CONDITIONAL_09_BLOBS,
];

pub const PILOT_BLOB_IDS: [u16; 7] = [9, 10, 11, 12, 13, 14, 3];
