// Auto-generated by tools/sf2/extract_palettes.py -- do not edit by hand.
// Extracted from the user-owned retail ROM at the docs/SF2_RECON.md
// offsets, reusing the SF1 engine formats. Regenerate with:
//   nix develop --command python3 tools/sf2/extract.py

//! Exact SF2 polygon-palette catalog as ordinary BGR555 assets.
//!
//! Shipping code selects these rows by semantic scene identity; the
//! source catalog position is represented only by this typed data id.

pub const COLORS_PER_POLYGON_PALETTE: usize = 16;
pub const POLYGON_PALETTE_COUNT: usize = 5;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u8)]
pub enum PolygonPaletteId {
    Standard = 0,
    CatalogOne = 1,
    CatalogTwo = 2,
    EladardSurface = 3,
    AstropolisExterior = 4,
}

impl PolygonPaletteId {
    pub const fn colors(self) -> &'static [u16; COLORS_PER_POLYGON_PALETTE] {
        &POLYGON_PALETTES[self as usize]
    }
}

#[rustfmt::skip]
pub static POLYGON_PALETTES:
    [[u16; COLORS_PER_POLYGON_PALETTE]; POLYGON_PALETTE_COUNT] = [
    [0x0000, 0x0C6F, 0x1559, 0x22BD, 0x377F, 0x4C63, 0x6D29, 0x7E8F, 0x7F76, 0x0CA3, 0x1D27, 0x35ED, 0x52D4, 0x6B9A, 0x7BFE, 0x1B46],
    [0x0000, 0x2C8B, 0x4952, 0x5E17, 0x767D, 0x4C63, 0x6D29, 0x7E8F, 0x7F76, 0x1C63, 0x28E3, 0x3986, 0x566D, 0x7754, 0x7FD8, 0x4AE6],
    [0x0000, 0x0C6F, 0x153A, 0x22BD, 0x377F, 0x4C68, 0x6D0D, 0x7E34, 0x7EF7, 0x0C66, 0x18CB, 0x2D70, 0x4A58, 0x631D, 0x77BF, 0x1AD1],
    [0x0000, 0x0C6F, 0x1559, 0x22BD, 0x377F, 0x4C63, 0x6D29, 0x7E8F, 0x7F76, 0x10C4, 0x2148, 0x35ED, 0x52D4, 0x6B9A, 0x7BFE, 0x1B46],
    [0x0000, 0x28B1, 0x395A, 0x4A9E, 0x573F, 0x60A5, 0x7D4A, 0x7EB0, 0x7F97, 0x24C4, 0x3548, 0x4E0E, 0x66D4, 0x7B9A, 0x7FFE, 0x4F06],
];
