// Auto-generated by tools/sf2/extract_shapes.py -- do not edit by hand.
// Extracted from the user-owned retail ROM at the docs/SF2_RECON.md
// offsets, reusing the SF1 engine formats. Regenerate with:
//   nix develop --command python3 tools/sf2/extract.py

//! SF2 3D shape data -- UNVERIFIED CANDIDATES ONLY.
//!
//! Struct layout mirrors `sf_render::shape_data`. HOWEVER: applying
//! SF1's point/face byte-grammar to SF2 banks 0x12-0x17 does NOT
//! recover SF2's shapes -- 0 self-consistent face streams parse and
//! the point-block matches below are largely coincidental. SF2's
//! GSU-2 3D data is reordered/re-encoded (likely compressed)
//! relative to SF1. Real shape extraction is DEFERRED to the
//! disassembly-gated phase (see docs/SF2_RECON.md sections 3 & 5).
//! Diagnostics: byte point-block candidates=5, word candidates=6, face streams=0.

/// Mesh vertex, matching `sf_render::shape_data::ShapeVertex`.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct ShapeVertex {
    pub x: f32,
    pub y: f32,
    pub z: f32,
}

/// Polygon face, matching `sf_render::shape_data::ShapeFace`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ShapeFace {
    pub vertex_indices: [u16; 12],
    pub num_verts: u8,
    pub color_index: u8,
}

/// One candidate shape, matching `sf_render::shape_data::ShapeDataEntry`.
#[derive(Debug, Clone, Copy)]
pub struct ShapeDataEntry {
    pub shape_id: u16,
    /// Source ROM file offset of the point block (for later verification).
    pub rom_off: u32,
    pub vertices: &'static [ShapeVertex],
    pub faces: &'static [ShapeFace],
    pub name: &'static str,
}

const fn v(x: f32, y: f32, z: f32) -> ShapeVertex { ShapeVertex { x, y, z } }

// Candidate 0: bank $14 @ 0x0A20E6, 4 verts
static SHAPE_0_VERTS: [ShapeVertex; 4] = [
    v(13.0, -13.0, 13.0),
    v(13.0, -13.0, 13.0),
    v(13.0, -13.0, 13.0),
    v(13.0, -9.0, 9.0),
];
// Candidate 1: bank $16 @ 0x0B7263, 11 verts
static SHAPE_1_VERTS: [ShapeVertex; 11] = [
    v(-31.0, -67.0, -128.0),
    v(-64.0, 64.0, 112.0),
    v(-16.0, 100.0, 124.0),
    v(6.0, 66.0, -80.0),
    v(-82.0, 56.0, -105.0),
    v(79.0, 31.0, -84.0),
    v(17.0, 117.0, 7.0),
    v(-112.0, -45.0, 13.0),
    v(-32.0, -14.0, -8.0),
    v(14.0, 100.0, 79.0),
    v(16.0, -25.0, -113.0),
];
// Candidate 2: bank $17 @ 0x0B8B38, 7 verts
static SHAPE_2_VERTS: [ShapeVertex; 7] = [
    v(7.0, -102.0, -16.0),
    v(-40.0, -48.0, -52.0),
    v(0.0, -18.0, 13.0),
    v(-29.0, 61.0, 1.0),
    v(-119.0, 125.0, -109.0),
    v(-111.0, 119.0, 119.0),
    v(12.0, -7.0, 19.0),
];
// Candidate 3: bank $17 @ 0x0B92BC, 15 verts
static SHAPE_3_VERTS: [ShapeVertex; 15] = [
    v(0.0, -41.0, -80.0),
    v(-16.0, -93.0, -95.0),
    v(3.0, 80.0, -1.0),
    v(-95.0, -3.0, 66.0),
    v(112.0, 0.0, 115.0),
    v(-124.0, 120.0, 7.0),
    v(-60.0, -32.0, 49.0),
    v(46.0, -49.0, 30.0),
    v(10.0, 117.0, 38.0),
    v(16.0, -37.0, 29.0),
    v(-110.0, -32.0, 3.0),
    v(-124.0, 97.0, 58.0),
    v(-122.0, 94.0, 37.0),
    v(119.0, -60.0, 52.0),
    v(-1.0, 13.0, -12.0),
];
// Candidate 4: bank $17 @ 0x0BB5A3, 45 verts
static SHAPE_4_VERTS: [ShapeVertex; 45] = [
    v(8.0, -24.0, 20.0),
    v(52.0, -73.0, -56.0),
    v(28.0, -29.0, -111.0),
    v(1.0, -36.0, 0.0),
    v(104.0, -33.0, -45.0),
    v(-62.0, 26.0, 7.0),
    v(-50.0, -14.0, 62.0),
    v(63.0, 1.0, -2.0),
    v(3.0, 4.0, 3.0),
    v(-4.0, -3.0, -4.0),
    v(3.0, 4.0, 3.0),
    v(-4.0, -3.0, -4.0),
    v(3.0, 4.0, 3.0),
    v(-4.0, -1.0, -4.0),
    v(1.0, 4.0, 1.0),
    v(-4.0, -1.0, -4.0),
    v(1.0, 4.0, 1.0),
    v(-4.0, -1.0, -4.0),
    v(1.0, 4.0, 9.0),
    v(-10.0, -17.0, -18.0),
    v(32.0, -94.0, 1.0),
    v(63.0, -1.0, -97.0),
    v(-127.0, 34.0, -128.0),
    v(-34.0, 128.0, -34.0),
    v(1.0, 2.0, 1.0),
    v(-1.0, 127.0, -2.0),
    v(-64.0, 2.0, 96.0),
    v(126.0, -32.0, 63.0),
    v(33.0, -63.0, 33.0),
    v(62.0, 0.0, 58.0),
    v(0.0, -58.0, 48.0),
    v(8.0, -112.0, 74.0),
    v(114.0, -74.0, 48.0),
    v(72.0, -52.0, 76.0),
    v(112.0, -13.0, -3.0),
    v(-57.0, 3.0, -57.0),
    v(-1.0, 57.0, -3.0),
    v(-59.0, 3.0, -59.0),
    v(-1.0, 121.0, -1.0),
    v(-121.0, 1.0, -126.0),
    v(0.0, -120.0, 1.0),
    v(-7.0, -70.0, 124.0),
    v(0.0, -1.0, -15.0),
    v(-31.0, 32.0, 96.0),
    v(52.0, -1.0, 3.0),
];

static NO_FACES: [ShapeFace; 0] = [];

pub const SHAPE_DATA_COUNT: usize = 5;
pub static SHAPE_DATA: [ShapeDataEntry; SHAPE_DATA_COUNT] = [
    ShapeDataEntry { shape_id: 0, rom_off: 0x0A20E6, vertices: &SHAPE_0_VERTS, faces: &NO_FACES, name: "sf2_cand_0" },
    ShapeDataEntry { shape_id: 1, rom_off: 0x0B7263, vertices: &SHAPE_1_VERTS, faces: &NO_FACES, name: "sf2_cand_1" },
    ShapeDataEntry { shape_id: 2, rom_off: 0x0B8B38, vertices: &SHAPE_2_VERTS, faces: &NO_FACES, name: "sf2_cand_2" },
    ShapeDataEntry { shape_id: 3, rom_off: 0x0B92BC, vertices: &SHAPE_3_VERTS, faces: &NO_FACES, name: "sf2_cand_3" },
    ShapeDataEntry { shape_id: 4, rom_off: 0x0BB5A3, vertices: &SHAPE_4_VERTS, faces: &NO_FACES, name: "sf2_cand_4" },
];
