// Auto-generated by tools/sf2/extract_surface_particles.py -- do not edit by hand.
// Extracted from the user-owned retail ROM at the docs/SF2_RECON.md
// offsets, reusing the SF1 engine formats. Regenerate with:
//   nix develop --command python3 tools/sf2/extract.py

//! Exact color-pair bytes for surface-selected ambient particles.

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SurfaceParticlePalette {
    Negative,
    Nonnegative,
}

impl SurfaceParticlePalette {
    pub const fn colors(self) -> &'static [u8; 8] {
        match self {
            Self::Negative => &[0x76, 0x76, 0x76, 0x75, 0x74, 0x74, 0x77, 0x74],
            Self::Nonnegative => &[0x65, 0x65, 0x65, 0x65, 0x74, 0x74, 0x74, 0x74],
        }
    }
}
