// @generated by tools/sf2/generate_native_paths.py; do not edit.
//! Complete statically lowered source paths. This is an explicit subset,
//! not a fallback catalog for paths that have not been ported.
use super::path_appearance::{AnimationChannel, AnimationCommand};
use super::path_commands::ControlCommand;
use super::path_program::{PathCatalog, Statement};
use super::{PathCursor, PathId};

const fn cursor(path: u16, command_index: u16) -> PathCursor {
    PathCursor {
        path: PathId::from_catalog_index(path),
        command_index,
    }
}
pub const ALTERNATE_EXHAUST: PathCursor = cursor(0, 0);
pub const LOWERED_ROOT_COUNT: usize = 1;
pub const LOWERED_COMMAND_COUNT: usize = 5;
pub fn catalog() -> PathCatalog {
    PathCatalog::new(vec![vec![
        Statement::Sprite {
            color: 0,
            size: 0,
            next: cursor(0, 1),
        },
        Statement::Control(ControlCommand::BeginLoop {
            iterations: 3,
            next: cursor(0, 2),
        }),
        Statement::Animation {
            command: AnimationCommand::Advance {
                channel: AnimationChannel::Color,
                amount: 1,
                period: 2,
            },
            next: cursor(0, 3),
        },
        Statement::Control(ControlCommand::Next {
            immediate: false,
            next: cursor(0, 4),
        }),
        Statement::Control(ControlCommand::End),
    ]])
    .expect("generated catalog indices fit native cursors")
}
