// Auto-generated by tools/sf2/generate_native_maps.py; do not edit by hand.
//! Reviewed authored map scripts as a typed native catalog.

use super::hit_response::HitSide;
use super::map_effects::{DisplayModeRequest, MapEffect, MapSpawn, PresentationByte};
use super::scene_map::{
    CatalogError, MapActorSpawn, MapCatalog, MapCondition, MapCursor, MapInstruction, PhaseExit,
};
use super::{Behavior, ObjectKind, ShapeId, Vector3};

pub const MAP_COMMAND_COUNT: usize = 44;
/// `$05:8003`.
pub const SCENE_PLAYER_PROLOGUE: MapCursor = MapCursor::from_index(0);
/// `$05:FBE7`.
pub const ATTRACT_SCENE_SIX: MapCursor = MapCursor::from_index(24);
/// `$05:8035`.
pub const ATTRACT_SCENE_SEVEN: MapCursor = MapCursor::from_index(5);

pub static MAP_INSTRUCTIONS: [MapInstruction<MapEffect, MapSpawn>; 44] = [
    // $05:8003
    MapInstruction::Spawn {
        specification: MapSpawn::Actor(MapActorSpawn {
            kind: ObjectKind::Player,
            shape: ShapeId::from_catalog_index(0),
            behavior: Behavior::PlayerSceneInit(HitSide::Primary),
            position: Vector3 {
                x: 400,
                y: -150,
                z: 0,
            },
        }),
        marker: 0,
        next: MapCursor::from_index(1),
    },
    // $05:8011
    MapInstruction::Branch {
        condition: MapCondition::SinglePlayer,
        taken: MapCursor::from_index(3),
        otherwise: MapCursor::from_index(2),
    },
    // $05:8021
    MapInstruction::Spawn {
        specification: MapSpawn::Actor(MapActorSpawn {
            kind: ObjectKind::Player,
            shape: ShapeId::from_catalog_index(0),
            behavior: Behavior::PlayerSceneInit(HitSide::Secondary),
            position: Vector3 {
                x: 200,
                y: -50,
                z: 0,
            },
        }),
        marker: 0,
        next: MapCursor::from_index(3),
    },
    // $05:802F
    MapInstruction::Apply {
        effect: MapEffect::Presentation(PresentationByte::PlayerCountLatch, 1),
        next: MapCursor::from_index(4),
    },
    // $05:8034
    MapInstruction::Stop,
    // $05:8035
    MapInstruction::Apply {
        effect: MapEffect::DisplayMode(DisplayModeRequest::Blank),
        next: MapCursor::from_index(6),
    },
    // $05:8036
    MapInstruction::Await {
        condition: MapCondition::DisplayReady,
        retry_marker: Some(1),
        next: MapCursor::from_index(7),
    },
    // $05:8037
    MapInstruction::Apply {
        effect: MapEffect::SceneLoad(3),
        next: MapCursor::from_index(8),
    },
    // $05:803A
    MapInstruction::Await {
        condition: MapCondition::LoadTableIdle,
        retry_marker: None,
        next: MapCursor::from_index(9),
    },
    // $05:803B
    MapInstruction::Apply {
        effect: MapEffect::LoaderHold,
        next: MapCursor::from_index(10),
    },
    // $05:803C
    MapInstruction::Apply {
        effect: MapEffect::ResetSceneDisplay,
        next: MapCursor::from_index(11),
    },
    // $05:8040
    MapInstruction::Apply {
        effect: MapEffect::Presentation(PresentationByte::SceneStyle, 10),
        next: MapCursor::from_index(12),
    },
    // $05:8045
    MapInstruction::Apply {
        effect: MapEffect::AmbientControl(80),
        next: MapCursor::from_index(13),
    },
    // $05:8048
    MapInstruction::Apply {
        effect: MapEffect::Presentation(PresentationByte::TitleLayout, 32),
        next: MapCursor::from_index(14),
    },
    // $05:804D
    MapInstruction::Apply {
        effect: MapEffect::DisplayMode(DisplayModeRequest::Scene),
        next: MapCursor::from_index(15),
    },
    // $05:804E
    MapInstruction::Apply {
        effect: MapEffect::HandoffFlags(0),
        next: MapCursor::from_index(16),
    },
    // $05:8053
    MapInstruction::Apply {
        effect: MapEffect::ActionGate(1),
        next: MapCursor::from_index(17),
    },
    // $05:8058
    MapInstruction::Apply {
        effect: MapEffect::SceneSelection(7),
        next: MapCursor::from_index(18),
    },
    // $05:805D
    MapInstruction::Jump(MapCursor::from_index(19)),
    // $05:8063
    MapInstruction::Apply {
        effect: MapEffect::SaveContinuation(MapCursor::from_index(22)),
        next: MapCursor::from_index(20),
    },
    // $05:8068
    MapInstruction::Yield {
        marker: 5000,
        next: MapCursor::from_index(21),
    },
    // $05:806B
    MapInstruction::Jump(MapCursor::from_index(20)),
    // $05:806F
    MapInstruction::Yield {
        marker: 5000,
        next: MapCursor::from_index(23),
    },
    // $05:8072
    MapInstruction::Jump(MapCursor::from_index(22)),
    // $05:FBE7
    MapInstruction::Apply {
        effect: MapEffect::DisplayMode(DisplayModeRequest::Blank),
        next: MapCursor::from_index(25),
    },
    // $05:FBE8
    MapInstruction::Await {
        condition: MapCondition::DisplayReady,
        retry_marker: Some(1),
        next: MapCursor::from_index(26),
    },
    // $05:FBE9
    MapInstruction::Apply {
        effect: MapEffect::SceneLoad(141),
        next: MapCursor::from_index(27),
    },
    // $05:FBEC
    MapInstruction::Await {
        condition: MapCondition::LoadTableIdle,
        retry_marker: None,
        next: MapCursor::from_index(28),
    },
    // $05:FBED
    MapInstruction::Apply {
        effect: MapEffect::LoaderHold,
        next: MapCursor::from_index(29),
    },
    // $05:FBEE
    MapInstruction::Apply {
        effect: MapEffect::CameraProjectionBase(400),
        next: MapCursor::from_index(30),
    },
    // $05:FBF4
    MapInstruction::Apply {
        effect: MapEffect::ResetSceneDisplay,
        next: MapCursor::from_index(31),
    },
    // $05:FBF8
    MapInstruction::Apply {
        effect: MapEffect::Presentation(PresentationByte::SceneStyle, 3),
        next: MapCursor::from_index(32),
    },
    // $05:FBFD
    MapInstruction::Apply {
        effect: MapEffect::DisplayMode(DisplayModeRequest::Scene),
        next: MapCursor::from_index(33),
    },
    // $05:FBFE
    MapInstruction::Apply {
        effect: MapEffect::AmbientControl(80),
        next: MapCursor::from_index(34),
    },
    // $05:FC01
    MapInstruction::Apply {
        effect: MapEffect::Presentation(PresentationByte::TitleLayout, 64),
        next: MapCursor::from_index(35),
    },
    // $05:FC06
    MapInstruction::Apply {
        effect: MapEffect::HandoffFlags(0),
        next: MapCursor::from_index(36),
    },
    // $05:FC0B
    MapInstruction::Apply {
        effect: MapEffect::ActionGate(1),
        next: MapCursor::from_index(37),
    },
    // $05:FC10
    MapInstruction::Apply {
        effect: MapEffect::SceneSelection(6),
        next: MapCursor::from_index(38),
    },
    // $05:FC15
    MapInstruction::Jump(MapCursor::from_index(39)),
    // $05:FC1B
    MapInstruction::Apply {
        effect: MapEffect::SaveContinuation(MapCursor::from_index(42)),
        next: MapCursor::from_index(40),
    },
    // $05:FC20
    MapInstruction::Yield {
        marker: 5000,
        next: MapCursor::from_index(41),
    },
    // $05:FC23
    MapInstruction::Jump(MapCursor::from_index(40)),
    // $05:FC27
    MapInstruction::Yield {
        marker: 5000,
        next: MapCursor::from_index(43),
    },
    // $05:FC2A
    MapInstruction::Jump(MapCursor::from_index(42)),
];

pub static MAP_PHASE_EXITS: [PhaseExit; 2] = [
    PhaseExit {
        parked: MapCursor::from_index(21),
        continuation: MapCursor::from_index(22),
    },
    PhaseExit {
        parked: MapCursor::from_index(41),
        continuation: MapCursor::from_index(42),
    },
];

pub fn catalog() -> Result<MapCatalog<'static, MapEffect, MapSpawn>, CatalogError> {
    MapCatalog::new(&MAP_INSTRUCTIONS, &MAP_PHASE_EXITS)
}
