//! Generated semantic continuation of the retail first-sortie fighter task.
//! Source addresses and machine state remain in oracle tooling.

use super::{FighterLogicDispatch, FighterLogicDispatchPair, FighterRandomCadence};

pub(super) const START_RETAIL_FRAME: u16 = 2_452;
#[cfg(test)]
pub(super) const LAST_VISIBLE_RETAIL_FRAME: u16 = 3_652;
pub(super) const END_RETAIL_FRAME: u16 = 3_656;
pub(super) const LOWER_DEPARTURE_RETAIL_FRAME: u16 = 2_452;
pub(super) const UPPER_DEPARTURE_RETAIL_FRAME: u16 = 3_656;

pub(super) const DISPATCH: [FighterLogicDispatchPair; 302] = [
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::ThreeQuarterWave,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::ApplyWave,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Wait,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::PrepareMovement,
        FighterLogicDispatch::Wait,
    ).with_upper_next_slice(
        FighterLogicDispatch::FinishPreparedAndBeginMovement,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::MovementContinuation,
        FighterLogicDispatch::Wait,
    ).with_upper_next_slice(
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Wait,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Wait,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::PrepareMovement,
        FighterLogicDispatch::Wait,
    ).with_upper_next_slice(
        FighterLogicDispatch::FinishPreparedAndBeginMovement,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::MovementContinuation,
        FighterLogicDispatch::Wait,
    ).with_upper_next_slice(
        FighterLogicDispatch::PrepareWave,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::ApplyWave,
        FighterLogicDispatch::Wait,
    ).with_upper_next_slice(
        FighterLogicDispatch::QuarterWave,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::ApplyWave,
        FighterLogicDispatch::Wait,
    ).with_upper_next_slice(
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ).with_upper_next_slices(
        FighterLogicDispatch::AdvanceCurrentMovement,
        FighterLogicDispatch::SplitWave,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::ApplyWave,
        FighterLogicDispatch::Wait,
    ).with_upper_next_slice(
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ).with_upper_next_slices(
        FighterLogicDispatch::AdvanceCurrentMovement,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ).with_upper_next_slices(
        FighterLogicDispatch::AdvanceCurrentMovement,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ).with_upper_next_slices(
        FighterLogicDispatch::AdvanceCurrentMovement,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::PrepareMovement,
        FighterLogicDispatch::Wait,
    ).with_upper_next_slice(
        FighterLogicDispatch::FinishPreparedAndBeginMovement,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::PrepareMovement,
        FighterLogicDispatch::Wait,
    ).with_upper_next_slice(
        FighterLogicDispatch::FinishPreparedAndBeginMovement,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::MovementContinuation,
        FighterLogicDispatch::Wait,
    ).with_upper_next_slices(
        FighterLogicDispatch::PitchContinuation,
        FighterLogicDispatch::CompleteAfterEarlyAltitude,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::PrepareMovement,
        FighterLogicDispatch::Wait,
    ).with_upper_next_slice(
        FighterLogicDispatch::FinishPreparedAndBeginMovement,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::MovementContinuation,
        FighterLogicDispatch::Wait,
    ).with_upper_next_slice(
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ).with_upper_next_slices(
        FighterLogicDispatch::AdvanceCurrentMovement,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::PrepareWave,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::ApplyWave,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ).with_upper_next_slices(
        FighterLogicDispatch::AdvanceCurrentMovement,
        FighterLogicDispatch::TurnOnly,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::MovementContinuation,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Wait,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::PrepareMovement,
        FighterLogicDispatch::Wait,
    ).with_upper_next_slice(
        FighterLogicDispatch::FinishPreparedAndBeginMovement,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::MovementContinuation,
        FighterLogicDispatch::Wait,
    ).with_upper_next_slice(
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::AltitudeAndTurnOnly,
        FighterLogicDispatch::Wait,
    ).with_upper_next_slice(
        FighterLogicDispatch::FinishPreparedAndBeginMovement,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ).with_upper_next_slice(
        FighterLogicDispatch::CompleteAfterEarlyAltitude,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ).with_upper_next_slices(
        FighterLogicDispatch::AdvanceCurrentMovement,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::PrepareMovement,
        FighterLogicDispatch::Wait,
    ).with_upper_next_slice(
        FighterLogicDispatch::FinishPreparedAndBeginMovement,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::MovementContinuation,
        FighterLogicDispatch::Wait,
    ).with_upper_next_slice(
        FighterLogicDispatch::CompleteAfterEarlyAltitude,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ).with_upper_next_slices(
        FighterLogicDispatch::AdvanceCurrentMovement,
        FighterLogicDispatch::PrepareWave,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::ApplyWave,
        FighterLogicDispatch::Wait,
    ).with_upper_next_slice(
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ).with_upper_next_slices(
        FighterLogicDispatch::AdvanceCurrentMovement,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ).with_upper_next_slices(
        FighterLogicDispatch::AdvanceCurrentMovement,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ).with_upper_next_slices(
        FighterLogicDispatch::AdvanceCurrentMovement,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ).with_upper_next_slices(
        FighterLogicDispatch::AdvanceCurrentMovement,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ).with_upper_next_slices(
        FighterLogicDispatch::AdvanceCurrentMovement,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ).with_upper_next_slices(
        FighterLogicDispatch::AdvanceCurrentMovement,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ).with_upper_next_slices(
        FighterLogicDispatch::AdvanceCurrentMovement,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ).with_upper_next_slices(
        FighterLogicDispatch::AdvanceCurrentMovement,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ).with_upper_next_slices(
        FighterLogicDispatch::AdvanceCurrentMovement,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::PrepareMovement,
        FighterLogicDispatch::Wait,
    ).with_upper_next_slice(
        FighterLogicDispatch::FinishPreparedAndBeginMovement,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::MovementContinuation,
        FighterLogicDispatch::Wait,
    ).with_upper_next_slice(
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Wait,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Wait,
        FighterLogicDispatch::Wait,
    ),
];

pub(super) const RANDOM_CADENCE: [FighterRandomCadence; 302] = [
    FighterRandomCadence::around_fighter_checks(0, 0, 2),
    FighterRandomCadence::around_fighter_checks(0, 0, 2),
    FighterRandomCadence::around_fighter_checks(0, 0, 2),
    FighterRandomCadence::around_fighter_checks(0, 0, 2),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 2),
    FighterRandomCadence::around_fighter_checks(0, 0, 2),
    FighterRandomCadence::around_fighter_checks(0, 0, 2),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 2),
    FighterRandomCadence::around_fighter_checks(0, 0, 2),
    FighterRandomCadence::around_fighter_checks(0, 0, 2),
    FighterRandomCadence::around_fighter_checks(0, 0, 2),
    FighterRandomCadence::around_fighter_checks(0, 0, 2),
    FighterRandomCadence::around_fighter_checks(0, 0, 2),
    FighterRandomCadence::around_fighter_checks(0, 0, 2),
    FighterRandomCadence::around_fighter_checks(0, 0, 2),
    FighterRandomCadence::around_fighter_checks(0, 0, 2),
    FighterRandomCadence::around_fighter_checks(0, 0, 2),
    FighterRandomCadence::around_fighter_checks(0, 0, 2),
    FighterRandomCadence::around_fighter_checks(0, 0, 2),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 2),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 4),
    FighterRandomCadence::around_fighter_checks(0, 0, 0),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 0),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 2),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 2),
    FighterRandomCadence::around_fighter_checks(0, 0, 0),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 3),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 2),
    FighterRandomCadence::around_fighter_checks(0, 0, 2),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 2),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 2),
    FighterRandomCadence::around_fighter_checks(0, 0, 0),
    FighterRandomCadence::around_fighter_checks(0, 0, 2),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 2),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 2),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 2),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 2),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 2),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 3),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 3),
    FighterRandomCadence::around_fighter_checks(0, 0, 0),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 2),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 2),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 2),
    FighterRandomCadence::around_fighter_checks(0, 0, 0),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 3),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 3),
    FighterRandomCadence::around_fighter_checks(0, 0, 0),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 2),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 2),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 2),
    FighterRandomCadence::around_fighter_checks(0, 0, 0),
    FighterRandomCadence::around_fighter_checks(0, 0, 2),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 2),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 2),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 3),
    FighterRandomCadence::around_fighter_checks(0, 0, 2),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 2),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 2),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 2),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 2),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 3),
    FighterRandomCadence::around_fighter_checks(0, 0, 0),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 2),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 2),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 2),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 2),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::around_fighter_checks(0, 0, 2),
    FighterRandomCadence::around_fighter_checks(0, 0, 3),
    FighterRandomCadence::around_fighter_checks(0, 0, 2),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
];

#[cfg(test)]
pub(super) const EXPECTED_RANDOM_STATES: [[u8; 4]; 302] = [
    [116, 148, 245, 5],
    [81, 143, 165, 193],
    [199, 70, 42, 208],
    [162, 61, 231, 96],
    [122, 100, 125, 28],
    [213, 235, 82, 215],
    [191, 255, 104, 169],
    [60, 45, 215, 41],
    [209, 14, 55, 13],
    [50, 234, 94, 224],
    [200, 141, 165, 157],
    [55, 243, 93, 102],
    [87, 3, 30, 159],
    [224, 234, 180, 30],
    [166, 76, 11, 233],
    [242, 100, 22, 177],
    [52, 69, 206, 7],
    [217, 245, 213, 189],
    [190, 146, 132, 52],
    [186, 136, 225, 110],
    [155, 244, 163, 194],
    [164, 166, 2, 64],
    [75, 24, 29, 98],
    [103, 50, 21, 179],
    [4, 52, 31, 108],
    [63, 207, 175, 67],
    [60, 111, 191, 123],
    [84, 204, 12, 145],
    [148, 135, 122, 233],
    [19, 12, 146, 168],
    [183, 6, 116, 203],
    [185, 176, 60, 113],
    [98, 240, 132, 139],
    [254, 113, 236, 96],
    [65, 140, 160, 63],
    [146, 180, 19, 212],
    [98, 221, 201, 245],
    [97, 132, 186, 196],
    [97, 132, 186, 196],
    [251, 220, 33, 93],
    [164, 30, 253, 159],
    [67, 133, 136, 232],
    [8, 189, 52, 76],
    [192, 74, 21, 201],
    [214, 117, 96, 151],
    [146, 96, 0, 105],
    [53, 49, 49, 200],
    [212, 3, 210, 9],
    [32, 208, 254, 244],
    [4, 234, 153, 62],
    [60, 25, 127, 64],
    [38, 34, 163, 98],
    [214, 3, 96, 253],
    [158, 210, 114, 117],
    [68, 203, 88, 227],
    [247, 120, 31, 60],
    [44, 126, 95, 35],
    [254, 173, 77, 42],
    [218, 80, 3, 217],
    [210, 137, 134, 173],
    [66, 72, 194, 20],
    [224, 249, 54, 34],
    [173, 230, 175, 141],
    [219, 198, 22, 137],
    [153, 20, 254, 116],
    [227, 243, 108, 91],
    [68, 239, 130, 39],
    [101, 84, 209, 169],
    [47, 16, 63, 149],
    [26, 30, 223, 73],
    [183, 251, 27, 210],
    [21, 187, 159, 205],
    [213, 89, 185, 235],
    [0, 123, 194, 214],
    [233, 132, 193, 234],
    [194, 213, 14, 1],
    [26, 236, 221, 220],
    [87, 45, 79, 114],
    [16, 41, 218, 103],
    [147, 230, 11, 164],
    [104, 172, 160, 252],
    [181, 187, 26, 30],
    [11, 249, 222, 192],
    [74, 83, 33, 176],
    [15, 227, 14, 234],
    [34, 43, 28, 50],
    [135, 142, 180, 12],
    [176, 248, 67, 55],
    [140, 183, 115, 60],
    [152, 212, 96, 36],
    [166, 195, 98, 62],
    [155, 226, 127, 65],
    [91, 184, 56, 247],
    [22, 162, 105, 114],
    [128, 115, 9, 151],
    [132, 222, 219, 111],
    [55, 47, 102, 12],
    [194, 85, 180, 31],
    [214, 108, 184, 152],
    [66, 105, 177, 24],
    [204, 216, 38, 14],
    [242, 243, 204, 190],
    [128, 254, 49, 115],
    [81, 217, 137, 173],
    [238, 119, 237, 63],
    [91, 118, 137, 73],
    [182, 228, 90, 17],
    [175, 209, 118, 101],
    [82, 221, 102, 1],
    [114, 69, 56, 44],
    [85, 44, 244, 199],
    [22, 40, 52, 108],
    [54, 237, 184, 76],
    [12, 72, 143, 66],
    [228, 195, 51, 241],
    [245, 245, 7, 12],
    [246, 255, 247, 235],
    [28, 246, 254, 18],
    [247, 37, 38, 19],
    [161, 209, 171, 152],
    [233, 207, 35, 139],
    [133, 103, 113, 6],
    [32, 29, 172, 165],
    [246, 140, 54, 134],
    [182, 105, 51, 173],
    [181, 76, 25, 108],
    [45, 104, 79, 227],
    [99, 196, 116, 145],
    [52, 158, 41, 152],
    [42, 8, 157, 201],
    [143, 33, 132, 186],
    [159, 109, 233, 46],
    [207, 35, 35, 60],
    [125, 171, 136, 76],
    [126, 209, 72, 252],
    [232, 172, 99, 103],
    [136, 59, 216, 112],
    [95, 12, 82, 155],
    [95, 12, 82, 155],
    [5, 82, 0, 101],
    [78, 148, 226, 149],
    [242, 185, 214, 64],
    [47, 56, 98, 33],
    [67, 246, 147, 114],
    [2, 76, 184, 69],
    [180, 181, 252, 182],
    [150, 254, 1, 75],
    [180, 151, 149, 74],
    [136, 28, 135, 60],
    [31, 107, 228, 167],
    [7, 179, 206, 38],
    [86, 83, 132, 93],
    [202, 2, 126, 32],
    [246, 45, 224, 187],
    [54, 200, 232, 44],
    [33, 109, 132, 87],
    [181, 179, 46, 215],
    [69, 1, 211, 251],
    [46, 67, 112, 116],
    [215, 234, 121, 5],
    [150, 236, 114, 109],
    [50, 169, 54, 201],
    [85, 136, 81, 136],
    [156, 204, 122, 242],
    [197, 207, 84, 98],
    [121, 245, 160, 62],
    [42, 131, 226, 163],
    [245, 166, 195, 31],
    [118, 78, 139, 107],
    [11, 146, 246, 197],
    [11, 146, 246, 197],
    [175, 120, 129, 187],
    [73, 54, 181, 249],
    [10, 37, 124, 54],
    [39, 228, 103, 49],
    [129, 66, 218, 168],
    [57, 62, 100, 187],
    [160, 250, 149, 218],
    [148, 165, 15, 53],
    [21, 238, 222, 169],
    [135, 38, 71, 157],
    [244, 96, 25, 124],
    [9, 147, 122, 254],
    [241, 117, 250, 251],
    [147, 123, 129, 133],
    [125, 23, 150, 16],
    [202, 47, 35, 214],
    [214, 154, 119, 161],
    [76, 59, 196, 34],
    [221, 16, 76, 41],
    [122, 204, 128, 87],
    [90, 173, 44, 213],
    [79, 172, 127, 170],
    [40, 162, 34, 120],
    [193, 133, 98, 234],
    [44, 59, 217, 238],
    [251, 240, 22, 40],
    [208, 10, 244, 203],
    [53, 197, 209, 5],
    [98, 111, 157, 151],
    [90, 242, 84, 189],
    [49, 146, 128, 43],
    [192, 158, 29, 242],
    [81, 33, 4, 18],
    [200, 47, 43, 25],
    [140, 152, 109, 84],
    [165, 243, 133, 49],
    [84, 177, 43, 250],
    [39, 162, 118, 124],
    [105, 132, 13, 145],
    [220, 228, 214, 69],
    [254, 247, 32, 219],
    [12, 6, 230, 10],
    [8, 5, 31, 20],
    [75, 195, 224, 17],
    [73, 135, 166, 148],
    [60, 193, 26, 134],
    [75, 33, 194, 232],
    [240, 8, 161, 34],
    [172, 76, 5, 225],
    [204, 95, 90, 121],
    [204, 108, 18, 153],
    [231, 95, 77, 180],
    [158, 135, 58, 134],
    [183, 22, 220, 85],
    [183, 160, 196, 110],
    [43, 22, 82, 227],
    [178, 20, 194, 222],
    [73, 157, 219, 252],
    [136, 171, 207, 210],
    [177, 220, 12, 58],
    [220, 212, 199, 141],
    [213, 7, 64, 178],
    [5, 205, 141, 219],
    [81, 143, 230, 24],
    [112, 193, 218, 193],
    [161, 174, 211, 17],
    [108, 242, 30, 13],
    [225, 121, 90, 77],
    [222, 103, 13, 192],
    [202, 118, 105, 169],
    [128, 34, 56, 247],
    [173, 93, 37, 46],
    [78, 79, 42, 252],
    [136, 254, 211, 215],
    [233, 23, 3, 204],
    [92, 71, 120, 117],
    [40, 181, 25, 243],
    [60, 114, 88, 101],
    [207, 201, 112, 11],
    [186, 5, 149, 137],
    [219, 180, 31, 150],
    [149, 38, 7, 113],
    [50, 241, 137, 147],
    [240, 64, 182, 34],
    [230, 175, 249, 214],
    [127, 54, 61, 102],
    [37, 72, 11, 165],
    [38, 41, 88, 44],
    [81, 252, 163, 119],
    [231, 84, 176, 56],
    [194, 146, 226, 169],
    [224, 47, 77, 163],
    [43, 46, 203, 10],
    [251, 252, 48, 38],
    [172, 254, 205, 167],
    [139, 173, 223, 55],
    [58, 221, 253, 197],
    [172, 0, 162, 9],
    [84, 171, 9, 0],
    [74, 168, 158, 158],
    [25, 161, 2, 100],
    [247, 119, 116, 16],
    [136, 244, 124, 0],
    [142, 147, 22, 22],
    [63, 250, 227, 205],
    [82, 68, 96, 146],
    [200, 13, 173, 26],
    [67, 111, 97, 110],
    [192, 211, 113, 3],
    [183, 236, 122, 119],
    [32, 202, 79, 216],
    [12, 85, 5, 45],
    [20, 192, 15, 140],
    [162, 83, 67, 183],
    [177, 78, 11, 84],
    [82, 98, 87, 3],
    [66, 239, 151, 148],
    [205, 144, 214, 176],
    [231, 60, 102, 181],
    [167, 170, 68, 143],
    [129, 252, 183, 40],
    [34, 132, 204, 163],
    [100, 108, 155, 110],
    [136, 247, 91, 237],
    [190, 144, 52, 71],
    [243, 45, 249, 177],
    [39, 197, 204, 26],
    [143, 240, 91, 226],
    [80, 140, 157, 14],
    [87, 251, 29, 87],
    [142, 91, 61, 230],
];
