//! Generated semantic continuation of the retail first-sortie fighter task schedule.
//! Source addresses and machine state remain in the oracle trace tooling.

use super::{FighterLogicDispatch, FighterLogicDispatchPair, FighterRandomCadence};

pub(super) const START_RETAIL_FRAME: u16 = 1_592;
pub(super) const END_RETAIL_FRAME: u16 = 2_448;
const SHARED_RANDOM_SERVICE_PARTIAL_RESULT: [u8; 4] = [221, 230, 194, 199];
const SHARED_RANDOM_SERVICE_COMPLETION_RESULT: [u8; 4] = [56, 246, 51, 108];

pub(super) const DISPATCH: [FighterLogicDispatchPair; 215] = [
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::MovementAndRoll,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::QuarterWave,
        FighterLogicDispatch::SteeringOnly,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::ApplyWave,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::PrepareWave,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::ApplyWave,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::MovementOnly,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::SteeringOnly,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(FighterLogicDispatch::Complete, FighterLogicDispatch::Wait),
    FighterLogicDispatchPair::new(FighterLogicDispatch::Wait, FighterLogicDispatch::Complete),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::AltitudeCenteringOnly,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::CompleteAfterEarlyAltitude,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::MovementAndRoll,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::PitchContinuation,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(FighterLogicDispatch::SplitWave, FighterLogicDispatch::Wait),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::ApplyWave,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(FighterLogicDispatch::Complete, FighterLogicDispatch::Wait),
    FighterLogicDispatchPair::new(FighterLogicDispatch::Wait, FighterLogicDispatch::Complete),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(FighterLogicDispatch::Complete, FighterLogicDispatch::Wait),
    FighterLogicDispatchPair::new(FighterLogicDispatch::Wait, FighterLogicDispatch::Complete),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(FighterLogicDispatch::Wait, FighterLogicDispatch::Wait),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::MovementOnly,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::SteeringOnly,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::MovementOnly,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::SteeringOnly,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::MovementOnly,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::SteeringOnly,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::MovementOnly,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::SteeringOnly,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::TurnOnly,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::PrepareWave,
        FighterLogicDispatch::MovementContinuation,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::ApplyWave,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(FighterLogicDispatch::Complete, FighterLogicDispatch::Wait),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::TurnOnly,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::MovementContinuation,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::MovementOnly,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::SteeringOnly,
    ),
    FighterLogicDispatchPair::new(FighterLogicDispatch::Wait, FighterLogicDispatch::Complete),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::PrepareWave,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::ApplyWave,
    ),
    FighterLogicDispatchPair::new(FighterLogicDispatch::Wait, FighterLogicDispatch::Complete),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::PrepareWave,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::ApplyWave,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::MovementOnly,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::SteeringOnly,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::AltitudeAndTurnOnly,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::MovementContinuationAfterEarlyAltitude,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::PrepareMovement,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::FinishPreparedAndBeginMovement,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::SteeringAfterEarlyAltitude,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
    FighterLogicDispatchPair::new(
        FighterLogicDispatch::Complete,
        FighterLogicDispatch::Complete,
    ),
];

pub(super) const RANDOM_CADENCE: [FighterRandomCadence; 215] = [
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(0),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(0),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::around_fighter_checks(1, 0, 1),
    FighterRandomCadence::ambient(0),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(3),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(2),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(0),
    FighterRandomCadence::shared_service_completion(SHARED_RANDOM_SERVICE_PARTIAL_RESULT),
    FighterRandomCadence::shared_service_completion(SHARED_RANDOM_SERVICE_COMPLETION_RESULT),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::around_fighter_checks(1, 0, 1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(0),
    FighterRandomCadence::ambient(2),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(0),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(0),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(2),
    FighterRandomCadence::ambient(0),
    FighterRandomCadence::ambient(3),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(0),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::around_fighter_checks(0, 0, 1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(3),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(0),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(0),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::around_fighter_checks(0, 1, 1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(3),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(0),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(0),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(0),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(2),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::around_fighter_checks(2, 0, 0),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(2),
    FighterRandomCadence::ambient(2),
    FighterRandomCadence::ambient(2),
    FighterRandomCadence::ambient(2),
    FighterRandomCadence::ambient(2),
    FighterRandomCadence::ambient(2),
    FighterRandomCadence::ambient(2),
    FighterRandomCadence::ambient(2),
    FighterRandomCadence::ambient(2),
    FighterRandomCadence::ambient(2),
    FighterRandomCadence::ambient(2),
    FighterRandomCadence::ambient(2),
    FighterRandomCadence::ambient(3),
    FighterRandomCadence::ambient(2),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(2),
    FighterRandomCadence::ambient(2),
    FighterRandomCadence::ambient(2),
    FighterRandomCadence::ambient(2),
    FighterRandomCadence::ambient(2),
    FighterRandomCadence::ambient(2),
    FighterRandomCadence::ambient(2),
    FighterRandomCadence::ambient(2),
    FighterRandomCadence::ambient(2),
    FighterRandomCadence::ambient(4),
    FighterRandomCadence::ambient(1),
    FighterRandomCadence::ambient(2),
    FighterRandomCadence::ambient(2),
    FighterRandomCadence::ambient(2),
    FighterRandomCadence::around_fighter_checks(2, 0, 1),
];
