//! Generated semantic projectile dynamics for the retail three-fighter interception.
//! Source addresses and opaque machine state remain in oracle tooling.

use super::{
    mission_encounter_pose, HostileProjectileAction, HostileProjectileTarget, MissionEncounterPose,
};

pub(super) const PROJECTILE_COUNT: usize = 8;
const RETAIL_FRAME_STEP: u16 = 4;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(super) struct HostileProjectileDescriptor {
    pub start_retail_frame: u16,
    pub end_retail_frame: u16,
    pub initial_pose: MissionEncounterPose,
    pub collision_enabled: bool,
    tick_offset: u16,
    tick_count: u8,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
struct ActionRange {
    start: u16,
    len: u8,
}

static DESCRIPTORS: [HostileProjectileDescriptor; 8] = [
    HostileProjectileDescriptor {
        start_retail_frame: 1_016,
        end_retail_frame: 1_176,
        initial_pose: mission_encounter_pose([-9_033, -3_088, 9_729, 33, 157, 0, 63]),
        collision_enabled: true,
        tick_offset: 0,
        tick_count: 40,
    },
    HostileProjectileDescriptor {
        start_retail_frame: 1_396,
        end_retail_frame: 1_552,
        initial_pose: mission_encounter_pose([-1_843, 2_562, -196, 247, 51, 0, 63]),
        collision_enabled: false,
        tick_offset: 40,
        tick_count: 39,
    },
    HostileProjectileDescriptor {
        start_retail_frame: 1_460,
        end_retail_frame: 1_596,
        initial_pose: mission_encounter_pose([-6_105, -1_004, 1_160, 27, 58, 0, 63]),
        collision_enabled: false,
        tick_offset: 79,
        tick_count: 34,
    },
    HostileProjectileDescriptor {
        start_retail_frame: 1_696,
        end_retail_frame: 1_864,
        initial_pose: mission_encounter_pose([-7_917, 866, 2_379, 12, 65, 0, 63]),
        collision_enabled: false,
        tick_offset: 113,
        tick_count: 42,
    },
    HostileProjectileDescriptor {
        start_retail_frame: 1_760,
        end_retail_frame: 1_904,
        initial_pose: mission_encounter_pose([-11_883, -460, 1_777, 23, 62, 0, 63]),
        collision_enabled: false,
        tick_offset: 155,
        tick_count: 36,
    },
    HostileProjectileDescriptor {
        start_retail_frame: 1_824,
        end_retail_frame: 1_948,
        initial_pose: mission_encounter_pose([-16_998, -2_092, 2_606, 37, 67, 0, 63]),
        collision_enabled: false,
        tick_offset: 191,
        tick_count: 31,
    },
    HostileProjectileDescriptor {
        start_retail_frame: 2_412,
        end_retail_frame: 2_532,
        initial_pose: mission_encounter_pose([-25_998, -2_223, -4_676, 33, 57, 0, 63]),
        collision_enabled: true,
        tick_offset: 222,
        tick_count: 30,
    },
    HostileProjectileDescriptor {
        start_retail_frame: 2_856,
        end_retail_frame: 2_924,
        initial_pose: mission_encounter_pose([-26_610, 165, 6_462, 13, 99, 0, 63]),
        collision_enabled: true,
        tick_offset: 252,
        tick_count: 17,
    },
];

static TICKS: [ActionRange; 269] = [
    ActionRange { start: 0, len: 5 },
    ActionRange { start: 5, len: 5 },
    ActionRange { start: 10, len: 4 },
    ActionRange { start: 14, len: 1 },
    ActionRange { start: 15, len: 5 },
    ActionRange { start: 20, len: 5 },
    ActionRange { start: 25, len: 5 },
    ActionRange { start: 30, len: 0 },
    ActionRange { start: 30, len: 5 },
    ActionRange { start: 35, len: 5 },
    ActionRange { start: 40, len: 0 },
    ActionRange { start: 40, len: 5 },
    ActionRange { start: 45, len: 5 },
    ActionRange { start: 50, len: 0 },
    ActionRange { start: 50, len: 5 },
    ActionRange { start: 55, len: 3 },
    ActionRange { start: 58, len: 0 },
    ActionRange { start: 58, len: 2 },
    ActionRange { start: 60, len: 0 },
    ActionRange { start: 60, len: 1 },
    ActionRange { start: 61, len: 0 },
    ActionRange { start: 61, len: 1 },
    ActionRange { start: 62, len: 1 },
    ActionRange { start: 63, len: 0 },
    ActionRange { start: 63, len: 1 },
    ActionRange { start: 64, len: 1 },
    ActionRange { start: 65, len: 0 },
    ActionRange { start: 65, len: 1 },
    ActionRange { start: 66, len: 1 },
    ActionRange { start: 67, len: 1 },
    ActionRange { start: 68, len: 1 },
    ActionRange { start: 69, len: 1 },
    ActionRange { start: 70, len: 1 },
    ActionRange { start: 71, len: 1 },
    ActionRange { start: 72, len: 1 },
    ActionRange { start: 73, len: 1 },
    ActionRange { start: 74, len: 1 },
    ActionRange { start: 75, len: 1 },
    ActionRange { start: 76, len: 1 },
    ActionRange { start: 77, len: 0 },
    ActionRange { start: 77, len: 5 },
    ActionRange { start: 82, len: 5 },
    ActionRange { start: 87, len: 5 },
    ActionRange { start: 92, len: 5 },
    ActionRange { start: 97, len: 5 },
    ActionRange { start: 102, len: 5 },
    ActionRange { start: 107, len: 5 },
    ActionRange { start: 112, len: 5 },
    ActionRange { start: 117, len: 5 },
    ActionRange { start: 122, len: 5 },
    ActionRange { start: 127, len: 5 },
    ActionRange { start: 132, len: 5 },
    ActionRange { start: 137, len: 5 },
    ActionRange { start: 142, len: 5 },
    ActionRange { start: 147, len: 5 },
    ActionRange { start: 152, len: 5 },
    ActionRange { start: 157, len: 4 },
    ActionRange { start: 161, len: 1 },
    ActionRange { start: 162, len: 2 },
    ActionRange { start: 164, len: 1 },
    ActionRange { start: 165, len: 1 },
    ActionRange { start: 166, len: 1 },
    ActionRange { start: 167, len: 0 },
    ActionRange { start: 167, len: 1 },
    ActionRange { start: 168, len: 1 },
    ActionRange { start: 169, len: 1 },
    ActionRange { start: 170, len: 1 },
    ActionRange { start: 171, len: 1 },
    ActionRange { start: 172, len: 1 },
    ActionRange { start: 173, len: 1 },
    ActionRange { start: 174, len: 1 },
    ActionRange { start: 175, len: 0 },
    ActionRange { start: 175, len: 1 },
    ActionRange { start: 176, len: 1 },
    ActionRange { start: 177, len: 1 },
    ActionRange { start: 178, len: 1 },
    ActionRange { start: 179, len: 1 },
    ActionRange { start: 180, len: 1 },
    ActionRange { start: 181, len: 1 },
    ActionRange { start: 182, len: 5 },
    ActionRange { start: 187, len: 5 },
    ActionRange { start: 192, len: 5 },
    ActionRange { start: 197, len: 5 },
    ActionRange { start: 202, len: 5 },
    ActionRange { start: 207, len: 5 },
    ActionRange { start: 212, len: 5 },
    ActionRange { start: 217, len: 5 },
    ActionRange { start: 222, len: 2 },
    ActionRange { start: 224, len: 3 },
    ActionRange { start: 227, len: 5 },
    ActionRange { start: 232, len: 5 },
    ActionRange { start: 237, len: 3 },
    ActionRange { start: 240, len: 2 },
    ActionRange { start: 242, len: 1 },
    ActionRange { start: 243, len: 0 },
    ActionRange { start: 243, len: 2 },
    ActionRange { start: 245, len: 1 },
    ActionRange { start: 246, len: 1 },
    ActionRange { start: 247, len: 1 },
    ActionRange { start: 248, len: 1 },
    ActionRange { start: 249, len: 1 },
    ActionRange { start: 250, len: 1 },
    ActionRange { start: 251, len: 1 },
    ActionRange { start: 252, len: 1 },
    ActionRange { start: 253, len: 1 },
    ActionRange { start: 254, len: 1 },
    ActionRange { start: 255, len: 1 },
    ActionRange { start: 256, len: 1 },
    ActionRange { start: 257, len: 1 },
    ActionRange { start: 258, len: 1 },
    ActionRange { start: 259, len: 1 },
    ActionRange { start: 260, len: 1 },
    ActionRange { start: 261, len: 1 },
    ActionRange { start: 262, len: 5 },
    ActionRange { start: 267, len: 5 },
    ActionRange { start: 272, len: 5 },
    ActionRange { start: 277, len: 5 },
    ActionRange { start: 282, len: 5 },
    ActionRange { start: 287, len: 5 },
    ActionRange { start: 292, len: 5 },
    ActionRange { start: 297, len: 5 },
    ActionRange { start: 302, len: 5 },
    ActionRange { start: 307, len: 5 },
    ActionRange { start: 312, len: 5 },
    ActionRange { start: 317, len: 5 },
    ActionRange { start: 322, len: 5 },
    ActionRange { start: 327, len: 5 },
    ActionRange { start: 332, len: 5 },
    ActionRange { start: 337, len: 5 },
    ActionRange { start: 342, len: 4 },
    ActionRange { start: 346, len: 1 },
    ActionRange { start: 347, len: 5 },
    ActionRange { start: 352, len: 5 },
    ActionRange { start: 357, len: 4 },
    ActionRange { start: 361, len: 3 },
    ActionRange { start: 364, len: 1 },
    ActionRange { start: 365, len: 2 },
    ActionRange { start: 367, len: 1 },
    ActionRange { start: 368, len: 1 },
    ActionRange { start: 369, len: 1 },
    ActionRange { start: 370, len: 1 },
    ActionRange { start: 371, len: 1 },
    ActionRange { start: 372, len: 1 },
    ActionRange { start: 373, len: 1 },
    ActionRange { start: 374, len: 1 },
    ActionRange { start: 375, len: 1 },
    ActionRange { start: 376, len: 1 },
    ActionRange { start: 377, len: 1 },
    ActionRange { start: 378, len: 1 },
    ActionRange { start: 379, len: 1 },
    ActionRange { start: 380, len: 0 },
    ActionRange { start: 380, len: 1 },
    ActionRange { start: 381, len: 1 },
    ActionRange { start: 382, len: 1 },
    ActionRange { start: 383, len: 1 },
    ActionRange { start: 384, len: 5 },
    ActionRange { start: 389, len: 5 },
    ActionRange { start: 394, len: 1 },
    ActionRange { start: 395, len: 4 },
    ActionRange { start: 399, len: 5 },
    ActionRange {
        start: 404,
        len: 10,
    },
    ActionRange { start: 414, len: 5 },
    ActionRange { start: 419, len: 5 },
    ActionRange { start: 424, len: 5 },
    ActionRange { start: 429, len: 5 },
    ActionRange { start: 434, len: 5 },
    ActionRange { start: 439, len: 5 },
    ActionRange { start: 444, len: 5 },
    ActionRange { start: 449, len: 5 },
    ActionRange { start: 454, len: 5 },
    ActionRange { start: 459, len: 4 },
    ActionRange { start: 463, len: 1 },
    ActionRange { start: 464, len: 2 },
    ActionRange { start: 466, len: 1 },
    ActionRange { start: 467, len: 2 },
    ActionRange { start: 469, len: 1 },
    ActionRange { start: 470, len: 0 },
    ActionRange { start: 470, len: 1 },
    ActionRange { start: 471, len: 1 },
    ActionRange { start: 472, len: 1 },
    ActionRange { start: 473, len: 1 },
    ActionRange { start: 474, len: 1 },
    ActionRange { start: 475, len: 2 },
    ActionRange { start: 477, len: 1 },
    ActionRange { start: 478, len: 1 },
    ActionRange { start: 479, len: 1 },
    ActionRange { start: 480, len: 1 },
    ActionRange { start: 481, len: 1 },
    ActionRange { start: 482, len: 1 },
    ActionRange { start: 483, len: 1 },
    ActionRange { start: 484, len: 1 },
    ActionRange { start: 485, len: 5 },
    ActionRange { start: 490, len: 5 },
    ActionRange { start: 495, len: 5 },
    ActionRange { start: 500, len: 5 },
    ActionRange { start: 505, len: 5 },
    ActionRange { start: 510, len: 0 },
    ActionRange { start: 510, len: 5 },
    ActionRange { start: 515, len: 5 },
    ActionRange { start: 520, len: 5 },
    ActionRange { start: 525, len: 5 },
    ActionRange { start: 530, len: 8 },
    ActionRange { start: 538, len: 2 },
    ActionRange { start: 540, len: 1 },
    ActionRange { start: 541, len: 2 },
    ActionRange { start: 543, len: 1 },
    ActionRange { start: 544, len: 1 },
    ActionRange { start: 545, len: 1 },
    ActionRange { start: 546, len: 1 },
    ActionRange { start: 547, len: 1 },
    ActionRange { start: 548, len: 1 },
    ActionRange { start: 549, len: 1 },
    ActionRange { start: 550, len: 1 },
    ActionRange { start: 551, len: 1 },
    ActionRange { start: 552, len: 1 },
    ActionRange { start: 553, len: 1 },
    ActionRange { start: 554, len: 1 },
    ActionRange { start: 555, len: 1 },
    ActionRange { start: 556, len: 1 },
    ActionRange { start: 557, len: 1 },
    ActionRange { start: 558, len: 1 },
    ActionRange { start: 559, len: 1 },
    ActionRange { start: 560, len: 5 },
    ActionRange { start: 565, len: 5 },
    ActionRange { start: 570, len: 5 },
    ActionRange { start: 575, len: 5 },
    ActionRange { start: 580, len: 5 },
    ActionRange { start: 585, len: 5 },
    ActionRange { start: 590, len: 5 },
    ActionRange { start: 595, len: 5 },
    ActionRange { start: 600, len: 5 },
    ActionRange { start: 605, len: 5 },
    ActionRange { start: 610, len: 5 },
    ActionRange { start: 615, len: 5 },
    ActionRange { start: 620, len: 4 },
    ActionRange { start: 624, len: 1 },
    ActionRange { start: 625, len: 1 },
    ActionRange { start: 626, len: 1 },
    ActionRange { start: 627, len: 1 },
    ActionRange { start: 628, len: 1 },
    ActionRange { start: 629, len: 1 },
    ActionRange { start: 630, len: 1 },
    ActionRange { start: 631, len: 1 },
    ActionRange { start: 632, len: 1 },
    ActionRange { start: 633, len: 1 },
    ActionRange { start: 634, len: 1 },
    ActionRange { start: 635, len: 1 },
    ActionRange { start: 636, len: 1 },
    ActionRange { start: 637, len: 1 },
    ActionRange { start: 638, len: 1 },
    ActionRange { start: 639, len: 1 },
    ActionRange { start: 640, len: 1 },
    ActionRange { start: 641, len: 5 },
    ActionRange { start: 646, len: 5 },
    ActionRange { start: 651, len: 5 },
    ActionRange { start: 656, len: 5 },
    ActionRange { start: 661, len: 5 },
    ActionRange { start: 666, len: 5 },
    ActionRange { start: 671, len: 5 },
    ActionRange { start: 676, len: 5 },
    ActionRange { start: 681, len: 5 },
    ActionRange { start: 686, len: 5 },
    ActionRange { start: 691, len: 5 },
    ActionRange { start: 696, len: 5 },
    ActionRange { start: 701, len: 5 },
    ActionRange { start: 706, len: 5 },
    ActionRange { start: 711, len: 4 },
    ActionRange { start: 715, len: 1 },
    ActionRange { start: 716, len: 1 },
];

static ACTIONS: [HostileProjectileAction; 717] = [
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::SetCruiseSpeed,
    HostileProjectileAction::AdvanceAimCorrection,
    HostileProjectileAction::AdvanceAimCorrection,
    HostileProjectileAction::FaceTargetSmooth(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceAimCorrection,
    HostileProjectileAction::AdvanceAimCorrection,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::SetCruiseSpeed,
    HostileProjectileAction::AdvanceAimCorrection,
    HostileProjectileAction::FaceTargetSmooth(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceAimCorrection,
    HostileProjectileAction::AdvanceAimCorrection,
    HostileProjectileAction::FaceTargetSmooth(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceAimCorrection,
    HostileProjectileAction::AdvanceAimCorrection,
    HostileProjectileAction::AdvanceAimCorrection,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Previous),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Previous),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::SetCruiseSpeed,
    HostileProjectileAction::AdvanceAimCorrection,
    HostileProjectileAction::AdvanceAimCorrection,
    HostileProjectileAction::FaceTargetSmooth(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceAimCorrection,
    HostileProjectileAction::AdvanceAimCorrection,
    HostileProjectileAction::FaceTargetSmooth(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceAimCorrection,
    HostileProjectileAction::AdvanceAimCorrection,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Previous),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Previous),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Previous),
    HostileProjectileAction::SetCruiseSpeed,
    HostileProjectileAction::AdvanceAimCorrection,
    HostileProjectileAction::FaceTargetSmooth(HostileProjectileTarget::Previous),
    HostileProjectileAction::AdvanceAimCorrection,
    HostileProjectileAction::AdvanceAimCorrection,
    HostileProjectileAction::FaceTargetSmooth(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceAimCorrection,
    HostileProjectileAction::AdvanceAimCorrection,
    HostileProjectileAction::FaceTargetSmooth(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceAimCorrection,
    HostileProjectileAction::AdvanceAimCorrection,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Previous),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Previous),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Previous),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Midpoint),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Midpoint),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Midpoint),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Midpoint),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Previous),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Previous),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Previous),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Previous),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Previous),
    HostileProjectileAction::SetCruiseSpeed,
    HostileProjectileAction::AdvanceAimCorrection,
    HostileProjectileAction::FaceTargetSmooth(HostileProjectileTarget::Previous),
    HostileProjectileAction::AdvanceAimCorrection,
    HostileProjectileAction::AdvanceAimCorrection,
    HostileProjectileAction::FaceTargetSmooth(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceAimCorrection,
    HostileProjectileAction::AdvanceAimCorrection,
    HostileProjectileAction::FaceTargetSmooth(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceAimCorrection,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Previous),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Previous),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Previous),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Previous),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Previous),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::SetCruiseSpeed,
    HostileProjectileAction::AdvanceAimCorrection,
    HostileProjectileAction::AdvanceAimCorrection,
    HostileProjectileAction::FaceTargetSmooth(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceAimCorrection,
    HostileProjectileAction::AdvanceAimCorrection,
    HostileProjectileAction::FaceTargetSmooth(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceAimCorrection,
    HostileProjectileAction::AdvanceAimCorrection,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::SetCruiseSpeed,
    HostileProjectileAction::AdvanceAimCorrection,
    HostileProjectileAction::FaceTargetSmooth(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceAimCorrection,
    HostileProjectileAction::AdvanceAimCorrection,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Previous),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Previous),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Previous),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::SetCruiseSpeed,
    HostileProjectileAction::AdvanceAimCorrection,
    HostileProjectileAction::FaceTargetSmooth(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceAimCorrection,
    HostileProjectileAction::AdvanceCruise,
];

static ACTION_PLAYER_TARGETS: [Option<HostileProjectileTarget>; 717] = [
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    None,
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Midpoint),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Midpoint),
    Some(HostileProjectileTarget::Midpoint),
    Some(HostileProjectileTarget::Midpoint),
    Some(HostileProjectileTarget::Midpoint),
    Some(HostileProjectileTarget::Midpoint),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    None,
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    None,
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    None,
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    None,
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    None,
];

pub(super) fn descriptor(track_index: usize) -> Option<&'static HostileProjectileDescriptor> {
    DESCRIPTORS.get(track_index)
}

pub(super) fn actions(track_index: usize, retail_frame: u16) -> &'static [HostileProjectileAction] {
    let Some(descriptor) = descriptor(track_index) else {
        return &[];
    };
    let Some(offset) = retail_frame.checked_sub(descriptor.start_retail_frame + RETAIL_FRAME_STEP)
    else {
        return &[];
    };
    if offset % RETAIL_FRAME_STEP != 0 {
        return &[];
    }
    let tick = offset / RETAIL_FRAME_STEP;
    if tick >= u16::from(descriptor.tick_count) {
        return &[];
    }
    let range = TICKS[usize::from(descriptor.tick_offset + tick)];
    let start = usize::from(range.start);
    &ACTIONS[start..start + usize::from(range.len)]
}

pub(super) fn action_player_targets(
    track_index: usize,
    retail_frame: u16,
) -> &'static [Option<HostileProjectileTarget>] {
    let Some(descriptor) = descriptor(track_index) else {
        return &[];
    };
    let Some(offset) = retail_frame.checked_sub(descriptor.start_retail_frame + RETAIL_FRAME_STEP)
    else {
        return &[];
    };
    if offset % RETAIL_FRAME_STEP != 0 {
        return &[];
    }
    let tick = offset / RETAIL_FRAME_STEP;
    if tick >= u16::from(descriptor.tick_count) {
        return &[];
    }
    let range = TICKS[usize::from(descriptor.tick_offset + tick)];
    let start = usize::from(range.start);
    &ACTION_PLAYER_TARGETS[start..start + usize::from(range.len)]
}
