//! Generated semantic flight plans for the two retail final rivals.
//! Source addresses and opaque machine state remain in oracle tooling.

use super::{
    mission_encounter_pose, FinalRivalAction, MissionEncounterPose, PlayerTargetTiming,
    RivalApproachSteering,
};

#[derive(Debug, Clone, Copy)]
pub(super) struct FinalRivalFlightPlan {
    pub presentation_start_retail_frame: u16,
    pub flight_start_retail_frame: u16,
    pub end_retail_frame: u16,
    pub departure_retail_frame: u16,
    pub initial_pose: MissionEncounterPose,
    hidden_retail_frames: &'static [u16],
    frames: &'static [FrameActions],
    actions: &'static [FinalRivalAction],
}

impl FinalRivalFlightPlan {
    pub fn actions(self, retail_frame: u16) -> &'static [FinalRivalAction] {
        if retail_frame > self.end_retail_frame {
            return &[];
        }
        let Ok(index) = self
            .frames
            .binary_search_by_key(&retail_frame, |frame| frame.retail_frame)
        else {
            return &[];
        };
        let range = self.frames[index];
        let start = usize::from(range.start);
        &self.actions[start..start + usize::from(range.len)]
    }

    pub fn is_hidden(self, retail_frame: u16) -> bool {
        self.hidden_retail_frames.contains(&retail_frame)
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
struct FrameActions {
    retail_frame: u16,
    start: u16,
    len: u8,
}

static FINAL_PURSUER_FRAMES: [FrameActions; 123] = [
    FrameActions {
        retail_frame: 404,
        start: 0,
        len: 2,
    },
    FrameActions {
        retail_frame: 408,
        start: 2,
        len: 1,
    },
    FrameActions {
        retail_frame: 412,
        start: 3,
        len: 2,
    },
    FrameActions {
        retail_frame: 416,
        start: 5,
        len: 1,
    },
    FrameActions {
        retail_frame: 420,
        start: 6,
        len: 1,
    },
    FrameActions {
        retail_frame: 424,
        start: 7,
        len: 2,
    },
    FrameActions {
        retail_frame: 428,
        start: 9,
        len: 1,
    },
    FrameActions {
        retail_frame: 432,
        start: 10,
        len: 1,
    },
    FrameActions {
        retail_frame: 436,
        start: 11,
        len: 2,
    },
    FrameActions {
        retail_frame: 440,
        start: 13,
        len: 1,
    },
    FrameActions {
        retail_frame: 444,
        start: 14,
        len: 1,
    },
    FrameActions {
        retail_frame: 448,
        start: 15,
        len: 2,
    },
    FrameActions {
        retail_frame: 452,
        start: 17,
        len: 1,
    },
    FrameActions {
        retail_frame: 456,
        start: 18,
        len: 1,
    },
    FrameActions {
        retail_frame: 460,
        start: 19,
        len: 2,
    },
    FrameActions {
        retail_frame: 464,
        start: 21,
        len: 1,
    },
    FrameActions {
        retail_frame: 468,
        start: 22,
        len: 1,
    },
    FrameActions {
        retail_frame: 472,
        start: 23,
        len: 1,
    },
    FrameActions {
        retail_frame: 476,
        start: 24,
        len: 2,
    },
    FrameActions {
        retail_frame: 480,
        start: 26,
        len: 1,
    },
    FrameActions {
        retail_frame: 484,
        start: 27,
        len: 1,
    },
    FrameActions {
        retail_frame: 488,
        start: 28,
        len: 2,
    },
    FrameActions {
        retail_frame: 492,
        start: 30,
        len: 1,
    },
    FrameActions {
        retail_frame: 496,
        start: 31,
        len: 1,
    },
    FrameActions {
        retail_frame: 500,
        start: 32,
        len: 1,
    },
    FrameActions {
        retail_frame: 504,
        start: 33,
        len: 2,
    },
    FrameActions {
        retail_frame: 508,
        start: 35,
        len: 1,
    },
    FrameActions {
        retail_frame: 512,
        start: 36,
        len: 1,
    },
    FrameActions {
        retail_frame: 516,
        start: 37,
        len: 1,
    },
    FrameActions {
        retail_frame: 520,
        start: 38,
        len: 2,
    },
    FrameActions {
        retail_frame: 524,
        start: 40,
        len: 1,
    },
    FrameActions {
        retail_frame: 528,
        start: 41,
        len: 1,
    },
    FrameActions {
        retail_frame: 532,
        start: 42,
        len: 1,
    },
    FrameActions {
        retail_frame: 536,
        start: 43,
        len: 1,
    },
    FrameActions {
        retail_frame: 540,
        start: 44,
        len: 2,
    },
    FrameActions {
        retail_frame: 544,
        start: 46,
        len: 1,
    },
    FrameActions {
        retail_frame: 548,
        start: 47,
        len: 1,
    },
    FrameActions {
        retail_frame: 552,
        start: 48,
        len: 1,
    },
    FrameActions {
        retail_frame: 556,
        start: 49,
        len: 2,
    },
    FrameActions {
        retail_frame: 560,
        start: 51,
        len: 1,
    },
    FrameActions {
        retail_frame: 564,
        start: 52,
        len: 1,
    },
    FrameActions {
        retail_frame: 568,
        start: 53,
        len: 1,
    },
    FrameActions {
        retail_frame: 572,
        start: 54,
        len: 1,
    },
    FrameActions {
        retail_frame: 576,
        start: 55,
        len: 2,
    },
    FrameActions {
        retail_frame: 580,
        start: 57,
        len: 1,
    },
    FrameActions {
        retail_frame: 584,
        start: 58,
        len: 1,
    },
    FrameActions {
        retail_frame: 588,
        start: 59,
        len: 1,
    },
    FrameActions {
        retail_frame: 592,
        start: 60,
        len: 7,
    },
    FrameActions {
        retail_frame: 596,
        start: 67,
        len: 4,
    },
    FrameActions {
        retail_frame: 600,
        start: 71,
        len: 5,
    },
    FrameActions {
        retail_frame: 604,
        start: 76,
        len: 5,
    },
    FrameActions {
        retail_frame: 608,
        start: 81,
        len: 5,
    },
    FrameActions {
        retail_frame: 612,
        start: 86,
        len: 5,
    },
    FrameActions {
        retail_frame: 616,
        start: 91,
        len: 8,
    },
    FrameActions {
        retail_frame: 620,
        start: 99,
        len: 5,
    },
    FrameActions {
        retail_frame: 624,
        start: 104,
        len: 5,
    },
    FrameActions {
        retail_frame: 628,
        start: 109,
        len: 5,
    },
    FrameActions {
        retail_frame: 632,
        start: 114,
        len: 5,
    },
    FrameActions {
        retail_frame: 636,
        start: 119,
        len: 8,
    },
    FrameActions {
        retail_frame: 640,
        start: 127,
        len: 5,
    },
    FrameActions {
        retail_frame: 644,
        start: 132,
        len: 5,
    },
    FrameActions {
        retail_frame: 648,
        start: 137,
        len: 5,
    },
    FrameActions {
        retail_frame: 652,
        start: 142,
        len: 8,
    },
    FrameActions {
        retail_frame: 656,
        start: 150,
        len: 5,
    },
    FrameActions {
        retail_frame: 660,
        start: 155,
        len: 5,
    },
    FrameActions {
        retail_frame: 664,
        start: 160,
        len: 5,
    },
    FrameActions {
        retail_frame: 668,
        start: 165,
        len: 8,
    },
    FrameActions {
        retail_frame: 672,
        start: 173,
        len: 8,
    },
    FrameActions {
        retail_frame: 676,
        start: 181,
        len: 5,
    },
    FrameActions {
        retail_frame: 680,
        start: 186,
        len: 5,
    },
    FrameActions {
        retail_frame: 684,
        start: 191,
        len: 5,
    },
    FrameActions {
        retail_frame: 688,
        start: 196,
        len: 9,
    },
    FrameActions {
        retail_frame: 692,
        start: 205,
        len: 5,
    },
    FrameActions {
        retail_frame: 696,
        start: 210,
        len: 8,
    },
    FrameActions {
        retail_frame: 700,
        start: 218,
        len: 5,
    },
    FrameActions {
        retail_frame: 704,
        start: 223,
        len: 5,
    },
    FrameActions {
        retail_frame: 708,
        start: 228,
        len: 4,
    },
    FrameActions {
        retail_frame: 712,
        start: 232,
        len: 4,
    },
    FrameActions {
        retail_frame: 716,
        start: 236,
        len: 2,
    },
    FrameActions {
        retail_frame: 720,
        start: 238,
        len: 4,
    },
    FrameActions {
        retail_frame: 724,
        start: 242,
        len: 2,
    },
    FrameActions {
        retail_frame: 728,
        start: 244,
        len: 2,
    },
    FrameActions {
        retail_frame: 732,
        start: 246,
        len: 2,
    },
    FrameActions {
        retail_frame: 736,
        start: 248,
        len: 2,
    },
    FrameActions {
        retail_frame: 740,
        start: 250,
        len: 2,
    },
    FrameActions {
        retail_frame: 744,
        start: 252,
        len: 2,
    },
    FrameActions {
        retail_frame: 748,
        start: 254,
        len: 4,
    },
    FrameActions {
        retail_frame: 752,
        start: 258,
        len: 2,
    },
    FrameActions {
        retail_frame: 756,
        start: 260,
        len: 2,
    },
    FrameActions {
        retail_frame: 760,
        start: 262,
        len: 2,
    },
    FrameActions {
        retail_frame: 764,
        start: 264,
        len: 2,
    },
    FrameActions {
        retail_frame: 768,
        start: 266,
        len: 2,
    },
    FrameActions {
        retail_frame: 772,
        start: 268,
        len: 2,
    },
    FrameActions {
        retail_frame: 776,
        start: 270,
        len: 2,
    },
    FrameActions {
        retail_frame: 780,
        start: 272,
        len: 2,
    },
    FrameActions {
        retail_frame: 784,
        start: 274,
        len: 2,
    },
    FrameActions {
        retail_frame: 788,
        start: 276,
        len: 2,
    },
    FrameActions {
        retail_frame: 792,
        start: 278,
        len: 2,
    },
    FrameActions {
        retail_frame: 796,
        start: 280,
        len: 2,
    },
    FrameActions {
        retail_frame: 800,
        start: 282,
        len: 1,
    },
    FrameActions {
        retail_frame: 804,
        start: 283,
        len: 1,
    },
    FrameActions {
        retail_frame: 808,
        start: 284,
        len: 2,
    },
    FrameActions {
        retail_frame: 812,
        start: 286,
        len: 1,
    },
    FrameActions {
        retail_frame: 816,
        start: 287,
        len: 1,
    },
    FrameActions {
        retail_frame: 820,
        start: 288,
        len: 1,
    },
    FrameActions {
        retail_frame: 824,
        start: 289,
        len: 1,
    },
    FrameActions {
        retail_frame: 828,
        start: 290,
        len: 2,
    },
    FrameActions {
        retail_frame: 832,
        start: 292,
        len: 1,
    },
    FrameActions {
        retail_frame: 836,
        start: 293,
        len: 1,
    },
    FrameActions {
        retail_frame: 840,
        start: 294,
        len: 2,
    },
    FrameActions {
        retail_frame: 844,
        start: 296,
        len: 1,
    },
    FrameActions {
        retail_frame: 848,
        start: 297,
        len: 2,
    },
    FrameActions {
        retail_frame: 852,
        start: 299,
        len: 1,
    },
    FrameActions {
        retail_frame: 856,
        start: 300,
        len: 2,
    },
    FrameActions {
        retail_frame: 860,
        start: 302,
        len: 3,
    },
    FrameActions {
        retail_frame: 864,
        start: 305,
        len: 5,
    },
    FrameActions {
        retail_frame: 868,
        start: 310,
        len: 3,
    },
    FrameActions {
        retail_frame: 872,
        start: 313,
        len: 4,
    },
    FrameActions {
        retail_frame: 876,
        start: 317,
        len: 3,
    },
    FrameActions {
        retail_frame: 880,
        start: 320,
        len: 3,
    },
    FrameActions {
        retail_frame: 884,
        start: 323,
        len: 2,
    },
    FrameActions {
        retail_frame: 888,
        start: 325,
        len: 2,
    },
    FrameActions {
        retail_frame: 892,
        start: 327,
        len: 1,
    },
];

static FINAL_PURSUER_ACTIONS: [FinalRivalAction; 328] = [
    FinalRivalAction::BeginApproach,
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryClimb),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryClimb),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryClimb),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryClimb),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryClimb),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryClimb),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryClimb),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryClimb),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryClimb),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryClimb),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryClimb),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryClimb),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryClimb),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryClimb),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryClimb),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryDive),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryDive),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryDive),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryDive),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryDive),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryDive),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryDive),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryDive),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryDive),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryDive),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryDive),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryDive),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryDive),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryDive),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryDive),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryDive),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryDive),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryDive),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryDive),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryDive),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryDive),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryDive),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryDive),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryDive),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryDive),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryDive),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryDive),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryDive),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryDive),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryDive),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryDive),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryDive),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryDive),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryDive),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryDive),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryDive),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryDive),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryDive),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryDive),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryDive),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryDive),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryDive),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryDive),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryDive),
    FinalRivalAction::BeginCombatManeuver,
    FinalRivalAction::ChaseRollToLevel,
    FinalRivalAction::Advance,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::ChaseRollToLevel,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::Advance,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::ChaseRollToLevel,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::Advance,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::ChaseRollToLevel,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::Advance,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::ChaseRollToLevel,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::Advance,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::ChaseRollToLevel,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::Advance,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::ChaseRollToLevel,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::Advance,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::ChaseRollToLevel,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::Advance,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::ChaseRollToLevel,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::Advance,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::ChaseRollToLevel,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::Advance,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::ChaseRollToLevel,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::Advance,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::ChaseRollToLevel,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::Advance,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::ChaseRollToLevel,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::Advance,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::ChaseRollToLevel,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::Advance,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::ChaseRollToLevel,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::Advance,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::ChaseRollToLevel,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::Advance,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::ChaseRollToLevel,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::Advance,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::ChaseRollToLevel,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::Advance,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::ChaseRollToLevel,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::Advance,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::ChaseRollToLevel,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::Advance,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::ChaseRollToLevel,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::Advance,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::ChaseRollToLevel,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::Advance,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::ChaseRollToLevel,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::Advance,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::ChaseRollToLevel,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::BeginAttack,
    FinalRivalAction::FacePlayerYawAndLevelPitch(PlayerTargetTiming::Midpoint),
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::Advance,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::FacePlayerYawAndLevelPitch(PlayerTargetTiming::Previous),
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::Advance,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::FacePlayerYawAndLevelPitch(PlayerTargetTiming::Current),
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::Advance,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::FacePlayerYawAndLevelPitch(PlayerTargetTiming::Current),
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::Advance,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::FacePlayerYawAndLevelPitch(PlayerTargetTiming::Midpoint),
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::Advance,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::FacePlayerYawAndLevelPitch(PlayerTargetTiming::Previous),
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::Advance,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::FacePlayerYawAndLevelPitch(PlayerTargetTiming::Previous),
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::Advance,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::FacePlayerYawAndLevelPitch(PlayerTargetTiming::Current),
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::Advance,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::FacePlayerYawAndLevelPitch(PlayerTargetTiming::Midpoint),
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::Advance,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::FacePlayerYawAndLevelPitch(PlayerTargetTiming::Previous),
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::Advance,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::FacePlayerYawAndLevelPitch(PlayerTargetTiming::Current),
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::Advance,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::FacePlayerYawAndLevelPitch(PlayerTargetTiming::Current),
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::Advance,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::FacePlayerSmooth(PlayerTargetTiming::Midpoint),
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::Advance,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::FacePlayerSmooth(PlayerTargetTiming::Previous),
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::Advance,
    FinalRivalAction::FacePlayerSmooth(PlayerTargetTiming::Previous),
    FinalRivalAction::Advance,
    FinalRivalAction::FacePlayerSmooth(PlayerTargetTiming::Current),
    FinalRivalAction::Advance,
    FinalRivalAction::FacePlayerSmooth(PlayerTargetTiming::Midpoint),
    FinalRivalAction::Advance,
    FinalRivalAction::FacePlayerSmooth(PlayerTargetTiming::Previous),
    FinalRivalAction::Advance,
    FinalRivalAction::FacePlayerSmooth(PlayerTargetTiming::Current),
    FinalRivalAction::Advance,
    FinalRivalAction::FacePlayerSmooth(PlayerTargetTiming::Current),
    FinalRivalAction::Advance,
    FinalRivalAction::FacePlayerSmooth(PlayerTargetTiming::Current),
    FinalRivalAction::Advance,
    FinalRivalAction::FacePlayerSmooth(PlayerTargetTiming::Current),
    FinalRivalAction::Advance,
    FinalRivalAction::FacePlayerSmooth(PlayerTargetTiming::Midpoint),
    FinalRivalAction::Advance,
    FinalRivalAction::FacePlayerSmooth(PlayerTargetTiming::Previous),
    FinalRivalAction::Advance,
    FinalRivalAction::FacePlayerSmooth(PlayerTargetTiming::Previous),
    FinalRivalAction::Advance,
    FinalRivalAction::FacePlayerSmooth(PlayerTargetTiming::Previous),
    FinalRivalAction::Advance,
    FinalRivalAction::FacePlayerSmooth(PlayerTargetTiming::Current),
    FinalRivalAction::Advance,
    FinalRivalAction::FacePlayerSmooth(PlayerTargetTiming::Current),
    FinalRivalAction::Advance,
    FinalRivalAction::FacePlayerSmooth(PlayerTargetTiming::Current),
    FinalRivalAction::Advance,
    FinalRivalAction::FacePlayerSmooth(PlayerTargetTiming::Current),
    FinalRivalAction::Advance,
    FinalRivalAction::FacePlayerSmooth(PlayerTargetTiming::Current),
    FinalRivalAction::Advance,
    FinalRivalAction::FacePlayerSmooth(PlayerTargetTiming::Current),
    FinalRivalAction::Advance,
    FinalRivalAction::FacePlayerSmooth(PlayerTargetTiming::Current),
    FinalRivalAction::Advance,
    FinalRivalAction::FacePlayerSmooth(PlayerTargetTiming::Midpoint),
    FinalRivalAction::Advance,
    FinalRivalAction::FacePlayerSmooth(PlayerTargetTiming::Previous),
    FinalRivalAction::Advance,
    FinalRivalAction::FacePlayerSmooth(PlayerTargetTiming::Previous),
    FinalRivalAction::Advance,
    FinalRivalAction::FacePlayerSmooth(PlayerTargetTiming::Previous),
    FinalRivalAction::Advance,
    FinalRivalAction::FacePlayerSmooth(PlayerTargetTiming::Current),
    FinalRivalAction::Advance,
    FinalRivalAction::BeginDeparture,
    FinalRivalAction::LaunchDeparture,
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::SecondClimb),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::SecondClimb),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::SecondClimb),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::SecondClimb),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::SecondClimb),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::SecondClimb),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::SecondClimb),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::SecondClimb),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::SecondClimb),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::SecondClimb),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::SecondClimb),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::SecondClimb),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::SecondClimb),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::SecondClimb),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::SecondClimb),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::SecondClimb),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::SecondClimb),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::SecondClimb),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::SecondClimb),
    FinalRivalAction::ClampFlightAltitude,
    FinalRivalAction::ClampFlightAltitude,
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::SecondClimb),
    FinalRivalAction::ClampFlightAltitude,
    FinalRivalAction::ClampFlightAltitude,
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::SecondClimb),
    FinalRivalAction::ClampFlightAltitude,
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::SecondClimb),
    FinalRivalAction::ClampFlightAltitude,
    FinalRivalAction::ClampFlightAltitude,
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::SecondDive),
    FinalRivalAction::ClampFlightAltitude,
    FinalRivalAction::ClampFlightAltitude,
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::SecondDive),
    FinalRivalAction::ClampFlightAltitude,
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::SecondDive),
    FinalRivalAction::ClampFlightAltitude,
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::SecondDive),
    FinalRivalAction::ClampFlightAltitude,
    FinalRivalAction::ClampFlightAltitude,
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::SecondDive),
    FinalRivalAction::ClampFlightAltitude,
    FinalRivalAction::ClampFlightAltitude,
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::SecondDive),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::SecondDive),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::SecondDive),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::SecondDive),
];

pub(super) const FINAL_PURSUER: FinalRivalFlightPlan = FinalRivalFlightPlan {
    presentation_start_retail_frame: 56,
    flight_start_retail_frame: 404,
    end_retail_frame: 892,
    departure_retail_frame: 896,
    initial_pose: mission_encounter_pose([10_148, 0, 8_192, 21, 76, 0, 0]),
    hidden_retail_frames: &[324],
    frames: &FINAL_PURSUER_FRAMES,
    actions: &FINAL_PURSUER_ACTIONS,
};

static WOLF_BLOCKADE_FRAMES: [FrameActions; 135] = [
    FrameActions {
        retail_frame: 408,
        start: 0,
        len: 2,
    },
    FrameActions {
        retail_frame: 412,
        start: 2,
        len: 2,
    },
    FrameActions {
        retail_frame: 416,
        start: 4,
        len: 1,
    },
    FrameActions {
        retail_frame: 420,
        start: 5,
        len: 1,
    },
    FrameActions {
        retail_frame: 424,
        start: 6,
        len: 1,
    },
    FrameActions {
        retail_frame: 428,
        start: 7,
        len: 2,
    },
    FrameActions {
        retail_frame: 432,
        start: 9,
        len: 1,
    },
    FrameActions {
        retail_frame: 436,
        start: 10,
        len: 1,
    },
    FrameActions {
        retail_frame: 440,
        start: 11,
        len: 2,
    },
    FrameActions {
        retail_frame: 444,
        start: 13,
        len: 1,
    },
    FrameActions {
        retail_frame: 448,
        start: 14,
        len: 1,
    },
    FrameActions {
        retail_frame: 452,
        start: 15,
        len: 2,
    },
    FrameActions {
        retail_frame: 456,
        start: 17,
        len: 1,
    },
    FrameActions {
        retail_frame: 460,
        start: 18,
        len: 1,
    },
    FrameActions {
        retail_frame: 464,
        start: 19,
        len: 2,
    },
    FrameActions {
        retail_frame: 468,
        start: 21,
        len: 1,
    },
    FrameActions {
        retail_frame: 472,
        start: 22,
        len: 1,
    },
    FrameActions {
        retail_frame: 476,
        start: 23,
        len: 1,
    },
    FrameActions {
        retail_frame: 480,
        start: 24,
        len: 2,
    },
    FrameActions {
        retail_frame: 484,
        start: 26,
        len: 1,
    },
    FrameActions {
        retail_frame: 488,
        start: 27,
        len: 1,
    },
    FrameActions {
        retail_frame: 492,
        start: 28,
        len: 2,
    },
    FrameActions {
        retail_frame: 496,
        start: 30,
        len: 1,
    },
    FrameActions {
        retail_frame: 500,
        start: 31,
        len: 1,
    },
    FrameActions {
        retail_frame: 504,
        start: 32,
        len: 1,
    },
    FrameActions {
        retail_frame: 508,
        start: 33,
        len: 2,
    },
    FrameActions {
        retail_frame: 512,
        start: 35,
        len: 1,
    },
    FrameActions {
        retail_frame: 516,
        start: 36,
        len: 1,
    },
    FrameActions {
        retail_frame: 520,
        start: 37,
        len: 1,
    },
    FrameActions {
        retail_frame: 524,
        start: 38,
        len: 1,
    },
    FrameActions {
        retail_frame: 528,
        start: 39,
        len: 1,
    },
    FrameActions {
        retail_frame: 532,
        start: 40,
        len: 1,
    },
    FrameActions {
        retail_frame: 536,
        start: 41,
        len: 1,
    },
    FrameActions {
        retail_frame: 540,
        start: 42,
        len: 1,
    },
    FrameActions {
        retail_frame: 544,
        start: 43,
        len: 2,
    },
    FrameActions {
        retail_frame: 548,
        start: 45,
        len: 1,
    },
    FrameActions {
        retail_frame: 552,
        start: 46,
        len: 1,
    },
    FrameActions {
        retail_frame: 556,
        start: 47,
        len: 1,
    },
    FrameActions {
        retail_frame: 560,
        start: 48,
        len: 1,
    },
    FrameActions {
        retail_frame: 564,
        start: 49,
        len: 1,
    },
    FrameActions {
        retail_frame: 568,
        start: 50,
        len: 1,
    },
    FrameActions {
        retail_frame: 572,
        start: 51,
        len: 1,
    },
    FrameActions {
        retail_frame: 576,
        start: 52,
        len: 1,
    },
    FrameActions {
        retail_frame: 580,
        start: 53,
        len: 1,
    },
    FrameActions {
        retail_frame: 584,
        start: 54,
        len: 1,
    },
    FrameActions {
        retail_frame: 588,
        start: 55,
        len: 1,
    },
    FrameActions {
        retail_frame: 592,
        start: 56,
        len: 2,
    },
    FrameActions {
        retail_frame: 596,
        start: 58,
        len: 1,
    },
    FrameActions {
        retail_frame: 600,
        start: 59,
        len: 1,
    },
    FrameActions {
        retail_frame: 604,
        start: 60,
        len: 4,
    },
    FrameActions {
        retail_frame: 608,
        start: 64,
        len: 5,
    },
    FrameActions {
        retail_frame: 612,
        start: 69,
        len: 5,
    },
    FrameActions {
        retail_frame: 616,
        start: 74,
        len: 5,
    },
    FrameActions {
        retail_frame: 620,
        start: 79,
        len: 5,
    },
    FrameActions {
        retail_frame: 624,
        start: 84,
        len: 5,
    },
    FrameActions {
        retail_frame: 628,
        start: 89,
        len: 5,
    },
    FrameActions {
        retail_frame: 632,
        start: 94,
        len: 5,
    },
    FrameActions {
        retail_frame: 636,
        start: 99,
        len: 5,
    },
    FrameActions {
        retail_frame: 640,
        start: 104,
        len: 5,
    },
    FrameActions {
        retail_frame: 644,
        start: 109,
        len: 5,
    },
    FrameActions {
        retail_frame: 648,
        start: 114,
        len: 5,
    },
    FrameActions {
        retail_frame: 652,
        start: 119,
        len: 5,
    },
    FrameActions {
        retail_frame: 656,
        start: 124,
        len: 8,
    },
    FrameActions {
        retail_frame: 660,
        start: 132,
        len: 5,
    },
    FrameActions {
        retail_frame: 664,
        start: 137,
        len: 5,
    },
    FrameActions {
        retail_frame: 668,
        start: 142,
        len: 5,
    },
    FrameActions {
        retail_frame: 672,
        start: 147,
        len: 5,
    },
    FrameActions {
        retail_frame: 676,
        start: 152,
        len: 5,
    },
    FrameActions {
        retail_frame: 680,
        start: 157,
        len: 5,
    },
    FrameActions {
        retail_frame: 684,
        start: 162,
        len: 5,
    },
    FrameActions {
        retail_frame: 688,
        start: 167,
        len: 5,
    },
    FrameActions {
        retail_frame: 692,
        start: 172,
        len: 8,
    },
    FrameActions {
        retail_frame: 696,
        start: 180,
        len: 5,
    },
    FrameActions {
        retail_frame: 700,
        start: 185,
        len: 8,
    },
    FrameActions {
        retail_frame: 704,
        start: 193,
        len: 5,
    },
    FrameActions {
        retail_frame: 708,
        start: 198,
        len: 5,
    },
    FrameActions {
        retail_frame: 712,
        start: 203,
        len: 5,
    },
    FrameActions {
        retail_frame: 716,
        start: 208,
        len: 5,
    },
    FrameActions {
        retail_frame: 720,
        start: 213,
        len: 9,
    },
    FrameActions {
        retail_frame: 724,
        start: 222,
        len: 5,
    },
    FrameActions {
        retail_frame: 728,
        start: 227,
        len: 5,
    },
    FrameActions {
        retail_frame: 732,
        start: 232,
        len: 5,
    },
    FrameActions {
        retail_frame: 736,
        start: 237,
        len: 5,
    },
    FrameActions {
        retail_frame: 740,
        start: 242,
        len: 9,
    },
    FrameActions {
        retail_frame: 744,
        start: 251,
        len: 5,
    },
    FrameActions {
        retail_frame: 748,
        start: 256,
        len: 5,
    },
    FrameActions {
        retail_frame: 752,
        start: 261,
        len: 5,
    },
    FrameActions {
        retail_frame: 756,
        start: 266,
        len: 5,
    },
    FrameActions {
        retail_frame: 760,
        start: 271,
        len: 5,
    },
    FrameActions {
        retail_frame: 764,
        start: 276,
        len: 5,
    },
    FrameActions {
        retail_frame: 768,
        start: 281,
        len: 3,
    },
    FrameActions {
        retail_frame: 772,
        start: 284,
        len: 2,
    },
    FrameActions {
        retail_frame: 776,
        start: 286,
        len: 2,
    },
    FrameActions {
        retail_frame: 780,
        start: 288,
        len: 2,
    },
    FrameActions {
        retail_frame: 784,
        start: 290,
        len: 2,
    },
    FrameActions {
        retail_frame: 788,
        start: 292,
        len: 2,
    },
    FrameActions {
        retail_frame: 792,
        start: 294,
        len: 2,
    },
    FrameActions {
        retail_frame: 796,
        start: 296,
        len: 2,
    },
    FrameActions {
        retail_frame: 800,
        start: 298,
        len: 2,
    },
    FrameActions {
        retail_frame: 804,
        start: 300,
        len: 2,
    },
    FrameActions {
        retail_frame: 808,
        start: 302,
        len: 4,
    },
    FrameActions {
        retail_frame: 816,
        start: 306,
        len: 4,
    },
    FrameActions {
        retail_frame: 824,
        start: 310,
        len: 2,
    },
    FrameActions {
        retail_frame: 828,
        start: 312,
        len: 2,
    },
    FrameActions {
        retail_frame: 832,
        start: 314,
        len: 2,
    },
    FrameActions {
        retail_frame: 836,
        start: 316,
        len: 2,
    },
    FrameActions {
        retail_frame: 840,
        start: 318,
        len: 2,
    },
    FrameActions {
        retail_frame: 844,
        start: 320,
        len: 2,
    },
    FrameActions {
        retail_frame: 848,
        start: 322,
        len: 2,
    },
    FrameActions {
        retail_frame: 852,
        start: 324,
        len: 2,
    },
    FrameActions {
        retail_frame: 856,
        start: 326,
        len: 1,
    },
    FrameActions {
        retail_frame: 860,
        start: 327,
        len: 1,
    },
    FrameActions {
        retail_frame: 864,
        start: 328,
        len: 2,
    },
    FrameActions {
        retail_frame: 868,
        start: 330,
        len: 2,
    },
    FrameActions {
        retail_frame: 872,
        start: 332,
        len: 2,
    },
    FrameActions {
        retail_frame: 876,
        start: 334,
        len: 1,
    },
    FrameActions {
        retail_frame: 880,
        start: 335,
        len: 1,
    },
    FrameActions {
        retail_frame: 884,
        start: 336,
        len: 1,
    },
    FrameActions {
        retail_frame: 888,
        start: 337,
        len: 1,
    },
    FrameActions {
        retail_frame: 892,
        start: 338,
        len: 1,
    },
    FrameActions {
        retail_frame: 896,
        start: 339,
        len: 1,
    },
    FrameActions {
        retail_frame: 900,
        start: 340,
        len: 1,
    },
    FrameActions {
        retail_frame: 904,
        start: 341,
        len: 1,
    },
    FrameActions {
        retail_frame: 908,
        start: 342,
        len: 1,
    },
    FrameActions {
        retail_frame: 912,
        start: 343,
        len: 1,
    },
    FrameActions {
        retail_frame: 916,
        start: 344,
        len: 1,
    },
    FrameActions {
        retail_frame: 920,
        start: 345,
        len: 1,
    },
    FrameActions {
        retail_frame: 924,
        start: 346,
        len: 1,
    },
    FrameActions {
        retail_frame: 928,
        start: 347,
        len: 1,
    },
    FrameActions {
        retail_frame: 932,
        start: 348,
        len: 1,
    },
    FrameActions {
        retail_frame: 936,
        start: 349,
        len: 1,
    },
    FrameActions {
        retail_frame: 940,
        start: 350,
        len: 2,
    },
    FrameActions {
        retail_frame: 944,
        start: 352,
        len: 1,
    },
    FrameActions {
        retail_frame: 948,
        start: 353,
        len: 1,
    },
    FrameActions {
        retail_frame: 952,
        start: 354,
        len: 1,
    },
];

static WOLF_BLOCKADE_ACTIONS: [FinalRivalAction; 355] = [
    FinalRivalAction::BeginApproach,
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryClimb),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryClimb),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryClimb),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryClimb),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryClimb),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryClimb),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryClimb),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryClimb),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryClimb),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryClimb),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryClimb),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryClimb),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryClimb),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryClimb),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryClimb),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryDive),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryDive),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryDive),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryDive),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryDive),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryDive),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryDive),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryDive),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryDive),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryDive),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryDive),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryDive),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryDive),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryDive),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryDive),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryDive),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryDive),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryDive),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryDive),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryDive),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryDive),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryDive),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryDive),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryDive),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryDive),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryDive),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryDive),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryDive),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryDive),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryDive),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryDive),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryDive),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryDive),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryDive),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryDive),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryDive),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryDive),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryDive),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryDive),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryDive),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryDive),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryDive),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryDive),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::EntryDive),
    FinalRivalAction::BeginCombatManeuver,
    FinalRivalAction::ChaseRollToLevel,
    FinalRivalAction::Advance,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::ChaseRollToLevel,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::Advance,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::ChaseRollToLevel,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::Advance,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::ChaseRollToLevel,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::Advance,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::ChaseRollToLevel,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::Advance,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::ChaseRollToLevel,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::Advance,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::ChaseRollToLevel,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::Advance,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::ChaseRollToLevel,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::Advance,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::ChaseRollToLevel,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::Advance,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::ChaseRollToLevel,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::Advance,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::ChaseRollToLevel,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::Advance,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::ChaseRollToLevel,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::Advance,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::ChaseRollToLevel,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::Advance,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::ChaseRollToLevel,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::Advance,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::ChaseRollToLevel,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::Advance,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::ChaseRollToLevel,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::Advance,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::ChaseRollToLevel,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::Advance,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::ChaseRollToLevel,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::Advance,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::ChaseRollToLevel,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::Advance,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::ChaseRollToLevel,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::Advance,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::ChaseRollToLevel,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::Advance,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::ChaseRollToLevel,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::Advance,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::ChaseRollToLevel,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::Advance,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::ChaseRollToLevel,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::BeginAttack,
    FinalRivalAction::FacePlayerYawAndLevelPitch(PlayerTargetTiming::Midpoint),
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::Advance,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::FacePlayerYawAndLevelPitch(PlayerTargetTiming::Previous),
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::Advance,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::FacePlayerYawAndLevelPitch(PlayerTargetTiming::Previous),
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::Advance,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::FacePlayerYawAndLevelPitch(PlayerTargetTiming::Current),
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::Advance,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::FacePlayerYawAndLevelPitch(PlayerTargetTiming::Current),
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::Advance,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::FacePlayerYawAndLevelPitch(PlayerTargetTiming::Current),
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::Advance,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::FacePlayerYawAndLevelPitch(PlayerTargetTiming::Midpoint),
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::Advance,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::FacePlayerYawAndLevelPitch(PlayerTargetTiming::Previous),
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::Advance,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::FacePlayerYawAndLevelPitch(PlayerTargetTiming::Previous),
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::Advance,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::FacePlayerYawAndLevelPitch(PlayerTargetTiming::Current),
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::Advance,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::FacePlayerYawAndLevelPitch(PlayerTargetTiming::Current),
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::Advance,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::FacePlayerYawAndLevelPitch(PlayerTargetTiming::Current),
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::Advance,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::FacePlayerYawAndLevelPitch(PlayerTargetTiming::Midpoint),
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::Advance,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::FacePlayerYawAndLevelPitch(PlayerTargetTiming::Previous),
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::Advance,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::FacePlayerYawAndLevelPitch(PlayerTargetTiming::Previous),
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::Advance,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::FacePlayerYawAndLevelPitch(PlayerTargetTiming::Current),
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::Advance,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::FacePlayerYawAndLevelPitch(PlayerTargetTiming::Current),
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::Advance,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::FacePlayerYawAndLevelPitch(PlayerTargetTiming::Current),
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::Advance,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::FacePlayerYawAndLevelPitch(PlayerTargetTiming::Midpoint),
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::Advance,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::FacePlayerYawAndLevelPitch(PlayerTargetTiming::Previous),
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::Advance,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::FacePlayerYawAndLevelPitch(PlayerTargetTiming::Previous),
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::Advance,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::FacePlayerSmooth(PlayerTargetTiming::Previous),
    FinalRivalAction::MaintainCombatAltitude,
    FinalRivalAction::Advance,
    FinalRivalAction::FacePlayerSmooth(PlayerTargetTiming::Current),
    FinalRivalAction::Advance,
    FinalRivalAction::FacePlayerSmooth(PlayerTargetTiming::Current),
    FinalRivalAction::Advance,
    FinalRivalAction::FacePlayerSmooth(PlayerTargetTiming::Current),
    FinalRivalAction::Advance,
    FinalRivalAction::FacePlayerSmooth(PlayerTargetTiming::Current),
    FinalRivalAction::Advance,
    FinalRivalAction::FacePlayerSmooth(PlayerTargetTiming::Midpoint),
    FinalRivalAction::Advance,
    FinalRivalAction::FacePlayerSmooth(PlayerTargetTiming::Previous),
    FinalRivalAction::Advance,
    FinalRivalAction::FacePlayerSmooth(PlayerTargetTiming::Previous),
    FinalRivalAction::Advance,
    FinalRivalAction::FacePlayerSmooth(PlayerTargetTiming::Previous),
    FinalRivalAction::Advance,
    FinalRivalAction::FacePlayerSmooth(PlayerTargetTiming::Previous),
    FinalRivalAction::Advance,
    FinalRivalAction::FacePlayerSmooth(PlayerTargetTiming::Previous),
    FinalRivalAction::Advance,
    FinalRivalAction::FacePlayerSmooth(PlayerTargetTiming::Previous),
    FinalRivalAction::Advance,
    FinalRivalAction::FacePlayerSmooth(PlayerTargetTiming::Previous),
    FinalRivalAction::Advance,
    FinalRivalAction::FacePlayerSmooth(PlayerTargetTiming::Current),
    FinalRivalAction::Advance,
    FinalRivalAction::FacePlayerSmooth(PlayerTargetTiming::Previous),
    FinalRivalAction::Advance,
    FinalRivalAction::FacePlayerSmooth(PlayerTargetTiming::Current),
    FinalRivalAction::Advance,
    FinalRivalAction::FacePlayerSmooth(PlayerTargetTiming::Previous),
    FinalRivalAction::Advance,
    FinalRivalAction::FacePlayerSmooth(PlayerTargetTiming::Previous),
    FinalRivalAction::Advance,
    FinalRivalAction::FacePlayerSmooth(PlayerTargetTiming::Current),
    FinalRivalAction::Advance,
    FinalRivalAction::FacePlayerSmooth(PlayerTargetTiming::Current),
    FinalRivalAction::Advance,
    FinalRivalAction::FacePlayerSmooth(PlayerTargetTiming::Current),
    FinalRivalAction::Advance,
    FinalRivalAction::FacePlayerSmooth(PlayerTargetTiming::Current),
    FinalRivalAction::Advance,
    FinalRivalAction::FacePlayerSmooth(PlayerTargetTiming::Current),
    FinalRivalAction::Advance,
    FinalRivalAction::FacePlayerSmooth(PlayerTargetTiming::Current),
    FinalRivalAction::Advance,
    FinalRivalAction::FacePlayerSmooth(PlayerTargetTiming::Current),
    FinalRivalAction::Advance,
    FinalRivalAction::FacePlayerSmooth(PlayerTargetTiming::Previous),
    FinalRivalAction::Advance,
    FinalRivalAction::FacePlayerSmooth(PlayerTargetTiming::Previous),
    FinalRivalAction::Advance,
    FinalRivalAction::BeginDeparture,
    FinalRivalAction::LaunchDeparture,
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::SecondClimb),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::SecondClimb),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::SecondClimb),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::SecondClimb),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::SecondClimb),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::SecondClimb),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::SecondClimb),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::SecondClimb),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::SecondClimb),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::SecondClimb),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::SecondClimb),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::SecondClimb),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::SecondDive),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::SecondDive),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::SecondDive),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::SecondDive),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::SecondDive),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::SecondDive),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::SecondDive),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::SecondDive),
    FinalRivalAction::AdvanceSteered(RivalApproachSteering::SecondDive),
];

pub(super) const WOLF_BLOCKADE: FinalRivalFlightPlan = FinalRivalFlightPlan {
    presentation_start_retail_frame: 60,
    flight_start_retail_frame: 408,
    end_retail_frame: 952,
    departure_retail_frame: 956,
    initial_pose: mission_encounter_pose([10_137, 0, 8_181, 21, 76, 0, 0]),
    hidden_retail_frames: &[],
    frames: &WOLF_BLOCKADE_FRAMES,
    actions: &WOLF_BLOCKADE_ACTIONS,
};
