//! Generated semantic projectile dynamics for the final pursuer sortie.
//! Source addresses and opaque machine state remain in oracle tooling.

use super::{
    mission_encounter_pose, HostileProjectileAction, HostileProjectileTarget, MissionEncounterPose,
};

pub(super) const PROJECTILE_COUNT: usize = 3;
const RETAIL_FRAME_STEP: u16 = 4;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(super) struct HostileProjectileDescriptor {
    pub start_retail_frame: u16,
    pub end_retail_frame: u16,
    pub initial_pose: MissionEncounterPose,
    tick_offset: u16,
    tick_count: u8,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
struct ActionRange {
    start: u16,
    len: u8,
}

static DESCRIPTORS: [HostileProjectileDescriptor; 3] = [
    HostileProjectileDescriptor {
        start_retail_frame: 728,
        end_retail_frame: 836,
        initial_pose: mission_encounter_pose([3_171, -2_982, 7_116, 24, 122, 0, 63]),
        tick_offset: 0,
        tick_count: 27,
    },
    HostileProjectileDescriptor {
        start_retail_frame: 756,
        end_retail_frame: 800,
        initial_pose: mission_encounter_pose([2_981, -1_858, 5_303, 22, 123, 0, 63]),
        tick_offset: 27,
        tick_count: 11,
    },
    HostileProjectileDescriptor {
        start_retail_frame: 788,
        end_retail_frame: 820,
        initial_pose: mission_encounter_pose([2_811, -886, 3_394, 17, 124, 0, 63]),
        tick_offset: 38,
        tick_count: 8,
    },
];

static TICKS: [ActionRange; 46] = [
    ActionRange { start: 0, len: 5 },
    ActionRange { start: 5, len: 5 },
    ActionRange { start: 10, len: 5 },
    ActionRange { start: 15, len: 5 },
    ActionRange { start: 20, len: 6 },
    ActionRange { start: 26, len: 9 },
    ActionRange { start: 35, len: 5 },
    ActionRange { start: 40, len: 5 },
    ActionRange { start: 45, len: 5 },
    ActionRange { start: 50, len: 5 },
    ActionRange { start: 55, len: 4 },
    ActionRange { start: 59, len: 1 },
    ActionRange { start: 60, len: 2 },
    ActionRange { start: 62, len: 1 },
    ActionRange { start: 63, len: 1 },
    ActionRange { start: 64, len: 1 },
    ActionRange { start: 65, len: 1 },
    ActionRange { start: 66, len: 1 },
    ActionRange { start: 67, len: 1 },
    ActionRange { start: 68, len: 1 },
    ActionRange { start: 69, len: 2 },
    ActionRange { start: 71, len: 1 },
    ActionRange { start: 72, len: 1 },
    ActionRange { start: 73, len: 1 },
    ActionRange { start: 74, len: 2 },
    ActionRange { start: 76, len: 1 },
    ActionRange { start: 77, len: 1 },
    ActionRange { start: 78, len: 5 },
    ActionRange { start: 83, len: 5 },
    ActionRange { start: 88, len: 5 },
    ActionRange { start: 93, len: 5 },
    ActionRange { start: 98, len: 5 },
    ActionRange { start: 103, len: 5 },
    ActionRange { start: 108, len: 5 },
    ActionRange { start: 113, len: 5 },
    ActionRange { start: 118, len: 3 },
    ActionRange { start: 121, len: 1 },
    ActionRange { start: 122, len: 1 },
    ActionRange { start: 123, len: 5 },
    ActionRange { start: 128, len: 5 },
    ActionRange { start: 133, len: 5 },
    ActionRange { start: 138, len: 5 },
    ActionRange { start: 143, len: 4 },
    ActionRange { start: 147, len: 2 },
    ActionRange { start: 149, len: 1 },
    ActionRange { start: 150, len: 1 },
];

static ACTIONS: [HostileProjectileAction; 151] = [
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Midpoint),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Midpoint),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Midpoint),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Midpoint),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Previous),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Previous),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Previous),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Previous),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::SetCruiseSpeed,
    HostileProjectileAction::AdvanceAimCorrection,
    HostileProjectileAction::FaceTargetSmooth(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceAimCorrection,
    HostileProjectileAction::AdvanceAimCorrection,
    HostileProjectileAction::FaceTargetSmooth(HostileProjectileTarget::Previous),
    HostileProjectileAction::AdvanceAimCorrection,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Midpoint),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Midpoint),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Midpoint),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Midpoint),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Previous),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Previous),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::SetCruiseSpeed,
    HostileProjectileAction::AdvanceAimCorrection,
    HostileProjectileAction::AdvanceAimCorrection,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Midpoint),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Midpoint),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Midpoint),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Midpoint),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Previous),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Previous),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Previous),
    HostileProjectileAction::SetCruiseSpeed,
    HostileProjectileAction::AdvanceAimCorrection,
    HostileProjectileAction::AdvanceAimCorrection,
    HostileProjectileAction::FaceTargetSmooth(HostileProjectileTarget::Previous),
    HostileProjectileAction::AdvanceAimCorrection,
    HostileProjectileAction::AdvanceAimCorrection,
    HostileProjectileAction::AdvanceCruise,
];

pub(super) fn descriptor(track_index: usize) -> Option<&'static HostileProjectileDescriptor> {
    DESCRIPTORS.get(track_index)
}

pub(super) fn actions(track_index: usize, retail_frame: u16) -> &'static [HostileProjectileAction] {
    let Some(descriptor) = descriptor(track_index) else {
        return &[];
    };
    let Some(offset) = retail_frame.checked_sub(descriptor.start_retail_frame + RETAIL_FRAME_STEP)
    else {
        return &[];
    };
    if offset % RETAIL_FRAME_STEP != 0 {
        return &[];
    }
    let tick = offset / RETAIL_FRAME_STEP;
    if tick >= u16::from(descriptor.tick_count) {
        return &[];
    }
    let range = TICKS[usize::from(descriptor.tick_offset + tick)];
    let start = usize::from(range.start);
    &ACTIONS[start..start + usize::from(range.len)]
}
