//! Generated semantic projectile dynamics for the extended retail Leon duel.
//! Source addresses and opaque machine state remain in oracle tooling.

use super::{
    mission_encounter_pose, HostileProjectileAction, HostileProjectileTarget, MissionEncounterPose,
};

pub(super) const PROJECTILE_COUNT: usize = 6;
const RETAIL_FRAME_STEP: u16 = 4;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(super) struct HostileProjectileDescriptor {
    pub start_retail_frame: u16,
    pub end_retail_frame: u16,
    pub initial_pose: MissionEncounterPose,
    pub collision_enabled: bool,
    tick_offset: u16,
    tick_count: u8,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
struct ActionRange {
    start: u16,
    len: u8,
}

static DESCRIPTORS: [HostileProjectileDescriptor; 6] = [
    HostileProjectileDescriptor {
        start_retail_frame: 764,
        end_retail_frame: 816,
        initial_pose: mission_encounter_pose([2_910, -2_490, 7_261, 24, 119, 0, 63]),
        collision_enabled: true,
        tick_offset: 0,
        tick_count: 13,
    },
    HostileProjectileDescriptor {
        start_retail_frame: 792,
        end_retail_frame: 880,
        initial_pose: mission_encounter_pose([2_586, -1_391, 5_455, 21, 120, 0, 63]),
        collision_enabled: true,
        tick_offset: 13,
        tick_count: 22,
    },
    HostileProjectileDescriptor {
        start_retail_frame: 1_184,
        end_retail_frame: 1_296,
        initial_pose: mission_encounter_pose([-906, -2_277, -944, 21, 224, 0, 63]),
        collision_enabled: false,
        tick_offset: 35,
        tick_count: 28,
    },
    HostileProjectileDescriptor {
        start_retail_frame: 1_216,
        end_retail_frame: 1_320,
        initial_pose: mission_encounter_pose([476, -1_332, 387, 17, 223, 0, 63]),
        collision_enabled: false,
        tick_offset: 63,
        tick_count: 26,
    },
    HostileProjectileDescriptor {
        start_retail_frame: 1_636,
        end_retail_frame: 1_688,
        initial_pose: mission_encounter_pose([7_792, 2_325, 10_350, 233, 111, 0, 63]),
        collision_enabled: true,
        tick_offset: 89,
        tick_count: 13,
    },
    HostileProjectileDescriptor {
        start_retail_frame: 1_668,
        end_retail_frame: 1_764,
        initial_pose: mission_encounter_pose([7_086, 1_258, 8_632, 236, 111, 0, 63]),
        collision_enabled: true,
        tick_offset: 102,
        tick_count: 24,
    },
];

static TICKS: [ActionRange; 126] = [
    ActionRange { start: 0, len: 8 },
    ActionRange { start: 8, len: 12 },
    ActionRange { start: 20, len: 12 },
    ActionRange { start: 32, len: 8 },
    ActionRange { start: 40, len: 8 },
    ActionRange { start: 48, len: 8 },
    ActionRange { start: 56, len: 8 },
    ActionRange { start: 64, len: 8 },
    ActionRange { start: 72, len: 4 },
    ActionRange { start: 76, len: 1 },
    ActionRange { start: 77, len: 1 },
    ActionRange { start: 78, len: 1 },
    ActionRange { start: 79, len: 0 },
    ActionRange { start: 79, len: 8 },
    ActionRange { start: 87, len: 8 },
    ActionRange { start: 95, len: 8 },
    ActionRange { start: 103, len: 8 },
    ActionRange { start: 111, len: 8 },
    ActionRange { start: 119, len: 4 },
    ActionRange { start: 123, len: 1 },
    ActionRange { start: 124, len: 2 },
    ActionRange { start: 126, len: 1 },
    ActionRange { start: 127, len: 1 },
    ActionRange { start: 128, len: 1 },
    ActionRange { start: 129, len: 1 },
    ActionRange { start: 130, len: 1 },
    ActionRange { start: 131, len: 2 },
    ActionRange { start: 133, len: 1 },
    ActionRange { start: 134, len: 1 },
    ActionRange { start: 135, len: 1 },
    ActionRange { start: 136, len: 2 },
    ActionRange { start: 138, len: 1 },
    ActionRange { start: 139, len: 1 },
    ActionRange { start: 140, len: 1 },
    ActionRange { start: 141, len: 1 },
    ActionRange { start: 142, len: 8 },
    ActionRange { start: 150, len: 8 },
    ActionRange { start: 158, len: 8 },
    ActionRange { start: 166, len: 8 },
    ActionRange { start: 174, len: 8 },
    ActionRange { start: 182, len: 8 },
    ActionRange { start: 190, len: 8 },
    ActionRange { start: 198, len: 8 },
    ActionRange { start: 206, len: 8 },
    ActionRange { start: 214, len: 8 },
    ActionRange { start: 222, len: 3 },
    ActionRange { start: 225, len: 2 },
    ActionRange { start: 227, len: 1 },
    ActionRange { start: 228, len: 1 },
    ActionRange { start: 229, len: 1 },
    ActionRange { start: 230, len: 1 },
    ActionRange { start: 231, len: 1 },
    ActionRange { start: 232, len: 1 },
    ActionRange { start: 233, len: 1 },
    ActionRange { start: 234, len: 1 },
    ActionRange { start: 235, len: 1 },
    ActionRange { start: 236, len: 1 },
    ActionRange { start: 237, len: 1 },
    ActionRange { start: 238, len: 1 },
    ActionRange { start: 239, len: 1 },
    ActionRange { start: 240, len: 1 },
    ActionRange { start: 241, len: 1 },
    ActionRange { start: 242, len: 1 },
    ActionRange { start: 243, len: 8 },
    ActionRange { start: 251, len: 8 },
    ActionRange { start: 259, len: 8 },
    ActionRange { start: 267, len: 8 },
    ActionRange { start: 275, len: 8 },
    ActionRange { start: 283, len: 8 },
    ActionRange { start: 291, len: 3 },
    ActionRange { start: 294, len: 2 },
    ActionRange { start: 296, len: 1 },
    ActionRange { start: 297, len: 2 },
    ActionRange { start: 299, len: 1 },
    ActionRange { start: 300, len: 1 },
    ActionRange { start: 301, len: 1 },
    ActionRange { start: 302, len: 1 },
    ActionRange { start: 303, len: 1 },
    ActionRange { start: 304, len: 1 },
    ActionRange { start: 305, len: 1 },
    ActionRange { start: 306, len: 1 },
    ActionRange { start: 307, len: 1 },
    ActionRange { start: 308, len: 1 },
    ActionRange { start: 309, len: 1 },
    ActionRange { start: 310, len: 1 },
    ActionRange { start: 311, len: 1 },
    ActionRange { start: 312, len: 1 },
    ActionRange { start: 313, len: 1 },
    ActionRange { start: 314, len: 1 },
    ActionRange { start: 315, len: 8 },
    ActionRange { start: 323, len: 8 },
    ActionRange { start: 331, len: 8 },
    ActionRange { start: 339, len: 8 },
    ActionRange { start: 347, len: 8 },
    ActionRange { start: 355, len: 8 },
    ActionRange { start: 363, len: 8 },
    ActionRange { start: 371, len: 8 },
    ActionRange { start: 379, len: 4 },
    ActionRange { start: 383, len: 4 },
    ActionRange { start: 387, len: 4 },
    ActionRange { start: 391, len: 1 },
    ActionRange { start: 392, len: 1 },
    ActionRange { start: 393, len: 8 },
    ActionRange { start: 401, len: 0 },
    ActionRange { start: 401, len: 8 },
    ActionRange { start: 409, len: 8 },
    ActionRange { start: 417, len: 8 },
    ActionRange { start: 425, len: 8 },
    ActionRange { start: 433, len: 4 },
    ActionRange { start: 437, len: 1 },
    ActionRange { start: 438, len: 2 },
    ActionRange { start: 440, len: 1 },
    ActionRange { start: 441, len: 1 },
    ActionRange { start: 442, len: 1 },
    ActionRange { start: 443, len: 1 },
    ActionRange { start: 444, len: 1 },
    ActionRange { start: 445, len: 1 },
    ActionRange { start: 446, len: 1 },
    ActionRange { start: 447, len: 1 },
    ActionRange { start: 448, len: 1 },
    ActionRange { start: 449, len: 2 },
    ActionRange { start: 451, len: 1 },
    ActionRange { start: 452, len: 1 },
    ActionRange { start: 453, len: 1 },
    ActionRange { start: 454, len: 1 },
    ActionRange { start: 455, len: 1 },
];

static ACTIONS: [HostileProjectileAction; 456] = [
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Previous),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Previous),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Previous),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Previous),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Previous),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Previous),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Previous),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Previous),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Previous),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Previous),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::SetCruiseSpeed,
    HostileProjectileAction::AdvanceAimCorrection,
    HostileProjectileAction::FaceTargetSmooth(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceAimCorrection,
    HostileProjectileAction::AdvanceAimCorrection,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::SetCruiseSpeed,
    HostileProjectileAction::AdvanceAimCorrection,
    HostileProjectileAction::FaceTargetSmooth(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceAimCorrection,
    HostileProjectileAction::AdvanceAimCorrection,
    HostileProjectileAction::FaceTargetSmooth(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceAimCorrection,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::SetCruiseSpeed,
    HostileProjectileAction::AdvanceAimCorrection,
    HostileProjectileAction::AdvanceAimCorrection,
    HostileProjectileAction::FaceTargetSmooth(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceAimCorrection,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::SetCruiseSpeed,
    HostileProjectileAction::AdvanceAimCorrection,
    HostileProjectileAction::AdvanceAimCorrection,
    HostileProjectileAction::FaceTargetSmooth(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceAimCorrection,
    HostileProjectileAction::AdvanceAimCorrection,
    HostileProjectileAction::FaceTargetSmooth(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceAimCorrection,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Previous),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Previous),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Previous),
    HostileProjectileAction::SetCruiseSpeed,
    HostileProjectileAction::AdvanceAimCorrection,
    HostileProjectileAction::FaceTargetSmooth(HostileProjectileTarget::Previous),
    HostileProjectileAction::AdvanceAimCorrection,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Previous),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Previous),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Previous),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Previous),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::SetCruiseSpeed,
    HostileProjectileAction::AdvanceAimCorrection,
    HostileProjectileAction::FaceTargetSmooth(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceAimCorrection,
    HostileProjectileAction::AdvanceAimCorrection,
    HostileProjectileAction::FaceTargetSmooth(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceAimCorrection,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
];

static ACTION_PLAYER_TARGETS: [Option<HostileProjectileTarget>; 456] = [
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Midpoint),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Midpoint),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Midpoint),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Midpoint),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Midpoint),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Previous),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
    Some(HostileProjectileTarget::Current),
];

pub(super) fn descriptor(track_index: usize) -> Option<&'static HostileProjectileDescriptor> {
    DESCRIPTORS.get(track_index)
}

pub(super) fn actions(track_index: usize, retail_frame: u16) -> &'static [HostileProjectileAction] {
    let Some(descriptor) = descriptor(track_index) else {
        return &[];
    };
    let Some(offset) = retail_frame.checked_sub(descriptor.start_retail_frame + RETAIL_FRAME_STEP)
    else {
        return &[];
    };
    if offset % RETAIL_FRAME_STEP != 0 {
        return &[];
    }
    let tick = offset / RETAIL_FRAME_STEP;
    if tick >= u16::from(descriptor.tick_count) {
        return &[];
    }
    let range = TICKS[usize::from(descriptor.tick_offset + tick)];
    let start = usize::from(range.start);
    &ACTIONS[start..start + usize::from(range.len)]
}

pub(super) fn action_player_targets(
    track_index: usize,
    retail_frame: u16,
) -> &'static [Option<HostileProjectileTarget>] {
    let Some(descriptor) = descriptor(track_index) else {
        return &[];
    };
    let Some(offset) = retail_frame.checked_sub(descriptor.start_retail_frame + RETAIL_FRAME_STEP)
    else {
        return &[];
    };
    if offset % RETAIL_FRAME_STEP != 0 {
        return &[];
    }
    let tick = offset / RETAIL_FRAME_STEP;
    if tick >= u16::from(descriptor.tick_count) {
        return &[];
    }
    let range = TICKS[usize::from(descriptor.tick_offset + tick)];
    let start = usize::from(range.start);
    &ACTION_PLAYER_TARGETS[start..start + usize::from(range.len)]
}

#[cfg(test)]
pub(super) const NATURAL_HITS: [(u16, usize, u8); 1] = [(808, 0, 2)];

#[cfg(test)]
use super::{mission_projectile_keyframe, MissionProjectileKeyframe};

#[cfg(test)]
static ORACLE_TRACK_0: [MissionProjectileKeyframe; 14] = [
    mission_projectile_keyframe(764, [2_910, -2_490, 7_261, 24, 119, 0, 63]),
    mission_projectile_keyframe(768, [2_789, -2_215, 6_716, 23, 119, 0, 63]),
    mission_projectile_keyframe(772, [2_620, -1_847, 5_939, 23, 120, 0, 63]),
    mission_projectile_keyframe(776, [2_444, -1_406, 5_071, 22, 120, 0, 63]),
    mission_projectile_keyframe(780, [2_330, -1_144, 4_519, 22, 120, 0, 63]),
    mission_projectile_keyframe(784, [2_216, -885, 3_964, 22, 120, 0, 63]),
    mission_projectile_keyframe(788, [2_102, -636, 3_405, 21, 120, 0, 63]),
    mission_projectile_keyframe(792, [1_988, -397, 2_839, 20, 120, 0, 63]),
    mission_projectile_keyframe(796, [1_874, -171, 2_270, 19, 120, 0, 63]),
    mission_projectile_keyframe(800, [1_834, -83, 2_046, 14, 119, 0, 63]),
    mission_projectile_keyframe(804, [1_786, -3, 1_826, 14, 119, 0, 63]),
    mission_projectile_keyframe(808, [1_738, 77, 1_606, 14, 119, 0, 63]),
    mission_projectile_keyframe(812, [1_690, 157, 1_386, 14, 119, 0, 63]),
    mission_projectile_keyframe(816, [1_690, 157, 1_386, 14, 119, 0, 63]),
];

#[cfg(test)]
static ORACLE_TRACK_1: [MissionProjectileKeyframe; 23] = [
    mission_projectile_keyframe(792, [2_586, -1_391, 5_455, 21, 120, 0, 63]),
    mission_projectile_keyframe(796, [2_469, -1_149, 4_890, 20, 120, 0, 63]),
    mission_projectile_keyframe(800, [2_352, -910, 4_324, 20, 120, 0, 63]),
    mission_projectile_keyframe(804, [2_235, -680, 3_758, 19, 120, 0, 63]),
    mission_projectile_keyframe(808, [2_118, -462, 3_185, 18, 120, 0, 63]),
    mission_projectile_keyframe(812, [2_001, -254, 2_608, 17, 120, 0, 63]),
    mission_projectile_keyframe(816, [1_961, -162, 2_388, 15, 119, 0, 63]),
    mission_projectile_keyframe(820, [1_917, -74, 2_168, 15, 119, 0, 63]),
    mission_projectile_keyframe(824, [1_873, 14, 1_948, 11, 120, 0, 63]),
    mission_projectile_keyframe(828, [1_833, 78, 1_716, 11, 120, 0, 63]),
    mission_projectile_keyframe(832, [1_793, 142, 1_484, 11, 120, 0, 63]),
    mission_projectile_keyframe(836, [1_753, 206, 1_252, 11, 120, 0, 63]),
    mission_projectile_keyframe(840, [1_713, 270, 1_020, 11, 120, 0, 63]),
    mission_projectile_keyframe(844, [1_673, 334, 788, 11, 120, 0, 63]),
    mission_projectile_keyframe(848, [1_593, 462, 324, 11, 120, 0, 63]),
    mission_projectile_keyframe(852, [1_553, 526, 92, 11, 120, 0, 63]),
    mission_projectile_keyframe(856, [1_513, 590, -140, 11, 120, 0, 63]),
    mission_projectile_keyframe(860, [1_473, 654, -372, 11, 120, 0, 63]),
    mission_projectile_keyframe(864, [1_393, 782, -836, 11, 120, 0, 63]),
    mission_projectile_keyframe(868, [1_353, 846, -1_068, 11, 120, 0, 63]),
    mission_projectile_keyframe(872, [1_313, 910, -1_300, 11, 120, 0, 63]),
    mission_projectile_keyframe(876, [1_273, 974, -1_532, 11, 120, 0, 63]),
    mission_projectile_keyframe(880, [1_233, 1_038, -1_764, 11, 120, 0, 63]),
];

#[cfg(test)]
static ORACLE_TRACK_2: [MissionProjectileKeyframe; 29] = [
    mission_projectile_keyframe(1_184, [-906, -2_277, -944, 21, 224, 0, 63]),
    mission_projectile_keyframe(1_188, [-500, -2_029, -550, 20, 224, 0, 63]),
    mission_projectile_keyframe(1_192, [-90, -1_784, -160, 20, 223, 0, 63]),
    mission_projectile_keyframe(1_196, [316, -1_546, 234, 19, 224, 0, 63]),
    mission_projectile_keyframe(1_200, [726, -1_311, 631, 19, 223, 0, 63]),
    mission_projectile_keyframe(1_204, [1_143, -1_087, 1_028, 18, 223, 0, 63]),
    mission_projectile_keyframe(1_208, [1_560, -869, 1_425, 18, 223, 0, 63]),
    mission_projectile_keyframe(1_212, [1_977, -658, 1_826, 17, 223, 0, 63]),
    mission_projectile_keyframe(1_216, [2_401, -461, 2_230, 16, 223, 0, 63]),
    mission_projectile_keyframe(1_220, [2_825, -274, 2_634, 15, 223, 0, 63]),
    mission_projectile_keyframe(1_224, [3_252, -107, 3_045, 14, 223, 0, 63]),
    mission_projectile_keyframe(1_228, [3_416, -43, 3_205, 11, 223, 0, 63]),
    mission_projectile_keyframe(1_232, [3_580, 21, 3_365, 6, 222, 0, 63]),
    mission_projectile_keyframe(1_236, [3_756, 53, 3_525, 6, 222, 0, 63]),
    mission_projectile_keyframe(1_240, [3_932, 85, 3_685, 6, 222, 0, 63]),
    mission_projectile_keyframe(1_244, [4_108, 117, 3_845, 6, 222, 0, 63]),
    mission_projectile_keyframe(1_248, [4_284, 149, 4_005, 6, 222, 0, 63]),
    mission_projectile_keyframe(1_252, [4_460, 181, 4_165, 6, 222, 0, 63]),
    mission_projectile_keyframe(1_256, [4_636, 213, 4_325, 6, 222, 0, 63]),
    mission_projectile_keyframe(1_260, [4_812, 245, 4_485, 6, 222, 0, 63]),
    mission_projectile_keyframe(1_264, [4_988, 277, 4_645, 6, 222, 0, 63]),
    mission_projectile_keyframe(1_268, [5_164, 309, 4_805, 6, 222, 0, 63]),
    mission_projectile_keyframe(1_272, [5_340, 341, 4_965, 6, 222, 0, 63]),
    mission_projectile_keyframe(1_276, [5_516, 373, 5_125, 6, 222, 0, 63]),
    mission_projectile_keyframe(1_280, [5_692, 405, 5_285, 6, 222, 0, 63]),
    mission_projectile_keyframe(1_284, [5_868, 437, 5_445, 6, 222, 0, 63]),
    mission_projectile_keyframe(1_288, [6_044, 469, 5_605, 6, 222, 0, 63]),
    mission_projectile_keyframe(1_292, [6_220, 501, 5_765, 6, 222, 0, 63]),
    mission_projectile_keyframe(1_296, [6_396, 533, 5_925, 6, 222, 0, 63]),
];

#[cfg(test)]
static ORACLE_TRACK_3: [MissionProjectileKeyframe; 27] = [
    mission_projectile_keyframe(1_216, [476, -1_332, 387, 17, 223, 0, 63]),
    mission_projectile_keyframe(1_220, [893, -1_123, 790, 17, 223, 0, 63]),
    mission_projectile_keyframe(1_224, [1_317, -926, 1_194, 16, 223, 0, 63]),
    mission_projectile_keyframe(1_228, [1_741, -732, 1_598, 16, 223, 0, 63]),
    mission_projectile_keyframe(1_232, [2_165, -545, 2_002, 15, 223, 0, 63]),
    mission_projectile_keyframe(1_236, [2_592, -364, 2_406, 15, 223, 0, 63]),
    mission_projectile_keyframe(1_240, [3_023, -202, 2_817, 13, 223, 0, 63]),
    mission_projectile_keyframe(1_244, [3_187, -134, 2_973, 12, 223, 0, 63]),
    mission_projectile_keyframe(1_248, [3_351, -66, 3_129, 11, 223, 0, 63]),
    mission_projectile_keyframe(1_252, [3_515, -2, 3_289, 11, 223, 0, 63]),
    mission_projectile_keyframe(1_256, [3_679, 62, 3_449, 2, 222, 0, 63]),
    mission_projectile_keyframe(1_260, [3_859, 70, 3_609, 2, 222, 0, 63]),
    mission_projectile_keyframe(1_264, [4_039, 78, 3_769, 2, 222, 0, 63]),
    mission_projectile_keyframe(1_268, [4_219, 86, 3_929, 2, 222, 0, 63]),
    mission_projectile_keyframe(1_272, [4_399, 94, 4_089, 2, 222, 0, 63]),
    mission_projectile_keyframe(1_276, [4_579, 102, 4_249, 2, 222, 0, 63]),
    mission_projectile_keyframe(1_280, [4_759, 110, 4_409, 2, 222, 0, 63]),
    mission_projectile_keyframe(1_284, [4_939, 118, 4_569, 2, 222, 0, 63]),
    mission_projectile_keyframe(1_288, [5_119, 126, 4_729, 2, 222, 0, 63]),
    mission_projectile_keyframe(1_292, [5_299, 134, 4_889, 2, 222, 0, 63]),
    mission_projectile_keyframe(1_296, [5_479, 142, 5_049, 2, 222, 0, 63]),
    mission_projectile_keyframe(1_300, [5_659, 150, 5_209, 2, 222, 0, 63]),
    mission_projectile_keyframe(1_304, [5_839, 158, 5_369, 2, 222, 0, 63]),
    mission_projectile_keyframe(1_308, [6_019, 166, 5_529, 2, 222, 0, 63]),
    mission_projectile_keyframe(1_312, [6_199, 174, 5_689, 2, 222, 0, 63]),
    mission_projectile_keyframe(1_316, [6_379, 182, 5_849, 2, 222, 0, 63]),
    mission_projectile_keyframe(1_320, [6_559, 190, 6_009, 2, 222, 0, 63]),
];

#[cfg(test)]
static ORACLE_TRACK_4: [MissionProjectileKeyframe; 14] = [
    mission_projectile_keyframe(1_636, [7_792, 2_325, 10_350, 233, 111, 0, 63]),
    mission_projectile_keyframe(1_640, [7_565, 2_053, 9_838, 233, 111, 0, 63]),
    mission_projectile_keyframe(1_644, [7_342, 1_786, 9_319, 234, 112, 0, 63]),
    mission_projectile_keyframe(1_648, [7_119, 1_521, 8_800, 234, 112, 0, 63]),
    mission_projectile_keyframe(1_652, [6_896, 1_263, 8_281, 235, 112, 0, 63]),
    mission_projectile_keyframe(1_656, [6_673, 1_010, 7_759, 235, 112, 0, 63]),
    mission_projectile_keyframe(1_660, [6_446, 765, 7_233, 236, 112, 0, 63]),
    mission_projectile_keyframe(1_664, [6_219, 526, 6_704, 236, 112, 0, 63]),
    mission_projectile_keyframe(1_668, [5_989, 305, 6_171, 238, 112, 0, 63]),
    mission_projectile_keyframe(1_672, [5_889, 233, 5_947, 238, 112, 0, 63]),
    mission_projectile_keyframe(1_676, [5_759, 98, 5_631, 239, 112, 0, 63]),
    mission_projectile_keyframe(1_680, [5_675, 22, 5_419, 244, 111, 0, 63]),
    mission_projectile_keyframe(1_684, [5_583, -46, 5_207, 244, 111, 0, 63]),
    mission_projectile_keyframe(1_688, [5_491, -114, 4_995, 244, 111, 0, 63]),
];

#[cfg(test)]
static ORACLE_TRACK_5: [MissionProjectileKeyframe; 25] = [
    mission_projectile_keyframe(1_668, [7_086, 1_258, 8_632, 236, 111, 0, 63]),
    mission_projectile_keyframe(1_672, [6_856, 1_023, 8_099, 237, 112, 0, 63]),
    mission_projectile_keyframe(1_676, [6_856, 1_023, 8_099, 237, 112, 0, 63]),
    mission_projectile_keyframe(1_680, [6_626, 791, 7_566, 237, 112, 0, 63]),
    mission_projectile_keyframe(1_684, [6_396, 573, 7_030, 238, 112, 0, 63]),
    mission_projectile_keyframe(1_688, [6_166, 365, 6_490, 239, 112, 0, 63]),
    mission_projectile_keyframe(1_692, [5_932, 171, 5_943, 240, 112, 0, 63]),
    mission_projectile_keyframe(1_696, [5_848, 91, 5_735, 243, 111, 0, 63]),
    mission_projectile_keyframe(1_700, [5_756, 15, 5_523, 243, 111, 0, 63]),
    mission_projectile_keyframe(1_704, [5_664, -61, 5_311, 5, 116, 0, 63]),
    mission_projectile_keyframe(1_708, [5_600, -33, 5_079, 5, 116, 0, 63]),
    mission_projectile_keyframe(1_712, [5_536, -5, 4_847, 5, 116, 0, 63]),
    mission_projectile_keyframe(1_716, [5_472, 23, 4_615, 5, 116, 0, 63]),
    mission_projectile_keyframe(1_720, [5_408, 51, 4_383, 5, 116, 0, 63]),
    mission_projectile_keyframe(1_724, [5_344, 79, 4_151, 5, 116, 0, 63]),
    mission_projectile_keyframe(1_728, [5_280, 107, 3_919, 5, 116, 0, 63]),
    mission_projectile_keyframe(1_732, [5_216, 135, 3_687, 5, 116, 0, 63]),
    mission_projectile_keyframe(1_736, [5_152, 163, 3_455, 5, 116, 0, 63]),
    mission_projectile_keyframe(1_740, [5_088, 191, 3_223, 5, 116, 0, 63]),
    mission_projectile_keyframe(1_744, [4_960, 247, 2_759, 5, 116, 0, 63]),
    mission_projectile_keyframe(1_748, [4_896, 275, 2_527, 5, 116, 0, 63]),
    mission_projectile_keyframe(1_752, [4_832, 303, 2_295, 5, 116, 0, 63]),
    mission_projectile_keyframe(1_756, [4_768, 331, 2_063, 5, 116, 0, 63]),
    mission_projectile_keyframe(1_760, [4_704, 359, 1_831, 5, 116, 0, 63]),
    mission_projectile_keyframe(1_764, [4_640, 387, 1_599, 5, 116, 0, 63]),
];

#[cfg(test)]
pub(super) static ORACLE_TRACKS: [&[MissionProjectileKeyframe]; 6] = [
    &ORACLE_TRACK_0,
    &ORACLE_TRACK_1,
    &ORACLE_TRACK_2,
    &ORACLE_TRACK_3,
    &ORACLE_TRACK_4,
    &ORACLE_TRACK_5,
];
