//! Generated semantic rival dynamics for the retail Leon duel.
//! Source addresses and opaque machine state remain in oracle tooling.

use super::{
    mission_encounter_pose, LeonRivalAction, MissionEncounterPose,
    RivalApproachSteering,
};

pub(super) const PRESENTATION_START_RETAIL_FRAME: u16 = 52;
pub(super) const FLIGHT_START_RETAIL_FRAME: u16 = 400;
pub(super) const END_RETAIL_FRAME: u16 = 660;
pub(super) const DEPARTURE_RETAIL_FRAME: u16 = 664;
pub(super) const INITIAL_POSE: MissionEncounterPose =
    mission_encounter_pose([10_139, 0, 8_138, 23, 78, 5, 1]);

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
struct FrameActions {
    retail_frame: u16,
    start: u16,
    len: u8,
}

static FRAMES: [FrameActions; 65] = [
    FrameActions { retail_frame: 400, start: 0, len: 1 },
    FrameActions { retail_frame: 404, start: 1, len: 1 },
    FrameActions { retail_frame: 408, start: 2, len: 1 },
    FrameActions { retail_frame: 412, start: 3, len: 1 },
    FrameActions { retail_frame: 416, start: 4, len: 1 },
    FrameActions { retail_frame: 420, start: 5, len: 1 },
    FrameActions { retail_frame: 424, start: 6, len: 1 },
    FrameActions { retail_frame: 428, start: 7, len: 1 },
    FrameActions { retail_frame: 432, start: 8, len: 1 },
    FrameActions { retail_frame: 436, start: 9, len: 1 },
    FrameActions { retail_frame: 440, start: 10, len: 1 },
    FrameActions { retail_frame: 444, start: 11, len: 2 },
    FrameActions { retail_frame: 448, start: 13, len: 1 },
    FrameActions { retail_frame: 452, start: 14, len: 1 },
    FrameActions { retail_frame: 456, start: 15, len: 1 },
    FrameActions { retail_frame: 460, start: 16, len: 1 },
    FrameActions { retail_frame: 464, start: 17, len: 1 },
    FrameActions { retail_frame: 468, start: 18, len: 2 },
    FrameActions { retail_frame: 472, start: 20, len: 1 },
    FrameActions { retail_frame: 476, start: 21, len: 1 },
    FrameActions { retail_frame: 480, start: 22, len: 1 },
    FrameActions { retail_frame: 484, start: 23, len: 1 },
    FrameActions { retail_frame: 488, start: 24, len: 2 },
    FrameActions { retail_frame: 492, start: 26, len: 1 },
    FrameActions { retail_frame: 496, start: 27, len: 1 },
    FrameActions { retail_frame: 500, start: 28, len: 1 },
    FrameActions { retail_frame: 504, start: 29, len: 1 },
    FrameActions { retail_frame: 508, start: 30, len: 1 },
    FrameActions { retail_frame: 512, start: 31, len: 1 },
    FrameActions { retail_frame: 516, start: 32, len: 2 },
    FrameActions { retail_frame: 520, start: 34, len: 1 },
    FrameActions { retail_frame: 524, start: 35, len: 1 },
    FrameActions { retail_frame: 528, start: 36, len: 1 },
    FrameActions { retail_frame: 532, start: 37, len: 1 },
    FrameActions { retail_frame: 536, start: 38, len: 1 },
    FrameActions { retail_frame: 540, start: 39, len: 1 },
    FrameActions { retail_frame: 544, start: 40, len: 1 },
    FrameActions { retail_frame: 548, start: 41, len: 1 },
    FrameActions { retail_frame: 552, start: 42, len: 1 },
    FrameActions { retail_frame: 556, start: 43, len: 1 },
    FrameActions { retail_frame: 560, start: 44, len: 1 },
    FrameActions { retail_frame: 564, start: 45, len: 1 },
    FrameActions { retail_frame: 568, start: 46, len: 1 },
    FrameActions { retail_frame: 572, start: 47, len: 1 },
    FrameActions { retail_frame: 576, start: 48, len: 1 },
    FrameActions { retail_frame: 580, start: 49, len: 1 },
    FrameActions { retail_frame: 584, start: 50, len: 2 },
    FrameActions { retail_frame: 588, start: 52, len: 1 },
    FrameActions { retail_frame: 596, start: 53, len: 2 },
    FrameActions { retail_frame: 600, start: 55, len: 2 },
    FrameActions { retail_frame: 604, start: 57, len: 1 },
    FrameActions { retail_frame: 608, start: 58, len: 1 },
    FrameActions { retail_frame: 612, start: 59, len: 1 },
    FrameActions { retail_frame: 616, start: 60, len: 4 },
    FrameActions { retail_frame: 620, start: 64, len: 5 },
    FrameActions { retail_frame: 624, start: 69, len: 5 },
    FrameActions { retail_frame: 628, start: 74, len: 5 },
    FrameActions { retail_frame: 632, start: 79, len: 5 },
    FrameActions { retail_frame: 636, start: 84, len: 5 },
    FrameActions { retail_frame: 640, start: 89, len: 5 },
    FrameActions { retail_frame: 644, start: 94, len: 5 },
    FrameActions { retail_frame: 648, start: 99, len: 5 },
    FrameActions { retail_frame: 652, start: 104, len: 5 },
    FrameActions { retail_frame: 656, start: 109, len: 5 },
    FrameActions { retail_frame: 660, start: 114, len: 5 },
];

static ACTIONS: [LeonRivalAction; 119] = [
    LeonRivalAction::BeginApproach,
    LeonRivalAction::AdvanceApproach(RivalApproachSteering::EntryClimb),
    LeonRivalAction::AdvanceApproach(RivalApproachSteering::EntryClimb),
    LeonRivalAction::AdvanceApproach(RivalApproachSteering::EntryClimb),
    LeonRivalAction::AdvanceApproach(RivalApproachSteering::EntryClimb),
    LeonRivalAction::AdvanceApproach(RivalApproachSteering::EntryClimb),
    LeonRivalAction::AdvanceApproach(RivalApproachSteering::EntryClimb),
    LeonRivalAction::AdvanceApproach(RivalApproachSteering::EntryClimb),
    LeonRivalAction::AdvanceApproach(RivalApproachSteering::EntryClimb),
    LeonRivalAction::AdvanceApproach(RivalApproachSteering::EntryClimb),
    LeonRivalAction::AdvanceApproach(RivalApproachSteering::EntryClimb),
    LeonRivalAction::AdvanceApproach(RivalApproachSteering::EntryClimb),
    LeonRivalAction::AdvanceApproach(RivalApproachSteering::EntryClimb),
    LeonRivalAction::AdvanceApproach(RivalApproachSteering::EntryClimb),
    LeonRivalAction::AdvanceApproach(RivalApproachSteering::EntryClimb),
    LeonRivalAction::AdvanceApproach(RivalApproachSteering::EntryDive),
    LeonRivalAction::AdvanceApproach(RivalApproachSteering::EntryDive),
    LeonRivalAction::AdvanceApproach(RivalApproachSteering::EntryDive),
    LeonRivalAction::AdvanceApproach(RivalApproachSteering::EntryDive),
    LeonRivalAction::AdvanceApproach(RivalApproachSteering::EntryDive),
    LeonRivalAction::AdvanceApproach(RivalApproachSteering::EntryDive),
    LeonRivalAction::AdvanceApproach(RivalApproachSteering::EntryDive),
    LeonRivalAction::AdvanceApproach(RivalApproachSteering::EntryDive),
    LeonRivalAction::AdvanceApproach(RivalApproachSteering::EntryDive),
    LeonRivalAction::AdvanceApproach(RivalApproachSteering::EntryDive),
    LeonRivalAction::AdvanceApproach(RivalApproachSteering::EntryDive),
    LeonRivalAction::AdvanceApproach(RivalApproachSteering::EntryDive),
    LeonRivalAction::AdvanceApproach(RivalApproachSteering::EntryDive),
    LeonRivalAction::AdvanceApproach(RivalApproachSteering::EntryDive),
    LeonRivalAction::AdvanceApproach(RivalApproachSteering::EntryDive),
    LeonRivalAction::AdvanceApproach(RivalApproachSteering::EntryDive),
    LeonRivalAction::AdvanceApproach(RivalApproachSteering::EntryDive),
    LeonRivalAction::AdvanceApproach(RivalApproachSteering::EntryDive),
    LeonRivalAction::AdvanceApproach(RivalApproachSteering::EntryDive),
    LeonRivalAction::AdvanceApproach(RivalApproachSteering::EntryDive),
    LeonRivalAction::AdvanceApproach(RivalApproachSteering::EntryDive),
    LeonRivalAction::AdvanceApproach(RivalApproachSteering::EntryDive),
    LeonRivalAction::AdvanceApproach(RivalApproachSteering::EntryDive),
    LeonRivalAction::AdvanceApproach(RivalApproachSteering::EntryDive),
    LeonRivalAction::AdvanceApproach(RivalApproachSteering::EntryDive),
    LeonRivalAction::AdvanceApproach(RivalApproachSteering::EntryDive),
    LeonRivalAction::AdvanceApproach(RivalApproachSteering::EntryDive),
    LeonRivalAction::AdvanceApproach(RivalApproachSteering::EntryDive),
    LeonRivalAction::AdvanceApproach(RivalApproachSteering::EntryDive),
    LeonRivalAction::AdvanceApproach(RivalApproachSteering::EntryDive),
    LeonRivalAction::AdvanceApproach(RivalApproachSteering::EntryDive),
    LeonRivalAction::AdvanceApproach(RivalApproachSteering::EntryDive),
    LeonRivalAction::AdvanceApproach(RivalApproachSteering::EntryDive),
    LeonRivalAction::AdvanceApproach(RivalApproachSteering::EntryDive),
    LeonRivalAction::AdvanceApproach(RivalApproachSteering::EntryDive),
    LeonRivalAction::AdvanceApproach(RivalApproachSteering::EntryDive),
    LeonRivalAction::AdvanceApproach(RivalApproachSteering::EntryDive),
    LeonRivalAction::AdvanceApproach(RivalApproachSteering::EntryDive),
    LeonRivalAction::AdvanceApproach(RivalApproachSteering::EntryDive),
    LeonRivalAction::PrepareApproachAdvance(RivalApproachSteering::EntryDive),
    LeonRivalAction::FinishPreparedApproachAdvance,
    LeonRivalAction::AdvanceApproach(RivalApproachSteering::EntryDive),
    LeonRivalAction::AdvanceApproach(RivalApproachSteering::EntryDive),
    LeonRivalAction::AdvanceApproach(RivalApproachSteering::EntryDive),
    LeonRivalAction::AdvanceApproach(RivalApproachSteering::EntryDive),
    LeonRivalAction::BeginCombatManeuver,
    LeonRivalAction::ChaseRollToLevel,
    LeonRivalAction::Advance,
    LeonRivalAction::MaintainCombatAltitude,
    LeonRivalAction::MaintainCombatAltitude,
    LeonRivalAction::ChaseRollToLevel,
    LeonRivalAction::MaintainCombatAltitude,
    LeonRivalAction::Advance,
    LeonRivalAction::MaintainCombatAltitude,
    LeonRivalAction::MaintainCombatAltitude,
    LeonRivalAction::ChaseRollToLevel,
    LeonRivalAction::MaintainCombatAltitude,
    LeonRivalAction::Advance,
    LeonRivalAction::MaintainCombatAltitude,
    LeonRivalAction::MaintainCombatAltitude,
    LeonRivalAction::ChaseRollToLevel,
    LeonRivalAction::MaintainCombatAltitude,
    LeonRivalAction::Advance,
    LeonRivalAction::MaintainCombatAltitude,
    LeonRivalAction::MaintainCombatAltitude,
    LeonRivalAction::ChaseRollToLevel,
    LeonRivalAction::MaintainCombatAltitude,
    LeonRivalAction::Advance,
    LeonRivalAction::MaintainCombatAltitude,
    LeonRivalAction::MaintainCombatAltitude,
    LeonRivalAction::ChaseRollToLevel,
    LeonRivalAction::MaintainCombatAltitude,
    LeonRivalAction::Advance,
    LeonRivalAction::MaintainCombatAltitude,
    LeonRivalAction::MaintainCombatAltitude,
    LeonRivalAction::ChaseRollToLevel,
    LeonRivalAction::MaintainCombatAltitude,
    LeonRivalAction::Advance,
    LeonRivalAction::MaintainCombatAltitude,
    LeonRivalAction::MaintainCombatAltitude,
    LeonRivalAction::ChaseRollToLevel,
    LeonRivalAction::MaintainCombatAltitude,
    LeonRivalAction::Advance,
    LeonRivalAction::MaintainCombatAltitude,
    LeonRivalAction::MaintainCombatAltitude,
    LeonRivalAction::ChaseRollToLevel,
    LeonRivalAction::MaintainCombatAltitude,
    LeonRivalAction::Advance,
    LeonRivalAction::MaintainCombatAltitude,
    LeonRivalAction::MaintainCombatAltitude,
    LeonRivalAction::ChaseRollToLevel,
    LeonRivalAction::MaintainCombatAltitude,
    LeonRivalAction::Advance,
    LeonRivalAction::MaintainCombatAltitude,
    LeonRivalAction::MaintainCombatAltitude,
    LeonRivalAction::ChaseRollToLevel,
    LeonRivalAction::MaintainCombatAltitude,
    LeonRivalAction::Advance,
    LeonRivalAction::MaintainCombatAltitude,
    LeonRivalAction::MaintainCombatAltitude,
    LeonRivalAction::ChaseRollToLevel,
    LeonRivalAction::MaintainCombatAltitude,
    LeonRivalAction::Advance,
    LeonRivalAction::MaintainCombatAltitude,
];

pub(super) fn actions(retail_frame: u16) -> &'static [LeonRivalAction] {
    if retail_frame > END_RETAIL_FRAME {
        return &[];
    }
    let Ok(index) = FRAMES.binary_search_by_key(&retail_frame, |frame| frame.retail_frame) else {
        return &[];
    };
    let range = FRAMES[index];
    let start = usize::from(range.start);
    &ACTIONS[start..start + usize::from(range.len)]
}
