//! Generated semantic rival dynamics for the retail Pigma duel.
//! Source addresses and opaque machine state remain in oracle tooling.

use super::{
    mission_encounter_pose, MissionEncounterPose, PigmaPlayerAltitudeTiming, PigmaRivalAction,
    PlayerTargetTiming, RivalApproachSteering,
};

pub(super) const PRESENTATION_START_RETAIL_FRAME: u16 = 36;
pub(super) const FLIGHT_START_RETAIL_FRAME: u16 = 384;
pub(super) const END_RETAIL_FRAME: u16 = 1_224;
pub(super) const DEPARTURE_RETAIL_FRAME: u16 = 1_228;
pub(super) const INITIAL_POSE: MissionEncounterPose =
    mission_encounter_pose([10_219, 0, 8_126, 21, 76, 0, 0]);

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
struct FrameActions {
    retail_frame: u16,
    start: u16,
    len: u8,
}

static FRAMES: [FrameActions; 197] = [
    FrameActions {
        retail_frame: 384,
        start: 0,
        len: 2,
    },
    FrameActions {
        retail_frame: 388,
        start: 2,
        len: 1,
    },
    FrameActions {
        retail_frame: 392,
        start: 3,
        len: 1,
    },
    FrameActions {
        retail_frame: 396,
        start: 4,
        len: 1,
    },
    FrameActions {
        retail_frame: 400,
        start: 5,
        len: 1,
    },
    FrameActions {
        retail_frame: 404,
        start: 6,
        len: 1,
    },
    FrameActions {
        retail_frame: 408,
        start: 7,
        len: 1,
    },
    FrameActions {
        retail_frame: 412,
        start: 8,
        len: 2,
    },
    FrameActions {
        retail_frame: 416,
        start: 10,
        len: 1,
    },
    FrameActions {
        retail_frame: 420,
        start: 11,
        len: 1,
    },
    FrameActions {
        retail_frame: 424,
        start: 12,
        len: 1,
    },
    FrameActions {
        retail_frame: 428,
        start: 13,
        len: 1,
    },
    FrameActions {
        retail_frame: 432,
        start: 14,
        len: 1,
    },
    FrameActions {
        retail_frame: 436,
        start: 15,
        len: 1,
    },
    FrameActions {
        retail_frame: 440,
        start: 16,
        len: 1,
    },
    FrameActions {
        retail_frame: 444,
        start: 17,
        len: 2,
    },
    FrameActions {
        retail_frame: 448,
        start: 19,
        len: 1,
    },
    FrameActions {
        retail_frame: 452,
        start: 20,
        len: 1,
    },
    FrameActions {
        retail_frame: 456,
        start: 21,
        len: 1,
    },
    FrameActions {
        retail_frame: 460,
        start: 22,
        len: 1,
    },
    FrameActions {
        retail_frame: 464,
        start: 23,
        len: 1,
    },
    FrameActions {
        retail_frame: 468,
        start: 24,
        len: 1,
    },
    FrameActions {
        retail_frame: 472,
        start: 25,
        len: 1,
    },
    FrameActions {
        retail_frame: 476,
        start: 26,
        len: 2,
    },
    FrameActions {
        retail_frame: 480,
        start: 28,
        len: 1,
    },
    FrameActions {
        retail_frame: 484,
        start: 29,
        len: 1,
    },
    FrameActions {
        retail_frame: 488,
        start: 30,
        len: 1,
    },
    FrameActions {
        retail_frame: 492,
        start: 31,
        len: 1,
    },
    FrameActions {
        retail_frame: 496,
        start: 32,
        len: 1,
    },
    FrameActions {
        retail_frame: 500,
        start: 33,
        len: 1,
    },
    FrameActions {
        retail_frame: 504,
        start: 34,
        len: 1,
    },
    FrameActions {
        retail_frame: 508,
        start: 35,
        len: 1,
    },
    FrameActions {
        retail_frame: 512,
        start: 36,
        len: 1,
    },
    FrameActions {
        retail_frame: 516,
        start: 37,
        len: 1,
    },
    FrameActions {
        retail_frame: 520,
        start: 38,
        len: 1,
    },
    FrameActions {
        retail_frame: 524,
        start: 39,
        len: 1,
    },
    FrameActions {
        retail_frame: 528,
        start: 40,
        len: 1,
    },
    FrameActions {
        retail_frame: 532,
        start: 41,
        len: 1,
    },
    FrameActions {
        retail_frame: 536,
        start: 42,
        len: 1,
    },
    FrameActions {
        retail_frame: 540,
        start: 43,
        len: 1,
    },
    FrameActions {
        retail_frame: 544,
        start: 44,
        len: 1,
    },
    FrameActions {
        retail_frame: 548,
        start: 45,
        len: 1,
    },
    FrameActions {
        retail_frame: 552,
        start: 46,
        len: 1,
    },
    FrameActions {
        retail_frame: 556,
        start: 47,
        len: 1,
    },
    FrameActions {
        retail_frame: 560,
        start: 48,
        len: 1,
    },
    FrameActions {
        retail_frame: 564,
        start: 49,
        len: 1,
    },
    FrameActions {
        retail_frame: 568,
        start: 50,
        len: 1,
    },
    FrameActions {
        retail_frame: 572,
        start: 51,
        len: 1,
    },
    FrameActions {
        retail_frame: 576,
        start: 52,
        len: 1,
    },
    FrameActions {
        retail_frame: 580,
        start: 53,
        len: 1,
    },
    FrameActions {
        retail_frame: 584,
        start: 54,
        len: 1,
    },
    FrameActions {
        retail_frame: 588,
        start: 55,
        len: 2,
    },
    FrameActions {
        retail_frame: 592,
        start: 57,
        len: 1,
    },
    FrameActions {
        retail_frame: 600,
        start: 58,
        len: 1,
    },
    FrameActions {
        retail_frame: 604,
        start: 59,
        len: 5,
    },
    FrameActions {
        retail_frame: 612,
        start: 64,
        len: 8,
    },
    FrameActions {
        retail_frame: 616,
        start: 72,
        len: 5,
    },
    FrameActions {
        retail_frame: 620,
        start: 77,
        len: 5,
    },
    FrameActions {
        retail_frame: 624,
        start: 82,
        len: 5,
    },
    FrameActions {
        retail_frame: 628,
        start: 87,
        len: 5,
    },
    FrameActions {
        retail_frame: 632,
        start: 92,
        len: 5,
    },
    FrameActions {
        retail_frame: 636,
        start: 97,
        len: 5,
    },
    FrameActions {
        retail_frame: 640,
        start: 102,
        len: 5,
    },
    FrameActions {
        retail_frame: 644,
        start: 107,
        len: 5,
    },
    FrameActions {
        retail_frame: 648,
        start: 112,
        len: 5,
    },
    FrameActions {
        retail_frame: 652,
        start: 117,
        len: 5,
    },
    FrameActions {
        retail_frame: 656,
        start: 122,
        len: 5,
    },
    FrameActions {
        retail_frame: 660,
        start: 127,
        len: 5,
    },
    FrameActions {
        retail_frame: 664,
        start: 132,
        len: 5,
    },
    FrameActions {
        retail_frame: 668,
        start: 137,
        len: 5,
    },
    FrameActions {
        retail_frame: 672,
        start: 142,
        len: 5,
    },
    FrameActions {
        retail_frame: 676,
        start: 147,
        len: 5,
    },
    FrameActions {
        retail_frame: 680,
        start: 152,
        len: 5,
    },
    FrameActions {
        retail_frame: 684,
        start: 157,
        len: 9,
    },
    FrameActions {
        retail_frame: 688,
        start: 166,
        len: 5,
    },
    FrameActions {
        retail_frame: 692,
        start: 171,
        len: 2,
    },
    FrameActions {
        retail_frame: 696,
        start: 173,
        len: 6,
    },
    FrameActions {
        retail_frame: 700,
        start: 179,
        len: 5,
    },
    FrameActions {
        retail_frame: 704,
        start: 184,
        len: 8,
    },
    FrameActions {
        retail_frame: 708,
        start: 192,
        len: 5,
    },
    FrameActions {
        retail_frame: 712,
        start: 197,
        len: 5,
    },
    FrameActions {
        retail_frame: 716,
        start: 202,
        len: 5,
    },
    FrameActions {
        retail_frame: 720,
        start: 207,
        len: 5,
    },
    FrameActions {
        retail_frame: 724,
        start: 212,
        len: 5,
    },
    FrameActions {
        retail_frame: 728,
        start: 217,
        len: 5,
    },
    FrameActions {
        retail_frame: 732,
        start: 222,
        len: 5,
    },
    FrameActions {
        retail_frame: 736,
        start: 227,
        len: 5,
    },
    FrameActions {
        retail_frame: 740,
        start: 232,
        len: 5,
    },
    FrameActions {
        retail_frame: 744,
        start: 237,
        len: 5,
    },
    FrameActions {
        retail_frame: 748,
        start: 242,
        len: 5,
    },
    FrameActions {
        retail_frame: 752,
        start: 247,
        len: 5,
    },
    FrameActions {
        retail_frame: 756,
        start: 252,
        len: 4,
    },
    FrameActions {
        retail_frame: 760,
        start: 256,
        len: 2,
    },
    FrameActions {
        retail_frame: 764,
        start: 258,
        len: 2,
    },
    FrameActions {
        retail_frame: 768,
        start: 260,
        len: 2,
    },
    FrameActions {
        retail_frame: 772,
        start: 262,
        len: 2,
    },
    FrameActions {
        retail_frame: 776,
        start: 264,
        len: 2,
    },
    FrameActions {
        retail_frame: 780,
        start: 266,
        len: 2,
    },
    FrameActions {
        retail_frame: 788,
        start: 268,
        len: 2,
    },
    FrameActions {
        retail_frame: 792,
        start: 270,
        len: 2,
    },
    FrameActions {
        retail_frame: 796,
        start: 272,
        len: 2,
    },
    FrameActions {
        retail_frame: 800,
        start: 274,
        len: 2,
    },
    FrameActions {
        retail_frame: 804,
        start: 276,
        len: 2,
    },
    FrameActions {
        retail_frame: 808,
        start: 278,
        len: 2,
    },
    FrameActions {
        retail_frame: 812,
        start: 280,
        len: 2,
    },
    FrameActions {
        retail_frame: 820,
        start: 282,
        len: 2,
    },
    FrameActions {
        retail_frame: 824,
        start: 284,
        len: 2,
    },
    FrameActions {
        retail_frame: 828,
        start: 286,
        len: 2,
    },
    FrameActions {
        retail_frame: 832,
        start: 288,
        len: 2,
    },
    FrameActions {
        retail_frame: 840,
        start: 290,
        len: 2,
    },
    FrameActions {
        retail_frame: 844,
        start: 292,
        len: 2,
    },
    FrameActions {
        retail_frame: 848,
        start: 294,
        len: 2,
    },
    FrameActions {
        retail_frame: 852,
        start: 296,
        len: 2,
    },
    FrameActions {
        retail_frame: 860,
        start: 298,
        len: 2,
    },
    FrameActions {
        retail_frame: 864,
        start: 300,
        len: 2,
    },
    FrameActions {
        retail_frame: 868,
        start: 302,
        len: 2,
    },
    FrameActions {
        retail_frame: 872,
        start: 304,
        len: 2,
    },
    FrameActions {
        retail_frame: 880,
        start: 306,
        len: 2,
    },
    FrameActions {
        retail_frame: 884,
        start: 308,
        len: 3,
    },
    FrameActions {
        retail_frame: 888,
        start: 311,
        len: 2,
    },
    FrameActions {
        retail_frame: 896,
        start: 313,
        len: 2,
    },
    FrameActions {
        retail_frame: 900,
        start: 315,
        len: 2,
    },
    FrameActions {
        retail_frame: 904,
        start: 317,
        len: 2,
    },
    FrameActions {
        retail_frame: 912,
        start: 319,
        len: 2,
    },
    FrameActions {
        retail_frame: 916,
        start: 321,
        len: 2,
    },
    FrameActions {
        retail_frame: 920,
        start: 323,
        len: 2,
    },
    FrameActions {
        retail_frame: 928,
        start: 325,
        len: 2,
    },
    FrameActions {
        retail_frame: 932,
        start: 327,
        len: 2,
    },
    FrameActions {
        retail_frame: 940,
        start: 329,
        len: 2,
    },
    FrameActions {
        retail_frame: 944,
        start: 331,
        len: 1,
    },
    FrameActions {
        retail_frame: 952,
        start: 332,
        len: 1,
    },
    FrameActions {
        retail_frame: 956,
        start: 333,
        len: 1,
    },
    FrameActions {
        retail_frame: 960,
        start: 334,
        len: 1,
    },
    FrameActions {
        retail_frame: 964,
        start: 335,
        len: 1,
    },
    FrameActions {
        retail_frame: 972,
        start: 336,
        len: 1,
    },
    FrameActions {
        retail_frame: 976,
        start: 337,
        len: 1,
    },
    FrameActions {
        retail_frame: 980,
        start: 338,
        len: 1,
    },
    FrameActions {
        retail_frame: 984,
        start: 339,
        len: 1,
    },
    FrameActions {
        retail_frame: 992,
        start: 340,
        len: 1,
    },
    FrameActions {
        retail_frame: 996,
        start: 341,
        len: 1,
    },
    FrameActions {
        retail_frame: 1_000,
        start: 342,
        len: 3,
    },
    FrameActions {
        retail_frame: 1_004,
        start: 345,
        len: 2,
    },
    FrameActions {
        retail_frame: 1_008,
        start: 347,
        len: 2,
    },
    FrameActions {
        retail_frame: 1_012,
        start: 349,
        len: 5,
    },
    FrameActions {
        retail_frame: 1_016,
        start: 354,
        len: 3,
    },
    FrameActions {
        retail_frame: 1_020,
        start: 357,
        len: 3,
    },
    FrameActions {
        retail_frame: 1_024,
        start: 360,
        len: 3,
    },
    FrameActions {
        retail_frame: 1_028,
        start: 363,
        len: 3,
    },
    FrameActions {
        retail_frame: 1_032,
        start: 366,
        len: 3,
    },
    FrameActions {
        retail_frame: 1_036,
        start: 369,
        len: 3,
    },
    FrameActions {
        retail_frame: 1_040,
        start: 372,
        len: 3,
    },
    FrameActions {
        retail_frame: 1_044,
        start: 375,
        len: 3,
    },
    FrameActions {
        retail_frame: 1_048,
        start: 378,
        len: 4,
    },
    FrameActions {
        retail_frame: 1_052,
        start: 382,
        len: 3,
    },
    FrameActions {
        retail_frame: 1_056,
        start: 385,
        len: 3,
    },
    FrameActions {
        retail_frame: 1_060,
        start: 388,
        len: 3,
    },
    FrameActions {
        retail_frame: 1_064,
        start: 391,
        len: 6,
    },
    FrameActions {
        retail_frame: 1_068,
        start: 397,
        len: 3,
    },
    FrameActions {
        retail_frame: 1_072,
        start: 400,
        len: 3,
    },
    FrameActions {
        retail_frame: 1_076,
        start: 403,
        len: 3,
    },
    FrameActions {
        retail_frame: 1_080,
        start: 406,
        len: 3,
    },
    FrameActions {
        retail_frame: 1_084,
        start: 409,
        len: 3,
    },
    FrameActions {
        retail_frame: 1_088,
        start: 412,
        len: 3,
    },
    FrameActions {
        retail_frame: 1_092,
        start: 415,
        len: 6,
    },
    FrameActions {
        retail_frame: 1_096,
        start: 421,
        len: 3,
    },
    FrameActions {
        retail_frame: 1_100,
        start: 424,
        len: 3,
    },
    FrameActions {
        retail_frame: 1_104,
        start: 427,
        len: 3,
    },
    FrameActions {
        retail_frame: 1_108,
        start: 430,
        len: 3,
    },
    FrameActions {
        retail_frame: 1_112,
        start: 433,
        len: 3,
    },
    FrameActions {
        retail_frame: 1_116,
        start: 436,
        len: 3,
    },
    FrameActions {
        retail_frame: 1_120,
        start: 439,
        len: 3,
    },
    FrameActions {
        retail_frame: 1_124,
        start: 442,
        len: 3,
    },
    FrameActions {
        retail_frame: 1_128,
        start: 445,
        len: 4,
    },
    FrameActions {
        retail_frame: 1_132,
        start: 449,
        len: 5,
    },
    FrameActions {
        retail_frame: 1_136,
        start: 454,
        len: 3,
    },
    FrameActions {
        retail_frame: 1_140,
        start: 457,
        len: 3,
    },
    FrameActions {
        retail_frame: 1_144,
        start: 460,
        len: 3,
    },
    FrameActions {
        retail_frame: 1_148,
        start: 463,
        len: 3,
    },
    FrameActions {
        retail_frame: 1_152,
        start: 466,
        len: 3,
    },
    FrameActions {
        retail_frame: 1_156,
        start: 469,
        len: 4,
    },
    FrameActions {
        retail_frame: 1_160,
        start: 473,
        len: 5,
    },
    FrameActions {
        retail_frame: 1_164,
        start: 478,
        len: 3,
    },
    FrameActions {
        retail_frame: 1_168,
        start: 481,
        len: 3,
    },
    FrameActions {
        retail_frame: 1_172,
        start: 484,
        len: 3,
    },
    FrameActions {
        retail_frame: 1_176,
        start: 487,
        len: 3,
    },
    FrameActions {
        retail_frame: 1_180,
        start: 490,
        len: 3,
    },
    FrameActions {
        retail_frame: 1_184,
        start: 493,
        len: 3,
    },
    FrameActions {
        retail_frame: 1_188,
        start: 496,
        len: 3,
    },
    FrameActions {
        retail_frame: 1_192,
        start: 499,
        len: 6,
    },
    FrameActions {
        retail_frame: 1_196,
        start: 505,
        len: 3,
    },
    FrameActions {
        retail_frame: 1_200,
        start: 508,
        len: 3,
    },
    FrameActions {
        retail_frame: 1_204,
        start: 511,
        len: 3,
    },
    FrameActions {
        retail_frame: 1_208,
        start: 514,
        len: 3,
    },
    FrameActions {
        retail_frame: 1_212,
        start: 517,
        len: 1,
    },
    FrameActions {
        retail_frame: 1_216,
        start: 518,
        len: 3,
    },
    FrameActions {
        retail_frame: 1_220,
        start: 521,
        len: 3,
    },
    FrameActions {
        retail_frame: 1_224,
        start: 524,
        len: 2,
    },
];

static ACTIONS: [PigmaRivalAction; 526] = [
    PigmaRivalAction::BeginApproach,
    PigmaRivalAction::AdvanceApproach(RivalApproachSteering::EntryClimb),
    PigmaRivalAction::AdvanceApproach(RivalApproachSteering::EntryClimb),
    PigmaRivalAction::AdvanceApproach(RivalApproachSteering::EntryClimb),
    PigmaRivalAction::AdvanceApproach(RivalApproachSteering::EntryClimb),
    PigmaRivalAction::AdvanceApproach(RivalApproachSteering::EntryClimb),
    PigmaRivalAction::AdvanceApproach(RivalApproachSteering::EntryClimb),
    PigmaRivalAction::AdvanceApproach(RivalApproachSteering::EntryClimb),
    PigmaRivalAction::AdvanceApproach(RivalApproachSteering::EntryClimb),
    PigmaRivalAction::AdvanceApproach(RivalApproachSteering::EntryClimb),
    PigmaRivalAction::AdvanceApproach(RivalApproachSteering::EntryClimb),
    PigmaRivalAction::AdvanceApproach(RivalApproachSteering::EntryClimb),
    PigmaRivalAction::AdvanceApproach(RivalApproachSteering::EntryClimb),
    PigmaRivalAction::AdvanceApproach(RivalApproachSteering::EntryClimb),
    PigmaRivalAction::AdvanceApproach(RivalApproachSteering::EntryClimb),
    PigmaRivalAction::AdvanceApproach(RivalApproachSteering::EntryClimb),
    PigmaRivalAction::AdvanceApproach(RivalApproachSteering::EntryDive),
    PigmaRivalAction::AdvanceApproach(RivalApproachSteering::EntryDive),
    PigmaRivalAction::AdvanceApproach(RivalApproachSteering::EntryDive),
    PigmaRivalAction::AdvanceApproach(RivalApproachSteering::EntryDive),
    PigmaRivalAction::AdvanceApproach(RivalApproachSteering::EntryDive),
    PigmaRivalAction::AdvanceApproach(RivalApproachSteering::EntryDive),
    PigmaRivalAction::AdvanceApproach(RivalApproachSteering::EntryDive),
    PigmaRivalAction::AdvanceApproach(RivalApproachSteering::EntryDive),
    PigmaRivalAction::AdvanceApproach(RivalApproachSteering::EntryDive),
    PigmaRivalAction::AdvanceApproach(RivalApproachSteering::EntryDive),
    PigmaRivalAction::AdvanceApproach(RivalApproachSteering::EntryDive),
    PigmaRivalAction::AdvanceApproach(RivalApproachSteering::EntryDive),
    PigmaRivalAction::AdvanceApproach(RivalApproachSteering::EntryDive),
    PigmaRivalAction::AdvanceApproach(RivalApproachSteering::EntryDive),
    PigmaRivalAction::AdvanceApproach(RivalApproachSteering::EntryDive),
    PigmaRivalAction::AdvanceApproach(RivalApproachSteering::EntryDive),
    PigmaRivalAction::AdvanceApproach(RivalApproachSteering::EntryDive),
    PigmaRivalAction::AdvanceApproach(RivalApproachSteering::EntryDive),
    PigmaRivalAction::AdvanceApproach(RivalApproachSteering::EntryDive),
    PigmaRivalAction::AdvanceApproach(RivalApproachSteering::EntryDive),
    PigmaRivalAction::AdvanceApproach(RivalApproachSteering::EntryDive),
    PigmaRivalAction::AdvanceApproach(RivalApproachSteering::EntryDive),
    PigmaRivalAction::AdvanceApproach(RivalApproachSteering::EntryDive),
    PigmaRivalAction::AdvanceApproach(RivalApproachSteering::EntryDive),
    PigmaRivalAction::AdvanceApproach(RivalApproachSteering::EntryDive),
    PigmaRivalAction::AdvanceApproach(RivalApproachSteering::EntryDive),
    PigmaRivalAction::AdvanceApproach(RivalApproachSteering::EntryDive),
    PigmaRivalAction::AdvanceApproach(RivalApproachSteering::EntryDive),
    PigmaRivalAction::AdvanceApproach(RivalApproachSteering::EntryDive),
    PigmaRivalAction::AdvanceApproach(RivalApproachSteering::EntryDive),
    PigmaRivalAction::AdvanceApproach(RivalApproachSteering::EntryDive),
    PigmaRivalAction::AdvanceApproach(RivalApproachSteering::EntryDive),
    PigmaRivalAction::AdvanceApproach(RivalApproachSteering::EntryDive),
    PigmaRivalAction::AdvanceApproach(RivalApproachSteering::EntryDive),
    PigmaRivalAction::AdvanceApproach(RivalApproachSteering::EntryDive),
    PigmaRivalAction::AdvanceApproach(RivalApproachSteering::EntryDive),
    PigmaRivalAction::AdvanceApproach(RivalApproachSteering::EntryDive),
    PigmaRivalAction::AdvanceApproach(RivalApproachSteering::EntryDive),
    PigmaRivalAction::AdvanceApproach(RivalApproachSteering::EntryDive),
    PigmaRivalAction::AdvanceApproach(RivalApproachSteering::EntryDive),
    PigmaRivalAction::AdvanceApproach(RivalApproachSteering::EntryDive),
    PigmaRivalAction::AdvanceApproach(RivalApproachSteering::EntryDive),
    PigmaRivalAction::AdvanceApproach(RivalApproachSteering::EntryDive),
    PigmaRivalAction::AdvanceApproach(RivalApproachSteering::EntryDive),
    PigmaRivalAction::BeginCombatManeuver,
    PigmaRivalAction::ChaseRollToLevel,
    PigmaRivalAction::Advance,
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::ChaseRollToLevel,
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::Advance,
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::ChaseRollToLevel,
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::Advance,
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::ChaseRollToLevel,
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::Advance,
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::ChaseRollToLevel,
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::Advance,
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::ChaseRollToLevel,
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::Advance,
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::ChaseRollToLevel,
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::Advance,
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::ChaseRollToLevel,
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::Advance,
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::ChaseRollToLevel,
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::Advance,
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::ChaseRollToLevel,
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::Advance,
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::ChaseRollToLevel,
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::Advance,
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::ChaseRollToLevel,
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::Advance,
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::ChaseRollToLevel,
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::Advance,
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::ChaseRollToLevel,
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::Advance,
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::ChaseRollToLevel,
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::Advance,
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::ChaseRollToLevel,
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::Advance,
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::ChaseRollToLevel,
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::Advance,
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::ChaseRollToLevel,
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::Advance,
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::ChaseRollToLevel,
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::Advance,
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::ChaseRollToLevel,
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::Advance,
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::ChaseRollToLevel,
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::Advance,
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::ChaseRollToLevel,
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::Advance,
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::ChaseRollToLevel,
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::Advance,
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::ChaseRollToLevel,
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::BeginAttack,
    PigmaRivalAction::FacePlayerYawAndLevelPitch(PlayerTargetTiming::Previous),
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::Advance,
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::FacePlayerYawAndLevelPitch(PlayerTargetTiming::Previous),
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::Advance,
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::FacePlayerYawAndLevelPitch(PlayerTargetTiming::Previous),
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::Advance,
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::FacePlayerYawAndLevelPitch(PlayerTargetTiming::Current),
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::Advance,
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::FacePlayerYawAndLevelPitch(PlayerTargetTiming::Current),
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::Advance,
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::FacePlayerYawAndLevelPitch(PlayerTargetTiming::Current),
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::Advance,
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::FacePlayerYawAndLevelPitch(PlayerTargetTiming::Current),
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::Advance,
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::FacePlayerYawAndLevelPitch(PlayerTargetTiming::Current),
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::Advance,
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::FacePlayerYawAndLevelPitch(PlayerTargetTiming::Current),
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::Advance,
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::FacePlayerYawAndLevelPitch(PlayerTargetTiming::Current),
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::Advance,
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::FacePlayerYawAndLevelPitch(PlayerTargetTiming::Current),
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::Advance,
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::FacePlayerYawAndLevelPitch(PlayerTargetTiming::Current),
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::Advance,
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::FacePlayerSmooth(PlayerTargetTiming::Current),
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::Advance,
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::FacePlayerSmooth(PlayerTargetTiming::Current),
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::Advance,
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::FacePlayerSmooth(PlayerTargetTiming::Current),
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::Advance,
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::FacePlayerSmooth(PlayerTargetTiming::Current),
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::Advance,
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::FacePlayerSmooth(PlayerTargetTiming::Current),
    PigmaRivalAction::MaintainCombatAltitude,
    PigmaRivalAction::Advance,
    PigmaRivalAction::FacePlayerSmooth(PlayerTargetTiming::Current),
    PigmaRivalAction::Advance,
    PigmaRivalAction::FacePlayerSmooth(PlayerTargetTiming::Current),
    PigmaRivalAction::Advance,
    PigmaRivalAction::FacePlayerSmooth(PlayerTargetTiming::Current),
    PigmaRivalAction::Advance,
    PigmaRivalAction::FacePlayerSmooth(PlayerTargetTiming::Current),
    PigmaRivalAction::Advance,
    PigmaRivalAction::FacePlayerSmooth(PlayerTargetTiming::Current),
    PigmaRivalAction::Advance,
    PigmaRivalAction::FacePlayerSmooth(PlayerTargetTiming::Current),
    PigmaRivalAction::Advance,
    PigmaRivalAction::FacePlayerSmooth(PlayerTargetTiming::Previous),
    PigmaRivalAction::Advance,
    PigmaRivalAction::FacePlayerSmooth(PlayerTargetTiming::Previous),
    PigmaRivalAction::Advance,
    PigmaRivalAction::FacePlayerSmooth(PlayerTargetTiming::Previous),
    PigmaRivalAction::Advance,
    PigmaRivalAction::FacePlayerSmooth(PlayerTargetTiming::Current),
    PigmaRivalAction::Advance,
    PigmaRivalAction::FacePlayerSmooth(PlayerTargetTiming::Current),
    PigmaRivalAction::Advance,
    PigmaRivalAction::FacePlayerSmooth(PlayerTargetTiming::Current),
    PigmaRivalAction::Advance,
    PigmaRivalAction::FacePlayerSmooth(PlayerTargetTiming::Current),
    PigmaRivalAction::Advance,
    PigmaRivalAction::FacePlayerSmooth(PlayerTargetTiming::Previous),
    PigmaRivalAction::Advance,
    PigmaRivalAction::FacePlayerSmooth(PlayerTargetTiming::Current),
    PigmaRivalAction::Advance,
    PigmaRivalAction::FacePlayerSmooth(PlayerTargetTiming::Current),
    PigmaRivalAction::Advance,
    PigmaRivalAction::FacePlayerSmooth(PlayerTargetTiming::Current),
    PigmaRivalAction::Advance,
    PigmaRivalAction::FacePlayerSmooth(PlayerTargetTiming::Previous),
    PigmaRivalAction::Advance,
    PigmaRivalAction::FacePlayerSmooth(PlayerTargetTiming::Current),
    PigmaRivalAction::Advance,
    PigmaRivalAction::FacePlayerSmooth(PlayerTargetTiming::Current),
    PigmaRivalAction::Advance,
    PigmaRivalAction::FacePlayerSmooth(PlayerTargetTiming::Current),
    PigmaRivalAction::Advance,
    PigmaRivalAction::FacePlayerSmooth(PlayerTargetTiming::Previous),
    PigmaRivalAction::Advance,
    PigmaRivalAction::FacePlayerSmooth(PlayerTargetTiming::Current),
    PigmaRivalAction::Advance,
    PigmaRivalAction::FacePlayerSmooth(PlayerTargetTiming::Current),
    PigmaRivalAction::Advance,
    PigmaRivalAction::FacePlayerSmooth(PlayerTargetTiming::Current),
    PigmaRivalAction::Advance,
    PigmaRivalAction::FacePlayerSmooth(PlayerTargetTiming::Previous),
    PigmaRivalAction::Advance,
    PigmaRivalAction::FacePlayerSmooth(PlayerTargetTiming::Current),
    PigmaRivalAction::Advance,
    PigmaRivalAction::BeginSecondApproach,
    PigmaRivalAction::LaunchSecondApproach,
    PigmaRivalAction::ApplySecondApproachWave,
    PigmaRivalAction::AdvanceApproach(RivalApproachSteering::SecondClimb),
    PigmaRivalAction::ApplySecondApproachWave,
    PigmaRivalAction::AdvanceApproach(RivalApproachSteering::SecondClimb),
    PigmaRivalAction::ApplySecondApproachWave,
    PigmaRivalAction::AdvanceApproach(RivalApproachSteering::SecondClimb),
    PigmaRivalAction::ApplySecondApproachWave,
    PigmaRivalAction::AdvanceApproach(RivalApproachSteering::SecondClimb),
    PigmaRivalAction::ApplySecondApproachWave,
    PigmaRivalAction::AdvanceApproach(RivalApproachSteering::SecondClimb),
    PigmaRivalAction::ApplySecondApproachWave,
    PigmaRivalAction::AdvanceApproach(RivalApproachSteering::SecondClimb),
    PigmaRivalAction::ApplySecondApproachWave,
    PigmaRivalAction::AdvanceApproach(RivalApproachSteering::SecondClimb),
    PigmaRivalAction::ApplySecondApproachWave,
    PigmaRivalAction::AdvanceApproach(RivalApproachSteering::SecondClimb),
    PigmaRivalAction::ApplySecondApproachWave,
    PigmaRivalAction::AdvanceApproach(RivalApproachSteering::SecondClimb),
    PigmaRivalAction::ApplySecondApproachWave,
    PigmaRivalAction::AdvanceApproach(RivalApproachSteering::SecondClimb),
    PigmaRivalAction::AdvanceApproach(RivalApproachSteering::SecondClimb),
    PigmaRivalAction::AdvanceApproach(RivalApproachSteering::SecondClimb),
    PigmaRivalAction::AdvanceApproach(RivalApproachSteering::SecondClimb),
    PigmaRivalAction::AdvanceApproach(RivalApproachSteering::SecondClimb),
    PigmaRivalAction::AdvanceApproach(RivalApproachSteering::SecondClimb),
    PigmaRivalAction::AdvanceApproach(RivalApproachSteering::SecondClimb),
    PigmaRivalAction::AdvanceApproach(RivalApproachSteering::SecondDive),
    PigmaRivalAction::AdvanceApproach(RivalApproachSteering::SecondDive),
    PigmaRivalAction::AdvanceApproach(RivalApproachSteering::SecondDive),
    PigmaRivalAction::AdvanceApproach(RivalApproachSteering::SecondDive),
    PigmaRivalAction::BeginDeceleration,
    PigmaRivalAction::ChaseRollToLevel,
    PigmaRivalAction::Advance,
    PigmaRivalAction::ChaseRollToLevel,
    PigmaRivalAction::Advance,
    PigmaRivalAction::ChaseRollToLevel,
    PigmaRivalAction::Advance,
    PigmaRivalAction::ChaseRollToLevel,
    PigmaRivalAction::BeginEscape,
    PigmaRivalAction::TurnAwayAndAdvance,
    PigmaRivalAction::ChasePlayerAltitude(PigmaPlayerAltitudeTiming::Previous),
    PigmaRivalAction::ApplyEscapeWobble,
    PigmaRivalAction::TurnAwayAndAdvance,
    PigmaRivalAction::ChasePlayerAltitude(PigmaPlayerAltitudeTiming::Previous),
    PigmaRivalAction::ApplyEscapeWobble,
    PigmaRivalAction::TurnAwayAndAdvance,
    PigmaRivalAction::ChasePlayerAltitude(PigmaPlayerAltitudeTiming::Previous),
    PigmaRivalAction::ApplyEscapeWobble,
    PigmaRivalAction::TurnAwayAndAdvance,
    PigmaRivalAction::ChasePlayerAltitude(PigmaPlayerAltitudeTiming::Previous),
    PigmaRivalAction::ApplyEscapeWobble,
    PigmaRivalAction::TurnAwayAndAdvance,
    PigmaRivalAction::ChasePlayerAltitude(PigmaPlayerAltitudeTiming::Previous),
    PigmaRivalAction::ApplyEscapeWobble,
    PigmaRivalAction::TurnAwayAndAdvance,
    PigmaRivalAction::ChasePlayerAltitude(PigmaPlayerAltitudeTiming::Previous),
    PigmaRivalAction::ApplyEscapeWobble,
    PigmaRivalAction::TurnAwayAndAdvance,
    PigmaRivalAction::ChasePlayerAltitude(PigmaPlayerAltitudeTiming::Previous),
    PigmaRivalAction::ApplyEscapeWobble,
    PigmaRivalAction::TurnAwayAndAdvance,
    PigmaRivalAction::ChasePlayerAltitude(PigmaPlayerAltitudeTiming::Previous),
    PigmaRivalAction::ApplyEscapeWobble,
    PigmaRivalAction::TurnAwayAndAdvance,
    PigmaRivalAction::ChasePlayerAltitude(PigmaPlayerAltitudeTiming::Previous),
    PigmaRivalAction::ApplyEscapeWobble,
    PigmaRivalAction::TurnAway,
    PigmaRivalAction::Advance,
    PigmaRivalAction::ChasePlayerAltitude(PigmaPlayerAltitudeTiming::Previous),
    PigmaRivalAction::ApplyEscapeWobble,
    PigmaRivalAction::Advance,
    PigmaRivalAction::ChasePlayerAltitude(PigmaPlayerAltitudeTiming::Previous),
    PigmaRivalAction::ApplyEscapeWobble,
    PigmaRivalAction::Advance,
    PigmaRivalAction::ChasePlayerAltitude(PigmaPlayerAltitudeTiming::Previous),
    PigmaRivalAction::ApplyEscapeWobble,
    PigmaRivalAction::Advance,
    PigmaRivalAction::ChasePlayerAltitude(PigmaPlayerAltitudeTiming::Previous),
    PigmaRivalAction::ApplyEscapeWobble,
    PigmaRivalAction::Advance,
    PigmaRivalAction::ChasePlayerAltitude(
        PigmaPlayerAltitudeTiming::EarlierMidpointWithEntryRounding,
    ),
    PigmaRivalAction::ApplyEscapeWobble,
    PigmaRivalAction::Advance,
    PigmaRivalAction::ChasePlayerAltitude(PigmaPlayerAltitudeTiming::Previous),
    PigmaRivalAction::ApplyEscapeWobble,
    PigmaRivalAction::Advance,
    PigmaRivalAction::ChasePlayerAltitude(PigmaPlayerAltitudeTiming::Previous),
    PigmaRivalAction::ApplyEscapeWobble,
    PigmaRivalAction::Advance,
    PigmaRivalAction::ChasePlayerAltitude(PigmaPlayerAltitudeTiming::Previous),
    PigmaRivalAction::ApplyEscapeWobble,
    PigmaRivalAction::Advance,
    PigmaRivalAction::ChasePlayerAltitude(PigmaPlayerAltitudeTiming::Previous),
    PigmaRivalAction::ApplyEscapeWobble,
    PigmaRivalAction::Advance,
    PigmaRivalAction::ChasePlayerAltitude(PigmaPlayerAltitudeTiming::Previous),
    PigmaRivalAction::ApplyEscapeWobble,
    PigmaRivalAction::Advance,
    PigmaRivalAction::ChasePlayerAltitude(PigmaPlayerAltitudeTiming::Previous),
    PigmaRivalAction::ApplyEscapeWobble,
    PigmaRivalAction::Advance,
    PigmaRivalAction::ChasePlayerAltitude(PigmaPlayerAltitudeTiming::Previous),
    PigmaRivalAction::ApplyEscapeWobble,
    PigmaRivalAction::Advance,
    PigmaRivalAction::ChasePlayerAltitude(PigmaPlayerAltitudeTiming::EarlierMidpoint),
    PigmaRivalAction::ApplyEscapeWobble,
    PigmaRivalAction::Advance,
    PigmaRivalAction::ChasePlayerAltitude(PigmaPlayerAltitudeTiming::Previous),
    PigmaRivalAction::ApplyEscapeWobble,
    PigmaRivalAction::Advance,
    PigmaRivalAction::ChasePlayerAltitude(PigmaPlayerAltitudeTiming::Previous),
    PigmaRivalAction::ApplyEscapeWobble,
    PigmaRivalAction::Advance,
    PigmaRivalAction::ChasePlayerAltitude(PigmaPlayerAltitudeTiming::Previous),
    PigmaRivalAction::ApplyEscapeWobble,
    PigmaRivalAction::Advance,
    PigmaRivalAction::ChasePlayerAltitude(PigmaPlayerAltitudeTiming::Previous),
    PigmaRivalAction::ApplyEscapeWobble,
    PigmaRivalAction::Advance,
    PigmaRivalAction::ChasePlayerAltitude(PigmaPlayerAltitudeTiming::Previous),
    PigmaRivalAction::ApplyEscapeWobble,
    PigmaRivalAction::Advance,
    PigmaRivalAction::ChasePlayerAltitude(PigmaPlayerAltitudeTiming::Previous),
    PigmaRivalAction::ApplyEscapeWobble,
    PigmaRivalAction::Advance,
    PigmaRivalAction::ChasePlayerAltitude(PigmaPlayerAltitudeTiming::Previous),
    PigmaRivalAction::ApplyEscapeWobble,
    PigmaRivalAction::Advance,
    PigmaRivalAction::ChasePlayerAltitude(PigmaPlayerAltitudeTiming::Previous),
    PigmaRivalAction::ApplyEscapeWobble,
    PigmaRivalAction::Advance,
    PigmaRivalAction::ChasePlayerAltitude(PigmaPlayerAltitudeTiming::Previous),
    PigmaRivalAction::ApplyEscapeWobble,
    PigmaRivalAction::Advance,
    PigmaRivalAction::ChasePlayerAltitude(PigmaPlayerAltitudeTiming::Previous),
    PigmaRivalAction::ApplyEscapeWobble,
    PigmaRivalAction::Advance,
    PigmaRivalAction::ChasePlayerAltitude(PigmaPlayerAltitudeTiming::Previous),
    PigmaRivalAction::ApplyEscapeWobble,
    PigmaRivalAction::Advance,
    PigmaRivalAction::ChasePlayerAltitude(PigmaPlayerAltitudeTiming::Previous),
    PigmaRivalAction::ApplyEscapeWobble,
    PigmaRivalAction::Advance,
    PigmaRivalAction::ChasePlayerAltitude(PigmaPlayerAltitudeTiming::Previous),
    PigmaRivalAction::ApplyEscapeWobble,
    PigmaRivalAction::Advance,
    PigmaRivalAction::ChasePlayerAltitude(PigmaPlayerAltitudeTiming::Previous),
    PigmaRivalAction::ApplyEscapeWobble,
    PigmaRivalAction::Advance,
    PigmaRivalAction::ChasePlayerAltitude(PigmaPlayerAltitudeTiming::Previous),
    PigmaRivalAction::ApplyEscapeWobble,
    PigmaRivalAction::Advance,
    PigmaRivalAction::ChasePlayerAltitude(PigmaPlayerAltitudeTiming::Previous),
    PigmaRivalAction::ApplyEscapeWobble,
    PigmaRivalAction::Advance,
    PigmaRivalAction::ChasePlayerAltitude(PigmaPlayerAltitudeTiming::Previous),
    PigmaRivalAction::ApplyEscapeWobble,
    PigmaRivalAction::Advance,
    PigmaRivalAction::ChasePlayerAltitude(PigmaPlayerAltitudeTiming::Previous),
    PigmaRivalAction::ApplyEscapeWobble,
    PigmaRivalAction::Advance,
    PigmaRivalAction::ChasePlayerAltitude(PigmaPlayerAltitudeTiming::Previous),
    PigmaRivalAction::ApplyEscapeWobble,
    PigmaRivalAction::Advance,
    PigmaRivalAction::ChasePlayerAltitude(PigmaPlayerAltitudeTiming::Previous),
    PigmaRivalAction::ApplyEscapeWobble,
    PigmaRivalAction::Advance,
    PigmaRivalAction::ChasePlayerAltitude(PigmaPlayerAltitudeTiming::Previous),
    PigmaRivalAction::ApplyEscapeWobble,
    PigmaRivalAction::Advance,
    PigmaRivalAction::ChasePlayerAltitude(PigmaPlayerAltitudeTiming::Previous),
    PigmaRivalAction::ApplyEscapeWobble,
    PigmaRivalAction::Advance,
    PigmaRivalAction::ChasePlayerAltitude(PigmaPlayerAltitudeTiming::Previous),
    PigmaRivalAction::ApplyEscapeWobble,
    PigmaRivalAction::Advance,
    PigmaRivalAction::ChasePlayerAltitude(PigmaPlayerAltitudeTiming::Previous),
    PigmaRivalAction::ApplyEscapeWobble,
    PigmaRivalAction::Advance,
    PigmaRivalAction::ChasePlayerAltitude(PigmaPlayerAltitudeTiming::Previous),
    PigmaRivalAction::ApplyEscapeWobble,
    PigmaRivalAction::Advance,
    PigmaRivalAction::ChasePlayerAltitude(PigmaPlayerAltitudeTiming::Previous),
    PigmaRivalAction::ApplyEscapeWobble,
    PigmaRivalAction::Advance,
    PigmaRivalAction::ChasePlayerAltitude(PigmaPlayerAltitudeTiming::Previous),
    PigmaRivalAction::ApplyEscapeWobble,
    PigmaRivalAction::Advance,
    PigmaRivalAction::ChasePlayerAltitude(PigmaPlayerAltitudeTiming::Previous),
    PigmaRivalAction::ApplyEscapeWobble,
    PigmaRivalAction::Advance,
    PigmaRivalAction::ChasePlayerAltitude(PigmaPlayerAltitudeTiming::Previous),
    PigmaRivalAction::ApplyEscapeWobble,
    PigmaRivalAction::Advance,
    PigmaRivalAction::ChasePlayerAltitude(PigmaPlayerAltitudeTiming::Previous),
    PigmaRivalAction::ApplyEscapeWobble,
    PigmaRivalAction::Advance,
    PigmaRivalAction::ChasePlayerAltitude(PigmaPlayerAltitudeTiming::Previous),
    PigmaRivalAction::ApplyEscapeWobble,
    PigmaRivalAction::Advance,
    PigmaRivalAction::ChasePlayerAltitude(PigmaPlayerAltitudeTiming::Previous),
    PigmaRivalAction::ApplyEscapeWobble,
    PigmaRivalAction::Advance,
    PigmaRivalAction::ChasePlayerAltitude(PigmaPlayerAltitudeTiming::Previous),
    PigmaRivalAction::ApplyEscapeWobble,
    PigmaRivalAction::Advance,
    PigmaRivalAction::Advance,
    PigmaRivalAction::ChasePlayerAltitude(PigmaPlayerAltitudeTiming::Previous),
    PigmaRivalAction::ApplyEscapeWobble,
    PigmaRivalAction::Advance,
    PigmaRivalAction::ChasePlayerAltitude(PigmaPlayerAltitudeTiming::Previous),
    PigmaRivalAction::ApplyEscapeWobble,
    PigmaRivalAction::ChasePlayerAltitude(PigmaPlayerAltitudeTiming::Previous),
    PigmaRivalAction::ApplyEscapeWobble,
];

pub(super) fn actions(retail_frame: u16) -> &'static [PigmaRivalAction] {
    if retail_frame > END_RETAIL_FRAME {
        return &[];
    }
    let Ok(index) = FRAMES.binary_search_by_key(&retail_frame, |frame| frame.retail_frame) else {
        return &[];
    };
    let range = FRAMES[index];
    let start = usize::from(range.start);
    &ACTIONS[start..start + usize::from(range.len)]
}
