//! Generated semantic projectile dynamics for the retail Pigma duel.
//! Source addresses and opaque machine state remain in oracle tooling.

use super::{
    mission_encounter_pose, HostileProjectileAction, HostileProjectileTarget, MissionEncounterPose,
};

pub(super) const PROJECTILE_COUNT: usize = 3;
const RETAIL_FRAME_STEP: u16 = 4;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(super) struct HostileProjectileDescriptor {
    pub start_retail_frame: u16,
    pub end_retail_frame: u16,
    pub initial_pose: MissionEncounterPose,
    tick_offset: u16,
    tick_count: u8,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
struct ActionRange {
    start: u16,
    len: u8,
}

static DESCRIPTORS: [HostileProjectileDescriptor; 3] = [
    HostileProjectileDescriptor {
        start_retail_frame: 772,
        end_retail_frame: 936,
        initial_pose: mission_encounter_pose([607, -3_868, 9_186, 7, 87, 0, 63]),
        tick_offset: 0,
        tick_count: 41,
    },
    HostileProjectileDescriptor {
        start_retail_frame: 808,
        end_retail_frame: 972,
        initial_pose: mission_encounter_pose([-1_494, -3_553, 8_116, 6, 82, 0, 63]),
        tick_offset: 41,
        tick_count: 41,
    },
    HostileProjectileDescriptor {
        start_retail_frame: 848,
        end_retail_frame: 988,
        initial_pose: mission_encounter_pose([-3_504, -3_265, 7_441, 6, 77, 0, 63]),
        tick_offset: 82,
        tick_count: 35,
    },
];

static TICKS: [ActionRange; 117] = [
    ActionRange { start: 0, len: 5 },
    ActionRange { start: 5, len: 5 },
    ActionRange { start: 10, len: 7 },
    ActionRange { start: 17, len: 8 },
    ActionRange { start: 25, len: 8 },
    ActionRange { start: 33, len: 8 },
    ActionRange { start: 41, len: 8 },
    ActionRange { start: 49, len: 8 },
    ActionRange { start: 57, len: 8 },
    ActionRange { start: 65, len: 0 },
    ActionRange { start: 65, len: 8 },
    ActionRange { start: 73, len: 8 },
    ActionRange { start: 81, len: 8 },
    ActionRange { start: 89, len: 7 },
    ActionRange { start: 96, len: 1 },
    ActionRange { start: 97, len: 3 },
    ActionRange { start: 100, len: 2 },
    ActionRange { start: 102, len: 1 },
    ActionRange { start: 103, len: 1 },
    ActionRange { start: 104, len: 0 },
    ActionRange { start: 104, len: 1 },
    ActionRange { start: 105, len: 1 },
    ActionRange { start: 106, len: 1 },
    ActionRange { start: 107, len: 1 },
    ActionRange { start: 108, len: 0 },
    ActionRange { start: 108, len: 1 },
    ActionRange { start: 109, len: 1 },
    ActionRange { start: 110, len: 1 },
    ActionRange { start: 111, len: 0 },
    ActionRange { start: 111, len: 1 },
    ActionRange { start: 112, len: 1 },
    ActionRange { start: 113, len: 1 },
    ActionRange { start: 114, len: 1 },
    ActionRange { start: 115, len: 0 },
    ActionRange { start: 115, len: 1 },
    ActionRange { start: 116, len: 1 },
    ActionRange { start: 117, len: 1 },
    ActionRange { start: 118, len: 0 },
    ActionRange { start: 118, len: 1 },
    ActionRange { start: 119, len: 1 },
    ActionRange { start: 120, len: 0 },
    ActionRange { start: 120, len: 0 },
    ActionRange { start: 120, len: 8 },
    ActionRange { start: 128, len: 8 },
    ActionRange { start: 136, len: 8 },
    ActionRange { start: 144, len: 8 },
    ActionRange { start: 152, len: 0 },
    ActionRange { start: 152, len: 8 },
    ActionRange { start: 160, len: 8 },
    ActionRange { start: 168, len: 8 },
    ActionRange { start: 176, len: 8 },
    ActionRange { start: 184, len: 6 },
    ActionRange { start: 190, len: 2 },
    ActionRange { start: 192, len: 4 },
    ActionRange { start: 196, len: 1 },
    ActionRange { start: 197, len: 2 },
    ActionRange { start: 199, len: 1 },
    ActionRange { start: 200, len: 0 },
    ActionRange { start: 200, len: 2 },
    ActionRange { start: 202, len: 1 },
    ActionRange { start: 203, len: 0 },
    ActionRange { start: 203, len: 1 },
    ActionRange { start: 204, len: 1 },
    ActionRange { start: 205, len: 1 },
    ActionRange { start: 206, len: 1 },
    ActionRange { start: 207, len: 0 },
    ActionRange { start: 207, len: 1 },
    ActionRange { start: 208, len: 1 },
    ActionRange { start: 209, len: 1 },
    ActionRange { start: 210, len: 0 },
    ActionRange { start: 210, len: 1 },
    ActionRange { start: 211, len: 1 },
    ActionRange { start: 212, len: 0 },
    ActionRange { start: 212, len: 1 },
    ActionRange { start: 213, len: 1 },
    ActionRange { start: 214, len: 0 },
    ActionRange { start: 214, len: 1 },
    ActionRange { start: 215, len: 1 },
    ActionRange { start: 216, len: 1 },
    ActionRange { start: 217, len: 0 },
    ActionRange { start: 217, len: 1 },
    ActionRange { start: 218, len: 1 },
    ActionRange { start: 219, len: 8 },
    ActionRange { start: 227, len: 0 },
    ActionRange { start: 227, len: 8 },
    ActionRange { start: 235, len: 8 },
    ActionRange { start: 243, len: 8 },
    ActionRange { start: 251, len: 8 },
    ActionRange { start: 259, len: 0 },
    ActionRange { start: 259, len: 8 },
    ActionRange { start: 267, len: 8 },
    ActionRange { start: 275, len: 0 },
    ActionRange { start: 275, len: 4 },
    ActionRange { start: 279, len: 1 },
    ActionRange { start: 280, len: 1 },
    ActionRange { start: 281, len: 1 },
    ActionRange { start: 282, len: 0 },
    ActionRange { start: 282, len: 1 },
    ActionRange { start: 283, len: 1 },
    ActionRange { start: 284, len: 1 },
    ActionRange { start: 285, len: 0 },
    ActionRange { start: 285, len: 1 },
    ActionRange { start: 286, len: 1 },
    ActionRange { start: 287, len: 0 },
    ActionRange { start: 287, len: 1 },
    ActionRange { start: 288, len: 1 },
    ActionRange { start: 289, len: 0 },
    ActionRange { start: 289, len: 1 },
    ActionRange { start: 290, len: 1 },
    ActionRange { start: 291, len: 1 },
    ActionRange { start: 292, len: 0 },
    ActionRange { start: 292, len: 1 },
    ActionRange { start: 293, len: 1 },
    ActionRange { start: 294, len: 1 },
    ActionRange { start: 295, len: 1 },
    ActionRange { start: 296, len: 1 },
    ActionRange { start: 297, len: 0 },
];

static ACTIONS: [HostileProjectileAction; 297] = [
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Previous),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Previous),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Previous),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Previous),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Previous),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Previous),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Previous),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Previous),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Previous),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Previous),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Previous),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Previous),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Previous),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Previous),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Previous),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Previous),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Previous),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Previous),
    HostileProjectileAction::SetCruiseSpeed,
    HostileProjectileAction::AdvanceAimCorrection,
    HostileProjectileAction::AdvanceAimCorrection,
    HostileProjectileAction::FaceTargetSmooth(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceAimCorrection,
    HostileProjectileAction::AdvanceAimCorrection,
    HostileProjectileAction::AdvanceAimCorrection,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Previous),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Previous),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Previous),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Previous),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Previous),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Previous),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Previous),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Previous),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Previous),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::SetCruiseSpeed,
    HostileProjectileAction::AdvanceAimCorrection,
    HostileProjectileAction::FaceTargetSmooth(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceAimCorrection,
    HostileProjectileAction::AdvanceAimCorrection,
    HostileProjectileAction::FaceTargetSmooth(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceAimCorrection,
    HostileProjectileAction::AdvanceAimCorrection,
    HostileProjectileAction::FaceTargetSmooth(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceAimCorrection,
    HostileProjectileAction::AdvanceAimCorrection,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::BeginTargetContraction(HostileProjectileTarget::Current),
    HostileProjectileAction::FinishTargetContraction,
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::SetCruiseSpeed,
    HostileProjectileAction::AdvanceAimCorrection,
    HostileProjectileAction::FaceTargetSmooth(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceAimCorrection,
    HostileProjectileAction::AdvanceAimCorrection,
    HostileProjectileAction::AdvanceAimCorrection,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
];

pub(super) fn descriptor(track_index: usize) -> Option<&'static HostileProjectileDescriptor> {
    DESCRIPTORS.get(track_index)
}

pub(super) fn actions(track_index: usize, retail_frame: u16) -> &'static [HostileProjectileAction] {
    let Some(descriptor) = descriptor(track_index) else {
        return &[];
    };
    let Some(offset) = retail_frame.checked_sub(descriptor.start_retail_frame + RETAIL_FRAME_STEP)
    else {
        return &[];
    };
    if offset % RETAIL_FRAME_STEP != 0 {
        return &[];
    }
    let tick = offset / RETAIL_FRAME_STEP;
    if tick >= u16::from(descriptor.tick_count) {
        return &[];
    }
    let range = TICKS[usize::from(descriptor.tick_offset + tick)];
    let start = usize::from(range.start);
    &ACTIONS[start..start + usize::from(range.len)]
}
