// @generated by tools/sf2/generate_pressure_fighter_live_projectiles.py
// Runtime tests consume only typed gameplay evidence, not source-machine state.

pub const FIRE_ATTEMPT_COUNT: usize = 48;
pub const ALLOCATED_PROJECTILE_COUNT: usize = 36;
pub const NATURAL_EXPIRY_COUNT: usize = 25;
pub const EARLY_TERMINATION_COUNT: usize = 11;
pub const REUSABLE_ALLOCATION_COUNT: usize = 4;
pub const MAXIMUM_CONCURRENT_PROJECTILES: usize = 3;
pub const MOVEMENT_INTERVAL_SUM: usize = 3234;
pub const MOVEMENT_INTERVAL_COUNT: usize = 966;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct OracleFireAttempt {
    pub distance: u16,
    pub launched: bool,
    pub start_delay: Option<u8>,
}

pub const FIRE_ATTEMPTS: [OracleFireAttempt; 48] = [
    OracleFireAttempt {
        distance: 10_649,
        launched: true,
        start_delay: Some(1),
    },
    OracleFireAttempt {
        distance: 8_619,
        launched: true,
        start_delay: Some(1),
    },
    OracleFireAttempt {
        distance: 6_529,
        launched: true,
        start_delay: Some(1),
    },
    OracleFireAttempt {
        distance: 17_388,
        launched: false,
        start_delay: None,
    },
    OracleFireAttempt {
        distance: 14_201,
        launched: false,
        start_delay: None,
    },
    OracleFireAttempt {
        distance: 12_241,
        launched: false,
        start_delay: None,
    },
    OracleFireAttempt {
        distance: 10_682,
        launched: true,
        start_delay: Some(0),
    },
    OracleFireAttempt {
        distance: 7_401,
        launched: true,
        start_delay: Some(1),
    },
    OracleFireAttempt {
        distance: 11_867,
        launched: true,
        start_delay: Some(1),
    },
    OracleFireAttempt {
        distance: 8_958,
        launched: true,
        start_delay: Some(1),
    },
    OracleFireAttempt {
        distance: 6_612,
        launched: true,
        start_delay: Some(0),
    },
    OracleFireAttempt {
        distance: 16_896,
        launched: false,
        start_delay: None,
    },
    OracleFireAttempt {
        distance: 13_888,
        launched: false,
        start_delay: None,
    },
    OracleFireAttempt {
        distance: 11_696,
        launched: true,
        start_delay: Some(1),
    },
    OracleFireAttempt {
        distance: 8_184,
        launched: true,
        start_delay: Some(1),
    },
    OracleFireAttempt {
        distance: 14_347,
        launched: false,
        start_delay: None,
    },
    OracleFireAttempt {
        distance: 11_972,
        launched: true,
        start_delay: Some(1),
    },
    OracleFireAttempt {
        distance: 7_940,
        launched: true,
        start_delay: Some(1),
    },
    OracleFireAttempt {
        distance: 12_402,
        launched: false,
        start_delay: None,
    },
    OracleFireAttempt {
        distance: 10_003,
        launched: true,
        start_delay: Some(1),
    },
    OracleFireAttempt {
        distance: 7_721,
        launched: true,
        start_delay: Some(1),
    },
    OracleFireAttempt {
        distance: 5_971,
        launched: true,
        start_delay: Some(0),
    },
    OracleFireAttempt {
        distance: 5_648,
        launched: true,
        start_delay: Some(1),
    },
    OracleFireAttempt {
        distance: 7_804,
        launched: true,
        start_delay: Some(1),
    },
    OracleFireAttempt {
        distance: 10_793,
        launched: true,
        start_delay: Some(1),
    },
    OracleFireAttempt {
        distance: 6_938,
        launched: true,
        start_delay: Some(0),
    },
    OracleFireAttempt {
        distance: 5_312,
        launched: true,
        start_delay: Some(1),
    },
    OracleFireAttempt {
        distance: 11_079,
        launched: true,
        start_delay: Some(1),
    },
    OracleFireAttempt {
        distance: 9_910,
        launched: true,
        start_delay: Some(1),
    },
    OracleFireAttempt {
        distance: 8_902,
        launched: true,
        start_delay: Some(1),
    },
    OracleFireAttempt {
        distance: 6_223,
        launched: true,
        start_delay: Some(1),
    },
    OracleFireAttempt {
        distance: 9_563,
        launched: true,
        start_delay: Some(1),
    },
    OracleFireAttempt {
        distance: 4_741,
        launched: true,
        start_delay: Some(1),
    },
    OracleFireAttempt {
        distance: 14_001,
        launched: false,
        start_delay: None,
    },
    OracleFireAttempt {
        distance: 10_055,
        launched: true,
        start_delay: Some(1),
    },
    OracleFireAttempt {
        distance: 6_225,
        launched: true,
        start_delay: Some(1),
    },
    OracleFireAttempt {
        distance: 8_474,
        launched: true,
        start_delay: Some(1),
    },
    OracleFireAttempt {
        distance: 10_604,
        launched: true,
        start_delay: Some(1),
    },
    OracleFireAttempt {
        distance: 8_196,
        launched: true,
        start_delay: Some(1),
    },
    OracleFireAttempt {
        distance: 13_038,
        launched: false,
        start_delay: None,
    },
    OracleFireAttempt {
        distance: 10_182,
        launched: true,
        start_delay: Some(1),
    },
    OracleFireAttempt {
        distance: 7_160,
        launched: true,
        start_delay: Some(1),
    },
    OracleFireAttempt {
        distance: 16_156,
        launched: false,
        start_delay: None,
    },
    OracleFireAttempt {
        distance: 12_810,
        launched: false,
        start_delay: None,
    },
    OracleFireAttempt {
        distance: 8_268,
        launched: true,
        start_delay: Some(1),
    },
    OracleFireAttempt {
        distance: 7_226,
        launched: true,
        start_delay: Some(1),
    },
    OracleFireAttempt {
        distance: 5_689,
        launched: true,
        start_delay: Some(1),
    },
    OracleFireAttempt {
        distance: 13_564,
        launched: false,
        start_delay: None,
    },
];

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct OracleProjectileLifetime {
    pub homing_steps: u8,
    pub aim_steps: u8,
    pub cruise_steps: u8,
    pub natural_expiry: bool,
}

pub const PROJECTILE_LIFETIMES: [OracleProjectileLifetime; 36] = [
    OracleProjectileLifetime {
        homing_steps: 16,
        aim_steps: 4,
        cruise_steps: 15,
        natural_expiry: true,
    },
    OracleProjectileLifetime {
        homing_steps: 15,
        aim_steps: 3,
        cruise_steps: 1,
        natural_expiry: false,
    },
    OracleProjectileLifetime {
        homing_steps: 12,
        aim_steps: 5,
        cruise_steps: 15,
        natural_expiry: true,
    },
    OracleProjectileLifetime {
        homing_steps: 18,
        aim_steps: 3,
        cruise_steps: 15,
        natural_expiry: true,
    },
    OracleProjectileLifetime {
        homing_steps: 11,
        aim_steps: 3,
        cruise_steps: 15,
        natural_expiry: true,
    },
    OracleProjectileLifetime {
        homing_steps: 18,
        aim_steps: 4,
        cruise_steps: 1,
        natural_expiry: false,
    },
    OracleProjectileLifetime {
        homing_steps: 13,
        aim_steps: 5,
        cruise_steps: 15,
        natural_expiry: true,
    },
    OracleProjectileLifetime {
        homing_steps: 13,
        aim_steps: 3,
        cruise_steps: 15,
        natural_expiry: true,
    },
    OracleProjectileLifetime {
        homing_steps: 19,
        aim_steps: 3,
        cruise_steps: 15,
        natural_expiry: true,
    },
    OracleProjectileLifetime {
        homing_steps: 14,
        aim_steps: 3,
        cruise_steps: 15,
        natural_expiry: true,
    },
    OracleProjectileLifetime {
        homing_steps: 21,
        aim_steps: 3,
        cruise_steps: 15,
        natural_expiry: true,
    },
    OracleProjectileLifetime {
        homing_steps: 11,
        aim_steps: 4,
        cruise_steps: 15,
        natural_expiry: true,
    },
    OracleProjectileLifetime {
        homing_steps: 15,
        aim_steps: 2,
        cruise_steps: 1,
        natural_expiry: false,
    },
    OracleProjectileLifetime {
        homing_steps: 12,
        aim_steps: 3,
        cruise_steps: 15,
        natural_expiry: true,
    },
    OracleProjectileLifetime {
        homing_steps: 9,
        aim_steps: 3,
        cruise_steps: 15,
        natural_expiry: true,
    },
    OracleProjectileLifetime {
        homing_steps: 8,
        aim_steps: 3,
        cruise_steps: 1,
        natural_expiry: false,
    },
    OracleProjectileLifetime {
        homing_steps: 12,
        aim_steps: 3,
        cruise_steps: 1,
        natural_expiry: false,
    },
    OracleProjectileLifetime {
        homing_steps: 17,
        aim_steps: 3,
        cruise_steps: 15,
        natural_expiry: true,
    },
    OracleProjectileLifetime {
        homing_steps: 11,
        aim_steps: 5,
        cruise_steps: 15,
        natural_expiry: true,
    },
    OracleProjectileLifetime {
        homing_steps: 12,
        aim_steps: 4,
        cruise_steps: 15,
        natural_expiry: true,
    },
    OracleProjectileLifetime {
        homing_steps: 17,
        aim_steps: 4,
        cruise_steps: 1,
        natural_expiry: false,
    },
    OracleProjectileLifetime {
        homing_steps: 15,
        aim_steps: 4,
        cruise_steps: 15,
        natural_expiry: true,
    },
    OracleProjectileLifetime {
        homing_steps: 14,
        aim_steps: 2,
        cruise_steps: 1,
        natural_expiry: false,
    },
    OracleProjectileLifetime {
        homing_steps: 9,
        aim_steps: 4,
        cruise_steps: 15,
        natural_expiry: true,
    },
    OracleProjectileLifetime {
        homing_steps: 15,
        aim_steps: 3,
        cruise_steps: 15,
        natural_expiry: true,
    },
    OracleProjectileLifetime {
        homing_steps: 7,
        aim_steps: 4,
        cruise_steps: 15,
        natural_expiry: true,
    },
    OracleProjectileLifetime {
        homing_steps: 15,
        aim_steps: 2,
        cruise_steps: 1,
        natural_expiry: false,
    },
    OracleProjectileLifetime {
        homing_steps: 9,
        aim_steps: 5,
        cruise_steps: 15,
        natural_expiry: true,
    },
    OracleProjectileLifetime {
        homing_steps: 13,
        aim_steps: 2,
        cruise_steps: 15,
        natural_expiry: true,
    },
    OracleProjectileLifetime {
        homing_steps: 17,
        aim_steps: 4,
        cruise_steps: 1,
        natural_expiry: false,
    },
    OracleProjectileLifetime {
        homing_steps: 14,
        aim_steps: 4,
        cruise_steps: 15,
        natural_expiry: true,
    },
    OracleProjectileLifetime {
        homing_steps: 18,
        aim_steps: 4,
        cruise_steps: 15,
        natural_expiry: true,
    },
    OracleProjectileLifetime {
        homing_steps: 12,
        aim_steps: 2,
        cruise_steps: 1,
        natural_expiry: false,
    },
    OracleProjectileLifetime {
        homing_steps: 14,
        aim_steps: 4,
        cruise_steps: 15,
        natural_expiry: true,
    },
    OracleProjectileLifetime {
        homing_steps: 14,
        aim_steps: 5,
        cruise_steps: 15,
        natural_expiry: true,
    },
    OracleProjectileLifetime {
        homing_steps: 11,
        aim_steps: 3,
        cruise_steps: 1,
        natural_expiry: false,
    },
];
