//! Generated semantic projectile dynamics for the Wolf blockade sortie.
//! Source addresses and opaque machine state remain in oracle tooling.

use super::{
    mission_encounter_pose, HostileProjectileAction, HostileProjectileTarget, MissionEncounterPose,
};

pub(super) const PROJECTILE_COUNT: usize = 3;
const RETAIL_FRAME_STEP: u16 = 4;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(super) struct HostileProjectileDescriptor {
    pub start_retail_frame: u16,
    pub end_retail_frame: u16,
    pub initial_pose: MissionEncounterPose,
    tick_offset: u16,
    tick_count: u8,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
struct ActionRange {
    start: u16,
    len: u8,
}

static DESCRIPTORS: [HostileProjectileDescriptor; 3] = [
    HostileProjectileDescriptor {
        start_retail_frame: 788,
        end_retail_frame: 920,
        initial_pose: mission_encounter_pose([1_519, -3_041, 5_470, 22, 112, 0, 63]),
        tick_offset: 0,
        tick_count: 33,
    },
    HostileProjectileDescriptor {
        start_retail_frame: 820,
        end_retail_frame: 932,
        initial_pose: mission_encounter_pose([810, -2_007, 3_731, 20, 112, 0, 63]),
        tick_offset: 33,
        tick_count: 28,
    },
    HostileProjectileDescriptor {
        start_retail_frame: 852,
        end_retail_frame: 952,
        initial_pose: mission_encounter_pose([49, -1_096, 1_936, 17, 111, 0, 63]),
        tick_offset: 61,
        tick_count: 25,
    },
];

static TICKS: [ActionRange; 86] = [
    ActionRange { start: 0, len: 5 },
    ActionRange { start: 5, len: 5 },
    ActionRange { start: 10, len: 5 },
    ActionRange { start: 15, len: 5 },
    ActionRange { start: 20, len: 5 },
    ActionRange { start: 25, len: 5 },
    ActionRange { start: 30, len: 5 },
    ActionRange { start: 35, len: 5 },
    ActionRange { start: 40, len: 5 },
    ActionRange { start: 45, len: 5 },
    ActionRange { start: 50, len: 5 },
    ActionRange { start: 55, len: 5 },
    ActionRange { start: 60, len: 3 },
    ActionRange { start: 63, len: 2 },
    ActionRange { start: 65, len: 1 },
    ActionRange { start: 66, len: 0 },
    ActionRange { start: 66, len: 1 },
    ActionRange { start: 67, len: 1 },
    ActionRange { start: 68, len: 1 },
    ActionRange { start: 69, len: 1 },
    ActionRange { start: 70, len: 1 },
    ActionRange { start: 71, len: 1 },
    ActionRange { start: 72, len: 1 },
    ActionRange { start: 73, len: 1 },
    ActionRange { start: 74, len: 1 },
    ActionRange { start: 75, len: 1 },
    ActionRange { start: 76, len: 1 },
    ActionRange { start: 77, len: 1 },
    ActionRange { start: 78, len: 1 },
    ActionRange { start: 79, len: 1 },
    ActionRange { start: 80, len: 1 },
    ActionRange { start: 81, len: 1 },
    ActionRange { start: 82, len: 0 },
    ActionRange { start: 82, len: 5 },
    ActionRange { start: 87, len: 5 },
    ActionRange { start: 92, len: 5 },
    ActionRange { start: 97, len: 5 },
    ActionRange { start: 102, len: 5 },
    ActionRange { start: 107, len: 5 },
    ActionRange { start: 112, len: 5 },
    ActionRange { start: 117, len: 2 },
    ActionRange { start: 119, len: 3 },
    ActionRange { start: 122, len: 5 },
    ActionRange { start: 127, len: 4 },
    ActionRange { start: 131, len: 1 },
    ActionRange { start: 132, len: 1 },
    ActionRange { start: 133, len: 1 },
    ActionRange { start: 134, len: 1 },
    ActionRange { start: 135, len: 1 },
    ActionRange { start: 136, len: 1 },
    ActionRange { start: 137, len: 1 },
    ActionRange { start: 138, len: 1 },
    ActionRange { start: 139, len: 1 },
    ActionRange { start: 140, len: 1 },
    ActionRange { start: 141, len: 1 },
    ActionRange { start: 142, len: 1 },
    ActionRange { start: 143, len: 1 },
    ActionRange { start: 144, len: 1 },
    ActionRange { start: 145, len: 1 },
    ActionRange { start: 146, len: 1 },
    ActionRange { start: 147, len: 1 },
    ActionRange { start: 148, len: 0 },
    ActionRange { start: 148, len: 5 },
    ActionRange { start: 153, len: 5 },
    ActionRange { start: 158, len: 5 },
    ActionRange { start: 163, len: 5 },
    ActionRange { start: 168, len: 5 },
    ActionRange { start: 173, len: 4 },
    ActionRange { start: 177, len: 1 },
    ActionRange { start: 178, len: 2 },
    ActionRange { start: 180, len: 1 },
    ActionRange { start: 181, len: 1 },
    ActionRange { start: 182, len: 1 },
    ActionRange { start: 183, len: 1 },
    ActionRange { start: 184, len: 1 },
    ActionRange { start: 185, len: 1 },
    ActionRange { start: 186, len: 1 },
    ActionRange { start: 187, len: 1 },
    ActionRange { start: 188, len: 1 },
    ActionRange { start: 189, len: 1 },
    ActionRange { start: 190, len: 1 },
    ActionRange { start: 191, len: 1 },
    ActionRange { start: 192, len: 1 },
    ActionRange { start: 193, len: 1 },
    ActionRange { start: 194, len: 2 },
    ActionRange { start: 196, len: 1 },
];

static ACTIONS: [HostileProjectileAction; 197] = [
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Previous),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Previous),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Previous),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Previous),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Previous),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Previous),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Previous),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Previous),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Previous),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::SetCruiseSpeed,
    HostileProjectileAction::AdvanceAimCorrection,
    HostileProjectileAction::AdvanceAimCorrection,
    HostileProjectileAction::FaceTargetSmooth(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceAimCorrection,
    HostileProjectileAction::AdvanceAimCorrection,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Previous),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Previous),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Previous),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Previous),
    HostileProjectileAction::SetCruiseSpeed,
    HostileProjectileAction::AdvanceAimCorrection,
    HostileProjectileAction::FaceTargetSmooth(HostileProjectileTarget::Previous),
    HostileProjectileAction::AdvanceAimCorrection,
    HostileProjectileAction::AdvanceAimCorrection,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Previous),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Previous),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Previous),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Previous),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::ContractTowardTarget(HostileProjectileTarget::Current),
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceHoming,
    HostileProjectileAction::FaceTargetImmediate(HostileProjectileTarget::Current),
    HostileProjectileAction::SetCruiseSpeed,
    HostileProjectileAction::AdvanceAimCorrection,
    HostileProjectileAction::FaceTargetSmooth(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceAimCorrection,
    HostileProjectileAction::AdvanceAimCorrection,
    HostileProjectileAction::FaceTargetSmooth(HostileProjectileTarget::Current),
    HostileProjectileAction::AdvanceAimCorrection,
    HostileProjectileAction::AdvanceAimCorrection,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
    HostileProjectileAction::AdvanceCruise,
];

pub(super) fn descriptor(track_index: usize) -> Option<&'static HostileProjectileDescriptor> {
    DESCRIPTORS.get(track_index)
}

pub(super) fn actions(track_index: usize, retail_frame: u16) -> &'static [HostileProjectileAction] {
    let Some(descriptor) = descriptor(track_index) else {
        return &[];
    };
    let Some(offset) = retail_frame.checked_sub(descriptor.start_retail_frame + RETAIL_FRAME_STEP)
    else {
        return &[];
    };
    if offset % RETAIL_FRAME_STEP != 0 {
        return &[];
    }
    let tick = offset / RETAIL_FRAME_STEP;
    if tick >= u16::from(descriptor.tick_count) {
        return &[];
    }
    let range = TICKS[usize::from(descriptor.tick_offset + tick)];
    let start = usize::from(range.start);
    &ACTIONS[start..start + usize::from(range.len)]
}
