[workspace]
resolver = "2"
members = [
    "sf-core",
    "sf-path",
    "sf-map",
    "sf-strat",
    "sf-game",
    "sf-render",
    "sf-spc",
    "sf-audio",
    "sf-app",
    "sf-difftest",
    "sf2-data",
    "sf2-map",
    "sf2-path",
    "sf2-game",
    "sf-oracle",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"

[workspace.dependencies]
sf-core = { path = "sf-core" }
sf-path = { path = "sf-path" }
sf-map = { path = "sf-map" }
sf-strat = { path = "sf-strat" }
sf-render = { path = "sf-render" }
sf-game = { path = "sf-game" }
sf-spc = { path = "sf-spc" }
sf-audio = { path = "sf-audio" }
sf2-data = { path = "sf2-data" }
sf2-map = { path = "sf2-map" }
sf2-path = { path = "sf2-path" }
sf2-game = { path = "sf2-game", default-features = false }
sf-oracle = { path = "sf-oracle" }

[profile.release]
debug = true
