// Auto-generated by tools/shape_compiler.py -- do not edit.
//! Flat semantic ShapeHdr metrics used by SF1 gameplay.

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Sf1ShapeMetrics {
    pub sort_depth: i16,
    pub visual_extent: u16,
    pub coordinate_shift: u8,
    pub half_extents: [i16; 3],
}

pub const SF1_SHAPE_METRICS: &[(u16, Sf1ShapeMetrics)] = &[
    (
        0,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 188,
            coordinate_shift: 2,
            half_extents: [136, 136, 144],
        },
    ), // nullshape
    (
        1,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 159,
            coordinate_shift: 0,
            half_extents: [0, 0, 0],
        },
    ), // exitlight
    (
        2,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 80,
            coordinate_shift: 0,
            half_extents: [36, 14, 80],
        },
    ), // myship_4
    (
        3,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 114,
            coordinate_shift: 0,
            half_extents: [90, 60, 50],
        },
    ), // iris
    (
        4,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 81,
            coordinate_shift: 0,
            half_extents: [20, 60, 60],
        },
    ), // truck
    (
        5,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 44,
            coordinate_shift: 2,
            half_extents: [40, 20, 40],
        },
    ), // rail_4
    (
        6,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 87,
            coordinate_shift: 0,
            half_extents: [40, 65, 55],
        },
    ), // m_tank
    (
        7,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 120,
            coordinate_shift: 2,
            half_extents: [104, 120, 20],
        },
    ), // gate_0
    (
        8,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 116,
            coordinate_shift: 1,
            half_extents: [20, 22, 116],
        },
    ), // miss_1_2
    (
        9,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 57,
            coordinate_shift: 0,
            half_extents: [10, 40, 50],
        },
    ), // kamikaze
    (
        10,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 64,
            coordinate_shift: 4,
            half_extents: [64, 64, 64],
        },
    ), // largeplasma
    (
        11,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 276,
            coordinate_shift: 2,
            half_extents: [216, 104, 160],
        },
    ), // flingboss
    (
        12,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 196,
            coordinate_shift: 1,
            half_extents: [120, 80, 180],
        },
    ), // shark
    (
        13,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 98,
            coordinate_shift: 1,
            half_extents: [40, 40, 80],
        },
    ), // d_head_0
    (
        14,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 72,
            coordinate_shift: 1,
            half_extents: [60, 40, 30],
        },
    ), // d_body_0
    (
        15,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 80,
            coordinate_shift: 0,
            half_extents: [80, 40, 20],
        },
    ), // cameleon
    (
        16,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 76,
            coordinate_shift: 0,
            half_extents: [30, 48, 59],
        },
    ), // beeanim
    (
        17,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 304,
            coordinate_shift: 2,
            half_extents: [40, 40, 40],
        },
    ), // round_0
    (
        18,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 90,
            coordinate_shift: 1,
            half_extents: [40, 60, 44],
        },
    ), // big_m
    (
        19,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 260,
            coordinate_shift: 2,
            half_extents: [40, 40, 80],
        },
    ), // boss_1_2
    (
        20,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 1000,
            coordinate_shift: 3,
            half_extents: [240, 160, 1000],
        },
    ), // ship_1
    (
        21,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 456,
            coordinate_shift: 2,
            half_extents: [152, 240, 400],
        },
    ), // ship_3
    (
        22,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 2416,
            coordinate_shift: 4,
            half_extents: [1600, 1072, 0],
        },
    ), // ship_0_c
    (
        23,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 604,
            coordinate_shift: 2,
            half_extents: [400, 268, 480],
        },
    ), // sship_0_c
    (
        24,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 952,
            coordinate_shift: 3,
            half_extents: [88, 320, 880],
        },
    ), // wall1
    (
        25,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 952,
            coordinate_shift: 3,
            half_extents: [88, 320, 880],
        },
    ), // wall2
    (
        26,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 160,
            coordinate_shift: 2,
            half_extents: [128, 392, 136],
        },
    ), // walker_0
    (
        27,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 480,
            coordinate_shift: 2,
            half_extents: [480, 480, 48],
        },
    ), // pillar3
    (
        28,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 159,
            coordinate_shift: 0,
            half_extents: [0, 0, 0],
        },
    ), // mwireexit
    (
        29,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 159,
            coordinate_shift: 0,
            half_extents: [0, 0, 0],
        },
    ), // lwireexit
    (
        30,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 159,
            coordinate_shift: 0,
            half_extents: [0, 0, 0],
        },
    ), // bltunnelface
    (
        31,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 34,
            coordinate_shift: 0,
            half_extents: [10, 12, 5],
        },
    ), // sea_0_0
    (
        32,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 170,
            coordinate_shift: 0,
            half_extents: [120, 120, 10],
        },
    ), // exit_1
    (
        33,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 159,
            coordinate_shift: 0,
            half_extents: [0, 0, 300],
        },
    ), // lblackface
    (
        34,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 69,
            coordinate_shift: 0,
            half_extents: [5, 60, 5],
        },
    ), // lcube
    (
        35,
        Sf1ShapeMetrics {
            sort_depth: 800,
            visual_extent: 200,
            coordinate_shift: 2,
            half_extents: [200, 20, 40],
        },
    ), // rail_0
    (
        36,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 44,
            coordinate_shift: 1,
            half_extents: [40, 20, 40],
        },
    ), // miss_1_1
    (
        37,
        Sf1ShapeMetrics {
            sort_depth: 400,
            visual_extent: 318,
            coordinate_shift: 1,
            half_extents: [200, 70, 20],
        },
    ), // exitface
    (
        38,
        Sf1ShapeMetrics {
            sort_depth: 200,
            visual_extent: 159,
            coordinate_shift: 0,
            half_extents: [70, 65, 10],
        },
    ), // mexitface
    (
        39,
        Sf1ShapeMetrics {
            sort_depth: 800,
            visual_extent: 636,
            coordinate_shift: 2,
            half_extents: [360, 160, 40],
        },
    ), // bshipexitface
    (
        40,
        Sf1ShapeMetrics {
            sort_depth: 400,
            visual_extent: 318,
            coordinate_shift: 1,
            half_extents: [40, 30, 20],
        },
    ), // ship3exitface
    (
        41,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 332,
            coordinate_shift: 2,
            half_extents: [32, 316, 40],
        },
    ), // pillar2
    (
        42,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 83,
            coordinate_shift: 0,
            half_extents: [8, 79, 10],
        },
    ), // spillar2
    (
        43,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 320,
            coordinate_shift: 2,
            half_extents: [240, 240, 120],
        },
    ), // boss_8_5
    (
        44,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 120,
            coordinate_shift: 3,
            half_extents: [160, 240, 192],
        },
    ), // hou_4
    (
        45,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 808,
            coordinate_shift: 3,
            half_extents: [80, 800, 40],
        },
    ), // boss_8_4
    (
        46,
        Sf1ShapeMetrics {
            sort_depth: 1600,
            visual_extent: 240,
            coordinate_shift: 3,
            half_extents: [240, 80, 88],
        },
    ), // boss_8_0
    (
        47,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 76,
            coordinate_shift: 1,
            half_extents: [40, 70, 40],
        },
    ), // wire_man
    (
        48,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 71,
            coordinate_shift: 0,
            half_extents: [40, 40, 50],
        },
    ), // bom_wing
    (
        49,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 64,
            coordinate_shift: 0,
            half_extents: [35, 60, 40],
        },
    ), // w_l
    (
        50,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 92,
            coordinate_shift: 2,
            half_extents: [80, 80, 76],
        },
    ), // rader_0
    (
        51,
        Sf1ShapeMetrics {
            sort_depth: 40,
            visual_extent: 124,
            coordinate_shift: 2,
            half_extents: [100, 124, 100],
        },
    ), // rader_1
    (
        52,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 80,
            coordinate_shift: 1,
            half_extents: [66, 20, 78],
        },
    ), // zaco_6
    (
        53,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 110,
            coordinate_shift: 0,
            half_extents: [80, 70, 30],
        },
    ), // zaco_5
    (
        54,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 156,
            coordinate_shift: 1,
            half_extents: [30, 134, 80],
        },
    ), // houdai_0
    (
        55,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 472,
            coordinate_shift: 3,
            half_extents: [160, 240, 440],
        },
    ), // boss_7_1
    (
        56,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 84,
            coordinate_shift: 2,
            half_extents: [60, 80, 60],
        },
    ), // boss_a_1
    (
        57,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 552,
            coordinate_shift: 3,
            half_extents: [480, 160, 160],
        },
    ), // boss_a_2
    (
        58,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 480,
            coordinate_shift: 2,
            half_extents: [80, 480, 160],
        },
    ), // tower_2
    (
        59,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 86,
            coordinate_shift: 0,
            half_extents: [20, 76, 20],
        },
    ), // para_0
    (
        60,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 392,
            coordinate_shift: 3,
            half_extents: [160, 320, 160],
        },
    ), // bu_0
    (
        61,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 416,
            coordinate_shift: 2,
            half_extents: [80, 400, 80],
        },
    ), // bu_1
    (
        62,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 584,
            coordinate_shift: 3,
            half_extents: [80, 560, 160],
        },
    ), // bu_2
    (
        63,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 460,
            coordinate_shift: 2,
            half_extents: [80, 320, 320],
        },
    ), // bu_3
    (
        64,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 488,
            coordinate_shift: 2,
            half_extents: [200, 400, 200],
        },
    ), // bu_4
    (
        65,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 488,
            coordinate_shift: 2,
            half_extents: [200, 400, 200],
        },
    ), // bu_5
    (
        66,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 488,
            coordinate_shift: 2,
            half_extents: [200, 400, 200],
        },
    ), // bu_6
    (
        67,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 384,
            coordinate_shift: 2,
            half_extents: [80, 340, 160],
        },
    ), // bu_7
    (
        68,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 196,
            coordinate_shift: 2,
            half_extents: [80, 160, 80],
        },
    ), // bu_8
    (
        69,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 232,
            coordinate_shift: 3,
            half_extents: [216, 240, 216],
        },
    ), // boss_2_2
    (
        70,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 180,
            coordinate_shift: 1,
            half_extents: [90, 120, 100],
        },
    ), // core_1_0
    (
        71,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 86,
            coordinate_shift: 1,
            half_extents: [26, 86, 26],
        },
    ), // core_1_1
    (
        72,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 150,
            coordinate_shift: 1,
            half_extents: [90, 120, 40],
        },
    ), // exit_2
    (
        73,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 159,
            coordinate_shift: 0,
            half_extents: [0, 0, 0],
        },
    ), // bmtunnelface
    (
        74,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 159,
            coordinate_shift: 0,
            half_extents: [0, 0, 300],
        },
    ), // mblackface
    (
        75,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 432,
            coordinate_shift: 2,
            half_extents: [384, 316, 272],
        },
    ), // boss_b_0
    (
        76,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 252,
            coordinate_shift: 2,
            half_extents: [180, 140, 240],
        },
    ), // boss_b_1
    (
        77,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 148,
            coordinate_shift: 2,
            half_extents: [80, 296, 152],
        },
    ), // boss_d_1
    (
        78,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 186,
            coordinate_shift: 1,
            half_extents: [78, 72, 178],
        },
    ), // boss_9_5
    (
        79,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 50,
            coordinate_shift: 0,
            half_extents: [15, 42, 110],
        },
    ), // air_1
    (
        80,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 100,
            coordinate_shift: 0,
            half_extents: [54, 0, 89],
        },
    ), // line_2
    (
        81,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 496,
            coordinate_shift: 3,
            half_extents: [400, 120, 488],
        },
    ), // boss_f_3
    (
        82,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 130,
            coordinate_shift: 1,
            half_extents: [50, 120, 10],
        },
    ), // tunnel_8
    (
        83,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 57,
            coordinate_shift: 0,
            half_extents: [25, 33, 52],
        },
    ), // tunnel_6
    (
        84,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 172,
            coordinate_shift: 2,
            half_extents: [136, 160, 68],
        },
    ), // boss_0_1
    (
        85,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 140,
            coordinate_shift: 1,
            half_extents: [120, 60, 40],
        },
    ), // door_1
    (
        86,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 100,
            coordinate_shift: 1,
            half_extents: [90, 20, 40],
        },
    ), // wall_0
    (
        87,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 122,
            coordinate_shift: 1,
            half_extents: [90, 40, 20],
        },
    ), // wall_1
    (
        88,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 124,
            coordinate_shift: 1,
            half_extents: [30, 60, 20],
        },
    ), // wall_2
    (
        89,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 130,
            coordinate_shift: 1,
            half_extents: [50, 60, 20],
        },
    ), // wall_3
    (
        90,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 122,
            coordinate_shift: 1,
            half_extents: [10, 60, 20],
        },
    ), // wall_4
    (
        91,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 94,
            coordinate_shift: 1,
            half_extents: [90, 10, 20],
        },
    ), // wall_5
    (
        92,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 68,
            coordinate_shift: 1,
            half_extents: [30, 30, 20],
        },
    ), // wall_6
    (
        93,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 82,
            coordinate_shift: 1,
            half_extents: [10, 40, 20],
        },
    ), // wall_7
    (
        94,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 528,
            coordinate_shift: 3,
            half_extents: [488, 88, 480],
        },
    ), // boss_f_4
    (
        95,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 214,
            coordinate_shift: 1,
            half_extents: [126, 120, 180],
        },
    ), // r_bu_0
    (
        96,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 81,
            coordinate_shift: 0,
            half_extents: [55, 50, 55],
        },
    ), // r_bu_1
    (
        97,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 156,
            coordinate_shift: 0,
            half_extents: [115, 10, 105],
        },
    ), // r_bu_2
    (
        98,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 68,
            coordinate_shift: 0,
            half_extents: [30, 60, 30],
        },
    ), // r_bu_3
    (
        99,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 113,
            coordinate_shift: 0,
            half_extents: [80, 25, 80],
        },
    ), // r_bu_4
    (
        100,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 226,
            coordinate_shift: 1,
            half_extents: [40, 80, 210],
        },
    ), // r_bu_5
    (
        101,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 154,
            coordinate_shift: 1,
            half_extents: [30, 30, 150],
        },
    ), // r_bu_6
    (
        102,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 128,
            coordinate_shift: 0,
            half_extents: [25, 125, 25],
        },
    ), // r_bu_7
    (
        103,
        Sf1ShapeMetrics {
            sort_depth: -800,
            visual_extent: 80,
            coordinate_shift: 3,
            half_extents: [80, 80, 80],
        },
    ), // amoeba2
    (
        104,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 84,
            coordinate_shift: 1,
            half_extents: [66, 60, 60],
        },
    ), // zaco_8
    (
        105,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 158,
            coordinate_shift: 1,
            half_extents: [140, 40, 120],
        },
    ), // zaco_4
    (
        106,
        Sf1ShapeMetrics {
            sort_depth: 1280,
            visual_extent: 1200,
            coordinate_shift: 4,
            half_extents: [320, 320, 320],
        },
    ), // ship_5
    (
        107,
        Sf1ShapeMetrics {
            sort_depth: 640,
            visual_extent: 600,
            coordinate_shift: 3,
            half_extents: [160, 160, 160],
        },
    ), // ship_5l
    (
        108,
        Sf1ShapeMetrics {
            sort_depth: 320,
            visual_extent: 300,
            coordinate_shift: 2,
            half_extents: [80, 80, 80],
        },
    ), // ship_5m
    (
        109,
        Sf1ShapeMetrics {
            sort_depth: 80,
            visual_extent: 122,
            coordinate_shift: 0,
            half_extents: [30, 50, 120],
        },
    ), // ship_5s
    (
        110,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 424,
            coordinate_shift: 3,
            half_extents: [344, 376, 128],
        },
    ), // ships
    (
        111,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 110,
            coordinate_shift: 1,
            half_extents: [92, 60, 10],
        },
    ), // s_door_1
    (
        112,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 110,
            coordinate_shift: 1,
            half_extents: [92, 60, 10],
        },
    ), // s_door_2
    (
        113,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 150,
            coordinate_shift: 1,
            half_extents: [90, 110, 60],
        },
    ), // leng_0
    (
        114,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 344,
            coordinate_shift: 2,
            half_extents: [328, 160, 292],
        },
    ), // carrier
    (
        115,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 296,
            coordinate_shift: 3,
            half_extents: [240, 320, 400],
        },
    ), // base_0
    (
        116,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 4,
            coordinate_shift: 0,
            half_extents: [4, 4, 4],
        },
    ), // kellogs
    (
        117,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 144,
            coordinate_shift: 1,
            half_extents: [64, 128, 10],
        },
    ), // k_door
    (
        118,
        Sf1ShapeMetrics {
            sort_depth: 3136,
            visual_extent: 256,
            coordinate_shift: 3,
            half_extents: [64, 144, 200],
        },
    ), // kichi_3
    (
        119,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 3072,
            coordinate_shift: 6,
            half_extents: [2560, 2560, 1600],
        },
    ), // kichi_0
    (
        120,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 106,
            coordinate_shift: 0,
            half_extents: [50, 60, 90],
        },
    ), // boss_g_0
    (
        121,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 36,
            coordinate_shift: 0,
            half_extents: [20, 20, 30],
        },
    ), // tunnel_0
    (
        122,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 124,
            coordinate_shift: 1,
            half_extents: [28, 120, 20],
        },
    ), // tunnel_4
    (
        123,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 21,
            coordinate_shift: 0,
            half_extents: [15, 5, 15],
        },
    ), // tunnel_7
    (
        124,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 664,
            coordinate_shift: 3,
            half_extents: [344, 352, 440],
        },
    ), // mybase_1
    (
        125,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 360,
            coordinate_shift: 3,
            half_extents: [336, 160, 24],
        },
    ), // ship_s_0
    (
        126,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 360,
            coordinate_shift: 3,
            half_extents: [360, 144, 40],
        },
    ), // ship_s_1
    (
        127,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 128,
            coordinate_shift: 1,
            half_extents: [80, 80, 120],
        },
    ), // ship_4
    (
        128,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 59,
            coordinate_shift: 0,
            half_extents: [58, 37, 28],
        },
    ), // zaco_7
    (
        129,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 44,
            coordinate_shift: 0,
            half_extents: [32, 42, 25],
        },
    ), // warker_3
    (
        130,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 65,
            coordinate_shift: 0,
            half_extents: [60, 25, 60],
        },
    ), // heli
    (
        131,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 204,
            coordinate_shift: 2,
            half_extents: [160, 100, 124],
        },
    ), // bazooka
    (
        132,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 92,
            coordinate_shift: 1,
            half_extents: [52, 64, 90],
        },
    ), // uper_m
    (
        133,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 108,
            coordinate_shift: 1,
            half_extents: [60, 34, 90],
        },
    ), // warp
    (
        134,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 180,
            coordinate_shift: 1,
            half_extents: [130, 100, 150],
        },
    ), // tank_2
    (
        135,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 340,
            coordinate_shift: 2,
            half_extents: [272, 100, 216],
        },
    ), // f_dragon
    (
        136,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 0,
            coordinate_shift: 0,
            half_extents: [0, 0, 0],
        },
    ), // xwirespacebar
    (
        137,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 0,
            coordinate_shift: 0,
            half_extents: [0, 0, 0],
        },
    ), // xpwirespacebar
    (
        138,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 0,
            coordinate_shift: 0,
            half_extents: [0, 0, 0],
        },
    ), // sxpwirespacebar
    (
        139,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 0,
            coordinate_shift: 0,
            half_extents: [0, 0, 0],
        },
    ), // ywirespacebar
    (
        140,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 0,
            coordinate_shift: 0,
            half_extents: [0, 0, 0],
        },
    ), // zwirespacebar
    (
        141,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 0,
            coordinate_shift: 0,
            half_extents: [0, 0, 0],
        },
    ), // sxwirespacebar
    (
        142,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 0,
            coordinate_shift: 0,
            half_extents: [0, 0, 0],
        },
    ), // sywirespacebar
    (
        143,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 0,
            coordinate_shift: 0,
            half_extents: [0, 0, 0],
        },
    ), // szwirespacebar
    (
        144,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 0,
            coordinate_shift: 0,
            half_extents: [0, 0, 0],
        },
    ), // xsolidspacebar
    (
        145,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 0,
            coordinate_shift: 0,
            half_extents: [0, 0, 0],
        },
    ), // xpsolidspacebar
    (
        146,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 0,
            coordinate_shift: 0,
            half_extents: [0, 0, 0],
        },
    ), // sxpsolidspacebar
    (
        147,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 0,
            coordinate_shift: 0,
            half_extents: [0, 0, 0],
        },
    ), // ysolidspacebar
    (
        148,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 0,
            coordinate_shift: 0,
            half_extents: [0, 0, 0],
        },
    ), // zsolidspacebar
    (
        149,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 0,
            coordinate_shift: 0,
            half_extents: [0, 0, 0],
        },
    ), // sxsolidspacebar
    (
        150,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 0,
            coordinate_shift: 0,
            half_extents: [0, 0, 0],
        },
    ), // sysolidspacebar
    (
        151,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 0,
            coordinate_shift: 0,
            half_extents: [0, 0, 0],
        },
    ), // szsolidspacebar
    (
        152,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 568,
            coordinate_shift: 3,
            half_extents: [400, 488, 280],
        },
    ), // colony_0
    (
        153,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 528,
            coordinate_shift: 3,
            half_extents: [440, 136, 280],
        },
    ), // colony_1
    (
        154,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 110,
            coordinate_shift: 1,
            half_extents: [92, 60, 40],
        },
    ), // colony_2
    (
        155,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 992,
            coordinate_shift: 4,
            half_extents: [80, 400, 160],
        },
    ), // colony3l
    (
        156,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 992,
            coordinate_shift: 4,
            half_extents: [672, 672, 800],
        },
    ), // colony3r
    (
        157,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 88,
            coordinate_shift: 1,
            half_extents: [64, 84, 50],
        },
    ), // bwarker_3
    (
        158,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 46,
            coordinate_shift: 1,
            half_extents: [42, 40, 40],
        },
    ), // item_5
    (
        159,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 48,
            coordinate_shift: 1,
            half_extents: [48, 40, 48],
        },
    ), // item_6
    (
        160,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 44,
            coordinate_shift: 1,
            half_extents: [40, 40, 34],
        },
    ), // item_7
    (
        161,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 64,
            coordinate_shift: 1,
            half_extents: [48, 58, 50],
        },
    ), // r_hou_0
    (
        162,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 64,
            coordinate_shift: 1,
            half_extents: [48, 58, 50],
        },
    ), // s_hou_0
    (
        163,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 64,
            coordinate_shift: 1,
            half_extents: [48, 58, 50],
        },
    ), // b_hou_0
    (
        164,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 88,
            coordinate_shift: 0,
            half_extents: [30, 87, 47],
        },
    ), // walker_2
    (
        165,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 1192,
            coordinate_shift: 3,
            half_extents: [480, 640, 960],
        },
    ), // base_0_0
    (
        166,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 1192,
            coordinate_shift: 3,
            half_extents: [480, 640, 960],
        },
    ), // base_0_1
    (
        167,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 156,
            coordinate_shift: 1,
            half_extents: [60, 120, 100],
        },
    ), // tank_1
    (
        168,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 240,
            coordinate_shift: 2,
            half_extents: [72, 236, 80],
        },
    ), // hou_5
    (
        169,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 672,
            coordinate_shift: 3,
            half_extents: [96, 640, 440],
        },
    ), // ro_0
    (
        170,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 672,
            coordinate_shift: 3,
            half_extents: [96, 640, 440],
        },
    ), // ro_1
    (
        171,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 680,
            coordinate_shift: 3,
            half_extents: [136, 640, 440],
        },
    ), // ro_2
    (
        172,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 680,
            coordinate_shift: 3,
            half_extents: [136, 640, 440],
        },
    ), // ro_3
    (
        173,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 696,
            coordinate_shift: 3,
            half_extents: [208, 640, 440],
        },
    ), // ro_4
    (
        174,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 696,
            coordinate_shift: 3,
            half_extents: [208, 640, 440],
        },
    ), // ro_5
    (
        175,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 432,
            coordinate_shift: 3,
            half_extents: [184, 400, 160],
        },
    ), // ro_6
    (
        176,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 672,
            coordinate_shift: 3,
            half_extents: [96, 640, 440],
        },
    ), // bro_0
    (
        177,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 672,
            coordinate_shift: 3,
            half_extents: [96, 640, 440],
        },
    ), // bro_1
    (
        178,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 680,
            coordinate_shift: 3,
            half_extents: [136, 640, 440],
        },
    ), // bro_2
    (
        179,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 680,
            coordinate_shift: 3,
            half_extents: [136, 640, 440],
        },
    ), // bro_3
    (
        180,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 696,
            coordinate_shift: 3,
            half_extents: [208, 640, 440],
        },
    ), // bro_4
    (
        181,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 696,
            coordinate_shift: 3,
            half_extents: [208, 640, 440],
        },
    ), // bro_5
    (
        182,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 432,
            coordinate_shift: 3,
            half_extents: [184, 400, 160],
        },
    ), // bro_6
    (
        183,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 672,
            coordinate_shift: 3,
            half_extents: [96, 640, 440],
        },
    ), // gro_0
    (
        184,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 672,
            coordinate_shift: 3,
            half_extents: [96, 640, 440],
        },
    ), // gro_1
    (
        185,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 680,
            coordinate_shift: 3,
            half_extents: [136, 640, 440],
        },
    ), // gro_2
    (
        186,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 680,
            coordinate_shift: 3,
            half_extents: [136, 640, 440],
        },
    ), // gro_3
    (
        187,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 696,
            coordinate_shift: 3,
            half_extents: [208, 640, 440],
        },
    ), // gro_4
    (
        188,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 696,
            coordinate_shift: 3,
            half_extents: [208, 640, 440],
        },
    ), // gro_5
    (
        189,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 432,
            coordinate_shift: 3,
            half_extents: [184, 400, 160],
        },
    ), // gro_6
    (
        190,
        Sf1ShapeMetrics {
            sort_depth: -40,
            visual_extent: 224,
            coordinate_shift: 2,
            half_extents: [120, 200, 200],
        },
    ), // volcano
    (
        191,
        Sf1ShapeMetrics {
            sort_depth: -20,
            visual_extent: 112,
            coordinate_shift: 1,
            half_extents: [60, 100, 100],
        },
    ), // svolcano
    (
        192,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 192,
            coordinate_shift: 1,
            half_extents: [182, 64, 188],
        },
    ), // meteo_0
    (
        193,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 64,
            coordinate_shift: 4,
            half_extents: [64, 64, 64],
        },
    ), // blackhole
    (
        194,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 64,
            coordinate_shift: 4,
            half_extents: [64, 64, 64],
        },
    ), // asteroid2
    (
        195,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 160,
            coordinate_shift: 3,
            half_extents: [160, 160, 0],
        },
    ), // b_holl
    (
        196,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 116,
            coordinate_shift: 1,
            half_extents: [60, 24, 100],
        },
    ), // car_0
    (
        197,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 78,
            coordinate_shift: 0,
            half_extents: [30, 75, 30],
        },
    ), // clisla_m
    (
        198,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 40,
            coordinate_shift: 0,
            half_extents: [25, 40, 20],
        },
    ), // clisla_s
    (
        199,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 284,
            coordinate_shift: 2,
            half_extents: [188, 204, 60],
        },
    ), // clisla_l
    (
        200,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 50,
            coordinate_shift: 0,
            half_extents: [15, 50, 15],
        },
    ), // snake_1
    (
        201,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 86,
            coordinate_shift: 0,
            half_extents: [70, 53, 49],
        },
    ), // zaco_b
    (
        202,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 80,
            coordinate_shift: 0,
            half_extents: [15, 40, 15],
        },
    ), // shieldr
    (
        203,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 120,
            coordinate_shift: 0,
            half_extents: [50, 25, 120],
        },
    ), // ray_0
    (
        204,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 111,
            coordinate_shift: 0,
            half_extents: [110, 23, 102],
        },
    ), // ray_1
    (
        205,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 36,
            coordinate_shift: 1,
            half_extents: [34, 20, 20],
        },
    ), // boss_e_4
    (
        206,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 130,
            coordinate_shift: 1,
            half_extents: [52, 130, 42],
        },
    ), // flower_1
    (
        207,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 170,
            coordinate_shift: 1,
            half_extents: [52, 170, 42],
        },
    ), // flower_2
    (
        208,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 50,
            coordinate_shift: 0,
            half_extents: [20, 50, 20],
        },
    ), // stalk
    (
        209,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 80,
            coordinate_shift: 1,
            half_extents: [60, 80, 60],
        },
    ), // mine_2
    (
        210,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 60,
            coordinate_shift: 1,
            half_extents: [52, 60, 14],
        },
    ), // gate_2
    (
        211,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 45,
            coordinate_shift: 0,
            half_extents: [10, 15, 41],
        },
    ), // s_fish
    (
        212,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 2144,
            coordinate_shift: 5,
            half_extents: [1248, 1920, 1504],
        },
    ), // last_b_0
    (
        213,
        Sf1ShapeMetrics {
            sort_depth: 1600,
            visual_extent: 1600,
            coordinate_shift: 4,
            half_extents: [112, 1600, 1600],
        },
    ), // last_b_2
    (
        214,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 108,
            coordinate_shift: 2,
            half_extents: [96, 0, 96],
        },
    ), // last_b_3
    (
        215,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 168,
            coordinate_shift: 1,
            half_extents: [112, 126, 20],
        },
    ), // door_l
    (
        216,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 114,
            coordinate_shift: 1,
            half_extents: [60, 50, 100],
        },
    ), // car_1
    (
        217,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 116,
            coordinate_shift: 1,
            half_extents: [72, 74, 60],
        },
    ), // zaco_a
    (
        218,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 80,
            coordinate_shift: 0,
            half_extents: [36, 14, 80],
        },
    ), // friendship_4
    (
        219,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 116,
            coordinate_shift: 1,
            half_extents: [50, 104, 48],
        },
    ), // s_wark_0
    (
        220,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 100,
            coordinate_shift: 0,
            half_extents: [46, 61, 100],
        },
    ), // ika
    (
        221,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 79,
            coordinate_shift: 0,
            half_extents: [60, 60, 50],
        },
    ), // s_zaco_0
    (
        222,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 192,
            coordinate_shift: 2,
            half_extents: [152, 100, 164],
        },
    ), // bazz_1
    (
        223,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 944,
            coordinate_shift: 4,
            half_extents: [480, 800, 80],
        },
    ), // face_b
    (
        224,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 125,
            coordinate_shift: 0,
            half_extents: [70, 28, 100],
        },
    ), // my_demos
    (
        225,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 250,
            coordinate_shift: 1,
            half_extents: [140, 56, 200],
        },
    ), // my_demo
    (
        226,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 16,
            coordinate_shift: 2,
            half_extents: [16, 16, 16],
        },
    ), // helpball
    (
        227,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 252,
            coordinate_shift: 2,
            half_extents: [60, 80, 240],
        },
    ), // tadpole
    (
        228,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 172,
            coordinate_shift: 2,
            half_extents: [120, 160, 40],
        },
    ), // arch_0
    (
        229,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 160,
            coordinate_shift: 1,
            half_extents: [74, 54, 220],
        },
    ), // s_tank_0
    (
        230,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 45,
            coordinate_shift: 0,
            half_extents: [45, 40, 40],
        },
    ), // zaco_1
    (
        231,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 84,
            coordinate_shift: 1,
            half_extents: [66, 60, 60],
        },
    ), // bzaco_8
    (
        232,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 736,
            coordinate_shift: 3,
            half_extents: [320, 640, 360],
        },
    ), // base_1
    (
        233,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 408,
            coordinate_shift: 2,
            half_extents: [200, 280, 300],
        },
    ), // big_gate
    (
        234,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 64,
            coordinate_shift: 1,
            half_extents: [48, 58, 50],
        },
    ), // r_hou
    (
        235,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 78,
            coordinate_shift: 0,
            half_extents: [45, 60, 20],
        },
    ), // open_l
    (
        236,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 110,
            coordinate_shift: 1,
            half_extents: [90, 60, 20],
        },
    ), // up_door
    (
        237,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 256,
            coordinate_shift: 6,
            half_extents: [256, 256, 256],
        },
    ), // big_meteor
    (
        238,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 60,
            coordinate_shift: 1,
            half_extents: [56, 20, 36],
        },
    ), // boss_d_4
    (
        239,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 156,
            coordinate_shift: 1,
            half_extents: [60, 120, 100],
        },
    ), // btank_1
    (
        240,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 34,
            coordinate_shift: 0,
            half_extents: [8, 30, 60],
        },
    ), // font_t
    (
        241,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 34,
            coordinate_shift: 0,
            half_extents: [8, 30, 60],
        },
    ), // font_h
    (
        242,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 34,
            coordinate_shift: 0,
            half_extents: [8, 30, 60],
        },
    ), // font_e
    (
        243,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 34,
            coordinate_shift: 0,
            half_extents: [8, 30, 60],
        },
    ), // font_n
    (
        244,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 34,
            coordinate_shift: 0,
            half_extents: [8, 10, 60],
        },
    ), // font_d
    (
        245,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 80,
            coordinate_shift: 3,
            half_extents: [80, 80, 80],
        },
    ), // gamesh
    (
        246,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 80,
            coordinate_shift: 3,
            half_extents: [80, 80, 80],
        },
    ), // oversh
    (
        247,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 164,
            coordinate_shift: 1,
            half_extents: [28, 160, 28],
        },
    ), // tow_0
    (
        248,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 94,
            coordinate_shift: 0,
            half_extents: [90, 20, 20],
        },
    ), // bou_0
    (
        256,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 1200,
            coordinate_shift: 4,
            half_extents: [800, 672, 752],
        },
    ), // mybase_0
    (
        257,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 56,
            coordinate_shift: 0,
            half_extents: [35, 47, 30],
        },
    ), // sea_0
    (
        258,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 49,
            coordinate_shift: 0,
            half_extents: [10, 20, 7],
        },
    ), // sea_0_1
    (
        259,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 320,
            coordinate_shift: 3,
            half_extents: [320, 320, 320],
        },
    ), // boss_2_0
    (
        260,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 320,
            coordinate_shift: 3,
            half_extents: [160, 560, 160],
        },
    ), // boss_2_1
    (
        261,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 528,
            coordinate_shift: 3,
            half_extents: [368, 248, 520],
        },
    ), // boss_2_3
    (
        262,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 440,
            coordinate_shift: 3,
            half_extents: [264, 528, 288],
        },
    ), // boss_2_4
    (
        263,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 320,
            coordinate_shift: 3,
            half_extents: [216, 480, 216],
        },
    ), // boss_2_5
    (
        264,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 840,
            coordinate_shift: 3,
            half_extents: [320, 800, 320],
        },
    ), // boss_8_1
    (
        265,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 840,
            coordinate_shift: 3,
            half_extents: [320, 800, 320],
        },
    ), // boss_8_1c
    (
        266,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 800,
            coordinate_shift: 3,
            half_extents: [56, 112, 800],
        },
    ), // sparklas
    (
        267,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 95,
            coordinate_shift: 0,
            half_extents: [60, 70, 70],
        },
    ), // shrap1
    (
        268,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 22,
            coordinate_shift: 0,
            half_extents: [20, 20, 0],
        },
    ), // shyper
    (
        269,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 74,
            coordinate_shift: 1,
            half_extents: [50, 40, 60],
        },
    ), // zaco_9
    (
        270,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 85,
            coordinate_shift: 0,
            half_extents: [50, 60, 60],
        },
    ), // boss_g_s
    (
        271,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 63,
            coordinate_shift: 0,
            half_extents: [55, 40, 60],
        },
    ), // f_fish
    (
        272,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 32,
            coordinate_shift: 3,
            half_extents: [32, 32, 32],
        },
    ), // rockbeam
    (
        273,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 160,
            coordinate_shift: 4,
            half_extents: [160, 160, 160],
        },
    ), // l2smoke
    (
        274,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 16,
            coordinate_shift: 2,
            half_extents: [16, 16, 16],
        },
    ), // explosion5
    (
        275,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 64,
            coordinate_shift: 4,
            half_extents: [64, 64, 64],
        },
    ), // asteroid1
    (
        276,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 16,
            coordinate_shift: 2,
            half_extents: [16, 16, 16],
        },
    ), // asteroid3
    (
        277,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 16,
            coordinate_shift: 2,
            half_extents: [16, 16, 16],
        },
    ), // asteroid4
    (
        279,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 256,
            coordinate_shift: 6,
            half_extents: [256, 256, 256],
        },
    ), // big_meteor
    (
        280,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 16,
            coordinate_shift: 2,
            half_extents: [16, 16, 16],
        },
    ), // clasteroid
    (
        281,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 776,
            coordinate_shift: 3,
            half_extents: [160, 160, 400],
        },
    ), // whale
    (
        282,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 172,
            coordinate_shift: 1,
            half_extents: [170, 134, 128],
        },
    ), // my_bird
    (
        283,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 40,
            coordinate_shift: 1,
            half_extents: [24, 18, 30],
        },
    ), // zaco_8p
    (
        284,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 66,
            coordinate_shift: 0,
            half_extents: [20, 60, 20],
        },
    ), // bou_1
    (
        285,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 2304,
            coordinate_shift: 3,
            half_extents: [1040, 480, 2000],
        },
    ), // pipe_8_0
    (
        286,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 640,
            coordinate_shift: 3,
            half_extents: [128, 120, 608],
        },
    ), // pipe_8
    (
        287,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 66,
            coordinate_shift: 0,
            half_extents: [20, 60, 20],
        },
    ), // bou_1b
    (
        288,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 114,
            coordinate_shift: 1,
            half_extents: [80, 78, 80],
        },
    ), // paper_1
    (
        289,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 228,
            coordinate_shift: 2,
            half_extents: [160, 224, 160],
        },
    ), // paper_3
    (
        290,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 220,
            coordinate_shift: 2,
            half_extents: [220, 220, 220],
        },
    ), // pole_0
    (
        291,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 432,
            coordinate_shift: 2,
            half_extents: [180, 400, 140],
        },
    ), // slot_0
    (
        292,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 34,
            coordinate_shift: 0,
            half_extents: [8, 30, 60],
        },
    ), // font_t2
    (
        293,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 34,
            coordinate_shift: 0,
            half_extents: [8, 30, 60],
        },
    ), // font_h2
    (
        294,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 34,
            coordinate_shift: 0,
            half_extents: [8, 30, 60],
        },
    ), // font_e2
    (
        295,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 34,
            coordinate_shift: 0,
            half_extents: [8, 30, 60],
        },
    ), // font_e3
    (
        296,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 34,
            coordinate_shift: 0,
            half_extents: [8, 30, 60],
        },
    ), // font_n2
    (
        297,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 34,
            coordinate_shift: 0,
            half_extents: [8, 10, 60],
        },
    ), // font_d2
    (
        298,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 60,
            coordinate_shift: 1,
            half_extents: [40, 60, 40],
        },
    ), // pilon
    (
        299,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 30,
            coordinate_shift: 1,
            half_extents: [20, 30, 18],
        },
    ), // mine_0
    (
        300,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 204,
            coordinate_shift: 2,
            half_extents: [192, 80, 192],
        },
    ), // boss_h_0
    (
        301,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 768,
            coordinate_shift: 3,
            half_extents: [160, 760, 768],
        },
    ), // boss_h_1
    (
        302,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 768,
            coordinate_shift: 3,
            half_extents: [560, 128, 760],
        },
    ), // boss_h_1a
    (
        303,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 256,
            coordinate_shift: 2,
            half_extents: [120, 240, 40],
        },
    ), // boss_h_2
    (
        304,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 400,
            coordinate_shift: 2,
            half_extents: [32, 400, 0],
        },
    ), // boss_h_3
    (
        305,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 304,
            coordinate_shift: 3,
            half_extents: [240, 216, 200],
        },
    ), // boss_f_1
    (
        306,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 688,
            coordinate_shift: 3,
            half_extents: [488, 600, 640],
        },
    ), // boss_f_2
    (
        307,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 264,
            coordinate_shift: 3,
            half_extents: [232, 200, 160],
        },
    ), // boss_f_5
    (
        308,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 568,
            coordinate_shift: 3,
            half_extents: [48, 168, 560],
        },
    ), // boss_f_6
    (
        309,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 568,
            coordinate_shift: 3,
            half_extents: [48, 168, 560],
        },
    ), // boss_f_7
    (
        310,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 2176,
            coordinate_shift: 3,
            half_extents: [720, 480, 2000],
        },
    ), // pipe_9_0
    (
        311,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 640,
            coordinate_shift: 3,
            half_extents: [128, 120, 608],
        },
    ), // pipe_9
    (
        312,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 1920,
            coordinate_shift: 4,
            half_extents: [400, 640, 1920],
        },
    ), // deboss_1
    (
        313,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 464,
            coordinate_shift: 4,
            half_extents: [208, 96, 416],
        },
    ), // pipe_0
    (
        314,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 464,
            coordinate_shift: 4,
            half_extents: [208, 96, 416],
        },
    ), // pipe_1
    (
        315,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 464,
            coordinate_shift: 4,
            half_extents: [208, 96, 416],
        },
    ), // pipe_2
    (
        316,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 464,
            coordinate_shift: 4,
            half_extents: [208, 96, 416],
        },
    ), // pipe_3
    (
        317,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 400,
            coordinate_shift: 4,
            half_extents: [208, 96, 320],
        },
    ), // pipe_4
    (
        318,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 400,
            coordinate_shift: 4,
            half_extents: [208, 96, 320],
        },
    ), // pipe_5
    (
        319,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 832,
            coordinate_shift: 4,
            half_extents: [224, 160, 800],
        },
    ), // pipe_6
    (
        320,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 66,
            coordinate_shift: 0,
            half_extents: [60, 20, 20],
        },
    ), // d_pilar
    (
        321,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 88,
            coordinate_shift: 1,
            half_extents: [60, 60, 20],
        },
    ), // half_d
    (
        322,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 130,
            coordinate_shift: 0,
            half_extents: [70, 96, 52],
        },
    ), // cockpit
    (
        323,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 188,
            coordinate_shift: 2,
            half_extents: [140, 68, 132],
        },
    ), // old_type
    (
        324,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 80,
            coordinate_shift: 0,
            half_extents: [36, 14, 80],
        },
    ), // item_0
    (
        325,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 156,
            coordinate_shift: 0,
            half_extents: [115, 110, 105],
        },
    ), // r_but_2
    (
        326,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 204,
            coordinate_shift: 2,
            half_extents: [120, 80, 200],
        },
    ), // walk_4_0
    (
        327,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 50,
            coordinate_shift: 1,
            half_extents: [160, 160, 160],
        },
    ), // arm
    (
        328,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 160,
            coordinate_shift: 1,
            half_extents: [40, 40, 160],
        },
    ), // bulge
    (
        329,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 240,
            coordinate_shift: 2,
            half_extents: [200, 200, 220],
        },
    ), // boss_e_0
    (
        330,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 240,
            coordinate_shift: 2,
            half_extents: [200, 200, 220],
        },
    ), // boss_e_1
    (
        331,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 240,
            coordinate_shift: 2,
            half_extents: [200, 200, 220],
        },
    ), // boss_e_1a
    (
        332,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 93,
            coordinate_shift: 0,
            half_extents: [40, 36, 88],
        },
    ), // boss_e_3
    (
        333,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 36,
            coordinate_shift: 1,
            half_extents: [34, 20, 20],
        },
    ), // boss_e_4
    (
        334,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 40,
            coordinate_shift: 2,
            half_extents: [40, 40, 120],
        },
    ), // ringlaser
    (
        335,
        Sf1ShapeMetrics {
            sort_depth: -200,
            visual_extent: 96,
            coordinate_shift: 1,
            half_extents: [76, 70, 80],
        },
    ), // snake_0
    (
        336,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 120,
            coordinate_shift: 0,
            half_extents: [15, 120, 23],
        },
    ), // snake_3
    (
        337,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 50,
            coordinate_shift: 0,
            half_extents: [15, 50, 15],
        },
    ), // snake_4
    (
        338,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 4,
            coordinate_shift: 0,
            half_extents: [4, 4, 4],
        },
    ), // smark
    (
        339,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 8,
            coordinate_shift: 1,
            half_extents: [8, 8, 8],
        },
    ), // mmark
    (
        340,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 16,
            coordinate_shift: 2,
            half_extents: [16, 16, 16],
        },
    ), // lmark
    (
        341,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 32,
            coordinate_shift: 3,
            half_extents: [32, 32, 32],
        },
    ), // escapee
    (
        342,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 16,
            coordinate_shift: 2,
            half_extents: [16, 16, 16],
        },
    ), // lfdie
    (
        343,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 200,
            coordinate_shift: 1,
            half_extents: [200, 200, 200],
        },
    ), // andross
    (
        344,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 0,
            coordinate_shift: 0,
            half_extents: [0, 0, 0],
        },
    ), // androsscube
    (
        345,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 1184,
            coordinate_shift: 4,
            half_extents: [448, 960, 976],
        },
    ), // face_0_1
    (
        346,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 1120,
            coordinate_shift: 4,
            half_extents: [480, 960, 400],
        },
    ), // face_1
    (
        347,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 400,
            coordinate_shift: 3,
            half_extents: [160, 400, 160],
        },
    ), // face_box
    (
        348,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 236,
            coordinate_shift: 2,
            half_extents: [120, 200, 20],
        },
    ), // sface_b
    (
        349,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 236,
            coordinate_shift: 2,
            half_extents: [120, 200, 20],
        },
    ), // sface2_b
    (
        350,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 30,
            coordinate_shift: 0,
            half_extents: [20, 30, 20],
        },
    ), // para_1
    (
        351,
        Sf1ShapeMetrics {
            sort_depth: -10,
            visual_extent: 80,
            coordinate_shift: 0,
            half_extents: [34, 14, 80],
        },
    ), // my_w
    (
        352,
        Sf1ShapeMetrics {
            sort_depth: -10,
            visual_extent: 80,
            coordinate_shift: 0,
            half_extents: [33, 16, 80],
        },
    ), // my_r_w
    (
        353,
        Sf1ShapeMetrics {
            sort_depth: -10,
            visual_extent: 80,
            coordinate_shift: 0,
            half_extents: [33, 16, 80],
        },
    ), // my_l_w
    (
        354,
        Sf1ShapeMetrics {
            sort_depth: -10,
            visual_extent: 80,
            coordinate_shift: 0,
            half_extents: [25, 13, 80],
        },
    ), // my_b_w
    (
        355,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 30,
            coordinate_shift: 1,
            half_extents: [20, 30, 18],
        },
    ), // up1_man
    (
        356,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 46,
            coordinate_shift: 0,
            half_extents: [36, 23, 35],
        },
    ), // f_dra_1
    (
        357,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 188,
            coordinate_shift: 2,
            half_extents: [136, 136, 144],
        },
    ), // fire
    (
        358,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 40,
            coordinate_shift: 2,
            half_extents: [40, 40, 40],
        },
    ), // smoke
    (
        359,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 16,
            coordinate_shift: 2,
            half_extents: [16, 16, 16],
        },
    ), // ssplash
    (
        360,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 32,
            coordinate_shift: 3,
            half_extents: [32, 32, 32],
        },
    ), // splash
    (
        361,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 8,
            coordinate_shift: 1,
            half_extents: [8, 8, 8],
        },
    ), // pexplod
    (
        362,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 20,
            coordinate_shift: 1,
            half_extents: [20, 20, 20],
        },
    ), // boostshape
    (
        363,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 40,
            coordinate_shift: 2,
            half_extents: [40, 40, 40],
        },
    ), // firebreath
    (
        364,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 80,
            coordinate_shift: 3,
            half_extents: [80, 80, 80],
        },
    ), // lsmoke
    (
        365,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 320,
            coordinate_shift: 5,
            half_extents: [320, 320, 320],
        },
    ), // folsmoke
    (
        366,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 400,
            coordinate_shift: 2,
            half_extents: [400, 400, 400],
        },
    ), // androsshole
    (
        367,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 16,
            coordinate_shift: 2,
            half_extents: [16, 16, 16],
        },
    ), // spexplod
    (
        368,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 80,
            coordinate_shift: 0,
            half_extents: [36, 14, 80],
        },
    ), // myship_r
    (
        369,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 80,
            coordinate_shift: 0,
            half_extents: [36, 14, 80],
        },
    ), // myship_l
    (
        370,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 80,
            coordinate_shift: 0,
            half_extents: [20, 14, 80],
        },
    ), // myship_b
    (
        371,
        Sf1ShapeMetrics {
            sort_depth: 3200,
            visual_extent: 0,
            coordinate_shift: 5,
            half_extents: [0, 0, 3200],
        },
    ), // my_up
    (
        372,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 80,
            coordinate_shift: 0,
            half_extents: [36, 14, 80],
        },
    ), // bmyship_4
    (
        373,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 80,
            coordinate_shift: 0,
            half_extents: [36, 14, 80],
        },
    ), // bmyship_r
    (
        374,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 80,
            coordinate_shift: 0,
            half_extents: [36, 14, 80],
        },
    ), // bmyship_l
    (
        375,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 80,
            coordinate_shift: 0,
            half_extents: [20, 14, 80],
        },
    ), // bmyship_b
    (
        376,
        Sf1ShapeMetrics {
            sort_depth: -1280,
            visual_extent: 1280,
            coordinate_shift: 4,
            half_extents: [576, 224, 1280],
        },
    ), // myzoom_4
    (
        377,
        Sf1ShapeMetrics {
            sort_depth: -1280,
            visual_extent: 1280,
            coordinate_shift: 4,
            half_extents: [576, 224, 1280],
        },
    ), // myzoom_r
    (
        378,
        Sf1ShapeMetrics {
            sort_depth: -1280,
            visual_extent: 1280,
            coordinate_shift: 4,
            half_extents: [576, 224, 1280],
        },
    ), // myzoom_l
    (
        379,
        Sf1ShapeMetrics {
            sort_depth: -1280,
            visual_extent: 1280,
            coordinate_shift: 4,
            half_extents: [320, 224, 1280],
        },
    ), // myzoom_b
    (
        380,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 22,
            coordinate_shift: 0,
            half_extents: [20, 20, 0],
        },
    ), // line
    (
        381,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 128,
            coordinate_shift: 1,
            half_extents: [88, 86, 96],
        },
    ), // boss_d_0
    (
        382,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 82,
            coordinate_shift: 1,
            half_extents: [40, 40, 60],
        },
    ), // boss_d_2
    (
        383,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 50,
            coordinate_shift: 1,
            half_extents: [160, 160, 160],
        },
    ), // neck
    (
        384,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 70,
            coordinate_shift: 1,
            half_extents: [60, 70, 52],
        },
    ), // grabber
    (
        385,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 112,
            coordinate_shift: 4,
            half_extents: [112, 112, 112],
        },
    ), // grabber2
    (
        386,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 48,
            coordinate_shift: 3,
            half_extents: [48, 48, 48],
        },
    ), // egg
    (
        387,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 372,
            coordinate_shift: 2,
            half_extents: [284, 284, 192],
        },
    ), // boss_d_8
    (
        388,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 372,
            coordinate_shift: 2,
            half_extents: [284, 284, 192],
        },
    ), // boss_d_9
    (
        389,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 40,
            coordinate_shift: 1,
            half_extents: [30, 40, 30],
        },
    ), // boss_d_6
    (
        390,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 42,
            coordinate_shift: 1,
            half_extents: [30, 40, 30],
        },
    ), // boss_d_7
    (
        391,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 108,
            coordinate_shift: 1,
            half_extents: [42, 36, 94],
        },
    ), // boss_9_0
    (
        392,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 128,
            coordinate_shift: 0,
            half_extents: [38, 117, 36],
        },
    ), // barrier
    (
        393,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 59,
            coordinate_shift: 0,
            half_extents: [30, 50, 5],
        },
    ), // fireface_b
    (
        394,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 336,
            coordinate_shift: 2,
            half_extents: [200, 180, 200],
        },
    ), // boss_a_3
    (
        395,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 552,
            coordinate_shift: 3,
            half_extents: [480, 176, 200],
        },
    ), // boss_a_4
    (
        396,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 552,
            coordinate_shift: 3,
            half_extents: [480, 176, 200],
        },
    ), // boss_a_5
    (
        397,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 204,
            coordinate_shift: 2,
            half_extents: [88, 176, 120],
        },
    ), // boss_b_l
    (
        398,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 204,
            coordinate_shift: 2,
            half_extents: [88, 176, 120],
        },
    ), // boss_b_r
    (
        399,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 268,
            coordinate_shift: 2,
            half_extents: [180, 136, 144],
        },
    ), // boss_b_h
    (
        400,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 236,
            coordinate_shift: 2,
            half_extents: [40, 120, 220],
        },
    ), // round0p
    (
        401,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 56,
            coordinate_shift: 0,
            half_extents: [36, 14, 40],
        },
    ), // ripair_w
    (
        402,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 40,
            coordinate_shift: 2,
            half_extents: [40, 40, 40],
        },
    ), // fireball
    (
        403,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 72,
            coordinate_shift: 1,
            half_extents: [24, 30, 60],
        },
    ), // missile
    (
        404,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 80,
            coordinate_shift: 3,
            half_extents: [80, 80, 240],
        },
    ), // ironball
    (
        405,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 32,
            coordinate_shift: 3,
            half_extents: [32, 32, 32],
        },
    ), // bouncyball
    (
        406,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 16,
            coordinate_shift: 2,
            half_extents: [40, 40, 40],
        },
    ), // shelpball
    (
        407,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 32,
            coordinate_shift: 3,
            half_extents: [32, 32, 32],
        },
    ), // nuke
    (
        408,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 176,
            coordinate_shift: 3,
            half_extents: [160, 160, 0],
        },
    ), // hyper
    (
        409,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 116,
            coordinate_shift: 2,
            half_extents: [80, 80, 20],
        },
    ), // hou_3
    (
        410,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 125,
            coordinate_shift: 0,
            half_extents: [70, 28, 100],
        },
    ), // my_demobs
    (
        411,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 125,
            coordinate_shift: 0,
            half_extents: [70, 28, 100],
        },
    ), // my_demos
    (
        412,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 90,
            coordinate_shift: 1,
            half_extents: [40, 60, 44],
        },
    ), // big_m
    (
        413,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 82,
            coordinate_shift: 1,
            half_extents: [60, 40, 80],
        },
    ), // boss_f_b
    (
        414,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 452,
            coordinate_shift: 2,
            half_extents: [200, 376, 132],
        },
    ), // walker_r
    (
        415,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 16,
            coordinate_shift: 2,
            half_extents: [64, 40, 120],
        },
    ), // playerbeam
    (
        416,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 32,
            coordinate_shift: 3,
            half_extents: [32, 32, 32],
        },
    ), // ovalbeam
    (
        417,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 120,
            coordinate_shift: 1,
            half_extents: [86, 100, 110],
        },
    ), // c_miss
    (
        418,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 25,
            coordinate_shift: 0,
            half_extents: [20, 25, 20],
        },
    ), // zaco_0
    (
        419,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 29,
            coordinate_shift: 0,
            half_extents: [25, 11, 15],
        },
    ), // zaco_7p
    (
        420,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 348,
            coordinate_shift: 2,
            half_extents: [80, 348, 80],
        },
    ), // robot_0
    (
        421,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 416,
            coordinate_shift: 3,
            half_extents: [240, 160, 360],
        },
    ), // boss_7_0
    (
        422,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 472,
            coordinate_shift: 3,
            half_extents: [160, 240, 440],
        },
    ), // boss_7_1o
    (
        423,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 360,
            coordinate_shift: 3,
            half_extents: [80, 160, 320],
        },
    ), // boss_7_2
    (
        424,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 416,
            coordinate_shift: 3,
            half_extents: [280, 280, 360],
        },
    ), // boss_7_3
    (
        425,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 440,
            coordinate_shift: 3,
            half_extents: [280, 328, 360],
        },
    ), // boss_7_4
    (
        426,
        Sf1ShapeMetrics {
            sort_depth: -120,
            visual_extent: 280,
            coordinate_shift: 2,
            half_extents: [228, 264, 100],
        },
    ), // boss_a_6
    (
        427,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 36,
            coordinate_shift: 2,
            half_extents: [40, 40, 40],
        },
    ), // boss_f_8
    (
        428,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 36,
            coordinate_shift: 2,
            half_extents: [40, 40, 40],
        },
    ), // boss_f_9
    (
        429,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 28,
            coordinate_shift: 2,
            half_extents: [16, 8, 20],
        },
    ), // boss_f_8a
    (
        430,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 28,
            coordinate_shift: 2,
            half_extents: [16, 8, 20],
        },
    ), // boss_f_9a
    (
        431,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 1120,
            coordinate_shift: 4,
            half_extents: [480, 960, 400],
        },
    ), // face_0
    (
        432,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 400,
            coordinate_shift: 2,
            half_extents: [344, 396, 336],
        },
    ), // boss_0_0
    (
        433,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 400,
            coordinate_shift: 2,
            half_extents: [396, 396, 336],
        },
    ), // boss_0_0a
    (
        434,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 120,
            coordinate_shift: 2,
            half_extents: [120, 120, 120],
        },
    ), // boss_0_2
    (
        435,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 132,
            coordinate_shift: 1,
            half_extents: [118, 130, 40],
        },
    ), // boss_0_3
    (
        436,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 420,
            coordinate_shift: 2,
            half_extents: [140, 160, 80],
        },
    ), // boss_1_0
    (
        437,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 84,
            coordinate_shift: 2,
            half_extents: [40, 40, 40],
        },
    ), // boss_1_1
    (
        438,
        Sf1ShapeMetrics {
            sort_depth: -400,
            visual_extent: 40,
            coordinate_shift: 2,
            half_extents: [40, 40, 40],
        },
    ), // amoeba1
    (
        439,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 480,
            coordinate_shift: 2,
            half_extents: [480, 480, 48],
        },
    ), // rpillar3
    (
        440,
        Sf1ShapeMetrics {
            sort_depth: 320,
            visual_extent: 2144,
            coordinate_shift: 5,
            half_extents: [1184, 352, 1888],
        },
    ), // deboss_0
    (
        441,
        Sf1ShapeMetrics {
            sort_depth: 320,
            visual_extent: 2240,
            coordinate_shift: 5,
            half_extents: [1344, 704, 1920],
        },
    ), // deboss_2
    (
        442,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 212,
            coordinate_shift: 2,
            half_extents: [72, 100, 72],
        },
    ), // flower
    (
        443,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 176,
            coordinate_shift: 1,
            half_extents: [36, 58, 172],
        },
    ), // big_bird
    (
        444,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 85,
            coordinate_shift: 0,
            half_extents: [60, 60, 20],
        },
    ), // leaf
    (
        445,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 160,
            coordinate_shift: 2,
            half_extents: [284, 196, 100],
        },
    ), // walk_4_l
    (
        446,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 160,
            coordinate_shift: 2,
            half_extents: [284, 196, 100],
        },
    ), // walk_4_r
    (
        447,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 72,
            coordinate_shift: 1,
            half_extents: [64, 50, 64],
        },
    ), // tow_1
    (
        448,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 240,
            coordinate_shift: 2,
            half_extents: [100, 228, 32],
        },
    ), // slot_1
    (
        449,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 56,
            coordinate_shift: 2,
            half_extents: [40, 40, 40],
        },
    ), // slot_2
    (
        450,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 22,
            coordinate_shift: 1,
            half_extents: [20, 20, 0],
        },
    ), // slot_3
    (
        451,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 56,
            coordinate_shift: 2,
            half_extents: [40, 40, 0],
        },
    ), // slot_4
    (
        452,
        Sf1ShapeMetrics {
            sort_depth: 400,
            visual_extent: 480,
            coordinate_shift: 2,
            half_extents: [480, 48, 48],
        },
    ), // pillar3_ns
    (
        453,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 44,
            coordinate_shift: 1,
            half_extents: [40, 40, 40],
        },
    ), // laserline
    (
        454,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 108,
            coordinate_shift: 1,
            half_extents: [60, 34, 90],
        },
    ), // warp_1
    (
        455,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 108,
            coordinate_shift: 1,
            half_extents: [60, 34, 90],
        },
    ), // warp_2
    (
        456,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 108,
            coordinate_shift: 1,
            half_extents: [60, 34, 90],
        },
    ), // warp_3
    (
        457,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 952,
            coordinate_shift: 3,
            half_extents: [880, 320, 88],
        },
    ), // wall_l
    (
        458,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 952,
            coordinate_shift: 3,
            half_extents: [880, 320, 88],
        },
    ), // wall_r
    (
        459,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 116,
            coordinate_shift: 0,
            half_extents: [50, 50, 100],
        },
    ), // iris_1
    (
        460,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 46,
            coordinate_shift: 0,
            half_extents: [20, 40, 20],
        },
    ), // stalk_1
    (
        461,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 32,
            coordinate_shift: 3,
            half_extents: [32, 32, 32],
        },
    ), // explosion
    (
        462,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 64,
            coordinate_shift: 4,
            half_extents: [64, 64, 64],
        },
    ), // explosion2
    (
        463,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 128,
            coordinate_shift: 5,
            half_extents: [128, 128, 128],
        },
    ), // explosion3
    (
        464,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 256,
            coordinate_shift: 6,
            half_extents: [256, 256, 256],
        },
    ), // explosion4
    (
        465,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 45,
            coordinate_shift: 0,
            half_extents: [27, 20, 35],
        },
    ), // expl_4
    (
        466,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 30,
            coordinate_shift: 0,
            half_extents: [19, 20, 29],
        },
    ), // expl_6
    (
        467,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 35,
            coordinate_shift: 0,
            half_extents: [17, 20, 32],
        },
    ), // expl_8
    (
        468,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 432,
            coordinate_shift: 2,
            half_extents: [384, 316, 272],
        },
    ), // boss_b_6
    (
        469,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 520,
            coordinate_shift: 2,
            half_extents: [80, 40, 80],
        },
    ), // boss_b_7
    (
        470,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 176,
            coordinate_shift: 3,
            half_extents: [160, 160, 0],
        },
    ), // hyper2
    (
        471,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 176,
            coordinate_shift: 3,
            half_extents: [160, 160, 0],
        },
    ), // hyper3
    (
        472,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 176,
            coordinate_shift: 3,
            half_extents: [160, 160, 0],
        },
    ), // hyper4
    (
        473,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 160,
            coordinate_shift: 2,
            half_extents: [64, 20, 148],
        },
    ), // bazz_1p
    (
        474,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 148,
            coordinate_shift: 2,
            half_extents: [28, 100, 112],
        },
    ), // bazz_1q
    (
        475,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 140,
            coordinate_shift: 2,
            half_extents: [40, 100, 124],
        },
    ), // bazooka1
    (
        476,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 112,
            coordinate_shift: 2,
            half_extents: [104, 60, 40],
        },
    ), // bazooka2
    (
        477,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 372,
            coordinate_shift: 2,
            half_extents: [200, 376, 120],
        },
    ), // walker_l
    (
        478,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 396,
            coordinate_shift: 2,
            half_extents: [8, 8, 120],
        },
    ), // elaser2a
    (
        479,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 64,
            coordinate_shift: 4,
            half_extents: [64, 64, 64],
        },
    ), // lflash_0
    (
        480,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 32,
            coordinate_shift: 3,
            half_extents: [32, 32, 32],
        },
    ), // mflash_0
    (
        481,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 16,
            coordinate_shift: 2,
            half_extents: [16, 16, 16],
        },
    ), // sflash_0
    (
        482,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 86,
            coordinate_shift: 1,
            half_extents: [80, 80, 10],
        },
    ), // training
    (
        508,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 512,
            coordinate_shift: 3,
            half_extents: [120, 120, 480],
        },
    ), // op_0
    (
        509,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 688,
            coordinate_shift: 3,
            half_extents: [344, 504, 480],
        },
    ), // op_1
    (
        510,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 512,
            coordinate_shift: 3,
            half_extents: [120, 120, 480],
        },
    ), // op_2
    (
        511,
        Sf1ShapeMetrics {
            sort_depth: 0,
            visual_extent: 396,
            coordinate_shift: 2,
            half_extents: [32, 20, 120],
        },
    ), // elaser2
];

pub fn sf1_shape_metrics(shape_id: u16) -> Option<Sf1ShapeMetrics> {
    SF1_SHAPE_METRICS
        .binary_search_by_key(&shape_id, |&(id, _)| id)
        .ok()
        .map(|index| SF1_SHAPE_METRICS[index].1)
}
