//! Scripted-input trace parity for the sf-strat player lane against the C
//! oracle.
//!
//! NOTE: the fixture intentionally DIVERGES from the frozen C oracle in two
//! places that fix player-facing bugs present in the C port:
//!   * barrel roll now triggers on the L/R shoulder buttons only (the C port
//!     wrongly also rolled on dpad LEFT/RIGHT steering), so the flight scenario
//!     no longer rolls at the LEFT/RIGHT press ticks;
//!   * player laser/beam bolts spawn with a visible shape (11) instead of the
//!     C stub's shape 0 + ASF_INVISIBLE, so laser objects read `slot:11:...`.
//! Re-baseline with `SF_BLESS_SP_PLAYER=<abs fixture path>` (see the test body).
//!
//! Fixture: `tests/fixtures/sp_player_trace.txt`, generated by a scratchpad
//! harness (`sp_harness/sp_player_trace.c`) compiling the real
//! `strat_player.c` + `strat_common.c` + `obj.c` + `game_vars.c` with pad/
//! RNG/sound stubs. Six scenarios:
//!   1. flight  — playermove/boost/brake/fire/barrel-roll, scripted body
//!      hit at t=150 and lethal hit at t=165 (hitflash RNG, death chain,
//!      lives decrement)
//!   2. opening — playeropening_Istrat + viewopening camera chain
//!   3. exitbase — hangar wait/Go/Follow launch + friendstart3 wingman
//!   4. nucleus — playerEscapeNucleus chain
//!   5. bridge  — playerclearbridge chain (incl. dupplayer + resumed fire)
//!   6. shipintro — MAP1_1A flyby object
//! Every tick both sides dump the player alien, the shared globals, every
//! active alien (slot order) and the sounds triggered; the texts must be
//! byte-identical.
//!
//! Regenerate (from the repo root, harness sources in the session
//! scratchpad `sp_harness/`):
//!   gcc -O2 -Isrc -o sp_player_trace sp_player_trace.c \
//!       src/strat/strat_player.c src/strat/strat_common.c \
//!       src/game/obj.c src/game/game_vars.c sp_stubs.c -lm && \
//!   ./sp_player_trace && cp sp_player_trace.txt \
//!       rust/sf-strat/tests/fixtures/

use sf_game::alien::{ASF_COLLIDE, NUMBER_AL};
use sf_game::vars::{GameVars, GF_STRATDONE2, SPACE_MODE, WATER_MODE};
use sf_game::{Game, Hooks};
use sf_strat::common::{strat_make_obj, sv, StratRam};
use sf_strat::player::{
    strat_player_clear_bridge_init, strat_player_escape_nucleus_init, strat_player_exit_base,
    strat_player_opening_init, strat_ship_intro_init, strat_spawn_player,
};
use std::cell::RefCell;
use std::fmt::Write;
use std::rc::Rc;

// Pad bits (sf-core pad module, C sf_rtl.h PAD_*).
use sf_core::pad;

const PML_ALL: u8 = 255;

struct RecHooks(Rc<RefCell<Vec<u8>>>);
impl Hooks for RecHooks {
    fn play_se(&mut self, sound_id: u8) {
        self.0.borrow_mut().push(sound_id);
    }
    fn trig_se(&mut self, sound_id: u8) {
        self.0.borrow_mut().push(sound_id);
    }
}

/// Mirror of the C harness `reset_state()`: fresh pool + zeroed globals +
/// the explicit baseline both harnesses share.
fn new_game(sounds: &Rc<RefCell<Vec<u8>>>) -> Game {
    let mut g = Game::with_hooks(Box::new(RecHooks(sounds.clone())));
    g.vars = GameVars::default(); // C BSS zero state
    g.vars.game_mode = SPACE_MODE;
    g.vars.minpmove_y = -210;
    let v = &mut g.vars;
    v.set_sv_i16(sv::MINPMOVEX, -240);
    v.set_sv_i16(sv::MAXPMOVEX, 240);
    v.set_sv_i16(sv::MAXPMOVEY, -20);
    v.set_sv_i16(sv::MINMMOVEX, -240);
    v.set_sv_i16(sv::MAXMMOVEX, 240);
    v.set_sv_i16(sv::MAXMMOVEY, 0);
    v.set_sv_i16(sv::MINPWMOVEY, -210);
    v.set_sv_i16(sv::MAXPWMOVEY, 0);
    v.set_sv_u8(sv::PMOVELIMITAND, PML_ALL);
    v.set_sv_i8(sv::STAYBLACK, -1);
    v.set_sv_u8(sv::LIVES, 3);
    v.set_sv_u16(sv::RNDVAL, 0x1234);
    sounds.borrow_mut().clear();
    g
}

fn dump(g: &Game, t: i32, sounds: &Rc<RefCell<Vec<u8>>>, out: &mut String) {
    let p = &g.objs.aliens[0];
    let v = &g.vars;
    write!(
        out,
        "T{} P {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {}",
        t,
        p.worldx,
        p.worldy,
        p.worldz,
        p.rotx,
        p.roty,
        p.rotz,
        p.vel,
        p.vx,
        p.vy,
        p.vz,
        p.sflags,
        p.sflags2,
        p.sbyte1,
        p.sbyte2,
        p.sbyte3,
        p.sbyte4,
        p.hp,
        p.shape,
        p.snd1,
        p.count
    )
    .unwrap();
    write!(
        out,
        " G {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {}",
        v.sv_i16(sv::PLAYER_SPEED),
        v.sv_u8(sv::PLAYER_TOSPEED),
        v.sv_u8(sv::PLAYER_MEDSPEED),
        v.sv_i16(sv::PVIEWPOSX),
        v.sv_i16(sv::PVIEWPOSY),
        v.sv_i16(sv::PVIEWPOSZ),
        v.pviewvelz,
        v.sv_i16(sv::VIEWPOSX),
        v.sv_i16(sv::VIEWPOSY),
        v.sv_i16(sv::VIEWPOSZ),
        v.sv_u8(sv::VIEWTYPE),
        v.sv_u8(sv::ARROWS),
        v.sv_u8(sv::FIRECNT),
        v.sv_u8(sv::FIREDELAY),
        v.sv_u8(sv::SPECIALDELAY),
        v.sv_u16(sv::SPECWEPCNT),
        v.sv_u8(sv::NUMPLASERS),
        v.sv_i16(sv::HUDROT),
        v.sv_u8(sv::PLAYER_ZTILT),
        v.sv_u8(sv::PLAYER_ROLLZOFF),
        v.sv_u8(sv::PLAYER_ROLLZVEL),
        v.sv_u8(sv::PLAYER_ROLLDELAY)
    )
    .unwrap();
    write!(
        out,
        " F {} {} {} {} {} {} {} {} {} {} {} {} {} {}",
        v.gameflags,
        v.pshipflags,
        v.pshipflags2,
        v.pshipflags3,
        v.pstratflags,
        v.sv_u8(sv::PSVAR_BYTE1),
        v.sv_u8(sv::PSVAR_BYTE2),
        v.sv_u8(sv::PSVAR_BYTE3),
        v.sv_u8(sv::LIVES),
        v.stagecnt,
        v.sv_i16(sv::BOOSTOBJ),
        v.sv_u8(sv::PNUMHITS),
        v.sv_u8(sv::SCREENFLASHCNT),
        v.sv_u8(sv::NOMAXBG2YSCROLL)
    )
    .unwrap();
    write!(
        out,
        " V {} {} {} {} {} {} {} {}",
        v.sv_i16(sv::SVAR_WORD1),
        v.sv_i16(sv::SVAR_WORD2),
        v.sv_i16(sv::SVAR_WORD3),
        v.sv_i16(sv::OUTVX),
        v.sv_i16(sv::OUTVY),
        v.sv_i16(sv::OUTDIST),
        v.sv_i16(sv::BGSSCROLLZ),
        v.sv_i16(sv::BG2YSCROLL)
    )
    .unwrap();
    write!(
        out,
        " R {} {} {} {}",
        v.sv_u8(sv::VIEWSHAKEX),
        v.sv_u8(sv::VIEWSHAKEY),
        v.sv_u8(sv::VIEWSHAKEZ),
        v.sv_u16(sv::RNDVAL)
    )
    .unwrap();
    out.push_str(" A");
    for i in 0..NUMBER_AL {
        let al = &g.objs.aliens[i];
        if !al.active {
            continue;
        }
        write!(
            out,
            " {}:{}:{}:{}:{}:{}:{}:{}:{}:{}",
            i, al.shape, al.worldx, al.worldy, al.worldz, al.rotx, al.roty, al.rotz, al.hp,
            al.count
        )
        .unwrap();
    }
    out.push_str(" S");
    for s in sounds.borrow_mut().drain(..) {
        write!(out, " {:02x}", s).unwrap();
    }
    out.push('\n');
}

fn tick(g: &mut Game, t: i32, padv: u16, sounds: &Rc<RefCell<Vec<u8>>>, out: &mut String) {
    // C harness: g_pad1_prev = g_pad1; g_pad1 = pad; g_pad1_new derived.
    let prev = g.vars.pad1;
    g.vars.lastcont0 = (prev >> 8) as u8;
    g.vars.lastcontl0 = (prev & 0xFF) as u8;
    g.vars.pad1 = padv;
    g.run_strategies();
    dump(g, t, sounds, out);
}

fn flight_pad(t: i32) -> u16 {
    match t {
        10..=24 => pad::UP,
        25..=39 => pad::LEFT,
        40..=59 => pad::RIGHT | pad::DOWN,
        60..=69 => pad::X,
        70..=89 => pad::Y,
        90..=99 => pad::B,
        100..=104 => pad::A,
        105..=139 => pad::Y | pad::RIGHT,
        140..=146 => pad::TLEFT,
        _ => 0,
    }
}

fn generate() -> String {
    let sounds: Rc<RefCell<Vec<u8>>> = Rc::new(RefCell::new(Vec::new()));
    let mut out = String::new();

    // ---- Scenario 1: flight ----
    out.push_str("== flight ==\n");
    let mut g = new_game(&sounds);
    let p = strat_spawn_player(&mut g).unwrap();
    for t in 0..230 {
        if t == 150 {
            g.objs.aliens[p as usize].sflags |= ASF_COLLIDE;
        }
        if t == 165 {
            g.objs.aliens[p as usize].hp = 0;
        }
        tick(&mut g, t, flight_pad(t), &sounds, &mut out);
    }

    // ---- Scenario 2: opening ----
    out.push_str("== opening ==\n");
    let mut g = new_game(&sounds);
    let p = strat_spawn_player(&mut g).unwrap();
    strat_player_opening_init(&mut g, p);
    for t in 0..260 {
        tick(&mut g, t, 0, &sounds, &mut out);
    }

    // ---- Scenario 3: exitbase ----
    out.push_str("== exitbase ==\n");
    let mut g = new_game(&sounds);
    let p = strat_spawn_player(&mut g).unwrap();
    g.vars.game_mode = WATER_MODE;
    strat_player_exit_base(&mut g, p);
    for t in 0..220 {
        tick(&mut g, t, 0, &sounds, &mut out);
    }

    // ---- Scenario 4: nucleus ----
    out.push_str("== nucleus ==\n");
    let mut g = new_game(&sounds);
    let p = strat_spawn_player(&mut g).unwrap();
    strat_player_escape_nucleus_init(&mut g, p);
    for t in 0..100 {
        tick(&mut g, t, 0, &sounds, &mut out);
    }

    // ---- Scenario 5: bridge ----
    out.push_str("== bridge ==\n");
    let mut g = new_game(&sounds);
    let p = strat_spawn_player(&mut g).unwrap();
    strat_player_clear_bridge_init(&mut g, p);
    for t in 0..220 {
        let padv = if (180..200).contains(&t) { pad::Y } else { 0 };
        tick(&mut g, t, padv, &sounds, &mut out);
    }

    // ---- Scenario 6: shipintro ----
    out.push_str("== shipintro ==\n");
    let mut g = new_game(&sounds);
    let s = strat_make_obj(&mut g, 2).unwrap(); // SHAPE_ARWING
    {
        let al = &mut g.objs.aliens[s as usize];
        al.worldx = 0;
        al.worldy = -20;
        al.worldz = 300;
        al.sword1 = 1;
        al.sbyte1 = 10;
        al.sbyte2 = 3;
    }
    strat_ship_intro_init(&mut g, s);
    for t in 0..120 {
        if t == 20 {
            g.vars.gameflags |= GF_STRATDONE2;
        }
        tick(&mut g, t, 0, &sounds, &mut out);
    }

    out
}

#[test]
fn player_trace_matches_c_oracle() {
    // Bless mode: `SF_BLESS_SP_PLAYER=<abs path>` rewrites the fixture from the
    // current (corrected) Rust output and returns. Used to re-baseline after an
    // intentional, documented divergence from the frozen C oracle (the C port's
    // barrel-roll trigger mask and the invisible-laser stub are both bugs the
    // Rust build fixes).
    if let Ok(path) = std::env::var("SF_BLESS_SP_PLAYER") {
        std::fs::write(&path, generate()).unwrap();
        eprintln!("blessed {path}");
        return;
    }

    let fixture = include_str!("fixtures/sp_player_trace.txt");
    let ours = generate();

    let mut mismatches = 0;
    for (n, (c_line, r_line)) in fixture.lines().zip(ours.lines()).enumerate() {
        if c_line != r_line {
            mismatches += 1;
            if mismatches <= 10 {
                eprintln!("line {}:\n  C    `{}`\n  Rust `{}`", n + 1, c_line, r_line);
            }
        }
    }
    assert_eq!(
        fixture.lines().count(),
        ours.lines().count(),
        "line count mismatch"
    );
    assert_eq!(mismatches, 0, "{} mismatched lines", mismatches);
}
