//! Generated by `tools/extract_sf1_paths.py`; do not hand-edit.
//!
//! This file contains only symbol-derived metadata. The assembled bytecode
//! remains in the user-owned, gitignored `data/path_catalog.bin`.

use crate::builder::PATH_MISSING_OFFSET;
use crate::ids::*;
use crate::literals::InlineIps;

pub const ROM_PATH_CATALOG_SIZE: usize = 0x4A0B;
pub const ROM_PATH_CPU_BASE: usize = 0xA420;
pub const ROM_PATH_CPU_END: usize = 0xEE2B;
pub const ROM_PATH_SECTION_FNV1A: u32 = 0x2D09BAC2;
pub const ROM_PATH_MAPPED_IDS: usize = 168;
pub const ROM_DINTRO1_LOOP_IP: u16 = 0x453B;
pub const ROM_DINTRO1_EXIT_IP: u16 = 0x453E;

pub fn offsets() -> Vec<u16> {
    let mut offsets = vec![PATH_MISSING_OFFSET; PATH_DATA_COUNT_LITERAL as usize];
    offsets[PATH_ID_E_GATE as usize] = 0x0000;
    offsets[PATH_ID_E_FLOWER as usize] = 0x0003;
    offsets[PATH_ID_E_FLOPEN as usize] = 0x0014;
    offsets[PATH_ID_BIRD_METEOR as usize] = 0x0176;
    offsets[PATH_ID_DAMY_EXP as usize] = 0x01B2;
    offsets[PATH_ID_DAMY_EXP2 as usize] = 0x01CF;
    offsets[PATH_ID_E_EGG as usize] = 0x01D0;
    offsets[PATH_ID_E_BIG_BIRD as usize] = 0x01F4;
    offsets[PATH_ID_CHIBIR_2 as usize] = 0x02C1;
    offsets[PATH_ID_CHIBIR_1 as usize] = 0x02C7;
    offsets[PATH_ID_PINITA_B as usize] = 0x02EF;
    offsets[PATH_ID_PINITA_A as usize] = 0x02F6;
    offsets[PATH_ID_E_PILL as usize] = 0x0346;
    offsets[PATH_ID_ITACHI_B as usize] = 0x034C;
    offsets[PATH_ID_ITACHI_A as usize] = 0x035F;
    offsets[PATH_ID_PONPON as usize] = 0x0BDF;
    offsets[PATH_ID_MATEMSG as usize] = 0x1DBD;
    offsets[PATH_ID_FROG1_1 as usize] = 0x341F;
    offsets[PATH_ID_FALCO_LV1 as usize] = 0x3611;
    offsets[PATH_ID_FROG_LV1 as usize] = 0x3622;
    offsets[PATH_ID_TOW_0 as usize] = 0x3AEA;
    offsets[PATH_ID_TOW_1 as usize] = 0x3B21;
    offsets[PATH_ID_DSMOKE2 as usize] = 0x3B57;
    offsets[PATH_ID_DSMOKE3 as usize] = 0x3B59;
    offsets[PATH_ID_DSMOKE as usize] = 0x3B5B;
    offsets[PATH_ID_ROBOT as usize] = 0x4461;
    offsets[PATH_ID_ROBOTSWITHLOG as usize] = 0x437B;
    offsets[PATH_ID_ROBOTWITHLOG2 as usize] = 0x43C5;
    offsets[PATH_ID_CARRIEDLOG as usize] = 0x43DC;
    offsets[PATH_ID_ROBEXPLODE as usize] = 0x44C7;
    offsets[PATH_ID_KORORI as usize] = 0x0572;
    offsets[PATH_ID_CHASE8_1 as usize] = 0x2EBC;
    offsets[PATH_ID_CHASE8_2 as usize] = 0x2F88;
    offsets[PATH_ID_CHASE8_3 as usize] = 0x2FDC;
    offsets[PATH_ID_PATROL as usize] = 0x1FD8;
    offsets[PATH_ID_ROBOTWITHLOG as usize] = 0x4353;
    offsets[PATH_ID_CHASE6_1 as usize] = 0x2B3B;
    offsets[PATH_ID_CHASE6_2 as usize] = 0x2C64;
    offsets[PATH_ID_E_RABBIT as usize] = 0x354B;
    offsets[PATH_ID_E_FROG as usize] = 0x3550;
    offsets[PATH_ID_E_FALCON as usize] = 0x3555;
    offsets[PATH_ID_DUMMY as usize] = 0x4377;
    offsets[PATH_ID_E_UFO as usize] = 0x0B61;
    offsets[PATH_ID_ASTEMSG as usize] = 0x1DD2;
    offsets[PATH_ID_MES_MESSAGE as usize] = 0x1F1C;
    offsets[PATH_ID_CHASE7_1 as usize] = 0x2CE6;
    offsets[PATH_ID_CHASE7_2 as usize] = 0x2E26;
    offsets[PATH_ID_MY_BIRD as usize] = 0x42AD;
    offsets[PATH_ID_RING as usize] = 0x434F;
    offsets[PATH_ID_CHASE1_1 as usize] = 0x210F;
    offsets[PATH_ID_CHASE1_2 as usize] = 0x21C0;
    offsets[PATH_ID_E_ASTE as usize] = 0x03E6;
    offsets[PATH_ID_PYONTA as usize] = 0x048D;
    offsets[PATH_ID_CHASE4_1 as usize] = 0x27B2;
    offsets[PATH_ID_CHASE4_2 as usize] = 0x290A;
    offsets[PATH_ID_CHASE4_3 as usize] = 0x2997;
    offsets[PATH_ID_E_ASTE_B as usize] = 0x03EB;
    offsets[PATH_ID_E_BREASTE as usize] = 0x0413;
    offsets[PATH_ID_INSEKIKUN as usize] = 0x0418;
    offsets[PATH_ID_SCREW as usize] = 0x20BB;
    offsets[PATH_ID_DAMYSCR as usize] = 0x20FD;
    offsets[PATH_ID_PATRET_IRAB as usize] = 0x3013;
    offsets[PATH_ID_PATRET_IFRO as usize] = 0x3031;
    offsets[PATH_ID_PATRET_IFAL as usize] = 0x304F;
    offsets[PATH_ID_SEPTER_RAB as usize] = 0x332F;
    offsets[PATH_ID_SEPTER_FRO as usize] = 0x3334;
    offsets[PATH_ID_SEPTER_FAL as usize] = 0x3339;
    offsets[PATH_ID_FALCON3_1 as usize] = 0x33F9;
    offsets[PATH_ID_CHECK as usize] = 0x06D6;
    offsets[PATH_ID_AT_HBEAM as usize] = 0x0718;
    offsets[PATH_ID_EGU6 as usize] = 0x0EF5;
    offsets[PATH_ID_CHASE2_1 as usize] = 0x223D;
    offsets[PATH_ID_CHASE2_2 as usize] = 0x237B;
    offsets[PATH_ID_CHASE3_1 as usize] = 0x244E;
    offsets[PATH_ID_CHASE3_2 as usize] = 0x2656;
    offsets[PATH_ID_E_SHIELDR as usize] = 0x1334;
    offsets[PATH_ID_EGU6_IRAB as usize] = 0x30C0;
    offsets[PATH_ID_EGU6_IFRO as usize] = 0x30DE;
    offsets[PATH_ID_EGU6_IFAL as usize] = 0x30FC;
    offsets[PATH_ID_GAMEOVER as usize] = 0x475B;
    offsets[PATH_ID_THEENDT as usize] = 0x477B;
    offsets[PATH_ID_THEENDH as usize] = 0x4791;
    offsets[PATH_ID_THEENDE as usize] = 0x47AC;
    offsets[PATH_ID_THEENDE2 as usize] = 0x47C7;
    offsets[PATH_ID_THEENDN as usize] = 0x47E2;
    offsets[PATH_ID_THEENDD as usize] = 0x47FD;
    offsets[PATH_ID_FADEINTOTAL as usize] = 0x4823;
    offsets[PATH_ID_TOTAL as usize] = 0x4837;
    offsets[PATH_ID_TOTALN as usize] = 0x4852;
    offsets[PATH_ID_AVE as usize] = 0x486D;
    offsets[PATH_ID_AVEN as usize] = 0x4888;
    offsets[PATH_ID_STAGE1 as usize] = 0x48A3;
    offsets[PATH_ID_STAGE2 as usize] = 0x48D5;
    offsets[PATH_ID_STAGE3 as usize] = 0x4907;
    offsets[PATH_ID_STAGE4 as usize] = 0x4939;
    offsets[PATH_ID_STAGE5 as usize] = 0x496B;
    offsets[PATH_ID_STAGE6 as usize] = 0x499D;
    offsets[PATH_ID_STAGE7 as usize] = 0x49CF;
    offsets[PATH_ID_E_WHALE as usize] = 0x1540;
    offsets[PATH_ID_E_RAY_0 as usize] = 0x1415;
    offsets[PATH_ID_E_RAY_1 as usize] = 0x160B;
    offsets[PATH_ID_IKA_2 as usize] = 0x1783;
    offsets[PATH_ID_E_IKA as usize] = 0x16CD;
    offsets[PATH_ID_EGU1 as usize] = 0x0C86;
    offsets[PATH_ID_EGU3 as usize] = 0x0CFB;
    offsets[PATH_ID_AMEBMSG as usize] = 0x1E99;
    offsets[PATH_ID_BRAYMSG as usize] = 0x1E79;
    offsets[PATH_ID_CHASE5_1 as usize] = 0x29D7;
    offsets[PATH_ID_CHASE5_2 as usize] = 0x2A87;
    offsets[PATH_ID_CHASE5_3 as usize] = 0x2B04;
    offsets[PATH_ID_PATRET as usize] = 0x203B;
    offsets[PATH_ID_REM_WHALE as usize] = 0x15ED;
    offsets[PATH_ID_HANDMSG as usize] = 0x1E13;
    offsets[PATH_ID_EGU1_IFRO as usize] = 0x3272;
    offsets[PATH_ID_EGU1_IRAB as usize] = 0x3254;
    offsets[PATH_ID_EGU1_IFAL as usize] = 0x3290;
    offsets[PATH_ID_L_CLISLA as usize] = 0x17ED;
    offsets[PATH_ID_R_CLISLA as usize] = 0x194D;
    offsets[PATH_ID_MINI_CLI as usize] = 0x1929;
    offsets[PATH_ID_E_WALK_1 as usize] = 0x11FD;
    offsets[PATH_ID_EGU4 as usize] = 0x0DC9;
    offsets[PATH_ID_E_HELI as usize] = 0x1110;
    offsets[PATH_ID_E_TANK as usize] = 0x123C;
    offsets[PATH_ID_E_KANI_0 as usize] = 0x1AAE;
    offsets[PATH_ID_TENKI_ON as usize] = 0x0158;
    offsets[PATH_ID_TENKI_DM as usize] = 0x0154;
    offsets[PATH_ID_KANIHAHA as usize] = 0x1A0C;
    offsets[PATH_ID_EGU5 as usize] = 0x0E67;
    offsets[PATH_ID_MINICAS2 as usize] = 0x1058;
    offsets[PATH_ID_MINICAS0 as usize] = 0x101B;
    offsets[PATH_ID_KASTMSG as usize] = 0x1E3B;
    offsets[PATH_ID_AMEBMSG2 as usize] = 0x1EB7;
    offsets[PATH_ID_E_BEE as usize] = 0x0925;
    offsets[PATH_ID_TOMSET as usize] = 0x09DE;
    offsets[PATH_ID_TOMHAHA as usize] = 0x09C1;
    offsets[PATH_ID_E_FLYFISH as usize] = 0x08B5;
    offsets[PATH_ID_KAMOME as usize] = 0x0794;
    offsets[PATH_ID_DRAGONMSG as usize] = 0x1DF0;
    offsets[PATH_ID_PAPER_1B as usize] = 0x3911;
    offsets[PATH_ID_SLOTMACHINE as usize] = 0x3B92;
    offsets[PATH_ID_PATCOM as usize] = 0x207F;
    offsets[PATH_ID_TOTUMSG as usize] = 0x1EC8;
    offsets[PATH_ID_CALL_FOL as usize] = 0x05FF;
    offsets[PATH_ID_MES_ANDROSS1 as usize] = 0x1EFD;
    offsets[PATH_ID_MES_ANDROSS2 as usize] = 0x1EE8;
    offsets[PATH_ID_TRN_CK as usize] = 0x00F6;
    offsets[PATH_ID_TRN_RING as usize] = 0x0062;
    offsets[PATH_ID_TRN_RING2 as usize] = 0x0058;
    offsets[PATH_ID_HENTAI_FAL as usize] = 0x368E;
    offsets[PATH_ID_HENTAI_FRO as usize] = 0x3649;
    offsets[PATH_ID_HENTAI_RAB as usize] = 0x364E;
    offsets[PATH_ID_DSIDESLIP as usize] = 0x45DF;
    offsets[PATH_ID_DSTARFOX as usize] = 0x45FD;
    offsets[PATH_ID_DPRESENTED as usize] = 0x4645;
    offsets[PATH_ID_DNINTENDO as usize] = 0x4621;
    offsets[PATH_ID_E_SHAWERL as usize] = 0x1F23;
    offsets[PATH_ID_E_SHAWERR as usize] = 0x1F2C;
    offsets[PATH_ID_E_DOSUN as usize] = 0x12D8;
    offsets[PATH_ID_ITADOSUN as usize] = 0x1306;
    offsets[PATH_ID_E_KURURI as usize] = 0x12A8;
    offsets[PATH_ID_PCOINEXPLODE as usize] = 0x4291;
    offsets[PATH_ID_EXPLODEPARTICLES as usize] = 0x45BD;
    offsets[PATH_ID_KASTMSG2 as usize] = 0x1E5B;
    offsets[PATH_ID_DINTRO1 as usize] = 0x44FD;
    offsets[PATH_ID_MINICASTANET as usize] = 0x468C;
    offsets[PATH_ID_MINICASTANETLR as usize] = 0x46DF;
    offsets[PATH_ID_FOLOW as usize] = 0x0652;
    offsets[PATH_ID_E_KURURI2 as usize] = 0x12D1;
    offsets
}

pub const fn inline_ips() -> InlineIps {
    InlineIps {
        tow_0_set_expstrat: 0x3AF5,
        robexplode_nopolyexp: 0x44C8,
        dsmoke_init_colanim: 0x3B60,
        dsmoke_add_colanim: 0x3B70,
        pbooston_makeengine: 0x4732,
        pboostcode_updateengine: 0x4742,
        makepollen: 0x0026,
        e_big_bird_touch: 0x0297,
        dintro1_zoom_to_centre: 0x4504,
        dintro1_keep_distance: 0x455D,
        checkifend1: 0x48B8,
        checkifend2: 0x48EA,
        checkifend3: 0x491C,
        checkifend4: 0x494E,
        checkifend5: 0x4980,
        checkifend6: 0x49B2,
        checkifend7: 0x49E4,
    }
}

/// Generated native-action continuations. These replace runtime decoding of
/// the original inline instruction blobs.
pub const fn inline_continuations() -> [(u16, u16); 17] {
    [
        (0x3AF5, 0x3B0D),
        (0x44C8, 0x44D5),
        (0x3B60, 0x3B6E),
        (0x3B70, 0x3B90),
        (0x4732, 0x473D),
        (0x4742, 0x474D),
        (0x0026, 0x0031),
        (0x0297, 0x02C0),
        (0x4504, 0x453E),
        (0x455D, 0x456E),
        (0x48B8, 0x48CB),
        (0x48EA, 0x48FD),
        (0x491C, 0x492F),
        (0x494E, 0x4961),
        (0x4980, 0x4993),
        (0x49B2, 0x49C5),
        (0x49E4, 0x49F7),
    ]
}

/// Actual 24-bit strategy addresses emitted by P_SETSTRAT in the assembled
/// ROM, indexed by the canonical ISTRATS.ASM row.
pub const ROM_ISTRAT_ADDRS: [u32; 256] = [
    0x0BB53C, 0x0BADA5, 0x0BAFE1, 0x0BB292, 0x08F193, 0x08F19B, 0x08F1A3, 0x08F1AB, 0x21864D,
    0x218658, 0x218741, 0x08F165, 0x08F14D, 0x08F20E, 0x08F208, 0x068289, 0x0682D8, 0x068327,
    0x0680FE, 0x06814C, 0x06819A, 0x0685B7, 0x068607, 0x068657, 0x06848F, 0x0684F3, 0x068557,
    0x0687C7, 0x068826, 0x068885, 0x068A03, 0x068A56, 0x068AA9, 0x068F04, 0x068F57, 0x068FAA,
    0x068C19, 0x068CEC, 0x068DBF, 0x069111, 0x06916E, 0x0691CB, 0x0685C1, 0x068611, 0x068661,
    0x0BA231, 0x08E8B6, 0x099525, 0x08BE24, 0x08BF68, 0x08B697, 0x08CAC9, 0x0997D6, 0x08B7B9,
    0x08C2A5, 0x08CFE0, 0x09B255, 0x09AA4B, 0x09B26D, 0x08C0E1, 0x08CB0A, 0x08CCD3, 0x09959D,
    0x08B937, 0x08E332, 0x08EAD4, 0x08EBBA, 0x08E60A, 0x08816A, 0x08A37E, 0x089E17, 0x08A02D,
    0x0ACC05, 0x08D06D, 0x099104, 0x09916D, 0x099176, 0x098BC2, 0x098AA0, 0x08C76F, 0x08C850,
    0x079809, 0x0799B7, 0x079190, 0x079B03, 0x089B0D, 0x089CB9, 0x08D241, 0x08D40C, 0x08D852,
    0x08DB31, 0x08B196, 0x08B18C, 0x08AC83, 0x08B1C3, 0x08B1D3, 0x08B567, 0x08B531, 0x07CF70,
    0x0A8031, 0x08B16E, 0x0A8485, 0x0A8000, 0x218595, 0x2185BB, 0x2185B1, 0x04F687, 0x088BBA,
    0x08A5E2, 0x08A6D3, 0x08A291, 0x08A250, 0x08A8F0, 0x08AB2F, 0x07AAC5, 0x288000, 0x09B319,
    0x07B83C, 0x09C15C, 0x09C55E, 0x09C54B, 0x078000, 0x09D77B, 0x09CC5C, 0x08AE07, 0x09E124,
    0x0A878C, 0x0A9F5F, 0x0AA18F, 0x0AA4E7, 0x0AAF20, 0x0AB014, 0x0AB2FC, 0x0AB502, 0x0AB5F5,
    0x0AB694, 0x21862F, 0x0A8817, 0x0A862D, 0x04F91F, 0x04F9E0, 0x04F919, 0x04F890, 0x04EE35,
    0x09F727, 0x09F733, 0x09F74B, 0x09F73F, 0x09F75F, 0x09F757, 0x09F763, 0x078133, 0x0AB719,
    0x0AB71F, 0x0ABBF2, 0x0AB344, 0x04801E, 0x0ABF45, 0x0ABF4B, 0x0AC243, 0x0AC351, 0x0AC68F,
    0x0ABB89, 0x0ABB17, 0x0ACC4C, 0x0ACF2F, 0x0ACF73, 0x0ACFCB, 0x0AD181, 0x0AD249, 0x0AD40F,
    0x0AD443, 0x0AD4C8, 0x0AD55F, 0x08D54E, 0x08D5E8, 0x08DDE4, 0x0AD5EF, 0x0AD5E9, 0x0AD6FF,
    0x0A87C0, 0x0A88A8, 0x0A87A6, 0x0A896E, 0x0A8A80, 0x0A8AD0, 0x0A8CF8, 0x0A8F31, 0x0A9025,
    0x0A90E5, 0x06BC68, 0x0AD763, 0x2185DB, 0x0ADABE, 0x0ADD00, 0x0ADDFE, 0x0999A5, 0x099993,
    0x0AE082, 0x0AE129, 0x0AE22B, 0x0AE387, 0x0AE470, 0x099B33, 0x099A74, 0x099A6C, 0x0AE677,
    0x0AE8AF, 0x0AE9E0, 0x2185FB, 0x078503, 0x07852C, 0x0785B9, 0x0AE5AD, 0x0AE5ED, 0x07DEA1,
    0x06959E, 0x069604, 0x069769, 0x069AB9, 0x21873A, 0x069E3E, 0x06A04A, 0x069CC2, 0x21A4F0,
    0x21859B, 0x099682, 0x0AEED6, 0x04800A, 0x2099D1, 0x08F1FF, 0x0AF0E0, 0x0AF171, 0x209A94,
    0x209AD7, 0x0AF229, 0x06AB2A, 0x209AEC, 0x07866F, 0x078C9F, 0x09F852, 0x1FFAD4, 0x048000,
    0x0A920D, 0x0A9212, 0x0A9217, 0x000000, 0x000000, 0x000000, 0x000000, 0x000000, 0x000000,
    0x000000, 0x000000, 0x000000, 0x000000,
];

pub const ROM_GATE3_ISTRAT_ADDR: u32 = 0x0AE80F;
pub const ROM_TOW0EXPLODE_ISTRAT_ADDR: u32 = 0x06BD99;
