//! Black Hole shape-shuffling path object.
//!
//! Its behavior is intentionally small: select one entry from the original
//! 32-shape disguise catalog, then run the shared `damyscr` path program.

use sf_game::alien::StratId;
use sf_game::game::{Game, StrategyFn};
use sf_game::world::World;
use sf_path::ids::PATH_ID_DAMYSCR;

use crate::common::sf_random;
use crate::path_adapter::{initialize_path_object, set_object_path};

/// Typed native dispatch identity used by Black Hole mother-map entries.
pub const STRATEGY_DAMYSCR: sf_map::consts::DirectStrategy =
    sf_map::consts::DirectStrategy::Damyscr;

const SHAPE_CHOICE_INDEX_MASK: u16 = 62;

/// Typed native identities for the exact source disguise catalog. Map-catalog
/// shapes retain their source ids; direct-only meshes occupy named extended
/// slots generated by `tools/shape_compiler.py`.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(u16)]
pub enum DamyscrShape {
    Zaco0 = 418,
    Zaco7P = 419,
    Zaco4 = 105,
    Zaco5 = 53,
    Zaco6 = 52,
    Zaco8 = 104,
    Zaco9 = 269,
    ZacoA = 217,
    ZacoB = 201,
    Kamikaze = 9,
    DragonHead = 13,
    Airship = 79,
    Walker3 = 129,
    BossSeven = 55,
    Shark = 12,
    Mine = 299,
    BossD = 381,
    BossE = 329,
    BossFHead = 305,
    Carrier = 114,
    Robot = 420,
    Helicopter = 130,
    Walker = 26,
    Windmill = 17,
    Bazooka = 131,
    Missile = 8,
    Walker2 = 164,
    Car = 196,
    OldType = 323,
    UpperMonster = 132,
    Tadpole = 227,
    Zaco1 = 230,
}

pub const DAMYSCR_SHAPES: [DamyscrShape; 32] = [
    DamyscrShape::Zaco0,
    DamyscrShape::Zaco7P,
    DamyscrShape::Zaco4,
    DamyscrShape::Zaco5,
    DamyscrShape::Zaco6,
    DamyscrShape::Zaco8,
    DamyscrShape::Zaco9,
    DamyscrShape::ZacoA,
    DamyscrShape::ZacoB,
    DamyscrShape::Kamikaze,
    DamyscrShape::DragonHead,
    DamyscrShape::Airship,
    DamyscrShape::Walker3,
    DamyscrShape::BossSeven,
    DamyscrShape::Shark,
    DamyscrShape::Mine,
    DamyscrShape::BossD,
    DamyscrShape::BossE,
    DamyscrShape::BossFHead,
    DamyscrShape::Carrier,
    DamyscrShape::Robot,
    DamyscrShape::Helicopter,
    DamyscrShape::Walker,
    DamyscrShape::Windmill,
    DamyscrShape::Bazooka,
    DamyscrShape::Missile,
    DamyscrShape::Walker2,
    DamyscrShape::Car,
    DamyscrShape::OldType,
    DamyscrShape::UpperMonster,
    DamyscrShape::Tadpole,
    DamyscrShape::Zaco1,
];

pub fn damyscr_init(g: &mut Game, idx: u16) {
    set_object_path(g, idx, PATH_ID_DAMYSCR);

    let choice = (sf_random(&mut g.vars) & SHAPE_CHOICE_INDEX_MASK) as usize / 2;
    g.objs.aliens[idx as usize].shape = DAMYSCR_SHAPES[choice] as u16;

    initialize_path_object(g, idx);
}

fn strategy_id(world: &mut World, strategy: StrategyFn) -> StratId {
    if let Some(index) = world
        .strat_registry
        .iter()
        .position(|&registered| registered as usize == strategy as usize)
    {
        StratId(index as u16)
    } else {
        world.register_strategy(strategy)
    }
}

pub fn register(world: &mut World) {
    let strategy = strategy_id(world, damyscr_init);
    world.register_direct_strategy(STRATEGY_DAMYSCR, strategy);
}
