#!/usr/bin/env python3
"""Reduce a retail Venom door replay to semantic gate evidence."""

from __future__ import annotations

import argparse
import hashlib
import re
from dataclasses import dataclass
from pathlib import Path


DEFAULT_OUTPUT = Path(__file__).with_name("fixtures") / "venom_knight_gate.trace"
EXPECTED_MAP_SEQUENCE = ("05:0ADE", "05:0AE2", "05:0B45")
EXPECTED_KNIGHT_POSITION = (0, 0, 6_004)
EXPECTED_KNIGHT_DURABILITY = 100

ELAPSED_PATTERN = re.compile(r"\belapsed=(\d+)\b")
MAP_PATTERN = re.compile(r"\bmap=([0-9A-F]{2}:[0-9A-F]{4})\b")
PLAYER_PATTERN = re.compile(r"\bplayerpose=([^ ]+)")
KNIGHT_PATTERN = re.compile(r"(?:objects=\[|;)([0-9A-F]{4},E974,[^;\]]+)")


@dataclass(frozen=True)
class GateSample:
    elapsed: int
    map_id: str
    player_position: tuple[int, int, int]
    knight_position: tuple[int, int, int]
    knight_durability: int


def parse_position(text: str) -> tuple[int, int, int]:
    fields = text.split(",")
    if len(fields) < 3:
        raise ValueError(f"malformed position: {text}")
    return tuple(int(value) for value in fields[:3])


def parse_raw_trace(path: Path) -> list[GateSample]:
    samples: dict[str, GateSample] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        if " event=sortie " not in line:
            continue
        elapsed_match = ELAPSED_PATTERN.search(line)
        map_match = MAP_PATTERN.search(line)
        player_match = PLAYER_PATTERN.search(line)
        knight_match = KNIGHT_PATTERN.search(line)
        if not all((elapsed_match, map_match, player_match, knight_match)):
            continue
        map_id = map_match.group(1)
        if map_id not in EXPECTED_MAP_SEQUENCE or map_id in samples:
            continue
        knight_fields = knight_match.group(1).split(",")
        if len(knight_fields) < 16:
            raise ValueError("retail Knight record is truncated")
        samples[map_id] = GateSample(
            elapsed=int(elapsed_match.group(1)),
            map_id=map_id,
            player_position=parse_position(player_match.group(1)),
            knight_position=tuple(int(value) for value in knight_fields[2:5]),
            knight_durability=int(knight_fields[15]),
        )

    missing = [map_id for map_id in EXPECTED_MAP_SEQUENCE if map_id not in samples]
    if missing:
        raise ValueError(f"raw trace is missing Venom gate maps: {', '.join(missing)}")
    ordered = [samples[map_id] for map_id in EXPECTED_MAP_SEQUENCE]
    if any(sample.player_position[2] != 6_600 for sample in ordered):
        raise ValueError("oracle player did not remain beyond the Venom reactor door")
    if any(sample.knight_position != EXPECTED_KNIGHT_POSITION for sample in ordered):
        raise ValueError("retail Knight moved from the certified gate position")
    if any(
        sample.knight_durability != EXPECTED_KNIGHT_DURABILITY for sample in ordered
    ):
        raise ValueError("retail Knight durability changed during the gate transition")
    return ordered


def render_fixture(raw_path: Path, samples: list[GateSample]) -> str:
    lines = [
        "# Generated by tools/sf2/generate_venom_knight_gate.py.",
        f"# Raw trace SHA-256: {hashlib.sha256(raw_path.read_bytes()).hexdigest()}",
        "# Oracle-only source map identifiers are retained for verification.",
    ]
    for sample in samples:
        lines.append(
            "gate "
            f"elapsed={sample.elapsed} "
            f"map={sample.map_id} "
            f"player={','.join(str(value) for value in sample.player_position)} "
            f"knight_position={','.join(str(value) for value in sample.knight_position)} "
            f"knight_durability={sample.knight_durability}"
        )
    lines.append(
        f"summary transition_frames={samples[-1].elapsed - samples[0].elapsed} "
        "knight_defeat_required=false"
    )
    return "\n".join(lines) + "\n"


def validate_fixture(contents: str) -> None:
    gate_lines = [line for line in contents.splitlines() if line.startswith("gate ")]
    if len(gate_lines) != len(EXPECTED_MAP_SEQUENCE):
        raise ValueError("Venom gate fixture must contain exactly three gate samples")
    maps = tuple(
        next(field.removeprefix("map=") for field in line.split() if field.startswith("map="))
        for line in gate_lines
    )
    if maps != EXPECTED_MAP_SEQUENCE:
        raise ValueError("Venom gate fixture has an unexpected map sequence")
    for line in gate_lines:
        if f"knight_durability={EXPECTED_KNIGHT_DURABILITY}" not in line:
            raise ValueError("Venom gate fixture does not retain full Knight durability")
    if "summary transition_frames=10 knight_defeat_required=false" not in contents:
        raise ValueError("Venom gate fixture has an unexpected transition summary")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--import-raw", type=Path)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    if args.import_raw is None:
        validate_fixture(args.output.read_text(encoding="utf-8"))
        return

    generated = render_fixture(args.import_raw, parse_raw_trace(args.import_raw))
    validate_fixture(generated)
    if args.check:
        current = args.output.read_text(encoding="utf-8")
        if current != generated:
            raise SystemExit(f"compact fixture is out of date: {args.output}")
    else:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(generated, encoding="utf-8")


if __name__ == "__main__":
    main()
