#!/usr/bin/env python3
"""Generate the native SF1 strategy-to-shape defaults from ISTRATS.ASM."""

from __future__ import annotations

import argparse
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "reference" / "ultrastarfox" / "SF" / "STRAT" / "ISTRATS.ASM"
OUTPUT = ROOT / "rust" / "sf-map" / "src" / "istrat_shapes.rs"
CAPACITY = 256


def parse_defaults() -> tuple[list[int], int]:
    shape_ids: dict[str, int] = {}
    defaults: list[int] = []

    for raw in SOURCE.read_text(encoding="latin1", errors="ignore").splitlines():
        line = raw.split(";", 1)[0].strip()
        if not line:
            continue

        shape_match = re.match(r"(?i)^def_shape\s+([A-Za-z0-9_]+)", line)
        if shape_match:
            name = shape_match.group(1).lower()
            if name != "macro":
                shape_ids[name] = len(shape_ids)
            continue

        strategy_match = re.match(
            r"(?i)^def_istrat\s+([A-Za-z0-9_]+)(?:\s*,\s*([A-Za-z0-9_]+))?",
            line,
        )
        if not strategy_match:
            continue
        strategy_name = strategy_match.group(1).lower()
        if strategy_name == "macro":
            continue
        shape_name = (strategy_match.group(2) or "nullshape").lower()
        if shape_name not in shape_ids:
            raise RuntimeError(
                f"strategy {strategy_name} refers to unknown shape {shape_name}"
            )
        defaults.append(shape_ids[shape_name])

    if len(defaults) > CAPACITY:
        raise RuntimeError(f"{len(defaults)} strategies exceed capacity {CAPACITY}")
    strategy_count = len(defaults)
    defaults.extend([0] * (CAPACITY - strategy_count))
    return defaults, strategy_count


def render(defaults: list[int], strategy_count: int) -> str:
    rows = []
    for start in range(0, len(defaults), 16):
        values = ", ".join(str(value) for value in defaults[start : start + 16])
        rows.append(f"    {values},")
    return "\n".join(
        [
            "//! Generated by `tools/istrat_shape_gen.py`; do not hand-edit.",
            "//! Canonical `def_Istrat` to `def_shape` defaults from ISTRATS.ASM.",
            "",
            f"pub const ISTRAT_DEFAULT_COUNT: usize = {strategy_count};",
            "",
            "#[rustfmt::skip]",
            f"pub const ISTRAT_SHAPE_DEFAULTS: [u16; {CAPACITY}] = [",
            *rows,
            "];",
            "",
        ]
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    generated = render(*parse_defaults())
    if args.check:
        if not OUTPUT.is_file() or OUTPUT.read_text() != generated:
            raise SystemExit(f"generated strategy-shape table is stale: {OUTPUT}")
        print(f"strategy-shape table is current: {OUTPUT}")
        return
    OUTPUT.write_text(generated)
    print(f"wrote {OUTPUT}")


if __name__ == "__main__":
    main()
