#!/usr/bin/env python3
"""Generate default strategy->shape mapping from ISTRATS.ASM."""

import os
import re
import sys


def main():
    repo_root = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
    src = os.path.join(repo_root, "reference", "ultrastarfox", "SF", "STRAT", "ISTRATS.ASM")
    shape_ids = {}
    strat_shapes = []
    cs = 0
    with open(src, "r", encoding="latin1", errors="ignore") as f:
        for raw in f:
            line = raw.split(";", 1)[0].strip()
            if not line:
                continue
            m_shape = re.match(r"(?i)^def_shape\s+([A-Za-z0-9_]+)", line)
            if m_shape:
                shape_ids[m_shape.group(1).lower()] = cs
                cs += 1
                continue
            m_strat = re.match(r"(?i)^def_istrat\s+([A-Za-z0-9_]+)(?:\s*,\s*([A-Za-z0-9_]+))?", line)
            if not m_strat:
                continue
            sh_name = (m_strat.group(2) or "nullshape").lower()
            strat_shapes.append(shape_ids.get(sh_name, 0))

    while len(strat_shapes) < 256:
        strat_shapes.append(0)

    out = []
    out.append("// Auto-generated by tools/istrat_shape_gen.py")
    out.append("#ifndef STARFOX_STRAT_ISTRAT_SHAPES_DATA_H")
    out.append("#define STARFOX_STRAT_ISTRAT_SHAPES_DATA_H")
    out.append("")
    out.append('#include "../types.h"')
    out.append("")
    out.append("static const uint16 g_istrat_shape_defaults[256] = {")
    row = []
    for i, v in enumerate(strat_shapes[:256]):
        row.append(str(v))
        if len(row) == 16:
            out.append("    " + ", ".join(row) + ",")
            row = []
    if row:
        out.append("    " + ", ".join(row))
    out.append("};")
    out.append("")
    out.append("#endif // STARFOX_STRAT_ISTRAT_SHAPES_DATA_H")
    out.append("")
    sys.stdout.write("\n".join(out))


if __name__ == "__main__":
    main()
