#!/usr/bin/env python3
"""Generate typed SF1 scene palettes and distance-colour families."""

from __future__ import annotations

import argparse
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
COL_DIR = ROOT / "reference/ultrastarfox/SF/DATA/COL"
COLTAB = ROOT / "reference/ultrastarfox/SF/ASM/COLTAB.ASM"
OUTPUT = ROOT / "rust/sf-render/src/scene_color_data.rs"

GAME_PALETTES = ("night", "red", "blue")
DEPTH_FAMILIES = ("night", "mist", "desert", "marine", "red")
GAME_PALETTE_ROW = 7
COLORS_PER_PALETTE = 16
DEPTH_BANKS = 4
DEPTH_COLORS = 32


def read_game_palette(name: str) -> list[int]:
    data = (COL_DIR / f"{name.upper()}.COL").read_bytes()
    start = GAME_PALETTE_ROW * COLORS_PER_PALETTE * 2
    row = data[start : start + COLORS_PER_PALETTE * 2]
    if len(row) != COLORS_PER_PALETTE * 2:
        raise RuntimeError(f"short palette row in {name}.COL")
    return [row[i] | row[i + 1] << 8 for i in range(0, len(row), 2)]


def read_depth_banks() -> dict[str, list[list[int]]]:
    wanted = {
        f"{family}{bank}": (family, bank - 1)
        for family in DEPTH_FAMILIES
        for bank in range(1, DEPTH_BANKS + 1)
    }
    found: dict[str, list[list[int]]] = {
        family: [[] for _ in range(DEPTH_BANKS)] for family in DEPTH_FAMILIES
    }
    current: tuple[str, int] | None = None
    for raw in COLTAB.read_text(errors="replace").splitlines():
        code = raw.split(";", 1)[0].strip().lower()
        if code in wanted:
            current = wanted[code]
            continue
        if current is None:
            continue
        match = re.match(r"dbh\s+(.+)$", code)
        if not match:
            if code:
                current = None
            continue
        family, bank = current
        found[family][bank].extend(
            int(token.strip(), 16) for token in match.group(1).split(",")
        )

    for family, banks in found.items():
        for bank, values in enumerate(banks, 1):
            if len(values) != DEPTH_COLORS:
                raise RuntimeError(
                    f"{family}{bank}: expected {DEPTH_COLORS} values, got {len(values)}"
                )
    return found


def rust_words(values: list[int]) -> str:
    return ", ".join(f"0x{value:04X}" for value in values)


def rust_bytes(values: list[int]) -> str:
    return ", ".join(f"0x{value:02X}" for value in values)


def generate() -> str:
    palettes = {name: read_game_palette(name) for name in GAME_PALETTES}
    depth = read_depth_banks()
    out = [
        "// Auto-generated by tools/scene_color_gen.py -- do not edit.",
        "//! Polygon palettes and distance-colour pairs from the retail source data.",
        "",
    ]
    for name in GAME_PALETTES:
        out.extend(
            [
                "#[rustfmt::skip]",
                f"pub static {name.upper()}_GAME_PALETTE: [u16; 16] = [{rust_words(palettes[name])}];",
                "",
            ]
        )
    for family in DEPTH_FAMILIES:
        for bank, values in enumerate(depth[family], 1):
            out.extend(
                [
                    "#[rustfmt::skip]",
                    f"pub static {family.upper()}_{bank}_DEPTH_COLORS: [u8; 32] = [{rust_bytes(values)}];",
                ]
            )
        refs = ", ".join(
            f"&{family.upper()}_{bank}_DEPTH_COLORS" for bank in range(1, 5)
        )
        out.extend(
            [
                f"pub static {family.upper()}_DEPTH_COLORS: [&[u8; 32]; 4] = [{refs}];",
                "",
            ]
        )
    return "\n".join(out)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    generated = generate()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != generated:
            raise SystemExit(f"{OUTPUT} is stale; run tools/scene_color_gen.py")
        return 0
    OUTPUT.write_text(generated)
    print(f"wrote {OUTPUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
